### PR TITLE
Nexus: Handle J3 terms in spin-orbit calculations

### PR DESCRIPTION
**Pull request by aannabe**
## Proposed changes
For spin-orbit calculations, we only have up electron species. Currently in Nexus, J3 is written as usual with up and down electrons, which errors out in qmcpack. This PR loops over the three-body-Jastrow object and deletes terms that have up-down interactions.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Local machine.

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Did you investigate the possibility of not creating these terms in the first place?

**Comment by aannabe** [comment]
I haven't investigated that route. Deleting the down terms seemed the easiest way in terms of handling it. Also, J2 was handled similarly to this, but for some reason J3 was left out. If you think it's better to not generate these terms in the first place, I can take a closer look.

**Comment by prckent** [comment]
Thanks -- I was just asking. Probably this is the pragmatic and quickest route and we should go ahead with this (@jtkrogel ?) but clearly it would be cleaner to never create incorrect terms in the first place. That would mean the parts of Nexus that create wavefunction components would inspect the spin and spin-orbit configuration before creating their terms.

**Comment by camelto2** [comment]
This LGTM. I am approving in case you need non-ORNL approval, and I would like to have this for my work.

**Review by camelto2 — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
