### PR TITLE
Consistent lstlisting and inlinelstlisting for Manual

### PR DESCRIPTION
**Pull request by PDoakORNL**
Addressing #1329 and additional issues.
I've also updated the contributing to the manual section.
Note that tabularx cannot take "verbatim" elements so we cannot use the inline formats there.
Those remain manually specified \texttt \textit \textbf etc.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Also fixed the overflowing xml spec table issue

**Comment by ye-luo** [comment]
What is this file?
manual/utils/fixing_verbatims.org

**Comment by ye-luo** [comment]
I can't build the manual with pdflatex due to `\ttfamily` but it can be caused by my old textlive2015.
Can you try pdflatex?

**Comment by prckent** [comment]
The manual will only build with recent texlive 2018 and maybe 2017 from memory. Use xelatex and the script.

I'll check if this builds in our VM.

**Comment by ye-luo** [comment]
@prckent Did you succeed with the pdflatex from textlive 2018?
I can build the manual in the develop branch with texlive 2015.
Here `\ttfamily` stops pdflatex with both textlive 2015 and 2017.
Not a fan of xetex.

**Comment by jtkrogel** [comment]
I can build with pdflatex from texlive 2015.  The changes in listing fonts, etc, amount to a big improvement.

At the moment, the pdflatex listings look a lot better than the xelatex ones.  There is a change in verbatim font that significantly degrades readability in xelatex IMO.  See e.g. Listing 13.4 with pdflatex and xelatex.  I'm guessing the font could be changed in xelatex?

Another small beef: pink urls?

**Comment by PDoakORNL** [comment]
Link color changed.  TexLive 2018 pdflatex build works. @jtkrogel its hard to know which font you are picking up for the XeLaTeX build.  That build first tries for DejaVu Sans Mono and if it can't find that Courier New and if it can't find that you end up with the default monospace font.

**Comment by ye-luo** [comment]
Texlive 2015 pdflatex works as well now. @PDoakORNL could you please resolve the conflict?

**Comment by prckent** [comment]
I was able to build in the VM, as expected. For reference this is a full "binary" install of TexLive2018. 
Since 99% of users interact with the manual via the PDF produced in the VM and the *official* build_manual.sh, how this looks is most important. Ideally the PDF produced other ways would not be much different, but we shouldn't spend much effort on it.

- The XML listings are much improved
- With the Link color fix, the URLs are now blue and clearly visible.
- The table of contents entries, which are clickable, are now ~black. Before the link color fix in this PR they were red. Making these visible again would be useful. Before this PR they were red outline boxes around black text - ugly but usable.
- The font in the PDF still the same as https://docs.qmcpack.org/qmcpack_manual.pdf , which is fine by me.

@PDoakORNL Can you tweak the table of contents entries color?

**Comment by PDoakORNL** [comment]
Yes what color, could be blue too, I think that is commonly understood as a link. I thought all the red looked a little crazy.

**Comment by prckent** [comment]
I am happy with the PDF produced in the VM with the latest updates.

**Comment by ye-luo** [comment]
@markdewing is not available today.

**Pull request merged**
