### PR TITLE
Split BareKineticEnergy

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
BareKineticEnergy.h template on T doesn't make much sense. T is almost not used. So better to just drop template. Split BareKineticEnergy.h and BareKineticEnergy.cpp.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by prckent** [comment]
Do you see a way to increase the test coverage in this file?

I notice that the sameMass optimization is responsible for some of the missed coverage. Even the comments suggest that this might be unnecessary.

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by PDoakORNL** [comment]
Additional test coverage would be good perhaps this deserves an issue.

**Comment by ye-luo** [comment]
#3463 for discussing SameMass=false.

**Comment by ye-luo** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
Start testing in-house

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Pull request merged**
