### PR TITLE
Add HIP_ARCH to ctest_script.cmake

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Add HIP_ARCH for convenient scripting

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen2 (gfx90a)

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
I feel this is not needed and try to avoid expanding the list of bypass in ctest_scripts.
Please pass options `-DQMC_OPTIONS='-DHIP_ARCH=gfx90a'.`
If you need multiple entry `-DQMC_OPTIONS='-DHIP_ARCH=gfx90a;-DENABLE_OFFLOAD=ON'`

**Comment by ye-luo** [comment]
With the current bypassing scheme, you will keep hitting this type of issue requiring updating ctest_scripts.
I reopened https://github.com/QMCPACK/qmcpack/issues/350

**Comment by prckent** [comment]
Updating QMC_OPTIONS is a pain in the existing scripts and this gets them running fastest; I certainly don't have time to update them now. That said I do agree that something less error prone is desirable. An additional problem imo is that we don't have a good way to catch arguments that are effectively silently dropped. It wouldn't surprise me if we have a few cases where the "wrong" test configuration is being run due to missing options or typos etc.

**Comment by ye-luo** [comment]
It should not be an all-in all-out approach. You may start adding new flags via QMC_OPTIONS and gradually phase out the old way. Probably start with adding QMC_OPTIONS variable parallel to CTCFG and at the ctest line add -DQMC_OPTIONS="$QMC_OPTIONS"

**Pull request closed without merging**
