### PR TITLE
Add feature documentation by K. Esler and S. Chiesa

### PR DESCRIPTION
**Pull request by jtkrogel**
Add feature documentation for optimized long-range breakup (Ewald), cubic splines, B-spline orbital tiling, hybrid representation, e-e-I Jastrow, and k-space Jastrow.

Notes are taken from QMCPACK and wfconvert files with permission from K. Esler.  These notes should be revised/corrected and expanded on in the future.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
Please DO NOT move the eeI Jastrow to the user manual. Apart from the first formula which may be useful to users, all the rest is meant only for developers. I will take care the user part in #415.

**Comment by ye-luo** [comment]
Since the files are incorporated into the manual, shall we remove individual files in the repo and we just update the manual?

**Comment by prckent** [comment]
@ye-luo eeI description is needed soon - it is an everyday feature with no docs!

I agree on removing the individual files. Not needed once included in manual.

**Comment by jtkrogel** [comment]
Look OK now?

**Pull request merged**
