### PR TITLE
[WIP] Enable LM Engine to Optimize Complex Wavefunction Parameters

### PR DESCRIPTION
**Pull request by chrislzhao**
@ye-luo This commit enables the LM engine to optimize complex wave functions parameters. Currently once QMC_COMPLEX is on and a multi-slater wavefunction is used, the CI coefficients are assumed to be complex. The LM engine would build the H and S matrix in complex and solve the eigenvalue problem. The complex part of the Jastrow factor is discarded so that the Jastrow are real.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by chrislzhao** [comment]
@ye-luo Will the review happen soon?

**Comment by ye-luo** [comment]
@chrislzhao let us arrange a meeting next week. Ping me via email

**Comment by ye-luo** [comment]
We have broken this PR into 4 parts and 2 of them have been merged. The other two are on the way. There is no more need to keep this WIP PR alive.

**Pull request closed without merging**
