### PR TITLE
Some C++ cleanup and use C++17 with nvcc and hipcc.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes

Move to C++17 std::disjunction and remove unused file.
Also use C++17 with nvcc and hipcc.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — DISMISSED** [review]

**Comment by prckent** [comment]
Test this  please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@prckent I have fixed the GPU compilation issue.

**Review by prckent — APPROVED** [review]

**Pull request merged**
