### PR TITLE
Restructure Platforms/CPU/SIMD files

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
1. remove `Platforms/CPU/SIMD/simd.hpp` all in one header file.
2. Keep only `simd::dot` functions in `inner_product.hpp` and move the rest routines to algorithms.
3. Allow precision override in all the `simd::dot` routines.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Tidying or do you have a hypothesis on the crash?

**Comment by ye-luo** [comment]
> Tidying or do you have a hypothesis on the crash?

I found the reasons (more than one) for the crash. Details will be provided when I make PRs.

**Pull request merged**
