### PR TITLE
Add determinant utlities 

### PR DESCRIPTION
**Pull request by TApplencourt**
Hi QMCPACK developers,

Recently QMCPACK, adopted a new representation of determinant inside the h5 file. Determinants are represented as a list of integer.
This pull request provides a `reference implementation` of some usuals operations that one can want to perform:
   - Convert a determinant into a string representation (where the first bit represent the first state/orbital)
   - Compute the excitation degree between to determinant
   - Compute the associated CSF 

This Python implementation can be used directly by other tools (Nexus, converter, ...) or can be used as a reference for C/C++ implementation.

To demonstrate the capability of this implementation, the python file `determinants_tools.py` can be used as a program to generate, one can argue, useful information on the multi-determinant wavefunction:

```
> determinants_tools.py ./tests/molecules/C2_pp/C2.h5
Summary:
exitation degree 0 count: 1
exitation degree 1 count: 6
exitation degree 2 count: 148
exitation degree 3 count: 27
exitation degree 4 count: 20

n_det 202
n_csf 104
```

```
> determinants_tools.py --verbose ./tests/molecules/C2_pp/C2.h5 | head
1
alpha  1111000000000000000000000000000000000000000000000000000000
beta   1111000000000000000000000000000000000000000000000000000000
scf    2222000000000000000000000000000000000000000000000000000000
excitation degree  0

2
alpha  1011100000000000000000000000000000000000000000000000000000
beta   1011100000000000000000000000000000000000000000000000000000
scf    2022200000000000000000000000000000000000000000000000000000
excitation degree  2
```

Final note:
- This script should be Python2/Python3 compatible
- Unit test a provided inside the Python file using the `doctest` module
- I didn't add CTest for few reasons:
    -  My CTest skills are near to non-existent
    - I don't know if QMCPACK developers want to add an `h5py` dependency on their CTest
    - UnitTests are run each time the script is used. 
   - This file has no external dependency and is not expected to change.  

Please let me know if you have any feedback, or if I don't conform to some guideline (mandatory CTest, pep8, Perl and not python, ...) 

Thanks

### CODE REVIEW

**Comment by markdewing** [comment]
This looks like good addition for using the h5 determinant files.   I can take care of moving the location as Ye requested - there are a number of spelling and grammar fixes that I want to make as well.

**Comment by prckent** [comment]
@TApplencourt Thanks. FYI, Due to the non-scalability of the current determinant representation in the QMCPACK inputs, we would like "at some point" to move to a system where the actual excitation is described. No one has reported actual science being blocked but the current setup, but the excitation based approach should be much more scalable. Internally we should do whatever is fast and also memory efficient. Ideas and comments are welcome.

**Comment by markdewing** [comment]
I wasn't able to push to Thomas' develop branch.  The spelling and grammar fixes are in a branch here
https://github.com/markdewing/qmcpack/tree/update_determinant_utilities

I could do a PR from that branch (instead of using this PR).  This PR is also coming directly from 'develop' rather than a disposable branch.

**Comment by TApplencourt** [comment]
@prckent  The integer representation gives you an 8fold reduction in memory consumption. For the computation of the excitation degrees, the integers approach give you more or less a 64x speedup.
You can find more information in this paper: https://arxiv.org/pdf/1311.6244.pdf

**Comment by TApplencourt** [comment]
@markdewing  Thanks! I merge your modifications in my fork.

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
Okay to test

**Comment by prckent** [comment]
Thomas - Please add a comment such as the following at the top of the script. Happy to merge afterwards. I could not push to your branch.)

```
# Provide information about a multideterminant wavefunction stored in HDF5 format.
#
# determinants_tools.py ./tests/molecules/C2_pp/C2.h5    # Summary excitation info only
# determinants_tools.py -v ./tests/molecules/C2_pp/C2.h5 # Verbose. Gives details of each determinant
```

**Comment by TApplencourt** [comment]
@prckent  Done. Thanks!

**Pull request merged**
