### PR TITLE
Specialize batched transfer of psiM_vgl.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
It doesn't seem to impact much when using LLVM OpenMP offload to NVIDIA but does have a huge impact on AOMP offload to AMD GPU. So add the specialization.

## What type(s) of changes does this code introduce?
- Other (please describe): performance optimization.

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
summit, crusher

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
A simple thing: the mw_transfer functions are missing definitions/docs.

**Comment by ye-luo** [comment]
> A simple thing: the mw_transfer functions are missing definitions/docs.

Updated.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Pull request merged**
