### PR TITLE
Address failures in GitHub Actions

### PR DESCRIPTION
**Pull request by williamfgc**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes
Attempting to fix GitHub Actions permission issue for users other than root, so MPI tests can run
Figure out test failures on GitHub Actions workflow

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted (NA)
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
OK to test

**Comment by williamfgc** [comment]
@prckent I didn't "dismiss" your review as GitHub says. I'm just trying to fix the GitHub issues doing more commits :smiley:

**Comment by ye-luo** [comment]
Could you do the following change?
1. Move github-actions from config to tests/test_automation
2. Add `-DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx` to cmake like to reduce the warning form cmake.

**Comment by prckent** [comment]
@williamfgc FYI a recent version of how we do nightlies see tests/test_automation/nightly_test_scripts and look at the *ornl* ones.

Nightlies take hours on 16 threads of a strong workstation, and by using our own hardware we can run on NVIDIA and AMD GPUs. Can we get access to any GPUs through github actions? Running the unit or full deterministic tests would be very helpful.

**Comment by williamfgc** [comment]
@ye-luo will do, thanks. As a side note, we can accommodate to CMake `MPI_<clang>_COMPILER` in the future, see [here](https://tianyuliukingcrimson.com/2017/09/18/the-correct-way-of-building-mpi-program-using-cmake/). @prckent yes, sounds about right as I got those on my local machine. BTW, it's possible to add our own runners, see [here](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
@williamfgc Thanks for the GPU note. AWS GPU charges historically were rather high. And using our own runners would require a very careful security audit. Not the highest priority fortunately - adding sanitizers, coverage checks etc. would be of much greater impact.

**Pull request merged**
