### PR TITLE
Refactor HybridRepCenterOrbitals

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
How bad my old code was ;)
1. move data exchanged between routines into a struct.
2. It used to rely on smooth function values to label regions and now changed to enum. 

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Let me fix tests and improve coverage first.

**Comment by ye-luo** [comment]
This this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
A step forward and improvement to the testing ~coverage~ as well.

**Pull request merged**
