### PR TITLE
Add code coverage using gcov and gcovr and upload report to Codecov

### PR DESCRIPTION
**Pull request by williamfgc**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Enable code coverage with gcov and uploads xml report to codecov using GitHub Actions
Uses QMC_COMPLEX=1 and deterministic tests
Enable Codecov configuration
Install gcovr in docker container

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Build related changes: reuse existing `ENABLE_GCOV` option
- Testing changes: new code coverage report

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 20.04, must pass GitHub Actions CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted (NA)
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
@williamfgc While we wait for the CI to run, what are your expectations and plans for this after initial merge? Will codecov start posting on PRs after it has an initial data point?  Rather like the initial github actions we can watch for a few days to see if there are any quirks. Besides basic coverage I think it will be interesting to see their "hot paths" feature and what our coverage is on those. Hopefully good, but we will see. Also, presumably adding a real build alongside this complex one is straightforward given the "dynamic" actions you have setup?

**Comment by williamfgc** [comment]
Hi @prckent yes, that's correct. For every PR a report is uploaded and devs can see how coverage is impacted in codecov on a per branch PR basis. I don't know if you can see this branch report [here](https://codecov.io/gh/QMCPACK/qmcpack/tree/7d4a90a5c727290898150502b990741a26ae7bd4). Once merged it would show `develop` and the analysis graphs. Yes, we can customize the reports on the `codecov.yaml` files for QMCPACK needs. BTW, I usually just log in once with GitHub and Codecov is seemless. I can add a codecov badge in README as well.

**Review by prckent — APPROVED** [review]
Good for me. Thanks for building William.

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
