### PR TITLE
Suppress QMCPACK printout in unit tests by default.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Failing unit test was not able to report all output to cdash.
"The rest of the test output was removed since it exceeds the threshold of 100000 bytes."
https://cdash.qmcpack.org/CDash/testDetails.php?test=19984254&build=325108
So it is better to suppress output by default.
Option "--turn-on-printout" added to make the printout through if needed.

## What type(s) of changes does this code introduce?
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
This is an issue with cdash configuration, not QMCPACK. Why change QMCPACK, or anything at all?

**Comment by ye-luo** [comment]
I tend to agree with @PDoakORNL most of the printout are unrelated with what one is working on.
When I run into a failure, going through the long printout is always painful and doesn't add valuable info.
Catch already reports where the failure is from.

> When run by hand I would like to see the unit test output.

There is an option being added to turn on the printout and you will be able to see all the printout.

**Review by PDoakORNL — APPROVED** [review]
Ok I admit I did not look at this closely enough.  Yes this is a good idea and then we can forget about outputManager in most tests.

**Review by prckent — CHANGES_REQUESTED** [review]
OK, but docs are required. i.e. *.md entries

**Comment by ye-luo** [comment]
> OK, but docs are required. i.e. *.md entries

Updated rst docs. I'm not aware of "*.md" files. Let me know I missed anything.
When you run unit tests manually, "QMCPACK printout is suppressed. Use --turn-on-printout to see all the printout." is on the first line if this option is not used.

**Comment by prckent** [comment]
Please indicate how to route turn-on-printouts to these tests via ctest invocation.

**Comment by ye-luo** [comment]
> Please indicate how to route turn-on-printouts to these tests via ctest invocation.

Simply cannot. Probably when one needs that, running individual tests manually is likely the best thing to do.
When a failure happens, adding these printout doesn't add useful info. What catch prints should be sufficient.

To add the control at ctest, the way I can think of is adding environment variable. That is quite involving code change, need to see a good reason for that.

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
