### PR TITLE
Checking number of kpoints for requested super twist

### PR DESCRIPTION
**Pull request by mcbennet**
## Proposed changes

The code currently checks each supertwist for the correct number of kpoints for tiling. In this PR, I propose that only the requested supertwist be sanity checked in this way.
Possibly, there are repercussions here that I am not seeing?

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

CADES/ORNL

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
These checks exist to stop users from using inconsistent input files.

Please can you explain how the current situation is a problem for you? Would the benefits of the weaker check outweigh the consequences of potentially letting more mistaken runs through?

**Comment by mcbennet** [comment]
> Would the benefits of the weaker check outweigh the consequences of potentially letting more mistaken runs through?

I was mistaken before about the code exiting for a super twist that is not requested with `twistnum` -- it turns out that the code only exists if the correct number of kpoints is not present for the user's _requested_ twist.

As it turns out the code was exiting due to insufficient memory, however, when I initially glanced at the error file, the end of it showed lines like the following:
`ERROR Super twist 1 should own 4 k-points, but owns 1.`
Though I asked for `twistnum=0` for which I knew the orbital file had the relevant kpoints.
Since nothing was printed about the memory, I assumed this was the issue.

Given that the code allows me to get my run through after resolving my memory issue, then in my opinion there is no problem. That being said, perhaps it is worth considering whether or not the above case should be printed as a Warning rather than an Error.

**Comment by prckent** [comment]
Do you know how your run ran out of memory? If it was on one of the big allocations (orbitals, determinant) then we might be missing an error check.

**Comment by mcbennet** [comment]
> Do you know how your run ran out of memory? If it was on one of the big allocations (orbitals, determinant) then we might be missing an error check.

It was the determinant. No memory issues were seen for a smaller cell with the same orbitals, but after tiling the same orbitals to a larger cell I saw the break.

**Comment by mcbennet** [comment]
Correction, I suspect it could have been the orbitals after tiling, though I am not sure the exact culprit. I can try to reproduce.

**Comment by prckent** [comment]
If you still have the run, otherwise don't worry - if it comes up again we'll know it is important.

**Comment by mcbennet** [comment]
Attaching .out and .err files. It appears the breakage occurred when generating the splines. However, there is no informative printout -- though the "error" from the super twists is visible.  

[opt.err.txt](https://github.com/QMCPACK/qmcpack/files/4735829/opt.err.txt)
[opt.out.txt](https://github.com/QMCPACK/qmcpack/files/4735830/opt.out.txt)

**Comment by prckent** [comment]
There is also a mismatch in the twists reported.

I think we can close this for now. If is reoccurs for you or others we should investigate.

**Pull request closed without merging**
