### PR TITLE
Nexus: enable driving spinor workflows

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Support generation of spinor inputs and driving of spinor workflows, including passing of u-u term from optimized collinear Jastrows.  Orbitals currently handled at the level of existing hdf5 keyword (`orbitals_h5`).  Full support for convertpw2qmc to be added later.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Workstation

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Would like to merge by  ntest_nexus_qmcpack_simulation  is failing

**Comment by camelto2** [comment]
Hold off on this for now. Trying to actually use this in nexus and running into some issues. Will sort it out shortly

**Comment by camelto2** [comment]
> Hold off on this for now. Trying to actually use this in nexus and running into some issues. Will sort it out shortly

I think it is good to go now. I'm able to run successful, uninterrupted workflows using this now

**Review by prckent — APPROVED** [review]
Approved subject to CI.

( #4854 is queued up first )

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
