### PR TITLE
Add docs and examples for sposet_collection

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Document sposet_collection style and add how to address "!!!!!!! Deprecated input style" warning. For #3456

## What type(s) of changes does this code introduce?
- Documentation changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by markdewing** [comment]
I'm working on some edits locally, and push them when I'm done.

**Comment by ye-luo** [comment]
@markdewing please go ahead and push your changes directly. I put the PR draft because I need some additional changes. Please push, I will resolve mine after.

**Comment by ye-luo** [comment]
Start testing in-house

**Review by prckent — APPROVED** [review]
Thank for the updates.

**Pull request merged**
