### PR TITLE
Keep compat multi afqmc

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update use of reshape in multi usage in AFQMC

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 20.10, nvcc 11.3

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
Ok, this is generating conflicts, I don't understand why.
I am cloning from my repository, but I can not update my repository the last version of QMCPACK/develop.

```bash
git clone https://github.com/correaa/qmcpack.git
cd qmcpack

git remote add upstream  https://github.com/correaa/qmcpack.git
git fetch upstream
git reset --hard upstream/develop
git push  # may need token (instead of password)
```

If somebody can help me, I will keep refactoring AFQMC to keep it compatible with Multi.

I am going to close this PR later.

**Comment by ye-luo** [comment]
You have a wrong upstream
```
git remote add upstream  https://github.com/QMCPACK/qmcpack.git
```

**Comment by correaa** [comment]
> You have a wrong upstream
> 
> ```
> git remote add upstream  https://github.com/QMCPACK/qmcpack.git
> ```

That explains a lot

**Comment by correaa** [comment]
continued in https://github.com/QMCPACK/qmcpack/pull/4008

**Pull request closed without merging**
