### PR TITLE
Nexus: enable rsync for Quantum Package

### PR DESCRIPTION
**Pull request by jtkrogel**
Enable rsync between subsequent QM Package runs performed in different directories.

Also include updates to the input spec to allow dft input and revert automatic writes of integrals back to user control.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Good suggestion.  Will do this in the morning.

**Comment by jtkrogel** [comment]
Done.  Ready to merge?

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
OK to merge this now?

**Pull request merged**
