### PR TITLE
Remove SQD

### PR DESCRIPTION
**Pull request by jtkrogel**
SQD provides limited benefit with ensured maintenance overhead.  It was last used peripherally in 2013 (by me).  

See also #561 and #807.  Both issues can be closed with this PR.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
Does this clean up the corresponding part inside QMCPACK?

**Comment by jtkrogel** [comment]
No.  I do not know all of the runtime code paths that are touched by a run using a HF atom.  

In the future we can get these by removing the one test case (C_NO) and search for dead code paths relative to all tests.  I don't know of a better way to comprehensively remove a feature like this.

**Comment by prckent** [comment]
Related functionality question:

If someone wanted to run atoms using radial numerical grids, e.g. as emitted by Froese Fischer's suite of MCHF codes or as emitted by many pseudopotential atomic codes, what would they do?

**Comment by jtkrogel** [comment]
They could generalize the existing NO code (which I leave untouched here) to handle multideterminants.  Also, unless I am mistaken, the current Gaussian code using quintic radial splines, so these could be repurposed to handle more than just mappings from radial gaussians.

**Comment by ye-luo** [comment]
Current GTO code allows transforming radial functions to quintic splines on a log grid. It is flexible to handle input radial functions on any grids.

**Comment by prckent** [comment]
OK. Potentially someone might want this to test dirac HF, spin orbit etc., or study atoms in fields etc. Since it is not tied in with the SQD code I am fine for it to go.

**Comment by anbenali** [comment]
I am planning to resurrect NO on grid soon.

**Comment by prckent** [comment]
Also useful for work with DFT functional developers

**Pull request merged**
