### PR TITLE
Fix AoS no Jastrow

### LINKED ISSUE #1995: Release 3.8.0 AoS build VMC energy evaluated incorrectly
Si primitive cell in the diamond structure was evaluated without Jastrow using VMC at k=(0,0,0).
3.8.0 AoS VMC energy (most likely due to LocalPotential part) shows dependence on time-step!
```
gs_noj  series 0 (time-step 2.0)
  LocalEnergy           =          -7.17459 +/-          0.00024    1.0 
  Variance              =            0.8321 +/-           0.0046    1.5 
  Kinetic               =           4.14627 +/-          0.00036    1.2 
  LocalPotential        =         -11.32086 +/-          0.00056    1.8 
  AcceptRatio           =          0.455069 +/-         0.000021    1.0 

gs_noj  series 1 (time-step 1.0)
  LocalEnergy           =          -7.18125 +/-          0.00029    1.0 
  Variance              =            0.8291 +/-           0.0050    1.0 
  Kinetic               =           4.14707 +/-          0.00033    1.0 
  LocalPotential        =         -11.32832 +/-          0.00045    1.0 
  AcceptRatio           =          0.693160 +/-         0.000022    1.0 

```
Note that kinetic energies are consistent, so this likely due to a bug in the evaluation of potential energy.
Switching to SoA 3.8.0 gives:
```
gs_noj  series 6 (time-step 2.0)
  LocalEnergy           =          -7.18168 +/-          0.00037    1.2 
  Variance              =            0.8422 +/-           0.0093    1.0 
  Kinetic               =           4.14671 +/-          0.00048    1.5 
  LocalPotential        =         -11.32839 +/-          0.00064    1.8 
  AcceptRatio           =          0.330954 +/-         0.000031    1.1 

gs_noj  series 7 (time-step 1.0)
  LocalEnergy           =          -7.18184 +/-          0.00032    1.0 
  Variance              =             0.857 +/-            0.024    1.1 
  Kinetic               =           4.14675 +/-          0.00043    1.0 
  LocalPotential        =         -11.32859 +/-          0.00053    1.0 
  AcceptRatio           =          0.462017 +/-         0.000025    1.0 
```
AoS 3.6.0:
```
gs_noj  series 10 (time-step 2.0)
  LocalEnergy           =          -7.18133 +/-          0.00025    1.0 
  Variance              =            0.8270 +/-           0.0033    1.0 
  Kinetic               =           4.14643 +/-          0.00032    1.0 
  LocalPotential        =         -11.32776 +/-          0.00040    1.0 
  AcceptRatio           =          0.455099 +/-         0.000021    1.0 

gs_noj  series 11 (time-step 1.0)
  LocalEnergy           =          -7.18169 +/-          0.00026    1.0 
  Variance              =             0.878 +/-            0.030    1.0 
  Kinetic               =           4.14716 +/-          0.00028    1.0 
  LocalPotential        =         -11.32885 +/-          0.00037    1.1 
  AcceptRatio           =          0.693157 +/-         0.000019    1.2 

```

### PR DESCRIPTION
**Pull request by ye-luo**
Fixes #1995.
A commit between v3.7 and v3.8 removed requesting AoS distance table in the spline SPO builder.
The first call to addTable adds e-e table in SoA. During PbyP loadWalker, RSoA didn't get updated and thus causes wrong values in Coulomb e-e energy.
This bug only affects the case that no Jastrow is used with AoS build. LCAO is not affected.

### CODE REVIEW

**Comment by prckent** [comment]
=> We need a deterministic spline based no jastrow case to catch this. deterministic-LiH_dimer_pp-vmc_hf_noj-1-1 won't catch the problem since it doesn't have splines.

@ye-luo What additional test do you suggest?

**Comment by ye-luo** [comment]
We need spline+noJas deterministic tests and example more unit tests for ParticleSet.

**Comment by prckent** [comment]
Do you agree that a deterministic version of short-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16 would suffice for the former?

**Comment by ye-luo** [comment]
Yes. That is sufficient.

**Comment by prckent** [comment]
Please can make an issue and assign to Hyeondeok?

We didn't catch this problem because we aren't running the short tests for aos on oxygen. Will have to add one complete set of aos tests back in.

**Pull request merged**
