### PR TITLE
Fix LD_LIBRARY_PATH for LLVM15 CI

### LINKED ISSUE #4211: Update CI Clang to 15
**Is your feature request related to a problem? Please describe.**
Clang 15.0.0-rc3 addressed a few issues of Clang 14.
1. 14 has non-deterministic behaviors which caused bad code generation. Namely less reliable CI.
2. 15 now supports linking static archives with device code in it.

So need to update ORNL CI to use clang 15 and also remove USE_OBJECT_TARGET

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Fix LD_LIBRARY_PATH for LLVM15 CI
Can be used to test LLVM15 on CI
Fixes #4211 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
specific to CI, must pass tests on sulfur

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
LGTM

**Comment by williamfgc** [comment]
@ye-luo @prckent we can use this PR to test LLVM15 CI on sulfur

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
Update tolerance needed due to compiler change.

**Review by prckent — APPROVED** [review]

**Pull request merged**
