### PR TITLE
Fix heg aos

### LINKED ISSUE #392: Need SoA implementation for gofr estimator
As #390 indicated.

### PR DESCRIPTION
**Pull request by ye-luo**
Closes #392
AoS tests all pass. SoA needs to fix backflow.

AoS:
```
ctest -R short-heg
Test project /sandbox/opt/qmcpack/build_Intel_real
      Start 24: short-heg_14_gamma-ni-16-1
 1/27 Test #24: short-heg_14_gamma-ni-16-1 .................   Passed    1.06 sec
      Start 25: short-heg_14_gamma-ni-16-1-totenergy
 2/27 Test #25: short-heg_14_gamma-ni-16-1-totenergy .......   Passed    0.03 sec
      Start 26: short-heg_14_gamma-ni-16-1-variance
 3/27 Test #26: short-heg_14_gamma-ni-16-1-variance ........   Passed    0.02 sec
      Start 27: short-heg_14_gamma-ni_dmc-16-1
 4/27 Test #27: short-heg_14_gamma-ni_dmc-16-1 .............   Passed    1.79 sec
      Start 28: short-heg_14_gamma-ni_dmc-16-1-totenergy
 5/27 Test #28: short-heg_14_gamma-ni_dmc-16-1-totenergy ...   Passed    0.03 sec
      Start 29: short-heg_14_gamma-ni_dmc-16-1-variance
 6/27 Test #29: short-heg_14_gamma-ni_dmc-16-1-variance ....   Passed    0.03 sec
      Start 30: short-heg_14_gamma-hf-16-1
 7/27 Test #30: short-heg_14_gamma-hf-16-1 .................   Passed   41.42 sec
      Start 31: short-heg_14_gamma-hf-16-1-totenergy
 8/27 Test #31: short-heg_14_gamma-hf-16-1-totenergy .......   Passed    0.07 sec
      Start 32: short-heg_14_gamma-hf-16-1-variance
 9/27 Test #32: short-heg_14_gamma-hf-16-1-variance ........   Passed    0.06 sec
      Start 33: short-heg_14_gamma-sj-16-1
10/27 Test #33: short-heg_14_gamma-sj-16-1 .................   Passed   12.04 sec
      Start 34: short-heg_14_gamma-sj-16-1-totenergy
11/27 Test #34: short-heg_14_gamma-sj-16-1-totenergy .......   Passed    0.02 sec
      Start 35: short-heg_14_gamma-sj-16-1-variance
12/27 Test #35: short-heg_14_gamma-sj-16-1-variance ........   Passed    0.03 sec
      Start 36: short-heg_14_gamma-sj_new-16-1
13/27 Test #36: short-heg_14_gamma-sj_new-16-1 .............   Passed    9.46 sec
      Start 37: short-heg_14_gamma-sj_new-16-1-totenergy
14/27 Test #37: short-heg_14_gamma-sj_new-16-1-totenergy ...   Passed    0.05 sec
      Start 38: short-heg_14_gamma-sj_new-16-1-variance
15/27 Test #38: short-heg_14_gamma-sj_new-16-1-variance ....   Passed    0.05 sec
      Start 39: short-heg_14_gamma-sjb-16-1
16/27 Test #39: short-heg_14_gamma-sjb-16-1 ................   Passed   47.51 sec
      Start 40: short-heg_14_gamma-sjb-16-1-totenergy
17/27 Test #40: short-heg_14_gamma-sjb-16-1-totenergy ......   Passed    0.04 sec
      Start 41: short-heg_14_gamma-sjb-16-1-variance
18/27 Test #41: short-heg_14_gamma-sjb-16-1-variance .......   Passed    0.04 sec
      Start 42: short-heg_14_gamma-sjb-4-4
19/27 Test #42: short-heg_14_gamma-sjb-4-4 .................   Passed   46.79 sec
      Start 43: short-heg_14_gamma-sjb-4-4-totenergy
20/27 Test #43: short-heg_14_gamma-sjb-4-4-totenergy .......   Passed    0.09 sec
      Start 44: short-heg_14_gamma-sjb-4-4-variance
21/27 Test #44: short-heg_14_gamma-sjb-4-4-variance ........   Passed    0.07 sec
      Start 45: short-heg_14_gamma-sjb-1-16
22/27 Test #45: short-heg_14_gamma-sjb-1-16 ................   Passed   27.64 sec
      Start 46: short-heg_14_gamma-sjb-1-16-totenergy
23/27 Test #46: short-heg_14_gamma-sjb-1-16-totenergy ......   Passed    0.02 sec
      Start 47: short-heg_14_gamma-sjb-1-16-variance
24/27 Test #47: short-heg_14_gamma-sjb-1-16-variance .......   Passed    0.02 sec
      Start 48: short-heg_14_gamma-sj_dmc-16-1
25/27 Test #48: short-heg_14_gamma-sj_dmc-16-1 .............   Passed   46.37 sec
      Start 49: short-heg_14_gamma-sj_dmc-16-1-totenergy
26/27 Test #49: short-heg_14_gamma-sj_dmc-16-1-totenergy ...   Passed    0.03 sec
      Start 50: short-heg_14_gamma-sj_dmc-16-1-variance
27/27 Test #50: short-heg_14_gamma-sj_dmc-16-1-variance ....   Passed    0.04 sec

100% tests passed, 0 tests failed out of 27

Label Time Summary:
QMCPACK                     = 234.08 sec (9 tests)
QMCPACK-checking-results    =   0.76 sec (18 tests)

Total Test time (real) = 235.06 sec
```
SoA:
```
Test project /sandbox/opt/qmcpack/build_Intel_real_SoA
      Start 24: short-heg_14_gamma-ni-16-1
 1/27 Test #24: short-heg_14_gamma-ni-16-1 .................   Passed    0.85 sec
      Start 25: short-heg_14_gamma-ni-16-1-totenergy
 2/27 Test #25: short-heg_14_gamma-ni-16-1-totenergy .......   Passed    0.02 sec
      Start 26: short-heg_14_gamma-ni-16-1-variance
 3/27 Test #26: short-heg_14_gamma-ni-16-1-variance ........   Passed    0.02 sec
      Start 27: short-heg_14_gamma-ni_dmc-16-1
 4/27 Test #27: short-heg_14_gamma-ni_dmc-16-1 .............   Passed    1.76 sec
      Start 28: short-heg_14_gamma-ni_dmc-16-1-totenergy
 5/27 Test #28: short-heg_14_gamma-ni_dmc-16-1-totenergy ...   Passed    0.02 sec
      Start 29: short-heg_14_gamma-ni_dmc-16-1-variance
 6/27 Test #29: short-heg_14_gamma-ni_dmc-16-1-variance ....   Passed    0.02 sec
      Start 30: short-heg_14_gamma-hf-16-1
 7/27 Test #30: short-heg_14_gamma-hf-16-1 .................   Passed   38.30 sec
      Start 31: short-heg_14_gamma-hf-16-1-totenergy
 8/27 Test #31: short-heg_14_gamma-hf-16-1-totenergy .......   Passed    0.09 sec
      Start 32: short-heg_14_gamma-hf-16-1-variance
 9/27 Test #32: short-heg_14_gamma-hf-16-1-variance ........   Passed    0.08 sec
      Start 33: short-heg_14_gamma-sj-16-1
10/27 Test #33: short-heg_14_gamma-sj-16-1 .................   Passed   11.33 sec
      Start 34: short-heg_14_gamma-sj-16-1-totenergy
11/27 Test #34: short-heg_14_gamma-sj-16-1-totenergy .......   Passed    0.04 sec
      Start 35: short-heg_14_gamma-sj-16-1-variance
12/27 Test #35: short-heg_14_gamma-sj-16-1-variance ........   Passed    0.04 sec
      Start 36: short-heg_14_gamma-sj_new-16-1
13/27 Test #36: short-heg_14_gamma-sj_new-16-1 .............   Passed    8.43 sec
      Start 37: short-heg_14_gamma-sj_new-16-1-totenergy
14/27 Test #37: short-heg_14_gamma-sj_new-16-1-totenergy ...   Passed    0.05 sec
      Start 38: short-heg_14_gamma-sj_new-16-1-variance
15/27 Test #38: short-heg_14_gamma-sj_new-16-1-variance ....   Passed    0.05 sec
      Start 39: short-heg_14_gamma-sjb-16-1
16/27 Test #39: short-heg_14_gamma-sjb-16-1 ................***Failed    3.94 sec
      Start 40: short-heg_14_gamma-sjb-16-1-totenergy
17/27 Test #40: short-heg_14_gamma-sjb-16-1-totenergy ......***Failed    0.03 sec
      Start 41: short-heg_14_gamma-sjb-16-1-variance
18/27 Test #41: short-heg_14_gamma-sjb-16-1-variance .......***Failed    0.03 sec
      Start 42: short-heg_14_gamma-sjb-4-4
19/27 Test #42: short-heg_14_gamma-sjb-4-4 .................***Failed    0.70 sec
      Start 43: short-heg_14_gamma-sjb-4-4-totenergy
20/27 Test #43: short-heg_14_gamma-sjb-4-4-totenergy .......***Failed    0.03 sec
      Start 44: short-heg_14_gamma-sjb-4-4-variance
21/27 Test #44: short-heg_14_gamma-sjb-4-4-variance ........***Failed    0.02 sec
      Start 45: short-heg_14_gamma-sjb-1-16
22/27 Test #45: short-heg_14_gamma-sjb-1-16 ................***Failed    1.13 sec
      Start 46: short-heg_14_gamma-sjb-1-16-totenergy
23/27 Test #46: short-heg_14_gamma-sjb-1-16-totenergy ......***Failed    0.02 sec
      Start 47: short-heg_14_gamma-sjb-1-16-variance
24/27 Test #47: short-heg_14_gamma-sjb-1-16-variance .......***Failed    0.02 sec
      Start 48: short-heg_14_gamma-sj_dmc-16-1
25/27 Test #48: short-heg_14_gamma-sj_dmc-16-1 .............   Passed  102.67 sec
      Start 49: short-heg_14_gamma-sj_dmc-16-1-totenergy
26/27 Test #49: short-heg_14_gamma-sj_dmc-16-1-totenergy ...   Passed    0.06 sec
      Start 50: short-heg_14_gamma-sj_dmc-16-1-variance
27/27 Test #50: short-heg_14_gamma-sj_dmc-16-1-variance ....   Passed    0.05 sec

67% tests passed, 9 tests failed out of 27

Label Time Summary:
QMCPACK                     = 169.11 sec (9 tests)
QMCPACK-checking-results    =   0.69 sec (18 tests)

Total Test time (real) = 170.02 sec

The following tests FAILED:
	 39 - short-heg_14_gamma-sjb-16-1 (Failed)
	 40 - short-heg_14_gamma-sjb-16-1-totenergy (Failed)
	 41 - short-heg_14_gamma-sjb-16-1-variance (Failed)
	 42 - short-heg_14_gamma-sjb-4-4 (Failed)
	 43 - short-heg_14_gamma-sjb-4-4-totenergy (Failed)
	 44 - short-heg_14_gamma-sjb-4-4-variance (Failed)
	 45 - short-heg_14_gamma-sjb-1-16 (Failed)
	 46 - short-heg_14_gamma-sjb-1-16-totenergy (Failed)
	 47 - short-heg_14_gamma-sjb-1-16-variance (Failed)
Errors while running CTest
```

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
CI has issue submitting jobs on rhea. @grahamlopez please have a look when you are available.

**Comment by grahamlopez** [comment]
I can't submit the job by hand, but the remote submission isn't working.
I've sent an email, but they may have already left for the day.

**Comment by prckent** [comment]
Test this please

**Comment by markdewing** [comment]
test this please

**Pull request merged**
