### PR TITLE
EstimatorManagerInput

### PR DESCRIPTION
**Pull request by PDoakORNL**
This PR creates a EstimatorManagerInput class and a method for delegating to the input classes of OperatorEstBase derived estimators and the mechanism by which an EstimatorManagerNew can be constructed from the EstimatorManagerInput. 

It will change the estimator input to be enclosed in an estimators node.  This provides a simple way for the Estimator Manager to take responsibility for that node and all children.  Then the eventual QMCSectionInput need only be aware of the EstimatorManagerInput.
```xml
<estimators>
<!-- all estimator nodes -->
<estimator type="MomentumDistribution" name="nofk" samples="5" kmax="3"/>
...
</estimators>
```

There are still some rough edges to smooth out but I think now that this is tested through the constructor of EstimatorManagerNew this is ready merging.

A later PR will remove the put and then the estimator input will be parsed in one step and the estimator manager constructed later.

## Proposed changes
The OperatorEstBase classes now take a constant reference to their input and the input classes are owned by the EstimatorManagerInput. This isn't optimal but seems necessary to break the parsing and construction phases apart.

The EstimatorManagerInput takes responsibility for the entire Estimators input node.

Once the Estimators input is parsed via EstimatorManagerInput and the EstimatorManagerNew is constructed via the EstimatorManagerInput the validation of estimator input will be quite complete and most of it will be at parse time.

## What type(s) of changes does this code introduce?
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by PDoakORNL** [comment]
I am not able to reproduce the gcc 11.2.0 compiler error at this time.  Looking for any help toward that.

**Comment by ye-luo** [comment]
> I am not able to reproduce the gcc 11.2.0 compiler error at this time. Looking for any help toward that.

The failed one treats warning as error. So you' need to resolve the warning.

**Comment by ye-luo** [comment]
Could you write some dev doc in the manual about the XML is stored and parsed and some examples?

**Comment by PDoakORNL** [comment]
I have tried and I don't get that warning with out with -Werror with gcc 11.2.0

**Comment by ye-luo** [comment]
I got the following warning with gcc-11.2
```
In member function ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >; _Args = {std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >}; _Tp = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >]’,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >; _Args = {std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >}; _Tp = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >]’ at /soft/gcc/gcc-11.2.0/include/c++/11.2.0/bits/alloc_traits.h:512:17,
    inlined from ‘std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >}; _Tp = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >; _Alloc = std::allocator<std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> > >]’ at /soft/gcc/gcc-11.2.0/include/c++/11.2.0/bits/vector.tcc:115:30,
    inlined from ‘void std::vector<_Tp, _Alloc>::push_back(std::vector<_Tp, _Alloc>::value_type&&) [with _Tp = std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> >; _Alloc = std::allocator<std::variant<std::reference_wrapper<qmcplusplus::SpinDensityInput>, std::reference_wrapper<qmcplusplus::MomentumDistributionInput>, std::reference_wrapper<qmcplusplus::OneBodyDensityMatricesInput> > >]’ at /soft/gcc/gcc-11.2.0/include/c++/11.2.0/bits/stl_vector.h:1204:21,
    inlined from ‘void qmcplusplus::EstimatorManagerInput::appendEstimatorInput(Args&& ...) [with T = qmcplusplus::SpinDensityInput; Args = {_xmlNode*&}]’ at /home/yeluo/opt/cleanup/qmcpack/src/Estimators/EstimatorManagerInput.h:74:31,
    inlined from ‘void qmcplusplus::testing::EstimatorManagerInputTests::testAppendFromXML(qmcplusplus::EstimatorManagerInput&, xmlNodePtr) [with T = qmcplusplus::SpinDensityInput]’ at /home/yeluo/opt/cleanup/qmcpack/src/Estimators/tests/test_EstimatorManagerInput.cpp:37:32,
    inlined from ‘void qmcplusplus::____C_A_T_C_H____T_E_S_T____0()’ at /home/yeluo/opt/cleanup/qmcpack/src/Estimators/tests/test_EstimatorManagerInput.cpp:94:45:
cc1plus: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
In file included from /soft/gcc/gcc-11.2.0/include/c++/11.2.0/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /soft/gcc/gcc-11.2.0/include/c++/11.2.0/bits/allocator.h:46,
                 from /soft/gcc/gcc-11.2.0/include/c++/11.2.0/string:41,
                 from /home/yeluo/opt/cleanup/qmcpack/external_codes/catch/catch.hpp:475,
                 from /home/yeluo/opt/cleanup/qmcpack/src/Estimators/tests/test_EstimatorManagerInput.cpp:12:
/soft/gcc/gcc-11.2.0/include/c++/11.2.0/ext/new_allocator.h: In function ‘void qmcplusplus::____C_A_T_C_H____T_E_S_T____0()’:
/soft/gcc/gcc-11.2.0/include/c++/11.2.0/ext/new_allocator.h:127:48: note: at offset 40 into destination object of size 32 allocated by ‘operator new’
  127 |         return static_cast<_Tp*>(::operator new(__n * sizeof(_Tp)));
      |                                  ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```
maybe you can try a fresh build.

**Review by ye-luo — CHANGES_REQUESTED** [review]
Need to break into smaller PRs.
There are new classes which can be upsteamed independently.

**Comment by PDoakORNL** [comment]
Will do.  Are you building on x86?

**Comment by PDoakORNL** [comment]
Yes that would help.  I'm wondering if this is just an issue of the compiler being less well developed wrt power9

**Comment by PDoakORNL** [comment]
This is getting broken up into a series of PR's now.

**Pull request closed without merging**
