### PR TITLE
Update performance/C-graphite input files.

### LINKED ISSUE #3630: graphite performance tests fail on initialization
**Describe the bug**

None of the graphite runs are working on any machine
https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=performance-C-graphite-cpu-a64-e256-1-16&date=2021-11-24
Symptom is consistent with a bad input file.

No machine other than sulfur or nitrogen is currently running these, so an install problem or finally surfaced bug in the application can not be ruled out. The NiO performance runs work on the same machines.

**To Reproduce**

ctest -R performance-C-graphite-cpu-a64-e256

Latest development version

**Expected behavior**
Tests pass

**System:**
Nightlies

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Closes #3630 

## What type(s) of changes does this code introduce?
- Bugfix in tests

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — COMMENTED** [review]
Thanks Ye. Are there sufficient digits in the positions?

**Comment by ye-luo** [comment]
> Thanks Ye. Are there sufficient digits in the positions?

I tested both full and mixed precision. Didn't get stopped.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
