### PR TITLE
Support QE v6.7.0

### LINKED ISSUE #2230: QE 6.5 support
This is a request from Fernando Reboredo and Tomohiro Ichibha.  They are anxious to use QE 6.5 to generate spin-polarized states with the SCAN functional for use in QMCPACK.  This would require an updated `download_and_patch_qe6.5.sh` script.

### PR DESCRIPTION
**Pull request by kgasperich**
## Proposed changes

adds a new patch for the latest version of QE. Closes #2230
This patches the [official v6.7.0 release](https://github.com/QEF/q-e/releases/tag/qe-6.7.0) to be up-to-date with the [release on Ye's fork](https://github.com/ye-luo/q-e/releases/tag/v6.7.0%2Bpw2qmcpack).

## What type(s) of changes does this code introduce?

- new converter patch for latest version of QE

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

- ALCF Cooley (built with mvapich 2.3.4, gcc 7.1.0)

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted (just a diff and a bash script)
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Thanks Kevin! What was the issue causing the problems with some of the tests in your previous PR? (Something we should remember for future patches of new QE versions.)

**Comment by kgasperich** [comment]
The filenames were not consistent in cases where pw2qmcpack split the data among multiple hdf5 files (there were [extra leading spaces](https://github.com/ye-luo/q-e/commit/455b7e329025e8e857b8f01bc5a0acab45e0e485#diff-7112d6cf7a1132755d38b2f6159c356b9698e4f37b747652601e406b3c56fd3aL414) before the part index, so data was being written to `*.pwscf.h5_part           1` instead of `*.pwscf.h5_part1`), but the function that read these parts to combine them into a single file for qmcpack [did not have the extra spaces](https://github.com/ye-luo/q-e/blob/e2b7e760e53c2397ed96470f277a3b123974c2c6/clib/esh5_interfaces.c#L871) in the filename.

**Comment by prckent** [comment]
Thanks. I was more fearful of a symmetry problem. Happily that was not the case.

I am currently building and testing this PR.

**Review by prckent — APPROVED** [review]
Confirmed working. Ran the qe workflow tests with both real and complex builds.

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
