### PR TITLE
Use RESOURCE_LOCK to run GPU performance tests exclusively

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Use RESOURCE_LOCK to run GPU performance tests exclusively at a time.
This feature is available since the minimal cmake version we support.

PS: minor update in Bora nightly script.

## What type(s) of changes does this code introduce?
- Other (please describe): testing

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Am I correct that with this fix we should be able to remove -DN_CONCURRENT_TESTS=1 from the GPU nightlies?

**Comment by prckent** [comment]
Why not set for all GPU tests? Long term NiO is clearly too local a place to set this.

**Comment by ye-luo** [comment]
> Am I correct that with this fix we should be able to remove -DN_CONCURRENT_TESTS=1 from the GPU nightlies?

It is intended for NiO performance tests only because of the memory contention and benchmark accuracy.
So it must be strictly 1 test at a time.
There is no reason to restrict small tests and N_CONCURRENT_TESTS=4 works fine on Bora.

**Comment by prckent** [comment]
OK. We get crashes with N_CONCURRENT_TESTS>1 on sulfur and nitrogen and their V100 cards.

**Pull request merged**
