### PR TITLE
Improve ppconvert

### PR DESCRIPTION
**Pull request by zenandrea**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Fix the conversion of casino format pseudos to xml format.
The behaviour was to take the cutoffs from the "summary.txt" file.
This file is no more provided on the new Trail and Needs pseudos (i.e., the CEPP and eCEPP).
Also, the cutoffs given there could be too short (for instance in the case of hydrogen).
In this change the behaviour is the following:
if the "summary.txt" file is not provided, the cutoffs are set to the point corresponding to an 
agreement of 1e-6 among the potentials in all the channels. 

## What type(s) of changes does this code introduce?

- Bugfix
- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Conversion of first row atoms

## Checklist

- Not sure. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
Better to add a test to cover casino pp to xml

**Review by prckent — CHANGES_REQUESTED** [review]
Just marking as changes requested consistent with the above discussion. Merge after addition of a test of the improved CASINO format conversion.

**Comment by prckent** [comment]
I looked at quickly adding the casino test, but it will require atomic wavefunctions https://qmcpack.readthedocs.io/en/develop/additional_tools.html#listing-72  or more time than I have with the atomic wavefunction solver. I don't think it wise to use untested parameters since someone will copy them. @zenandrea if you have time to make a test please do so in a later PR. Merging this one as is to keep things moving.

**Review by prckent — APPROVED** [review]

**Pull request merged**
