### PR TITLE
Add deterministic test of the excited state for batched driver

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

There are a lot of deterministic tests for batched driver now but missing tests of the observables for batched driver needs to be added.
This PR is to add deterministic test of the excited state which is still missing for batched driver tests. 
The other missing tests will be added in the order of priority.
  

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Other (please describe): Add tests

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
 Workstation

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Start testing in-house

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
Is the following documented anywhere?
```
                  <occupation mode="excited" spindataset="0">
                   -8 9
                  </occupation>
```

**Review by prckent — COMMENTED** [review]
I think we might be missing a short/long test of this specific excitation. How do we know that the batched implementation is correct &/or consistent with the unbatched case? This test is a good check to catch future changes, but if we don't already have a statistical batched excitation test or other way to know that the excitation code is correctly invoked, then the test is needed.

**Comment by Hyeondeok-Shin** [comment]
For the wavefunction example, only (ti, bi) notation is included in the manual, but nexus example shows both (ti, bi) and orbital index notation. (https://qmcpack.readthedocs.io/en/develop/lab_excited.html?highlight=excited#basics-and-excited-state-experiments)  We may add example for the orbital index notation to the manual. 

 Right. short/long statistical test for the excited state is needed for both batched and unbatched code to see if it is working well. I will add those after this PR.

**Comment by prckent** [comment]
@Hyeondeok-Shin When you make the statistical cases for the batched code, please can you add a short description in the main part of the manual? The lab should not be the first place this is mentioned. Somewhere in the "Trial wavefunction specification" section looks appropriate.

**Review by prckent — APPROVED** [review]
LGTM.
Additional tests+docs for later PR as discussed.

**Pull request merged**
