### PR TITLE
Update reference ParticleSet handling in VirtualParticleSet

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
It is better to update the reference ParticleSet whenever makeMoves happen.

## What type(s) of changes does this code introduce?
- Refactoring

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by camelto2** [comment]
Failing tests seem to be due to the test_ecp.cpp Evaluate_soecp tests. Need to add elec.isSpinor(true); to test_ecp.cpp:480

**Comment by ye-luo** [comment]
Test this please

**Comment by camelto2** [comment]
LGTM

**Review by camelto2 — APPROVED** [review]
LGTM

**Pull request merged**
