### PR TITLE
Add unit tests for gaussian basis sets.

### PR DESCRIPTION
**Pull request by markdewing**
Test the radial part and the angular part (cartesian functions).
Fix a few errors found in the third derivative tensors in the angular part.

Split the creation of a gaussian combo from the XML parsing.

### CODE REVIEW

**Comment by prckent** [comment]
@markdewing Do you really need or prefer to have Anouar's review or can I merge before you have it?

**Comment by prckent** [comment]
@markdewing Does the SOA implementation pass?

**Comment by markdewing** [comment]
@prckent I added Anouar as a reviewer because he had been working on the gaussian parts (at least for the converter).   It could be checked in w/o his review.
I will test the SOA build now.

**Comment by markdewing** [comment]
The unit tests pass with the SOA build

**Comment by prckent** [comment]
Thanks all.

**Pull request merged**
