### PR TITLE
Add output to DMC CPU driver.  Indicates status of t-moves

### PR DESCRIPTION
**Pull request by rcclay**
Oddly, DMCOMP doesn't display status of non-local moves, whereas DMC_CUDA does.  This writes a line of output to standard out.

### CODE REVIEW

**Comment by prckent** [comment]
Changed DMC_CUDA.cpp to match.

**Comment by ye-luo** [comment]
The print must be in run().
The flag used to distinguish T-move is different from the one actually used in the mover.
This place only print once when the movers are created but the code actually allows switch on and off T-moves in different DMC blocks.

**Comment by ye-luo** [comment]
@rcclay please resubmit a PR.
1, remove NonLocalMove in DMCOMP.h and DMCOMP.cpp
2, add a function in QMCUpdateBase which return the value of UseTMove
3, print from the end of resetUpdateEngines after "std::ostringstream o"
4, apply the same change on DMC_CUDA

**Comment by rcclay** [comment]
@ye-luo Thanks for the heads up.  I'll try to resubmit over the weekend.

**Pull request merged**
