### PR TITLE
Pyscf implementation and testing improvements 

### PR DESCRIPTION
**Pull request by anbenali**
- Cleaning code from large test  files
- Correcting Exit error for Spherical orbitals if AoS
- Moving FeCO6 tests from short to long

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Are the reference numbers in the tests correct? The following is with Intel2018 SoA. I tried several times.

ctest -R "short.*pyscf.*" -VV &>log

The following tests passed:
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-16-1
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-16-1-kinetic
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-16-1-samples
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-4-4
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-4-4-samples
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16-kinetic
	short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16-samples

53% tests passed, 7 tests failed out of 15

Label Time Summary:
QMCPACK                     =  56.47 sec (3 tests)
QMCPACK-checking-results    =   0.34 sec (12 tests)

Total Test time (real) =  56.98 sec

The following tests FAILED:
	146 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-16-1-totenergy (Failed)
	147 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-16-1-eeenergy (Failed)
	150 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-4-4-kinetic (Failed)
	151 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-4-4-totenergy (Failed)
	152 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-4-4-eeenergy (Failed)
	156 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16-totenergy (Failed)
	157 - short-LiH_dimer_ae_pyscf-vmc_hf_noj-1-16-eeenergy (Failed)
Errors while running CTest

**Comment by ye-luo** [comment]
In LiH dimer tests, both quantum package and pyscf LiH needs to use reference number from the original codes. Currently seems not. The one for Gamess is.

**Comment by prckent** [comment]
@anbenali We'll merge now so that the long tests can run over the weekend. The reference values for some of the tests need updating as noted by @ye-luo . This will be obvious as consistent test failures in cdash.

**Pull request merged**
