### PR TITLE
AFQMC kernel unit tests

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Add unit tests to cover kernels before portability work.

## What type(s) of changes does this code introduce?

- Other (please describe): Tests

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

intel xeon + summitish

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by fdmalone** [comment]
I need to remove some functions and enable one or two tests before merging.

**Comment by fdmalone** [comment]
Good to go now.

**Comment by ye-luo** [comment]
Okay to test

**Comment by fdmalone** [comment]
I think it should be good now.

**Comment by fdmalone** [comment]
yikes, give me a minute.

**Comment by fdmalone** [comment]
is __CUDA_ARCH__ < 600 for alcf-gnu-CUDA. The mkl failure looks unrelated to this PR.

**Comment by ye-luo** [comment]
CUDA_ARCH default is sm_35. Could you reproduce the failure if you leave CUDA_ARCH unset and build on your machine? The alcf-gnu-mkl18 failure is just a glitch.

**Comment by fdmalone** [comment]
Yeah. I was building with sm_70. I need to undo some things.

**Comment by ye-luo** [comment]
CUDA documentation mentions it only available for double since 600. Could you adopt the workaround provided in the doc?

**Comment by fdmalone** [comment]
It was there originally. I removed it in this PR.

**Comment by mmorale3** [comment]
The workaround is stupidly slow, makes the entire code useless if it is actually needed.
In my opinion, the AFQMC code does have the constraint CUDA_ARCH >= 600

**Comment by ye-luo** [comment]
Leave that workaround so we can still use sm_35 but we may raise the default value to sm_60 or sm_70 to prevent people hitting there by default.

**Comment by mmorale3** [comment]
Why are we doing the CI with sm_35? Do we actually support Kepler?
Even Maxwell is a real stretch. I don't see how any of the newer code will be able to maintain this.
Can you do offload to Kepler or Maxwell?

**Comment by ye-luo** [comment]
Yes. I can offload to kepler. For people trying on kepler, slow code is better than not build.
If we find too many workaround needed for kepler, we can consider drop it.
I also think we should raise the default arch to at least pascal.

**Comment by prckent** [comment]
I strongly vote in favor of a Pascal or Volta default and forgetting previous generations (it is 2020!). The current default is also clearly bad and I was thinking of PRing it to Volta in any case. We can discuss elsewhere as needed.

**Comment by fdmalone** [comment]
Sorry for the delay. Had to walk dog.

**Pull request merged**
