### PR TITLE
Change walker offset IO handling.

### PR DESCRIPTION
**Pull request by ye-luo**
Hit some issue on Mira when using >= 32768 ranks.

walker offsets (an array) of all the nodes are recorded in the config.h5 for restart.
It was written by every node to the file even though the file is open in collective IO mode.
It is not a problem when the node count was small (<=16384). With a large node count, hdf5 library crashed inside.
Changes to the offset IO:
write: collectively by every node, each contribute its own offset. The last node contributes 2 (for the end)
read: since the next run can be with a different node count, offset now is loaded by the master node and broadcast to all the nodes.
performance:
Both IO operations are measured faster.

Restart miniapp has passed all the checks with 65536 ranks.
restart tests also pass.

Wait for a big run (in a few days) on Mira before merge.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
Updated the PR comments and pasted the story into the commit log. Also updated in-source comments.

**Comment by prckent** [comment]
@ye-luo Will merge when you give the OK based on your test run (ECP ALCC time hopefully)

**Comment by ye-luo** [comment]
My jobs are near the top of the queue. I will comment when it passes through.

**Comment by ye-luo** [comment]
My big run confirms that the IO library crash is resolved. This PR is safe to merge.
Sadly, the restart still have some other issue at scale. Will PR when the issue is resolved.

**Pull request merged**
