### PR TITLE
Nexus: add PySCF examples

### PR DESCRIPTION
**Pull request by jtkrogel**
In this PR, examples are added for PySCF and PySCF to QMCPACK workflows for both molecular and solid state cases (water molecule and diamond).

There are two issues that remain before this PR can be merged.
- In the PySCF to QMCPACK workflow for all electron water, the QMCPACK total energy does not agree with PySCF Hartree-Fock (deferred until later)
- [x] In the PySCF to QMCPACK workflow for diamond, convert4qmc changes its output format relative to the molecular case (it appends "Twist0" to all file names).  This should not happen unless requested (moving target for both users and Nexus).  The existing -prefix mechanism might be preferred here.

Once confirmed by @anbenali, separate GitHub issues + resolution can be made for these points.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
@anbenali Any comments on the second point?  Is this a reasonable change?

**Comment by anbenali** [comment]
To address point 2, give me 1 or 2 more hours t and finalize the new API
for solids as the complex evaluation is almost complete. In the PR in
progress your point is addressed I believe but I am still finalizing a few
details.

For the water energy that is weird.. can you give more details?

**Comment by jtkrogel** [comment]
For point 2, all that is needed is that the files made by convert4qmc have the same names whether you are running a molecule or a solid.

For the water case (point 1), this is what I get with PySCF:
```
converged SCF energy = -76.0302783714398
```
And this is what I get with QMCPACK:
```
viribus>qmca -e 200 -q e *scalar*
vmc  series 0  LocalEnergy           =  -74.856150 +/- 0.058227 
```
The files are attached.  See scf.py, c4q.in, and vmc.in.xml.  Hopefully it is a novice mistake on my part.
[for_anouar.zip](https://github.com/QMCPACK/qmcpack/files/3109096/for_anouar.zip)

**Comment by jtkrogel** [comment]
@anbenali I see it now.  Pyscf is changing the atomic coordinates (presumably because symmetries are on?)

This is the input structure (angstrom):
```
 H    0.00000000   0.75716000   0.58626000
 H    0.00000000   0.75716000  -0.58626000
 O    0.00000000   0.00000000   0.00000000
```

This is what comes out of convert4qmc:
```
    <attrib name="position" datatype="posArray">
  0.0000000000e+00  0.0000000000e+00 -2.8616500650e-01
  0.0000000000e+00  1.1078708378e+00  1.1446600260e+00
  0.0000000000e+00 -1.1078708378e+00  1.1446600260e+00
</attrib>
    <attrib name="ionid" datatype="stringArray">
 O H H 
</attrib>
```

**Comment by anbenali** [comment]
Point 2 has been address in PR #1560. Point 1 is strange... Let me look at it.. yes symmetries are on but this is strange to move the Oxygen atom coordinates...

**Comment by anbenali** [comment]
@jtkrogel  : changes that will enable this PR are now awaiting in PR #1578

**Comment by jtkrogel** [comment]
Please go ahead and merge this one in.  I can check for compatibility and post a brief update if needed.

**Pull request merged**
