### PR TITLE
EstimatorManager refactor and mpi population fix

### PR DESCRIPTION
**Pull request by PDoakORNL**
## Proposed changes

This was originally just a refactor partial rewrite of EstimatorManager to support correct averaging. 
However by the time it was ready changes that broke DMCBatched had been introduced into develop.
These are also address here, the amount of effort that will be required to pull these apart in this not yet production code is not worth it from my perspective.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix: averaging is no longer done at multiple levels (this could result in errors due to variable number of walkers per crowd and rank.) In practice with a high walker count these errors should be very small (i.e. previous science does not include large errors from this.)
- Code style update (formatting, renaming) Since much of this was chasing subtle bugs whenever clarity would help, changes were made.
- Refactoring (no functional changes, no api changes)
- Build related changes: Additional tests were added in appropriate files that are added to the build.
- For Debug builds:  a number of and `#ifndef NDEBUG`  sections were added to trap bad numerical situations and invalid states.

### Does this introduce a breaking change?

- No (or not to code that was actually working)

## What systems has this change been tested on?
Leconte

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Thanks Peter! I think it important to stress that we believe that the previous averaging was incorrect, even if not obviously so and very subtly so under most circumstances. So this PR tackles an additional important bug besides the MPI.

**Comment by jtkrogel** [comment]
Does this affect estimators measured with the non-batched drivers?

**Comment by prckent** [comment]
@jtkrogel It is a good question whether and how this affects existing behavior or not. We definitely don't do sufficient MPI testing yet (historically this has not been a major source of bugs). 

How can we get better at DMC and observable testing?

**Comment by jtkrogel** [comment]
We have two MPI DMC estimator tests that work:

 short-diamondC_1x1x1_pp-dmc-estimator-density-4-4-check
 short-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4-check

The full and partial sum tests (statistical, removes equilibration equilibration) all pass:

https://cdash.qmcpack.org/CDash/testDetails.php?test=8965672&build=127786

The tests also correctly detect that the first DMC block is wrong (see issue #934), and so the test as a whole fails:

```
  Fixed sum per block tests:
    d 0 4.000010681199691!=4.0
    u 0 4.000010681199691!=4.0
    some per block sums do not match the reference
    status of this test: fail
```

These tests should be run for the current PR and the test output manually checked to verify that the full and partial sum tests still pass with these code changes.

**Comment by jtkrogel** [comment]
Actually, it would be ideal if Peter would just post here the full test output similar to what the cdash link above shows.

**Comment by ye-luo** [comment]
I think it is better to split the EstimatorManager refactor with MPI fix. EstimatorManager can be independently validated with VMC.

**Comment by jtkrogel** [comment]
Separated or not, each can affect estimators so I would like to see DMC tests of estimators for both.

**Comment by ye-luo** [comment]
> Separated or not, each can affect estimators so I would like to see DMC tests of estimators for both.

We need EstimatorManager with VMC test validation.
Then Fix DMC population control in batched driver. I'm not confident with the current fix.
Then fix DMC estimator tests.

**Comment by PDoakORNL** [comment]
This should be no change for legacy code.  I would rather not split this PR again.  The only reason the mpi update is with it is that the mpi was completely broken by other code added while I prepared the estimator manager refactor.  My code has been based on this change to estimator manager for the unified driver for quite some time.  If I split this again it must be accepted first. I will not restore the clearly incorrect averaging behavior of the legacy code to the unified driver again.  I'm not even sure I could easily replicate it without just rolling all this back and starting again.

**Comment by prckent** [comment]
Someone needs to run the short tests on CPU and with legacy CUDA for this PR. Who has bandwidth? (I don't, at least not for a few days, and we should get this merged sooner if we can.)

**Comment by PDoakORNL** [comment]
I was going to try to in a background thread but I owe other projects some time. I'd like to see it correct for develop first. I get a link error with the current develop and clang 7.9.0 need to figure out whether that is real or not. Then I will run it for this PR. Probably not today or tomorrow.

**Comment by ye-luo** [comment]
Let us do the "split" in a less burden way. in QMCAPCK repo, make a new branch Staging_Fix based on the current develop. Then split the touch files into several topics and make PRs to Staging_Fix branch. It is not required to Staging_Fix to build when we are dealing with individual PRs. Once all these PRs are merged to Staging_Fix, we make PR Staging_Fix to develop at that point, CI is fully required.

**Comment by PDoakORNL** [comment]
With i.e. clang 7.9.0 and the CPU build both the debug and release version of the dmc-estimator-density-4-4-check crash.

**Comment by prckent** [comment]
That estimator currently runs reliably with gcc, Intel, Clang e.g. https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=short-diamondC_1x1x1_pp-dmc-estimator-density-4-4&date=2020-07-15

**Comment by PDoakORNL** [comment]
I'm builidng a current gcc stack to build it and will go try it on x86 when I can.  But don't be alarmed and I'll be closing this PR soon to begin trying to PR it as "topics"

**Pull request closed without merging**
