### PR TITLE
Build with timer on by default

### LINKED ISSUE #2663: ENABLE_TIMERS=ON on by default
Our timer codes actually have near zero overhead if the level is set to none.
So I'd like to build with timers and set the level to none by default.
-DENABLE_TIMERS=OFF will be allowed for a while.
If we found it never needed, this build option will be removed.

Any comments?

### LINKED ISSUE #2664: Offload code should print GPU info
**Is your feature request related to a problem? Please describe.**

When compiled for offloading to accelerators there is very little information printed about which accelerators are available, what type they are, or even that the run is accelerated. The output file is therefore an incomplete record. We do print the MPI task and CPU OpenMP threading setup.

**Describe the solution you'd like**

Print the device count and ideally the types of devices.

**Describe alternatives you've considered**

None

**Additional context**

I could not find a vendor independent way to get more than the device count, but perhaps I missed an API call.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Default level is "coarse".
I don't see timing difference running a 16 electron system with timer=none and without timer built in (current develop branch).
Closes #2663 
offload info printing is added and closes #2664 

## What type(s) of changes does this code introduce?
- Build related changes
- Documentation content changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes.  Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by markdewing** [comment]
Would 'coarse' be a more useful default setting?

**Comment by ye-luo** [comment]
none collects nothing.

coarse:
```
Timer      Inclusive_time  Exclusive_time  Calls       Time_per_call
Total         1.7200     0.0005              1       1.720007896
  Startup     1.6674     1.6674              1       1.667369843
  VMC         0.0521     0.0521              1       0.052104950
```
medium
```
Timer                               Inclusive_time  Exclusive_time  Calls       Time_per_call
Total                                  1.7162     0.0006              1       1.716240883
  Startup                              1.6634     1.4933              1       1.663425922
    einspline::CreateSPOSetFromXML     0.1702     0.1702              2       0.085076451
  VMC                                  0.0522     0.0019              1       0.052225113
    QMCUpdateBase::WalkerInit          0.0031     0.0031              1       0.003136158
    VMCUpdatePbyP::Buffer              0.0001     0.0001             24       0.000005732
    VMCUpdatePbyP::Collectables        0.0000     0.0000             12       0.000000636
    VMCUpdatePbyP::Hamiltonian         0.0117     0.0117             12       0.000974039
    VMCUpdatePbyP::MovePbyP            0.0354     0.0354             12       0.002948523
```
fine
```
Stack timer profile
Timer                                    Inclusive_time  Exclusive_time  Calls       Time_per_call
Total                                       1.7419     0.0006              1       1.741889954
  Startup                                   1.6887     1.5040              1       1.688730001
    EwaldRef                                0.0013     0.0000              1       0.001332998
      EwaldSum                              0.0012     0.0012              1       0.001194954
      MadelungSum                           0.0001     0.0001              1       0.000123978
    ParticleSet::update                     0.0004     0.0004              4       0.000094831
    einspline::CreateSPOSetFromXML          0.1830     0.1830              2       0.091489911
      ParticleSet::update                   0.0000     0.0000              1       0.000000954
  VMC                                       0.0526     0.0016              1       0.052606821
    QMCUpdateBase::WalkerInit               0.0030     0.0000              1       0.002980947
      Hamiltonian::ElecElec                 0.0000     0.0000              1       0.000007153
      Hamiltonian::IonIon                   0.0000     0.0000              1       0.000000000
      Hamiltonian::Kinetic                  0.0000     0.0000              1       0.000000954
      Hamiltonian::LocalECP                 0.0000     0.0000              1       0.000004053
      Hamiltonian::NonLocalECP              0.0009     0.0000              1       0.000912905
        ParticleSet::update                 0.0000     0.0000              7       0.000003304
        WaveFunction::SlaterDet_NLratio     0.0009     0.0000              7       0.000122241
          DiracDeterminantBase::ratio       0.0000     0.0000              7       0.000000170
          DiracDeterminantBase::spoval      0.0009     0.0004              7       0.000121798
            SplineC2COMP::offload           0.0005     0.0005              7       0.000071219
        WaveFunction::jastrow_NLratio       0.0000     0.0000             14       0.000001652
      ParticleSet::update                   0.0001     0.0001              1       0.000113010
      WaveFunction::SlaterDet_buffer        0.0001     0.0000              3       0.000041008
        DiracDeterminantBase::buffer        0.0001     0.0001              4       0.000025749
      WaveFunction::SlaterDet_recompute     0.0018     0.0000              1       0.001781940
        DiracDeterminantBase::inverse       0.0003     0.0003              2       0.000166416
        DiracDeterminantBase::spovgl        0.0014     0.0010              2       0.000722051
          SplineC2COMP::offload             0.0004     0.0004              2       0.000197411
      WaveFunction::jastrow_buffer          0.0000     0.0000              6       0.000000834
      WaveFunction::jastrow_recompute       0.0000     0.0000              2       0.000007033
    VMCUpdatePbyP::Buffer                   0.0001     0.0000             24       0.000006189
      ParticleSet::update                   0.0000     0.0000             12       0.000000000
      WaveFunction::SlaterDet_buffer        0.0001     0.0000             24       0.000004639
        DiracDeterminantBase::buffer        0.0001     0.0001             48       0.000001942
```

I can't really tell which is better none or coarse. coarse level overhead is also negligible.
The info printed in coarse level timer is also very limited.

**Comment by markdewing** [comment]
The 'coarse' setting would at least show that the code does have timers.

**Comment by prckent** [comment]
My vote is coarse based on the presented timing data.

I added a help message after the table (hopefully does not break clang-format) since we will now be routinely printing it. Improve if you wish.

**Comment by ye-luo** [comment]
Done. Changed default level to coarse.

**Comment by ye-luo** [comment]
> My vote is coarse based on the presented timing data.
> 
> I added a help message after the table (hopefully does not break clang-format) since we will now be routinely printing it. Improve if you wish. We would like users to know that not only do we have timers but they can control them.

I moved the user massage to before the timer printout and shared by stack/flat timers.
When timer is coarse, little difference between and after the 5 lines of timer printout.
clang-format didn't complain.

**Comment by ye-luo** [comment]
From the timer, it seems actually putting fine is not an issue as well. Keep this in mind.

**Comment by prckent** [comment]
I have higher levels of paranoia. We can revisit after one successful release with coarse.

**Comment by prckent** [comment]
(I'll assume Mark's approval based on the comments above. This is not a high risk PR.)

**Review by prckent — APPROVED** [review]

**Pull request merged**
