### PR TITLE
Cleanup structor factor; Remove QMC_SK_USE_RECURSIVE

### PR DESCRIPTION
**Pull request by ye-luo**
As discussed in #972, remove QMC_SK_USE_RECURSIVE.

### CODE REVIEW

**Comment by ye-luo** [comment]
Actually, I feel "omp simd" is a better way to go in the future. eval_e2iphi should be retired.
1. simdized sincos needed by omp simd loop is available via libsmvl(intel) and libmvec(glibc). There is no more need to explicitly call vector specific math functions. With omp simd, a larger loop body can be vectorized instead of only one math function. To call the explicitly vectorized math library, scratch arrays are often needed but they all go away with "omp simd".
2. The vendor vector math library may also contain threading. Our vector math calls are not big enough to high omp parallel overhead. I noticed huge slowdown on such calls when nested parallelism is enabled. In the case here, there is no need to use nested parallelism at all. In other cases, the threaded region needs to be at the outer levels.  So it is better to have explict control than relying on the library which does unnecessary things out of our hands.
3. Profiler shows Intel compiler turns sincos into libsvml calls. With gnu, the glibc 2.23 libmvec sincos bug was triggered, namely the libmvec is used. I saw the new "omp simd"+libsvml implementation do runs faster than calling intel MKL vector math library although the change is negligible comparing to the overall walltime.

**Comment by ye-luo** [comment]
This portion is always very small (32 atom 3%, 128 atom <1%). For a while after we updated the cmake, we didn't use the AMD math library for Titan CPU. After that was fixed, I saw the gain was very marginal. I can't answer for all the platforms but our performance data will tell us more.

The libmvec bug only exists in 2.23 which is used by 16.04LTS but any newer Ubuntu is fine. On my desktop, I just built a newer glibc but removed everything but libmvec and then add the path to the LD_LIBRARAY_PATH.

**Comment by ye-luo** [comment]
The performance degradation is real on non-Intel compilers due to inability of proper vectorization. Since there is only 1 hot path, I just put an ifdef.

**Comment by prckent** [comment]
OK. We can track for other compilers + platforms and then update over time, hoping for simplification.

Do you have any suggestions for how to track these? List of known issues by platform? As several issues, multiple issues? We aren't short of GitHub issues.

**Comment by grahamlopez** [comment]
test this please

**Pull request merged**
