### PR TITLE
Remove owning raw pointers from HEGGrid

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Remove raw owning pointers by replacing `std::vector<PosType>*` with `std::vector<PosType>` and `kpoints_t*` with `std::optional<kpoints_t>`. I also removed the unused 2D specialization.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by PDoakORNL — APPROVED** [review]
This simplifies a number of aspects of HEGGrid.

**Comment by prckent** [comment]
Peter's point is a good one imo - move OHMMS_DIM to constants and to avoid magic numbers + for clarity.

**Review by prckent — CHANGES_REQUESTED** [review]
Peter's point is a good one imo - move OHMMS_DIMS to constants and to avoid magic numbers + for clarity. Can we avoid "3"s here?

Of course all the buffer packing is full of magic numbers, but it is a good idea to avoid increasing them.

**Comment by ye-luo** [comment]
Please hold on moving OHMMS_DIMS to Constants.h which is intended for fixing machine/OS/glibc related constants. Keep OHMMS_DIM in config.h.cmake.in for now, we maybe can move it to Configuration.h.

**Review by ye-luo — APPROVED** [review]
LGTM now

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
After discussion, we leave the dimensionality constant for now.

**Pull request merged**
