### PR TITLE
Update AFQMC visitor signature to add another unimplemented case

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

This is to maintain compatibility of the AFQMC code with new versions of Multi 

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 21.10 with cuda 11.3

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by markdewing** [comment]
(to maintainers) "Squash and merge" might be a good choice for this PR when merging.

**Review by markdewing — APPROVED** [review]

**Comment by correaa** [comment]
is that something I can still edit in this PR? I can't find the option.

**Comment by markdewing** [comment]
@correaa That option is nothing you need to do on this PR.  It's an option for the maintainers for merging it after the tests pass.

**Comment by correaa** [comment]
> @correaa That option is nothing you need to do on this PR. It's an option for the maintainers for merging it after the tests pass.

ok, I was confused because in gitlab you have the option to squash the PR when one creates it.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
