### PR TITLE
OneBodyDensityMatrices port evaluateMatrix + test

### PR DESCRIPTION
**Pull request by PDoakORNL**
## Proposed changes

Continuing port of `QMCHamiltonians/DensityMatrices1B` aka 1RDM --> `Estimators/OneBodyDensityMatrices`

Working on making test portable.  Obviously something is not as I expect with the std libraries mersenne twister or my wrapper.

Added the known working single walker evaluation method (as reported by @jtkrogel ) evaluateMatrix and added a "no change" unit test. This is not ideal but something better can be introduced in its place in the future.

This is still not connected to EstimatorManagerNew or the batched production it is just one more set of methods and a unit test of the key method.

To save some review time here are things I know are bad and will be fixed in future PR:
1.  inconsistent argument order for internal methods.
2. The delegated copy constructor.
3. Lack of unit tests for various basis generation functions and warmup sampling.
4. The odd semantics of the steps argument of generateSamples.

## What type(s) of changes does this code introduce?

- New feature
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Leconte

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by PDoakORNL** [comment]
In commit f771f6df189de02bc5d5ff29903ab1aabdd19421 I combine an initialization and assign and get different floating point values in Debug then I did before.  It's puzzling but shared behavior in gcc x? and clang 14.

**Comment by PDoakORNL** [comment]
Failure is some sort of pull failure

**Comment by ye-luo** [comment]
Yes. Jenkin's issue with moving HEAD in develop.

**Review by ye-luo — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Start testing in-house

**Pull request merged**
