### PR TITLE
Fix DLA+TMv1

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
The bug affects DLA+TMv1.
Tested and got consistent results with DLA+TMv0/1/3.

## What type(s) of changes does this code introduce?
- Bugfix
### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora
## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Review by PDoakORNL — APPROVED** [review]
This looks good to me.

**Review by prckent — COMMENTED** [review]
LGTM also. Does this pass Andrea's test? Do we exactly reproduce the other implementations now or are there some remaining differences?

**Comment by ye-luo** [comment]
> LGTM also. Does this pass Andrea's test? Do we exactly reproduce the other implementations now or are there some remaining differences?

I didn’t do full range of tests but the reproducer I got seems producing the correct numbers.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
