### PR TITLE
Move uninitialized array

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Move unitialized_array from CUDA_legacy to external_codes/thrust. Addresses #2634

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

amd mi60 / nvidia volta

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Please update legacy CUDA source files which use this header as well.

**Comment by fdmalone** [comment]
I think the real space cuda source files use thrust/.../util.h already? I can't see anyone including uninitialized.hpp or uninitialized_array.hpp

**Comment by fdmalone** [comment]
nvm

**Comment by ye-luo** [comment]
> I think the real space cuda source files use thrust/.../util.h already? I can't see anyone including uninitialized.hpp or uninitialized_array.hpp

$ grep -R 'CUDA_legacy/uninitialized_array.hpp' src
src/QMCWaveFunctions/detail/CUDA_legacy/determinant_update.cu:#include "CUDA_legacy/uninitialized_array.hpp"

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
