### PR TITLE
Added /docs for sphinx

### PR DESCRIPTION
**Pull request by jbatson5**
Conversion up to chapter 4 of the manual

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This PR adds a docs directory for sphinx (readthedocs). Conversion of the manual is up to chapter 4. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Documentation content changes

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

This PR is up to date with current the current state of 'develop'. Yes.
Code added or changed in the PR has been clang-formatted. N/A.
This PR adds tests to cover any new code, or to catch a bug that is being fixed. N/A.
Documentation has been added (if appropriate). Yes.

### CODE REVIEW

**Comment by fdmalone** [comment]
Looks great.

**Comment by jtkrogel** [comment]
What about everything in the `docs/_build` directory?  Aren't these temporaries?  I don't think we want to merge these.

**Comment by fdmalone** [comment]
I wasn't sure whether we want to ship the html version of the manual or expect people to build it themselves?

**Comment by prckent** [comment]
@fdmalone We will setup readthedocs to generate the manual so no one will need to build it routinely. The only people who are likely to be building the manual will be contributors and developers. And one day we'll have a CI robot.

**Comment by prckent** [comment]
@jbatson5 Confirming that I was able to produce HTML and PDF output using my own sphinx install.

**Pull request closed without merging**
