### PR TITLE
Remove ComputeForces flag in NLPP

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Phasing out `ComputeForces` flag in Hamiltonian member classes. It was used to control force related calculation during Hamiltonian evaluation which is no longer needed. ACForce estimator calls evaluateIonDerivs explicitly for the force calculation. Similar change will be made in Coulomb classes with `ComputeForce`.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — COMMENTED** [review]
Can you confirm that the force integration tests are OK? They are not run in CI.

**Comment by ye-luo** [comment]
> Can you confirm that the force integration tests are OK? They are not run in CI.

yes. I manually tested it.

**Review by prckent — APPROVED** [review]

**Review by rcclay — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
