### PR TITLE
Remove helper header and update multi

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi the last release and remove unnecessary header from AFQMC Utilities directory.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
The test are failing because of a missing, `<memory_resource>` header. https://github.com/QMCPACK/qmcpack/actions/runs/3048031166/jobs/4912661702#step:8:756

The header is a standard C++17 header if I understand correctly.
https://en.cppreference.com/w/cpp/header/memory_resource

**Comment by markdewing** [comment]
Not supported until gcc 9.1, it appears
https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017

**Comment by ye-luo** [comment]
I feel better to move on with requiring gcc 9 before doing that I need to check production machines
https://github.com/QMCPACK/qmcpack/issues/4011
and also CI needs update.

**Comment by ye-luo** [comment]
Please take a look at intel classic 20.2 failure.
I tested with gcc 9.4 libstdc++ and got the same error as CI https://github.com/QMCPACK/qmcpack/actions/runs/3048031166/jobs/4912661265

**Comment by correaa** [comment]
Intel 19 seems to be use the library of GCC 8, which seems to have a defect in type traits from the point of view of C++17.
https://github.com/QMCPACK/qmcpack/actions/runs/3048031166/jobs/4912661265#step:8:62

**Comment by ye-luo** [comment]
> Intel 19 seems to be use the library of GCC 8, which seems to have a defect in type traits from the point of view of C++17. https://github.com/QMCPACK/qmcpack/actions/runs/3048031166/jobs/4912661265#step:8:62

I got this with gcc 9.4
```
[ 45%] Building CXX object src/AFQMC/CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o
In file included from /scratch/opt/qmcpack/src/AFQMC/Hamiltonians/FactorizedSparseHamiltonian.h(17),
                 from /scratch/opt/qmcpack/src/AFQMC/Hamiltonians/Hamiltonian.hpp(24),
                 from /scratch/opt/qmcpack/src/AFQMC/Hamiltonians/HamiltonianFactory.h(13),
                 from /scratch/opt/qmcpack/src/AFQMC/AFQMCFactory.h(25),
                 from /scratch/opt/qmcpack/src/AFQMC/AFQMCFactory.cpp(25):
/nfs/gce/projects/QMCPACK_dev/spack/opt/spack/linux-ubuntu18.04-skylake_avx512/gcc-8.3.0/gcc-9.4.0-o37xaisenxcyp6a7dxoqfdv5sf3kwwce/include/c++/9.4.0/type_traits(1329): error: class "std::__is_convertible_helper<<error-type>, double *, false>" has no member class "type"
      : public __is_convertible_helper<_From, _To>::type
                                                    ^
          detected during:
            instantiation of class "std::is_convertible<_From, _To> [with _From=<error-type>, _To=double *]" at line 2993
            instantiation of "const bool std::is_convertible_v [with _From=<error-type>, _To=double *]" at line 831 of "/scratch/opt/qmcpack/external_codes/boost_multi/multi/include/multi/array_ref.hpp"
```

**Comment by prckent** [comment]
Test this please

**Comment by correaa** [comment]
I will be able to try fix this with `icpc (ICC) 2021.4.0 20210910`. What version is this "Intel 19" in the CI, is it "2020.4"?

**Comment by prckent** [comment]
Whatever reports as 19.1.3.20200925 in cmake. This and other details can be found out by drilling into the configure step of the failed test.

**Comment by ye-luo** [comment]
> I will be able to try to reproduce the error with `icpc (ICC) 2021.4.0 20210910`. What version is this "Intel 19" in the CI, is it "2020.4"?

Make your icc work and then we will use your fix to figure out how older Intel compilers work.

**Comment by correaa** [comment]
Any magic words to use an standard library that is compatible with icpc for QMCPACK?
I am getting a `-- libstdc++/C++ compiler version compatibility check failed`.


```
 $ export CXX=/home/correaa/intel/oneapi/compiler/latest/linux/bin/intel64/icpc
[  9:26PM ]  [ correaa@cuk:~/qmcpack/build(develop✔) ]
 $ export CC=/home/correaa/intel/oneapi/compiler/latest/linux/bin/intel64/icc 
[  9:26PM ]  [ correaa@cuk:~/qmcpack/build(develop✔) ]
 $ cmake -D CMAKE_BUILD_TYPE=Release ..
-- Defining the float point precision
   Base precision = float
   Full precision = double
-- CMAKE_BUILD_TYPE is RELEASE
-- LMY engine is not compatible with CPU mixed precision build! Disabling LMY engine
-- Enable sanitizer ENABLE_SANITIZER=none
-- Trying to figure out compiler options ....
-- C++ Compiler is identified by QMCPACK as : Intel
-- libstdc++/C++ compiler version compatibility check failed
CMake Error at CMake/Testlibstdc++.cmake:17 (message):
  Change Dir: /home/correaa/qmcpack/build/CMakeFiles/CMakeTmp

```

**Comment by ye-luo** [comment]
Put gcc 9 on your path and verify with `icpx -v`.

**Comment by correaa** [comment]
Thank you for the quick response. `g++-9` is in the path, if this below is what you mean:

```
$ which g++-9                                                         
/usr/bin/g++-9
$ /home/correaa/intel/oneapi/compiler/latest/linux/bin/intel64/icpc -v
icpc version 2021.4.0 (gcc version 11.2.0 compatibility)
```

**Comment by correaa** [comment]
Ah, got it, ` PATH: /opt/rh/gcc-toolset-9/root/bin:/opt/rh/gcc-toolset-9/root/bin:/usr/local/cuda/bin:/opt/llvm/13.0.0/bin:/home/wfg/.local/bin:/home/wfg/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin`

I found how to read the CI output.

**Comment by correaa** [comment]
mmm, still no luck. Any tip for Ubuntu 22.04? I have `g++-9` and `libstdc++-9-dev`

**Comment by correaa** [comment]
as a data point: compilation seems to work with `icpc version 2021.5.0 (gcc version 10.2.1 compatibility)`

https://gitlab.com/correaa/boost-multi/-/jobs/3058604883#L996

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
I found this confusing
```
using static_::static_;
```
static_ is both a type and a member? I'm wondering if this caused compiler issues.

**Comment by correaa** [comment]
This is for "inheriting" (really propagating) a consctructor of the base class.
In context looks better.

```
template<class T, dimensionality_type D, class Alloc>
struct array : static_array<T, D, Alloc> {
	using static_ = static_array<T, D, Alloc>;
        ...
	using static_::static_;

	using typename static_::value_type;
}
```

The base here is: `static_array<T, D, Alloc>`, so this could be written as 
```
	using static_array<T, D, Alloc>::static_array;
```

However, you had good eye, because not exactly this, but the line `using typename static_::value_type;` above, crashed a couple of compilers (and was accepted by others) when it was written as `using typename array::value_type;`.

To be 100% sure that this is not the icpc issue, I will rewrite the line as `using static_array<T, D, Alloc>::static_array;` next time I try to incorporate it to QMCPACK.

(In case you are wondering `static_array` is almost the same as `array` except that it is not resizable or movable and it is forced to have the same lifetime as a good old c-array (but allocated in the heap). It is very limited, it is not a real value type, because it is not generally assignable but it is very safe to use with monotonic memory resources and it doesn't have iterator invalidation.)

**Comment by correaa** [comment]
replaced by #4256

**Pull request closed without merging**
