### PR TITLE
Nexus: support for functions over discrete grids

### PR DESCRIPTION
**Pull request by jtkrogel**
The classes in this PR serve as a foundation layer for #1786.  Classes derived from Grid represent multidimensional grids of points, while classes derived from GridFunction represent (potentially multi-valued) functions over those grids.

These class abstractions will enable interpolation, integration, differentiation, and twist averaging of large volumetric datasets in real space and k-space that commonly comprise the estimator output from QMCPACK that appears in stat.h5 files.  This PR includes basic capabilities to define grids, define integration metrics, and plot function values.  In a subsequent PR, interpolation and differentiation capabilities will be added that are needed to obtain Fermi surface information from n(k) data.

This PR includes long-form function level documentation for all classes in a format that will be standard for Nexus going forward.

Remaining tasks:
- [x] Remove unused code.
- [x] Complete the unit tests.
- [x] Add module level documentation.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Ready to merge.

**Comment by markdewing** [comment]
@jtkrogel There's a conflict in nxs-test with the latest develop.  Could you resolve that?

**Comment by jtkrogel** [comment]
I'll have a look.

**Comment by jtkrogel** [comment]
@markdewing I think that did it.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
