### PR TITLE
Use GCC14 and macos-14 in macOS CI

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Try GCC 14 to avoid macOS CI failure

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

None. CI needs to run.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
Correctly used gcc14 but problem reoccurred. Trying macos15

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Review by ye-luo — CHANGES_REQUESTED** [review]
Unfortunately macos-15 doesn't exist and macos-14 still fails.

**Comment by PDoakORNL** [comment]
Where is this CI running?  Maybe I can log in and try to do something.  At least figure out if there is a reason the bus error occurs in the estimator tests.

**Comment by prckent** [comment]
GitHub actions CI, so no easy login. It appears and disappears with certain versions of the mac toolchains, different compilers etc. Could be easily be us or them. Since it is no showstopper, better to focus on things needed for v4: energy density, structure factor etc.

I do think we should merge this PR. Still useful to have the newer GCC.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
