### PR TITLE
Add "Additional Tools" chapter scaffolding to manual.  

### PR DESCRIPTION
**Pull request by rcclay**
Added a chapter scaffold for all the supplemental executables that QMCPACK provides.  Intro paragraph and then sections for all tools I know about (is wfconvert still a thing?).

### CODE REVIEW

**Comment by jtkrogel** [comment]
Adding this section is a good idea.  There are standalone tools built from Nexus components other than qmca (i.e. qmcfit and eshdf_mod).  Do we want to segregate by Python/C++ or by function?

I believe wfconvert is still needed at present as we do not have any other route (that I am aware of) to generate orbitals in the hybrid representation.  Luke's comments should be given the most weight on this.

**Comment by lshulen** [comment]
I think it is a good idea as well.  I might suggest that function is more important than Python/C++, but I could argue it either way since they are likely found in different directories.

**Comment by rcclay** [comment]
It would probably be a good idea to segregate by function.  Including the nexus executables would be a good idea too, since qmca is our default out-of-the-box analysis tool at the moment.  I would suggest having the utilities at the subsection level, and having the type of application at the section level... e.g. 1. Converters; 1.1 wfconvert.

**Comment by rcclay** [comment]
Actually, I'm not sure how to get this to play along with Chapter 10.  Using qmca as an example, perhaps have a basic man page for the tool in the "Additional Tools" section, then reference Chapter 10 for a more thorough tutorial/use case.

**Comment by prckent** [comment]
Agree on discussing by function. Good idea to add these.

**Comment by rcclay** [comment]
OK.  Here's a better scaffold.

**Comment by jtkrogel** [comment]
I might split "Converters" into "Wavefunction Conversion & Manipulation" (for example, eshdf_mod manipulates the eshdf file, but does no conversion while wfconvert does both) and "Pseudopotential Conversion" to separate by function.  Probably not a big deal either way.  PR accept +1.

On a related note, Nexus has inbuilt functionality to do fast PP conversion of the type: (gaussian, gamess, crystal) -> (gaussian, gamess, crystal) or (gaussian, gamess, crystal, casino, qmcpack) -> (casino, qmcpack).  I could easily wrap this functionality into a command line tool (name?) if it would be useful.

**Pull request merged**
