### PR TITLE
Update afqmc workflow tests

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Remove PYSCF_BIN cmake flag. Also updated naming convention.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)
- Build related changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

intel xeon real build

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
I am testing this and happily might have all the dependencies working correctly. My ctest is currently running the slow pyscf solid state converter tests.

**Comment by ye-luo** [comment]
Okay to test

**Comment by fdmalone** [comment]
Should these be relabelled? Lumping them together with the converter tests might be a bad idea as they are full workflow tests, i.e., they run pyscf, converter and qmcpack

**Comment by ye-luo** [comment]
pw2qmcpack workflow test is also under converter label

**Comment by prckent** [comment]
I also think the current situation is fine.

**Comment by fdmalone** [comment]
Some of these tests are failing due to out of date imports. Hold off on the merge.

**Comment by prckent** [comment]
Which tests? The converter tests looked to be working for me. short tests are still running.

**Comment by fdmalone** [comment]
Number 6 and number 5. Did you build with complex?

**Comment by prckent** [comment]
By hand complex build with gcc and MKL on sulfur. The short test are problematic since the OpenMPI configuration is currently bad on this machine (my problem), but the unit and converter tests seem to be OK.
```
Test project /home/pk7/projects/qmc/git_QMCPACK_qmcpack/build_gcc
      Start   1: deterministic-unit_test_afqmc_matrix
 1/31 Test   #1: deterministic-unit_test_afqmc_matrix .......................................   Passed    0.19 sec
      Start   2: deterministic-unit_test_afqmc_numerics
 2/31 Test   #2: deterministic-unit_test_afqmc_numerics .....................................   Passed    0.16 sec
      Start   3: deterministic-unit_test_afqmc_slaterdeterminantoperations
 3/31 Test   #3: deterministic-unit_test_afqmc_slaterdeterminantoperations ..................   Passed    0.16 sec
      Start   4: deterministic-unit_test_afqmc_walkers
 4/31 Test   #4: deterministic-unit_test_afqmc_walkers ......................................   Passed    0.17 sec
      Start   5: deterministic-unit_test_afqmc_hamiltonians_ham_chol_uc
 5/31 Test   #5: deterministic-unit_test_afqmc_hamiltonians_ham_chol_uc .....................   Passed    0.16 sec
      Start   6: deterministic-unit_test_afqmc_hamiltonians_ham_chol_sc
 6/31 Test   #6: deterministic-unit_test_afqmc_hamiltonians_ham_chol_sc .....................   Passed    0.18 sec
      Start   7: deterministic-unit_test_afqmc_hamiltonians_ham_thc_sc
 7/31 Test   #7: deterministic-unit_test_afqmc_hamiltonians_ham_thc_sc ......................   Passed    0.17 sec
      Start   8: deterministic-unit_test_afqmc_hamiltonian_operations_ham_chol_uc_wfn_rhf
 8/31 Test   #8: deterministic-unit_test_afqmc_hamiltonian_operations_ham_chol_uc_wfn_rhf ...   Passed    0.16 sec
      Start   9: deterministic-unit_test_afqmc_wfn_factory_ham_chol_uc_wfn_rhf
 9/31 Test   #9: deterministic-unit_test_afqmc_wfn_factory_ham_chol_uc_wfn_rhf ..............   Passed    0.18 sec
      Start  10: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_rhf
10/31 Test  #10: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_rhf ..............   Passed    0.35 sec
      Start  11: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_uhf
11/31 Test  #11: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_uhf ..............   Passed    0.37 sec
      Start  12: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_msd
12/31 Test  #12: deterministic-unit_test_afqmc_wfn_factory_ham_chol_sc_wfn_msd ..............   Passed    0.44 sec
      Start  13: deterministic-unit_test_afqmc_wfn_factory_ham_thc_sc_wfn_rhf
13/31 Test  #13: deterministic-unit_test_afqmc_wfn_factory_ham_thc_sc_wfn_rhf ...............   Passed    0.18 sec
      Start  14: deterministic-unit_test_afqmc_prop_factory_ham_chol_uc_wfn_rhf
14/31 Test  #14: deterministic-unit_test_afqmc_prop_factory_ham_chol_uc_wfn_rhf .............   Passed    0.33 sec
      Start  15: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_rhf
15/31 Test  #15: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_rhf .............   Passed    0.47 sec
      Start  16: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_uhf
16/31 Test  #16: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_uhf .............   Passed    0.52 sec
      Start  17: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_msd
17/31 Test  #17: deterministic-unit_test_afqmc_prop_factory_ham_chol_sc_wfn_msd .............   Passed    0.72 sec
      Start  18: deterministic-unit_test_afqmc_prop_factory_ham_thc_sc_wfn_rhf
18/31 Test  #18: deterministic-unit_test_afqmc_prop_factory_ham_thc_sc_wfn_rhf ..............   Passed    0.33 sec
      Start  19: deterministic-unit_test_afqmc_estimators_ham_chol_uc_wfn_rhf
19/31 Test  #19: deterministic-unit_test_afqmc_estimators_ham_chol_uc_wfn_rhf ...............   Passed    0.18 sec
      Start  20: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_rhf
20/31 Test  #20: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_rhf ...............   Passed    0.26 sec
      Start  21: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_uhf
21/31 Test  #21: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_uhf ...............   Passed    0.27 sec
      Start  22: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_msd
22/31 Test  #22: deterministic-unit_test_afqmc_estimators_ham_chol_sc_wfn_msd ...............   Passed    0.30 sec
      Start  23: deterministic-unit_test_afqmc_estimators_ham_thc_sc_wfn_rhf
23/31 Test  #23: deterministic-unit_test_afqmc_estimators_ham_thc_sc_wfn_rhf ................   Passed    0.17 sec
```

**Comment by fdmalone** [comment]
The workflow tests were certainly failing. Namely 05-N2_phmsd and 06-methane_converge_back_prop should certainly fail. My pushes should have fixed this.

**Comment by prckent** [comment]
Note that I added/restored a check of PySCF importability back to the main CMakeLists.txt. I think this is useful feedback to have early in the configuration.

**Comment by prckent** [comment]
Is the following name intended?

Start 1018: short-diamondC_afqmc_1x1x1_complex_cholesky-16-1-EnergyEstim__nume_real

**Comment by fdmalone** [comment]
Which part of the name? EnergyEstim__nume_real is unfortunately the name of real part of the energy estimator (and the numerator of it if free projection is being performed). This is a statistical test, not related to workflow.

**Pull request merged**
