### PR TITLE
Add pw open bc test

### PR DESCRIPTION
**Pull request by ye-luo**
1, Add the atomO openBC test starting from qe, only active when qe tests are enabled.
DP MP CPU code, MP GPU code pass.
2, Adjust optimizer tests.
See details in each commit logs.

### CODE REVIEW

**Comment by prckent** [comment]
Thanks. I am going to check that this works on oxygen before approving. This will require adding a build of QE to the current test script. Did you check if the CUDA open boundary condition code is OK or check CPU only?

Optimizer changes will not be merged until the above happens. Split unrelated changes if you need them merged sooner.

**Comment by prckent** [comment]
Please add a no jastrow test in addition and update the PR (can use the same orbitals and QE run). This will allow us to check that the kinetic energy correctly reproduces what is expected from the orbitals. The current tests that include a jastrow will only allow us to catch changes in the results since the exact answer is not known a priori.

Thanks, Paul

**Comment by ye-luo** [comment]
I recovered the CUDA open BC code long time ago. The CUDA code passed in this test today when I checked. The code is in good shape.

**Comment by ye-luo** [comment]
The fix to the optimizer tests is not urgent. I will leave it in current way.

Add the no Jastrow test.
pw2casino Kinetic 11.64963538
measured   Kinetic 11.64798 +/- 0.00017

I can accept having slightly different energy due to the limited sized box and change of BC.
We do not need a very accurate calculation as a test. Otherwise, it becomes too heavy.

**Comment by prckent** [comment]
I realize that these tests could be in molecules/atomO since "molecules" really means isolated systems, while "solids" (current location) are for periodic systems. For now lets get the tests rolling.

**Comment by ye-luo** [comment]
We have multiple places introducing the tests.
Under tests folder and under examples folder. We might need to reorganize them.
I left it in solid thinking that it mostly enter the code path for the solids, namely PW.

**Pull request merged**
