### PR TITLE
Add unit test for MultiQuinticSpline1D

### PR DESCRIPTION
**Pull request by markdewing**
Also fix a small bug in the 3rd derivative routine.

### CODE REVIEW

**Comment by markdewing** [comment]
It was a compile error as soon I as used it in the unit test.  The code was not called from QMCPACK, and being a template, it never got compile

**Comment by anbenali** [comment]
Ouch.. do you have an idea of the effect of this bug. I don't think that it
is too serious but from your test you maybe have a idea?? It should still
be in the nose but I don't see where the "d" comes from.

**Comment by ye-luo** [comment]
@anbenali Third derivative is only needed for the optimization of backflow. Not used at the moment.

**Comment by markdewing** [comment]
The formula is the same as in OneDimGridBase.h, but it was missing the array references.

**Pull request merged**
