### PR TITLE
Add one dim cubic spline with linear grid

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
To be used in short range Coulomb PBC AA.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Ye. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
1. Why is this needed?
2. Add comments/definitions
3. Class not struct?
4. Private not public
5. Hopefully 100% test coverage

**Comment by ye-luo** [comment]
> 1. Why is this needed?
class containing pointers with virtual function pointer calls. I'd like to stay away from them inside a GPU kernel.

>     2. Add comments/definitions
I will add more.
 
>     3. 4. Private not public
Will do

>     5. Hopefully 100% test coverage
I hope so.

**Comment by ye-luo** [comment]
It is 90.90% unfortunately not 100%.

**Comment by prckent** [comment]
Good try on the coverage. Can you put a note about avoiding virtual functions for future people using/modifying this?

**Comment by ye-luo** [comment]
I added a note explaining that this class was made to avoid virtual functions on GPU and how the member functions should be used.

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
