### PR TITLE
Update multi

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
test please

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
It is doesn't work and we a low on ideas, we could simply declare that it is time to move on from this compiler. If is proprietary and over 2 years old, so well outside our standard support window.

**Comment by prckent** [comment]
Now broken for complex with gcc9 and clang15, so hopefully easier to fix.

**Comment by correaa** [comment]
mmm, I think this is not the real problem with intel compiler. The problem here is that I didn't do a proper merge with the current develop branch.

Replacing with https://github.com/QMCPACK/qmcpack/pull/4264

**Pull request closed without merging**
