### PR TITLE
Add MPI support to ROCm legacy CI

### LINKED ISSUE #4048: legacy CUDA CI needs MPI
**Describe the bug**
Current CI for legacy CUDA doesn't include MPI and bugs went through.

We can just replace rocm legacy cuda build with MPI enabled. The nvidia legacy cuda can remain in noMPI.

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add MPI configuration based on OpenMPI using ROCm clang compilers
For CI running on nitrogen
Must merge onto develop before changes take place.
Fixes #4048

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
nitrogen, must pass CI

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

Note that sulfur has a no-mpi legacy CUDA build so we still have coverage for no-mpi legacy CUDA-related builds with this change.

**Comment by ye-luo** [comment]
No update to `workflows/ci-github-actions-self-hosted.yaml`?

**Comment by williamfgc** [comment]
@ye-luo good catch, I forgot to stage the file. Here it goes. Thanks!

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
