### PR TITLE
Make CUDA2HIP work with ENABLE_CUDA

### LINKED ISSUE #3374: cuda2hip.h hipBLAS.hpp have no license
**Describe the bug**
While I would like to just consider any code without a license in it to just be public domain I doubt this is the case for the two files above.  Whats the deal with them?  Are they under the same license as other QMCPACK code, none, an incompatible one?  Are we pretending they aren't there in case Nvidia decides to start an API lawsuit?

**To Reproduce**
Read Source

**Expected behavior**
A license

**System:**
Anything

**Additional context**
Would like to use part of them for another port to HIP.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Review after #3392
Enable code paths of ENABLE_CUDA to compile when CUDA2HIP is enabled.
Both `-DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON` and  `-DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON -DENABLE_OFFLOAD=ON` compiles. The latter case is still in early stage.

Pieces needs cuSOLVER has not been connected. cuSOLVER to rocSOLVER is not straight forward and needs additional work.

license headers added in all the files under `src/Platforms/ROCm`. Closes #3374
@jakurzak check if the info is accurate.

## What type(s) of changes does this code introduce?
- New feature
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
We will use #3405 . Please remake this PR after that is merged.

**Comment by ye-luo** [comment]
@prckent will handle merge conflict

**Comment by ye-luo** [comment]
Ready for review.

**Comment by prckent** [comment]
So we have a record, can you post a spock compatible cmake line?

**Comment by prckent** [comment]
hipBLAS.hip.cpp should not be a filename with more.than.one.dot. We are trying to get rid of these. Also please remake as a moved file so that we can see the diff - what did you change vs what was originally there?

**Comment by prckent** [comment]
Why is CUBLAS_STATUS_LICENSE_ERROR commented?

**Comment by ye-luo** [comment]
> CUBLAS_STATUS_LICENSE_ERROR

Not defined in hipBLAS

**Comment by ye-luo** [comment]
```
module load PrgEnv-cray
module load rocm/4.2.0 craype-accel-amd-gfx908
module load cray-fftw cray-hdf5 libxml2 boost/1.73.0
cmake -DCMAKE_SYSTEM_NAME=CrayLinuxEnvironment -DENABLE_CUDA=ON -DQMC_CUDA2HIP=ON \
  -DENABLE_OFFLOAD=ON -DCMAKE_PREFIX_PATH=$FFTW_DIR/.. ..
```
Cray 12.0.1 requires rocm 4.2

**Comment by ye-luo** [comment]
> hipBLAS.hip.cpp should not be a filename with more.than.one.dot. We are trying to get rid of these. 
This is recommended by HIP Porting Guild and all our AFQMC HIP code follows this convention. https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-porting-guide.html?highlight=extension#choosing-hip-file-extensions

> Also please remake as a moved file so that we can see the diff - what did you change vs what was originally there?
`git log --follow src/Platforms/ROCm/hipBLAS.hip.cpp` gives you the whole history.

**Review by prckent — APPROVED** [review]
Thanks Ye. Confirmed successful builds on spock, real & complex. Did not run.

Yes we should follow the hip guide for hip things. Not for QMCPACK in general though.

**Comment by ye-luo** [comment]
Start testing in-house

**Pull request merged**
