### PR TITLE
Initial implementation of batched cost function

### PR DESCRIPTION
**Pull request by markdewing**
## Proposed changes
Create versions of checkConfigurations and correlatedSampling that call batch code.

The code only works with one thread.  Some loops have been modified to be hardcoded to one thread, some have not.

The gradient and linear optimizers should work (in theory), as they only depend on quantities computed in checkConfigurations and correlatedSampling.  It's only been lightly tested on two examples.

Because this code creates vectors of ParticleSet, TrialWaveFunction, and QMCHamiltonian that are the length of the number of samples, memory usage may be an issue.   It is likely that a future change will need to process the samples in smaller batches.

There's a few other fixes
- set samples in vmcbatch correctly
- add destructor to SampleStack to free memory

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
laptop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes/ Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
@PDoakORNL Are there "do not use" comments / can you put some "do not use" comments in clonemanager etc.?

**Comment by markdewing** [comment]
I could close this PR and open another one that cleans up more of the legacy issues?

**Comment by PDoakORNL** [comment]
That's up to you Mark.  If my concerns are addressed in a future PRs that's fine with me. I'm not sure whether folks going through a process like Mark is will see those comments since one might not even look into the headers for the dropped or refactored classes. I think it might be better if I write a quick document of which classes are out and if they have a replacement what it is.  Where should we put something like that now?

**Comment by prckent** [comment]
Put the notes in the manual in the development section. (Since manual edits are easy and we have version control, it is a superior solution to the GitHub wiki.)

**Comment by markdewing** [comment]
I'll add additional changes to this PR

**Comment by markdewing** [comment]
All the legacy threading should be removed.  QMCCostFunctionBatched no longer inherits from CloneManager.

**Comment by prckent** [comment]
This LGTM. @PDoakORNL OK to merge at this point or would you like to see this branch matured more?

**Pull request merged**
