### PR TITLE
Update multi

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Updates multi to latest version and updates qmcpack correspondingly.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

quartz (intel xeon) and lassen (~summit) gcc builds only. Need nightlies to test  for other compilers. 

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes-ish This PR adds tests to cover any new code, or to catch a bug that is being fixed. (are multi unit tests run by qmcpack?)
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by fdmalone** [comment]
Was a policy agreed upon for updating external codes?

**Comment by mmorale3** [comment]
At least we are now in a position to implement one.

**Comment by mmorale3** [comment]
Okay to test!

**Comment by ye-luo** [comment]
Is the multi code added using subtree as `external_codes/boost_multi/multi/README` described?

**Comment by prckent** [comment]
If there is anything other than simple file copies, we need to discuss.

**Comment by mmorale3** [comment]
I wasn't aware of the policy, I just copied the files from fresh pull of his gitlab repo.
Notice that the afqmc code required massive changes to work with an unmodified
version of multi. My main goal was to do those changes.

**Comment by ye-luo** [comment]
> I wasn't aware of the policy, I just copied the files from fresh pull of his gitlab repo.
> Notice that the afqmc code required massive changes to work with an unmodified
> version of multi. My main goal was to do those changes.

We do need to track which commit you copied from the repo and modified. So it is better not to copy by hand. When I did "git subtree pull", there are only 6 conflicts. Instead if I do it on develop, there are massive amount. So I think this PR actually has all ready reduced divergence. So maybe @mmorale3 can just resolve the 6 conflict files and we are good.

**Comment by mmorale3** [comment]
Alfredo is working on some things (not used by qmcpack), so it is possible he pushed something this morning. What's on the PR is multi from last night.  I'll fix the 6 conflicts by hand for this PR. After this I'll stick to the policy, I just wasn't aware this was in place.

**Comment by prckent** [comment]
multi should have real releases with version numbers attached. Copying specific versions over will be very simple and straightforward at that point. We do something similar with other external codes.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
