### PR TITLE
Update multi 231212

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
I got to the same point. 

My best guest, based on CUDA experience, is that the non-trivial constructor (zero initialization) of complex is being called from the host to initialize memory on the device.

I don't have enough experience with offloading to tell. 

I will add a macro to the build to disable initialization of complex. 

Any ideas?

**Comment by correaa** [comment]
Fortunately (?), I have a way to "hack" multi into _skip_ zero-initialize `std::complex`, for efficiency reasons. 

I can use this feature to see if this is the origin of the offload-Complex failure.

Where is a good point to pass this flag to compilation (in the CI), `-D_MULTI_FORCE_TRIVIAL_STD_COMPLEX` ?

**Comment by ye-luo** [comment]
> Fortunately (?), I have a way to "hack" multi into _skip_ zero-initialize `std::complex`, for efficiency reasons.
> 
> I can use this feature to see if this is the origin of the offload-Complex failure.
> 
> Where is a good point to pass this flag to compilation (in the CI), `-D_MULTI_FORCE_TRIVIAL_STD_COMPLEX` ?

Similar to https://github.com/QMCPACK/qmcpack/blob/e95609ab8cf645c1397b442ca6e84cad9bc0dc52/external_codes/CMakeLists.txt#L14C8-L14C8. Use `target_compile_definitions`.

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
looking good

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
Why would  `/opt/rocm-5.7.1/include/thrust/detail/type_traits.h` include a header not in the system? Is there a problem with the installation of the rocm image?

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by correaa** [comment]
This is promising; the errors now happen at the level of the numeric test.

**Comment by correaa** [comment]
I have the impression that the HIP code in AFQMC was always broken and when enabling the HIP algorithm in Multi this was exposed.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> I have the impression that the HIP code in AFQMC (the tests really) was always broken and when enabling the HIP algorithm in Multi this was exposed.

Not understanding... Failures are from pure CUDA builds.

**Comment by correaa** [comment]
sorry, I got confused with something else.

**Comment by correaa** [comment]
replaced by #488

**Pull request closed without merging**
