### PR TITLE
Assign test dependent name to hdf5 files created by unit tests.

### LINKED ISSUE #1721: AFQMC unit tests failing - mostly factory related
See e.g. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=66990

Seems to be a missing or non-updated file issue:
```
Wavefunction type: NOMSD
Reading a RHF-type trial wave-function. 
ERROR  Error opening restart file in WavefunctionFactory. 
Fatal Error. Aborting at 
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

Do these tests work anywhere?

### PR DESCRIPTION
**Pull request by fdmalone**
Should resolve #1721 by naming test output based on wavefunction and hamiltonian used.

### CODE REVIEW

**Comment by fdmalone** [comment]
Accidentally added some files. I'll do a force push in a second.

**Comment by ye-luo** [comment]
Okay to test

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
rhea-gpu failed previously due to an problem cloning the repo from GitHub

**Pull request merged**
