### PR TITLE
Update CI naming in docs

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Update docs with GitHub Actions CI naming adopted in #3596 
Use this PR to trigger and verify self-hosted CI merged in #3596 

## What type(s) of changes does this code introduce?

- Code style update (formatting, renaming)
- Testing changes (e.g. new unit/integration/performance tests) self-hosted CI
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
None, must pass CI.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by williamfgc** [comment]
Start testing in-house

**Review by prckent — DISMISSED** [review]
I think the naming is currently consistent with the docs.

**Comment by williamfgc** [comment]
@prckent thanks. I'm waiting to see if GitHub Actions CI runs smoothly (so far, one hiccup) to update self-hosted job names in docs and remove the [WIP] after that. Then move to AMD hardware in #3582 .

**Comment by williamfgc** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
