### PR TITLE
Cleaner error handling when spline file not present

### LINKED ISSUE #36: Code crashes if spline file not present. Should be error trapped.
Reported by: prckent

As a usability feature, file open of the HDF5 file should be properly error trapped and a sensible error message printed. Code currently crashes, and source of error might not be clear to users.

[ Logical extension of this ticket: error trap every file open in the application ]

### PR DESCRIPTION
**Pull request by prckent**
Fixes #36

Replace default error handler in HDF5 so that we can preferentially print our error message.

### CODE REVIEW

**Comment by ye-luo** [comment]
Will this change decrease the accessible info when an issue happened at this call?

**Comment by prckent** [comment]
It is logically equivalent. Instead of getting the messy HDF5 error trace ("couldn't open the file") we print our own message. The error handler is restored after the open is successful, so all future HDF5 calls will print the full error trace.

**Comment by prckent** [comment]
Sometime in the future *all* the XML and HDF5 handling needs to be looked at and thoroughly decrufted but, e.g. #35 is far more important for users, as is simply catching errors such as #113

**Comment by ye-luo** [comment]
HDF5-DIAG: Error detected in HDF5 (1.8.12) thread 0:
  #000: ../../src/H5F.c line 1585 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../src/H5F.c line 1274 in H5F_open(): unable to open file: time = Tue Feb 21 20:20:15 2017
, name = '../NiO-fcc-supertwist111-supershift000-S8.h5', tent_flags = 1
    major: File accessibilty
    minor: Unable to open file
  #002: ../../src/H5FD.c line 987 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  **#003: ../../src/H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = '../NiO-fcc-supertwist111-supershift000-S8.h5', errno = 13, error message = 'Permission denied', flags = 1, o_flags = 2**
    major: File accessibilty
    minor: Unable to open file

This is what I see from your nightly tests and the error from h5 is more descriptive.

**Comment by prckent** [comment]
Not appropriately concise for a user code. Wontfix. The lengthy h5 error trace has been described as *our* crash and QMCPACK has been blamed when it was actually a user problem.

**Comment by ye-luo** [comment]
If a user ask why my run fails, and QMCPACK only print "unable to open file". We have no ways to help but guessing and try and error.

**Comment by prckent** [comment]
It should print
ERROR: Could not open HDF5 file "xyz.hdf" in EinsplineSetBuilder::ReadOrbitalInfo.  Aborting.

If it doesn't open a new ticket and describe the issue.

**Comment by ye-luo** [comment]
This PR also doesn't fix the code crashing problem #36, it still call the same interface APP_ABORT to stop the code.

**Comment by ye-luo** [comment]
Can it better if we print our error message to the app_log() and point people to look at the error that hdf5 library spits out. Or we just enable the error on the master if there is tons of it.

**Comment by prckent** [comment]
Make an issue to discuss this. Q is "what is the preferred way to handle errors and terminate the application?"

**Pull request merged**
