### PR TITLE
Fix issue with multithreaded CI coefficient optimization

### PR DESCRIPTION
**Pull request by markdewing**
## Proposed changes
The `CI_Optimizable` variable was introduced in https://github.com/QMCPACK/qmcpack/pull/879 and
Commit: 0df840610785a92b8e9e91739ef80c993b61ddf6

However, it was not copied in `makeClone`.   As a consequence, multithreaded optimization runs would only compute parameter derivative information on the main thread.  Other threads would return zero.

This affects both derivative methods and the linear method (Hamiltonian/overlap matrices) when optimizing CI coefficients.

This bug must not drive the CI coefficient optimization completely off the rails, otherwise it would have been noticed before now.    If only one of the threads is actually accumulating data, then fewer samples are used than expected.   The other effect is that all the matrix entries for the CI coefficients are going to be smaller than they should be (the normalizing values are the full number of samples).   However they might still be roughly the same relative to one another - so the direction to move the parameters might be correct, but the step size would be smaller than it should be (this last effect is just speculation).

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
laptop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
😢 

Thanks Mark. 

We should discuss next week but clearly

- We need some tests to avoid this ever happening again. Since this is a threading issue, do you have any ideas for how to reliably catch it in the present design?
- If we didn't know already, this bug tells us that the existing cloning design and implementation is very difficult to work with...

**Comment by ye-luo** [comment]
The makeClone function is intended to be the virtual copy construction and it should be as simple as just calling the copy constructor. We should implement proper copy constructor with value semantics instead of putting stuff in makeClone.
In the case here, the constructor is used instead of a proper copy constructor and thus the states have to be copied manually.

**Comment by prckent** [comment]
I was thinking something similar. It would seem that if we use copy constructors for cloning, makeClone can be completely deleted. It will still be possible to have errors in the constructor, but at least the design will be clearer.

**Comment by prckent** [comment]
Additionally, the naming is wrong. clones are identical. That is the dictionary definition. ours are not.

**Comment by ye-luo** [comment]
Here it mean indistinguishable copies. If we make clones from 1 to N and then keep any one of them by destroying all the rest, there should be no side effect.

**Comment by markdewing** [comment]
I have plans for some code that will let parameter gradients be tested.    Running those tests with multiple threads would have caught this issue.

**Pull request merged**
