### PR TITLE
Fix clang warning about non-virtual destructor

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
clang 15 complains.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — APPROVED** [review]
Fair enough complaint.
LGTM

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
