### PR TITLE
Add debug disable branching in classic DMC driver

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Using `reconfiguration = runwhileincorrect ` can be risky when not running strictly 1 node 16 walkers. It reminds me #1817
debug_disable_branching is supported in the batched DMC driver. I think it is good to add the same option for the classic DMC driver and make performance tests not vulnerable to reconfiguration issues.

This option was added in the documentation section of both classic and batched DMC drivers.

## What type(s) of changes does this code introduce?
- New feature
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by PDoakORNL** [comment]
I think there is now some documentation/error messages in DMC.cpp that doesn't make sense.

**Comment by ye-luo** [comment]
> I think there is now some documentation/error messages in DMC.cpp and DMCDriverInput.cpp that doesn't make sense.

I'm not getting this `reconfiguration = runwhileincorrect` option is still available.

**Comment by PDoakORNL** [comment]
If I understand the point of this correctly.

```c++
  if (reconfig_str == "yes")
    throw std::runtime_error(
        "Reconfiguration is currently broken and gives incorrect results. Set reconfiguration=\"no\" or remove the "
        "reconfiguration option from the DMC input section. To run performance tests, please set reconfiguration to "
        "\"runwhileincorrect\" instead of \"yes\" to restore consistent behaviour.");
  reconfiguration_ = (reconfig_str == "yes");
```

This is not what we suggest to run performance tests.  Instead we suggest `debug_disable_branching=yes`

**Comment by ye-luo** [comment]
> If I understand the point of this correctly.
> 
> ```c++
>   if (reconfig_str == "yes")
>     throw std::runtime_error(
>         "Reconfiguration is currently broken and gives incorrect results. Set reconfiguration=\"no\" or remove the "
>         "reconfiguration option from the DMC input section. To run performance tests, please set reconfiguration to "
>         "\"runwhileincorrect\" instead of \"yes\" to restore consistent behaviour.");
>   reconfiguration_ = (reconfig_str == "yes");
> ```
> 
> This is not what we suggest to run performance tests. Instead we suggest `debug_disable_branching=yes`

Thanks. Updated all the similar occurrence.

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Review by prckent — APPROVED** [review]
Good idea. The intent in the inputs is clearer now and this is a definite improvement over runwhileincorrect.

**Comment by prckent** [comment]
https://qmcpack.readthedocs.io/en/develop/methods.html#dmc-driver needs an update. Can wait if other updates will be soon.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
