### PR TITLE
Updated nightly test scripts

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Current versions including preliminary support of OpenMP offload builds with LLVM development compiler. CUDA builds are renamed Legacy-CUDA.

## What type(s) of changes does this code introduce?

- New feature
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen. Apart from the new offload build these versions have been in production since 10 February. Scipts use spack develop from that date.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Please delete all oxygen files and update the branch.
```
yeluo@ryzen-box:~/opt/qmcpack/tests/test_automation$ ls -lrt
total 100
-rw-rw-r-- 1 yeluo yeluo  1108 Feb 13 20:50 README.md
drwxrwxr-x 2 yeluo yeluo  4096 Feb 13 20:50 nightly_test_scripts
-rwxrwxr-x 1 yeluo yeluo  3430 Feb 13 20:50 jenkins_oxygen_gpu.sh
-rwxrwxr-x 1 yeluo yeluo  3460 Feb 13 20:50 jenkins_oxygen_cuda.sh
-rwxrwxr-x 1 yeluo yeluo  3468 Feb 13 20:50 jenkins_oxygen_cpu.sh
-rwxrwxr-x 1 yeluo yeluo   801 Feb 13 20:50 jenkins_ornl_test.sh
-rwxrwxr-x 1 yeluo yeluo  1695 Feb 13 20:50 jenkins_ornl_oxygen.sh
-rw-rw-r-- 1 yeluo yeluo   113 Feb 13 20:50 Jenkinsfile_ornl_vm
-rw-rw-r-- 1 yeluo yeluo   178 Feb 13 20:50 Jenkinsfile_ornl_oxygen_gpu
-rw-rw-r-- 1 yeluo yeluo   187 Feb 13 20:50 Jenkinsfile_ornl_oxygen_enable_cuda
-rw-rw-r-- 1 yeluo yeluo   178 Feb 13 20:50 Jenkinsfile_ornl_oxygen_cpu
-rwxrwxr-x 1 yeluo yeluo  1151 Feb 13 20:50 add_fortran_for_spack_clang.py
-rw-rw-r-- 1 yeluo yeluo   788 Feb 13 20:50 vm_spack_env_cpu.sh
-rwxrwxr-x 1 yeluo yeluo  4867 Feb 13 20:50 vm_setup.sh
-rw-rw-r-- 1 yeluo yeluo   492 Feb 13 20:50 start_spack_env.sh
-rw-rw-r-- 1 yeluo yeluo  1211 Feb 13 20:50 spack_supported_package_versions.sh
drwxrwxr-x 2 yeluo yeluo  4096 Feb 13 20:50 spack_integration_tests
-rwxrwxr-x 1 yeluo yeluo 14152 Feb 13 20:50 run_unit_tests_ornl_nitrogen.sh
-rw-rw-r-- 1 yeluo yeluo   418 Feb 13 20:50 ornl_oxygen_spack_env_gpu.sh
-rw-rw-r-- 1 yeluo yeluo   421 Feb 13 20:50 ornl_oxygen_spack_env_enable_cuda.sh
-rw-rw-r-- 1 yeluo yeluo   816 Feb 13 20:50 ornl_oxygen_spack_env_cpu.sh
```

**Comment by prckent** [comment]
I was waiting for input. Keeping the coverage script since this will need to be reactivated.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
