### PR TITLE
Provide encapsulation to OperatorBase members

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Start refactoring of OperatorBase turning it into a class
Add encapsulation to existing members
Avoid warning for member assigment ordering
Breaking original PR #3412 intro smaller PRs
Related to #3411 

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 20.04 

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — COMMENTED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Review by markdewing — DISMISSED** [review]

**Comment by ye-luo** [comment]
@williamfgc failing legacy CUDA builds.

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
