### PR TITLE
Fix convert4qmc when eigenval_0 is missing in h5.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes

QP format h5 doesn't include eigenvalues. Made the parsing in convert4qmc more flexible.
Should make converter_test_LiH_qp pass.

In convert4qmc main(), add a try catch block for exceptions.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Where does eigenval_0 come from these days? If only the tests we should update the test data and not the code.

**Comment by ye-luo** [comment]
Converters for some codes only drop eigenvectors but not eigenvalues in h5.

**Review by anbenali — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
