### PR TITLE
[WIP] Thread safety for global Random object.

### PR DESCRIPTION
**Pull request by PDoakORNL**
The additional concurrency in the batched drivers revealed a possible race on Random.  A surprising number of calls to Random() are sprinkled through the code despite it looking at first glance like we use one carefully seeded RNG per thread.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
DMCBatched no longer frequently crashes
patches but doesn't resolve #1983

**Comment by prckent** [comment]
Is there any change to the random utilization in the existing omp based qmc drivers with this update or were they always successfully using distinct random sequences in a thread safe manner? (I think yes, but want to confirm).

**Comment by PDoakORNL** [comment]
We need to look at the call stack at the time each of the Random() calls was made. I'll figure out how to get a tool to spit that out. My guess is there is not a race on it in the old drivers/ single evaluators since a rather large threads have been frequently run and this sort of crash not observed. The global random is init, saved and loaded along with the per thread local ones even though it is global instead of owned by the RandomNumberCotrol, so it was "part" of the simulation. My earlier alarm there is unfounded.

**Comment by PDoakORNL** [comment]
Spoke to soon its still broken, I neglected to remember that access was through a pointer to base in NonLocalECPotential which is where it matters.

**Comment by PDoakORNL** [comment]
This has gotten rolled in with my next PR as some of the issue was global but there was a specific bug related to the batched drivers with the NonLocalECPotentials  myRng

**Pull request closed without merging**
