### PR TITLE
Allow directly select openmp offload code path.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Somehow this change should have been introduced when DiracDeterminantBatched was added.
`<slaterdeterminant gpu="omptarget">` can be used to hit the offload code path in a CUDA+OpenMP offload build. The CUDA one is default.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Polaris

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
Can you please update the docs?

How would a user learn which options are supported?

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
Likely for later PRs:

Can you see a place to print the available candidate values in standard output?
e.g. " Using "omptarget" implementation. "cpu", "sycl" also available. "
In this or a later PR it would be good to note+ensure, e.g.  "yes" defaults to the optimal one. I think this would be a good pattern to repeat for all the Wavefunction Components.

**Comment by ye-luo** [comment]
> Can you see a place to print the available candidate values in standard output?
e.g. " Using "omptarget" implementation. "cpu", "sycl" also available. "

What you suggested seems to complicating our printout. Users are not expected to select specific implementation but relying on default. So they don't need to see additional info in the standard output.
In the manual, I'm thinking of documenting the general behavior of `gpu` option in the GPU section and then having each occurrence pointing to it. Probably a light task on a boring day.

**Review by prckent — APPROVED** [review]

**Pull request merged**
