### PR TITLE
SO bugfix

### PR DESCRIPTION
**Pull request by camelto2**
## Proposed changes

Small changes that were overlooked for Spin-orbit stuff. Namely, an array initialization for the ECPotentialBuilder for the SOECPotential as well as a makeClone for the SpinorSet. Both have been fixed. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

my workstation (linux)

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by rcclay** [comment]
OK to test

**Comment by ye-luo** [comment]
Could you help solving Clang warnings from SO related classes?
qmcpack/src/QMCHamiltonians/SOECPotential.h:43:17: warning: 'makeClone' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
https://cdash.qmcpack.org/CDash/viewBuildError.php?type=1&buildid=108164

**Comment by camelto2** [comment]
> Could you help solving Clang warnings from SO related classes?
> qmcpack/src/QMCHamiltonians/SOECPotential.h:43:17: warning: 'makeClone' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
> https://cdash.qmcpack.org/CDash/viewBuildError.php?type=1&buildid=108164

I think I caught each of the errors for the SOECPotential.

**Comment by camelto2** [comment]
added some other small changes that came up while tracking down a bug with @rcclay. These don't fix the problem, but could become an issue down the road. 

Since the Oxygen stuff has been failing I figured I would go ahead and add another change while that gets sorted out instead of issuing a separate PR

**Comment by ye-luo** [comment]
@camelto2 could you address residual issues in #2350

**Comment by camelto2** [comment]
per issue #2350, I updated the copyright info for SOECPotential files to reflect who created the files or developed existing files if they were edited to incorporate spin orbit stuff. a number of the previous PRs for SO stuff did not do this for various files, so I edited a number of them

**Comment by camelto2** [comment]
> 2020 QMCPACK developers.

oops, will fix. 

This seems to be a problem that is overlooked in a lot of PRs not updating the year for edited files and changing "YEAR Jeongnim Kim and QMCPACK developers" to "YEAR QMCPACK developers"

**Comment by PDoakORNL** [comment]
Ignore the ornl-vm-cpu CI as its is still a WIP

**Pull request merged**
