### PR TITLE
Rc 3160

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Propose v3.16.0 release

## What type(s) of changes does this code introduce?

- Bugfix
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

No "significant" changes since weekend CI runs. Branched after #4423 

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Mostly. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
I am currently running a gcc mpi build and will report the test results here.

**Comment by prckent** [comment]
```
The following tests FAILED:
         90 - estimator-acforce-legacy-1-16-check (Failed)
         92 - estimator-acforce-fast-1-16-check (Failed)
        197 - performance-NiO-a256-e3072-DU64-batched_driver-w16-1-4 (Timeout)
        198 - performance-NiO-a256-e3072-DU64-batched_driver-w16-1-4-time (Failed)
        199 - performance-NiO-a512-e6144-SM1-cpu_driver-w16-1-16 (Timeout)
        200 - performance-NiO-a512-e6144-SM1-cpu_driver-w16-1-16-time (Failed)
        205 - performance-NiO-a512-e6144-DU64-batched_driver-w16-1-4 (Timeout)
        206 - performance-NiO-a512-e6144-DU64-batched_driver-w16-1-4-time (Failed)
        207 - performance-NiO-a1024-e12288-SM1-cpu_driver-w16-1-16 (Timeout)
        208 - performance-NiO-a1024-e12288-SM1-cpu_driver-w16-1-16-time (Failed)
        209 - performance-NiO-a1024-e12288-DU64-cpu_driver-w16-1-16 (Timeout)
        210 - performance-NiO-a1024-e12288-DU64-cpu_driver-w16-1-16-time (Failed)
        211 - performance-NiO-a1024-e12288-DU64-J3-cpu_driver-w16-1-16 (Timeout)
        212 - performance-NiO-a1024-e12288-DU64-J3-cpu_driver-w16-1-16-time (Failed)
        213 - performance-NiO-a1024-e12288-DU64-batched_driver-w16-1-4 (Timeout)
        214 - performance-NiO-a1024-e12288-DU64-batched_driver-w16-1-4-time (Failed)
        515 - short-LiH_ae-vmc_hf_noj_estimator_energydensity_voronoi-4-4-check (Failed)
        544 - short-LiH_pp-vmc_hf_sdj_xml-16-1-kinetic (Failed)
        546 - short-LiH_pp-vmc_hf_sdj_xml-16-1-eeenergy (Failed)
        548 - short-LiH_pp-vmc_hf_sdj_xml-16-1-potential (Failed)
        609 - short-LiH_pp-vmc_hf_sdj_estimator_spindensity-4-4 (Failed)
        610 - short-LiH_pp-vmc_hf_sdj_estimator_spindensity-4-4-check (Failed)
        612 - short-LiH_pp-vmc_hf_sdj_estimator_energydensity_voronoi-4-4-check (Failed)
        628 - short-H4-RHF-orb-opt-16-1-totenergy (Failed)
        632 - short-H4-orb-opt-1-16-totenergy (Failed)
        633 - short-H4-orb-opt-dmc-16-1 (Failed)
        634 - short-H4-orb-opt-dmc-16-1-totenergy (Failed)
        644 - short-H4-target-descent-16-1-totenergy (Failed)
        646 - short-H4-target-descent-1-16-totenergy (Failed)
        652 - short-H4-batched-hybrid-16-1-totenergy (Failed)
        654 - short-H4-batched-hybrid-1-16-totenergy (Failed)
        671 - short-H4-msd-orb-opt-16-1-totenergy (Failed)
        966 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-dtotenergy_AB (Failed)
        980 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-eeenergy_A (Failed)
        981 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-eeenergy_B (Failed)
        1107 - short-diamondC_1x1x1_pp-vmcbatch-estimator-onebodydensitymatrices-4-4-check (Failed)
        1113 - short-diamondC_1x1x1_pp-vmc-noJ-estimator-1rdm-4-4-check (Failed)
        1115 - short-diamondC_1x1x1_pp-vmc-J2-estimator-1rdm-4-4-check (Failed)
        1117 - short-diamondC_1x1x1_pp-vmc-estimator-energydensity-cell-4-4-check (Failed)
        1119 - short-diamondC_1x1x1_pp-vmc-estimator-energydensity-voronoi-4-4-check (Failed)
        1121 - short-diamondC_1x1x1_pp-dmc-estimator-energydensity-cell-4-4-check (Failed)
        1495 - short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-kinetic (Failed)
Errors while running CTest
```
built and run with
```
cmake -GNinja -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DQMC_DATA=/scratch/pk7/QMC_DATA_FULL/ ../qmcpack/
 ninja
 nohup ctest -j 16 -E long --output-on-failure >& ctest.out &
```
using gcc12.2.

The short-H4-orb-opt-dmc-16-1 failure is unfortunate but not surprising.  Everything else looks reasonable to me.

The version is reporting as v3.16.0

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
Verified changelog and version number update.

**Pull request merged**
