### PR TITLE
SoA implementation of J1/J2 evaluateHessian

### PR DESCRIPTION
**Pull request by jtkrogel**
Addresses #1533 as part of #861.

The new SoA implementation was checked against AoS deterministically using a modified version of the NiO L2 statistical integration test.  Checks were performed without Jastrow (worked already), J1 only, and J1+J2, see below.
```
>qmca -e 0 -q e 0*J0/*scalar*
01_aos_deterministic_J0/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -368.208074 +/- 2.183875 
04_soa_deterministic_J0/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -368.208074 +/- 2.183875 

>qmca -e 0 -q e 0*J1/*scalar*
02_aos_deterministic_J1/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -323.706678 +/- 11.355735 
05_soa_deterministic_J1/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -323.706678 +/- 11.355735 

>qmca -e 0 -q e 0*J2/*scalar*
03_aos_deterministic_J2/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -371.940356 +/- 0.936515 
06_soa_deterministic_J2/NiO-fcc-S1-vmc  series 1  LocalEnergy  =  -371.940356 +/- 0.936515 
```

### CODE REVIEW

**Comment by ye-luo** [comment]
Could you expand the unit tests?
src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp

**Comment by jtkrogel** [comment]
Make an issue for further work?  Adding a deterministic test would be less work than the unit test.  Unit tests use data from finite differences, which likely originate from a script I don't have (@markdewing ?).

**Comment by markdewing** [comment]
The values for the unit tests come from gen_bspline_jastrow.py.   The derivatives are computed in the function 'gen_bspline_jastrow' (around line 120).

**Comment by ye-luo** [comment]
It's not necessary to do finite difference. Just do the minimal.
For the moment, there is no need to check the functor.
Just check J1 and J2.evaluateHessian call.

**Comment by markdewing** [comment]
I was looking at the wrong part of the unit tests - I see some of it comes from finite differences, and I don't know how those were computed.

**Comment by ye-luo** [comment]
Just like https://github.com/QMCPACK/qmcpack/blob/c985be2bdf0ef04b179c4e6d4ac7645891e61203/src/QMCWaveFunctions/tests/test_bspline_jastrow.cpp#L140

**Comment by prckent** [comment]
I agree with Ye that unit testing the current value would be fine imo. Then at least we'll catch a change or compiler optimization bug that breaks the code.

**Comment by jtkrogel** [comment]
Very well.  Will get to this in time.

**Comment by jtkrogel** [comment]
Done.  Unit tests confirmed to pass for AoS/SoA real/complex.

As an item for future investigation, I noticed that evaluateHessian has side effects.  For example, sometimes if evaluateLog is not called after evaluateHessian some other unit test would fail.  This is likely due to an incompatible change of internal state.

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
@jtkrogel I just commented the evaluateLog after evaluateHessian. The test passes. I tried both gcc7.3 on AMD ryzen and intel 18.3 on Xeon. Could you tried again on the develop branch by commenting the evaluateLog line? What is your testing platform?

**Pull request merged**
