### PR TITLE
Magnetization Density Observable for Spinors

### PR DESCRIPTION
**Pull request by rcclay**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This introduces a magnetization density estimator (legacy implementation) for use with non-collinear QMC calculations.  Use is very similar to existing density estimator.  Documentation on what is calculated and how to use in QMCPACK is added to the manual.  

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature
- Refactoring (no functional changes, no api changes)
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon
## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by PDoakORNL — COMMENTED** [review]
I am against adding any new feature using the legacy design. This is going to need to be ported to the batched version before the legacy driver can be dropped.

**Comment by prckent** [comment]
@rcclay This needs to be implemented and tested in the batched code. Please ask questions as needed about this.

**Comment by jtkrogel** [comment]
@rcclay thanks for working on this.  Any chance for supporting real space and/or grid count based ways of specifying the histogram cells as in `SpinDensity` (i.e. `dr` and `grid`)?

Also, one question: since the spin variables are sampled in non-collinear QMC, why are additional/different integrals performed over these variables?  I thought this would only be needed for off-diagonal estimators like the momentum distribution and 1RDM.

**Comment by jtkrogel** [comment]
Also, what are the physical systems you are testing the developments on?

**Comment by rcclay** [comment]
@PDoakORNL I am working on the batched implementation of this right now--I'm taking full responsibility for that, and this legacy implementation will be superceded by the batch implementation before it becomes useless (before end of FY or sooner).  However, this was the fastest way for me to stand up this **unique** capability and let ORNL/SNL folks start using it and stress testing it in the field.  There's going to be a lot of potential theory and application stumbling blocks associated with this estimator that will need to be sussed out independently of the code/performance aspects, and it's probably best for people to get a head start on that. 

@prckent I agree.  

@jtkrogel Right now, this is a dumb generalization of the DensityEstimator.  Can you hit me with a wishlist of features/gridding schemes so that I can fold that into the batched implementation?  Also, will the old binning scheme work for your team to start doing science with it, or does this need to be moved up the priority queue?

Re: additional spin integral.  Basically, if I'm in an Sz basis, Sx and Sy are nondiagonal.  The way that looks when you shift to this over complete continuous spin representation is you pick up an integral.  I've attached the integral performed:  
image

**Pull request closed without merging**
