### PR TITLE
Add tolerance to einspline 1D unit tests.

### PR DESCRIPTION
**Pull request by markdewing**
Addresses failure of unit tests on some systems.

### CODE REVIEW

**Comment by ye-luo** [comment]
Which systems?

**Comment by markdewing** [comment]
Kayahan (from ORNL) emailed me about these unit test failures on the OIC cluster, after compiling with the OIC5.cmake toolchain file.

**Comment by ye-luo** [comment]
@markdewing I see.
@jtkrogel Are OIC5.cmake and PsiIntelMPI.cmake still necessary?

**Comment by prckent** [comment]
1. Odd that this has not turned up on any other system. Perhaps there are some interesting optimization settings?

2. I would rather these be replaced by a build script, as we have for OLCF machines. I think the only odd thing about the OIC and PSI machines is the library locations. If a toolchain is still needed it is a sign that we need to work on CMakeLists.txt

**Comment by ye-luo** [comment]
@markdewing Did you checked this on OIC5 or someone at ORNL confirmed this patch solving the problem?

**Comment by kayahans** [comment]
Yes, after the fix that Mark suggested, all the tests ran fine. I had only these modules loaded during compilation: 
composerxe/2013.5.192    mpi/openmpi-1.6.4-gcc4

**Comment by ye-luo** [comment]
@kayahans Everything seems old. I don't think we should compromise the rigorous testing for legacy.
The toolchain indicates this is a machine with AMD processor but you are using intel compiler.
Do you have any newer compilers on this machine? gcc 4.8 or newer?

**Comment by prckent** [comment]
OIC5 has gcc4.9.3, openmpi 1.6.5, cmake 3.2.2. The issue is that no one has touched the toolchain in years. Less critically, it should also use a recent HDF5 and libxml2.

**Comment by markdewing** [comment]
I'm pretty sure all the floating point comparisons in the unit tests should
use Approx.  I don't think there's any place where we need to demand
bitwise reproducibility for floating point values.

Some checks do not have Approx because they were overlooked and haven't
caused problems (until now).

**Comment by ye-luo** [comment]
@markdewing True in general but seems not true in this case. 1.0+1.0 should be 2.0 instead of approx(2.0) even if they are floats.

**Comment by ye-luo** [comment]
@kayahans Could you check if a build with the most recent compiler on OIC5 without using toolchain still require this patch? You can find the way to get AMD libm passed to cmake in build_olcf_titan.sh.
If it is still needed, I will approve this PR.

**Comment by markdewing** [comment]
I see this failure on a regular workstation (x86_64) with clang 5.0 in release mode.

**Pull request merged**
