### PR TITLE
[Multi] make changes to rely on ADL get instead of std::get

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

use modified interface of Multi that doesn't rely in UB by specializing std::get in namespace std.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu gitlab CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
codecov in the CI is failing, https://github.com/QMCPACK/qmcpack/actions/runs/11831469869/job/32968026644?pr=5228#step:8:46

**Comment by correaa** [comment]
ok, I think I am ready with the changes Multi is updated to release v0.86.0
https://gitlab.com/correaa/boost-multi/-/releases/v0.86.0

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
@correaa there were build failure in the complex builds https://github.com/QMCPACK/qmcpack/actions/runs/11873027958/job/33107327082

**Comment by correaa** [comment]
Do you know a trick to compile the real and complex version simultaneously? Perhaps using Ninja Multiconfig?

**Comment by prckent** [comment]
The build system has no insight into which files are different between real and complex so there is currently no benefit to be gained over two independent builds.

**Comment by correaa** [comment]
The benefit, at the minimum, is that one has a single consistent cmake
command line.

**Comment by prckent** [comment]
@correaa Indeed. Long term we should have a single executable. Unfortunately that work was not completed during ECP and since it is not a major blocker it is not high on the to do list. Clearly it would be a user friendly feature and simplify builds, installs, and testing. If more arguments appear to complete that work it will be moved higher on the list.

**Comment by correaa** [comment]
ok, thanks. Sorry for the noise. Multi got caught in new undefined behavior introduced between C++17 and C++20 regarding overloading in std namespace.

See "Function templates and member functions of templates" in section https://en.cppreference.com/w/cpp/language/extending_std

Making the code compile in C++17 (without C++20 extensions) and C++20 requires this kind of tricks.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
