### PR TITLE
Nexus support for Kagayaki cluster at JAIST

### PR DESCRIPTION
**Pull request by ichibha**
## Proposed changes
This PR implements the Nexus settings for Kagayaki cluster at JAIST. 

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Kagayaki cluster at JAIST. 

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- N/A, only Python scripts are revised. Code added or changed in the PR has been clang-formatted.
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by jtkrogel** [comment]
@ichibha all tests pass with `nxs-test`?

**Comment by prckent** [comment]
The Nexus tests are failing in CI. Maybe we need some more examples on how to add a machine and have the tests pass?

**Comment by ichibha** [comment]
At least, I have to add Kagayaki in test_machines.py. I try to solve the errors myself first to pass this PR.

**Comment by jtkrogel** [comment]
@ichibha any luck?

**Comment by ichibha** [comment]
@jtkrogel Currently, this specific test is the only one that fails. It seems unrelated to the updates I made. It's possible that the failure is due to the use of the Apple M2 architecture. 

Before submitting the pull request, I have two tasks to complete:
- Confirm that job_write_ref['kagayaki'] functions correctly in the current environment.
- Enable the specification of number of OMP threads. 

```
 61/69 qdens_radial............................   Failed  12.76 sec
Test name     : qdens_radial
Test sublabel : test_radial_density
Test exception: "AssertionError: "
Test backtrace:
  File "/Users/maezono/qmcpack/nexus//bin/nxs-test", line 478, in run
    self.operation()
  File "/Users/maezono/qmcpack/nexus//bin/nxs-test", line 1631, in qdens_radial
    nunit_all()
  File "/Users/maezono/qmcpack/nexus//bin/nxs-test", line 362, in nunit_all
    run_external_unit_test(test_name,unit_test)
  File "/Users/maezono/qmcpack/nexus//bin/nxs-test", line 388, in run_external_unit_test
    unit_test()
  File "/Users/maezono/qmcpack/nexus/tests/unit/test_qdens_radial.py", line 155, in test_radial_density
    assert(text_eq(out,out_ref))
```

**Comment by ichibha** [comment]
@jtkrogel I wanted to inform you that the current version of our feature branch successfully passes all tests in the nxs-test suite with the exception of test 61/qdens_radial. I've been able to confirm that the generated PBS files are functioning as expected.

Given the above, I believe the branch is in a suitable state for merging. Please could you review and consider approving the merge request?

**Comment by ichibha** [comment]
I performed nxs-test of the latest develop branch, and 61/qdens_radial failed.
Thus, the failure at 61/qdens_radial would not be because of my updates.

**Comment by markdewing** [comment]
@jtkrogel Is PR this okay with you?   The nexus tests pass for me locally.

**Comment by jtkrogel** [comment]
Yes it is.  The qdens radial issue may be environment dependent and should be handled separately.

**Review by prckent — APPROVED** [review]
Based on discussion above

**Pull request merged**
