### PR TITLE
Deprecate SSE and improve cross-compiling

### PR DESCRIPTION
**Pull request by ye-luo**
1) Historically we have two sets of einspline implementation, intrinsic version (up to SSE4.1) and standard version. The selection is controlled via flags like 
HAVE_SSE HAVE_SSE2 HAVE_SSE3 HAVE_SSSE3 HAVE_SSE41 HAVE_FMA4
Which are set by either detecting the flags on the compiling host or user input.
They are very unfriendly to cross-compiling and often not set accurate enough.
My recent observation shows on both AMD(interlago) and Intel(haswell) CPUs the std3 version outperform the legacy SSE versions. There is no reason to keep the intrinsic versions. In addition, they are no more used in any critical part after the SoA change and they are needed to build the GPU code only. For this reason only std3 versions are kept and sse versions are moved to legacy.

2) More friendly cross-compiling #297 
All the detecting of instruction set on the compiling host is removed.
a) If building on a Cray, do nothing and respect the compiler wrapper.
b) if not on a Cray and user specified -march (GNU and Clang) or -x/ax (Intel) in CMake compiler flags, respect user choice
c) if not on a Cray and no user input, use -march=native (GNU and Clang) and -xhost (Intel)

Note: building recipes need to be updated. For example, NERSC cori phase 2 no more needs to specify -xMIC-AVX512 (no harm if you keep it).

3) removed a few cuda code files in einspline folder, they are never used.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Confirmation needed from people with cross-compile machines, e.g. @lshulen that this is OK

**Comment by prckent** [comment]
OK with deprecation, more than timely

**Comment by ye-luo** [comment]
I manually build the gpu code on rhea and it was successful.
GPU build needs twice make as the CI does.
In the first time, make will stop very quickly and issue some error.
In the second time, make will trigger cmake again and then build binaries only with warnings.
The CI fails seem like the first make didn't stop properly but the second started and then everything messed up.

@grahamlopez I'm wondering whether changing the first "make -j 8" to "make -j 1" helps.

**Comment by lshulen** [comment]
In general I think the cross-compilation part is reasonable.  I will try to get on one of our older crays and test this to see if it is working properly.  A question though.  Why should I not be able to override the compiler wrapper's choice of architecture flags on a cray?

**Comment by ye-luo** [comment]
@lshulen You can still override like -DCMAKE_CXX_FLAGS="-xMIC-AVX512" but no more necessary.
In the past, we have to override because our CMake setting puts -xhost but CC wrapper has -xMIC-AVX512 and you get tons of warnings. When our CMake setting detects -x from CMake command line, it drops -xhost and no more warnings.
Now, you fully trust CC wrapper to put the flag for you.

**Comment by lshulen** [comment]
That sounds reasonable.  I wonder if someone with access to NERSC could double check that this would work properly on Cori?  In particular, by changing the craype module can you properly produce executables for both phase 1 and phase 2 of the machine?  (Trinity will have the same thing to worry about but I don't have access at the moment)

**Comment by ye-luo** [comment]
Not much idea about NERSC. Based on the section for Cori in our manual, You need to switch modules for phase 1 and 2. I think the underneath flags of CC are changed. In this new setting, I think the manual can even been merged because the only difference is "module swap craype-haswell craype-mic-knl"

To build a single binary for both KNL and BDW, I found some info on NERSC website
http://www.nersc.gov/users/computational-systems/cori/programming/compiling-codes-on-cori/
There is also a compiler flag "-ax MIC-AVX-512,AVX" for Intel compilers that will build a fat binary for both Haswell and KNL, and at run time will use the binary for the correct architecture.
You can still pass it through CMAKE_CXX_FLAGS.

**Comment by ye-luo** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by lshulen** [comment]
I can build it on my local cray machines.  It looks fine to me.

**Comment by ye-luo** [comment]
The CI Rhea GPU build is resolved. The GPU node has HSW but the software is way behind.
Workaround by disabling AVX2 and BMI2.

**Pull request merged**
