### PR TITLE
test PR 2, remove a space from nexus.py

### PR DESCRIPTION
**Pull request by jtkrogel**

### CODE REVIEW

**Comment by grahamlopez** [comment]
+1 
(trailing whitespace == bad)

**Comment by grahamlopez** [comment]
The only other thing I would caution is to remember to pull changes from 'develop' into your 'dev' branch if it is going to be long-lived.

**Comment by jtkrogel** [comment]
Yes, intent is to pull->make small mods->push->pull request.

**Comment by ye-luo** [comment]
My last night experience shows if your previous pull request has not been approved, it will be automatically updated when your new changes are pushed to the same branch.

**Comment by prckent** [comment]
Yes. Pushing on the same branch will update a pending PR. This is intended to allow fixes to be made and reviewer comments to be addressed.

**Pull request merged**
