### PR TITLE
Llnl afqmc

### PR DESCRIPTION
**Pull request by mmorale3**
This big commit brings the development version of the AFQMC code in sync with local LLNL development. The large commit is caused by the change from svn (development after move to git) to git.

### CODE REVIEW

**Comment by mmorale3** [comment]
Done on next commit. I didn't know that changes pushed to the repository after the pull request is made are also included. Good to know.

**Comment by ye-luo** [comment]
The PR is automatically updated ;)

**Comment by ye-luo** [comment]
Start   1: unit_test_afqmc_matrix
1/3 Test   #1: unit_test_afqmc_matrix ...........***Failed    0.05 sec
    Start   2: unit_test_afqmc_numerics
2/3 Test   #2: unit_test_afqmc_numerics .........***Failed    0.06 sec
    Start 179: short-afqmc-N2_vdz-4-1
3/3 Test #179: short-afqmc-N2_vdz-4-1 ...........   Passed   37.04 sec
Are they broken just in PR or was broken before?

**Comment by ye-luo** [comment]
scoping rules it would have been variable "i" (declared at line 857)
          *(it++) = i; // loc of ci coeff
                    ^

/sandbox/opt/qmcpack-mmorales/src/AFQMC/Wavefunctions/MultiPureSingleDeterminant.cpp(898): warning #823: reference is to variable "i" (declared at line 829) -- under old for-init scoping rules it would have been variable "i" (declared at line 886)
          *(it++) = i; // loc of ci coeff
                    ^
should I just ignore these warnings?

**Comment by markdewing** [comment]
The 'i' line 886 should be renamed to  avoid warnings and confusion.

**Comment by mmorale3** [comment]
i made changes to the matrix routines, the unit tests may be broken as a result.

**Comment by mmorale3** [comment]
fixed the bug in MultiPureSingleDeterminant.cpp in latest commit

**Comment by ye-luo** [comment]
The failing tests will be fixed later as it only affects no-MKL case for AFQMC calcuation.

**Pull request merged**
