### PR TITLE
fix for unsupported -march=native on summit

### PR DESCRIPTION
**Pull request by grahamlopez**
we could replace with -mcpu=native, but when I did this I got lots of warnings of the sort:
```
/usr/bin/ld: LPQHIBasis.cpp:(.text+0x1bb8): toc optimization is not supported for 0xe6a90002 instruction.
```
so for now, just disabling completely.

### CODE REVIEW

**Comment by ye-luo** [comment]
Can we put the protection in the upper level as the miniqmc? The reason is any -march is invalid for ppc64.

**Comment by grahamlopez** [comment]
yes I see your point. I did this to let the user still use custom flags, but maybe we should protect them from themselves...

**Comment by prckent** [comment]
@grahamlopez We should be consistent with miniqmc

@ye-luo , others: Are there any other systems identifying as ppc64 that we need to guard for?

**Comment by grahamlopez** [comment]
@prckent, yes, sorry it wasn't clear, I'm agreeing with @ye-luo. 
I think this should guard anything that identifies as ppc64, not just summit

**Comment by prckent** [comment]
What do the BG head nodes identify as?

**Comment by ye-luo** [comment]
@grahamlopez In this [PR](https://github.com/QMCPACK/miniqmc/pull/87) on miniQMC the clang config is also changed like GNU accordingly. Share we do the same?
@prckent XL flags have significant changes since power8 (first little endian). Our XL configuration is targeting that. BGQ uses toolchain file.

**Comment by grahamlopez** [comment]
@ye-luo interestingly, clang on summit doesn't seem to have a problem with `-march=native` If you want me to add the guard anyway, I don't mind

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by ye-luo** [comment]
I tried the clang module and got
```
clang -march=native hello.cpp
clang-3.8: warning: argument unused during compilation: '-march=native' [-Wunused-command-line-argument]
```
So the guard seems necessary.

**Comment by grahamlopez** [comment]
test this please

**Pull request merged**
