### PR TITLE
Fix clang11 gcc9

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

make afqmc compile with clang-11+gcc-9 (requested in https://github.com/QMCPACK/qmcpack/issues/2937)

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 20.04, openmpi, clang-11, gcc-9

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
It is very likely that after this patch, the multi-dependent code will be compilable with c++17 (including clang-1X and gcc).

**Comment by correaa** [comment]
Should I open a different PR? All the changes are in Multi now.

**Comment by ye-luo** [comment]
The current branch has been polluted by multiple delete add submodule. It will be better to start from develop clean.
Please make sure `external_codes/boost_multi/multi/README` is not wiped out. We should put it under `external_codes/boost_multi`

**Comment by correaa** [comment]
Continued here https://github.com/QMCPACK/qmcpack/pull/2975

**Pull request closed without merging**
