### PR TITLE
Workaround for assignment-after-reduction bug in mixed precision

### PR DESCRIPTION
**Pull request by markdewing**
Workaround for #4767 in mixed precision builds.

Assign the x,y and z gradient components individually.
Otherwise in mixed precision builds, where these are floats, the z component does not get copied.

As noted in the comments, the workaround of reducing the size of the `iw` index variable to 16 bits also works, but a limit of 32K walkers for a loop is uncomfortably small.

This bug should not affect complex reductions, as complex number only have two components.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
local server

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by PDoakORNL — APPROVED** [review]
This seems ok to me.  We have reported this as an issue to the openmp target folks?

**Comment by ye-luo** [comment]
Does this workaround help particularly mixed precision complex?

**Comment by ye-luo** [comment]
1) your fix worked on complex mixed precision build with cuda 12.2
2) I tried cuda 12.3 and found it working without this PR and #4773.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Will merge tomorrow.

**Pull request merged**
