### PR TITLE
Add Molden2qmc

### PR DESCRIPTION
**Pull request by gjohnson3**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Adds molden2qmc in the documentation under docs/additional_tools. It is a python program that can convert quantum chemistry code into an hdf5 file for qmcpack.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature
- Code style update (formatting, renaming)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

-linux

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Many thanks for this. The extra capability and connections will be very useful - using your tool QMCPACK will now be able to use wavefunctions from PSI4, ORCA, MOLPRO, QCHEM, NWCHEM, and more.

Q. What testing have you done? For example, are there any concerns with high-angular momentum basis sets?

**Comment by prckent** [comment]
Test this please

**Comment by anbenali** [comment]
The tool comes with an internal testing tool. The tool tests if generated
H5 is identical to the one provided in the git. Every code is tested
against H5 correctness but we have added specific long VMC runs for each of
the codes with various basis sets sizes to test inaccuracies. Finally there
is one specific set of tests where the system is "fake" and the basis set
is formed of d-, f- and g-orbitals alone. Any error in normalization or
order would lead to guant errors. All the cases have VMC runs associated to
insure correctness.

These are shipped with molden2qmc and as mentioned, the only test to run
with molden2qmc is h5diff.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
