### PR TITLE
Spinor Unit Tests

### PR DESCRIPTION
**Pull request by rcclay**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds extensive unit tests of evaluateValue, evaluateVGL, and evaluate_spin for spinor type wave functions.  The bugs caught here were already fixed by Cody in PR #2343, but hopefully this will catch more subtle breakages in the future.  

## What type(s) of changes does this code introduce?

- Other (please describe):  unit tests

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Workstation

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Thank you @rcclay. Could you move all the spin set test from test_einset.cpp to test_einset_spin.cpp. The current file is getting too long.

**Comment by prckent** [comment]
Good to see these unit tests.

**Comment by rcclay** [comment]
@ye-luo Done.

**Comment by PDoakORNL** [comment]
```
CMake Error at src/QMCWaveFunctions/tests/CMakeLists.txt:57 (ADD_EXECUTABLE):

  Cannot find source file:


    test_einset_spinor.cpp


  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm

  .hpp .hxx .in .txx



CMake Error at src/QMCWaveFunctions/tests/CMakeLists.txt:57 (ADD_EXECUTABLE):

  No SOURCES given to target: test_wavefunction
```

**Comment by rcclay** [comment]
@ye-luo @PDoakORNL All fine?

**Comment by PDoakORNL** [comment]
Same test failures as #2342 looks like the slightly different software stack on the vm box is leading to failures. Since this is clearly an upstream issue I'm inclined to file and issue and merge #2354 & #2342. However the VM CI will need to be removed from the must pass CI checks.

**Pull request merged**
