### PR TITLE
Add QE 6.8 pw2qmcpack patch.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
QE 6.8 with pw2qmcpack. CMake has become the preferred way for building QE.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by jtkrogel** [comment]
Just an aside: what does QE still need to be able to accept pw2qmcpack into their repo?

**Comment by ye-luo** [comment]
If I'm a reviewer, I would like to see `clib/esh5_interfaces.c`  our hdf5 abstraction going away. It is half of the lines and it is not using iso_c_binding. So it is already a potential source of problems.

**Comment by prckent** [comment]
Release notes https://github.com/QEF/q-e/releases/tag/qe-6.8

**Comment by prckent** [comment]
Looking at this now.

**Review by prckent — APPROVED** [review]
Works for me. I was able to build QE after cmake configuration and get a pw2qmcpack executable included along with the standard binaries. I'll update our nightly tests scripts once merged.

Thanks for doing this so quickly after the QE6.8 release.

**Comment by prckent** [comment]
Start testing in-house

**Pull request merged**
