### PR TITLE
Refactor MinimalParticlePool, MinimalWaveFunctionPool, MinimalHamiltonianPool

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
1. Make all member static constexpr, make all functions const. Should be more readable.
2. Add a PBC distance table test.

## What type(s) of changes does this code introduce?
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
I like the look of this but will leave for Peter's input since he was tagged.

**Review by PDoakORNL — APPROVED** [review]
Looks good, these hadn't been touched for 3 years and I think the static function with comm is superior to the old functor design. It's more readable, simple, and leaves room for clearly labeled "mocks" of other systems.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
