### PR TITLE
Protect complex reduction in real builds.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Getting llvm-link error in real builds with icpx due to unprotected reduction on complex in offload regions. 

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
sunspot

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Q. Since we will likely gain more of these workarounds, how about adding // COMPILER WORKAROUND or similar so that we can find these in future?

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
> Q. Since we will likely gain more of these workarounds, how about adding // COMPILER WORKAROUND or similar so that we can find these in future?

Added on https://github.com/QMCPACK/qmcpack/pull/4380 which needs a new approval

**Pull request merged**
