### PR TITLE
Add a safe guard to updateInvMat

### PR DESCRIPTION
**Pull request by ye-luo**
I didn't see it causing problem but I feel it more safe to add this guard. It costs nothing.

### CODE REVIEW

**Comment by markdewing** [comment]
Could you say more about what makes this safe? (Or what was potentially unsafe about not having it set?)   Right now, with the comment in the code, I assume there is something very tricky going on and need to study all the called code carefully so see where Ainv_row_ind is updated between here and where it is set again later.

**Comment by ye-luo** [comment]
It is used to check if getInvRow was called for the same electron when ratioGrad is called.
If they matches, the code will not recomputed AinvRow.
Once a move is accepted or all the pbyp move is done. Ainv_row_ind is marked -1 for safety.
I'm thinking of a case that getInvRow is called but there is no accept. Ainv_row_ind is left not -1.
If the code start to work on a second walker and calls ratioGrad and by chance the Ainv_row_ind matched even getInvRow was not recomputed. The AinvRow from the last walker will be used and things go wrong. However, in reality evalGrad is always called before ratioGrad. Ainv_row_ind is always refreshed.

I feel more safe putting -1 when a move is accept (we ready have it) and all the moves are completed (added in this PR).

**Comment by prckent** [comment]
Obligatory comment: feelings about safety of code points to insufficient testing and poor design in overall the application. We are getting better but there is along way to go.

**Comment by prckent** [comment]
I agree that the comment simply needs improving here.

(For the future, and hopefully becoming less relevant as we remove state information: In general for state machines with exposed functions that can only be called in certain sequences, the state machine should have an explicit internal state where each state is labeled. Functions then assert() that the state machine is in an acceptable state before doing any work. This exposes the logic of the state machine in the source code and makes visible something which is otherwise hidden. If the state machine is complex or important enough, an explicit transition state table can be built to avoid any ambiguity. )

**Comment by ye-luo** [comment]
@markdewing I added point to point reply directly in your comment. Thank you so much for commenting at this level of detail.
@prckent I agree with you, we should document in source state machines as clear as possible. However, in this case, the state goes from -1 to Norb which can't be put in a table.

**Pull request merged**
