### PR TITLE
Nexus: update to current batched driver style

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Support `driver_version` and also currently working estimators for the batched drivers.  The sole Nexus example for the batched drivers has been updated (also including Jastrow optimization) and another has been added that includes all currently working estimators: MPC, spin density, and the momentum distribution.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by jtkrogel** [comment]
Nevermind on the 1RDM issue.  The batched 1RDM works; I just had to request the correct orbital count.

Ready for review.

**Review by prckent — APPROVED** [review]
LGTM

Thanks Jaron.

**Comment by prckent** [comment]
Q. How long does this take to run? I think several people including yourself have suggested that we start including the examples in our nightly runs or even CI.

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
```
The following tests FAILED:
	1704 - ntest_nexus_qmcpack_input (Failed)
	1728 - ntest_nexus_qdens (Failed)
	1732 - ntest_nexus_example_qmcpack_H2O (Failed)
	1733 - ntest_nexus_example_qmcpack_LiH (Failed)
```
Are you able to reproduce this locally?

**Comment by jtkrogel** [comment]
Yes, I can reproduce these.  Will fix.  The entire battery of Nexus tests takes under a minute on a single core of my 2017 laptop.

**Comment by jtkrogel** [comment]
Issues fixed.  Ready for review.

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
