### PR TITLE
 Update multi using release v0.80.1, second try

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Review by prckent — DISMISSED** [review]
LGTM

Hoping for successful CI

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
victory?

**Review by ye-luo — APPROVED** [review]

**Comment by correaa** [comment]
After making it work with `icpc 2021.7.0` and updating the compiler I noticed this message: "The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023.  The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.".

**Comment by prckent** [comment]
Indeed. Hence the discussion around dropping the classic compilers and moving to the oneapi ones. However there is a large installed base on clusters etc. with only the older classic compiler, so if they can be supported that makes things easier for users.

**Comment by correaa** [comment]
Yes, as I use more rvalue references, I see Intel Classic getting more things wrong.
I have to workaround several tests and at about 20 places in the libraries making it hard to maintain.
The worst used to be PGI C++ but now PGI C++ (now NVHPC) is ok and Intel Classic is the worst.

```
examples/loops_timings.cpp:	#if defined(__INTEL_COMPILER)
include/multi/adaptors/fftw/test/moved.cpp:	#if not defined(__INTEL_COMPILER)  // TODO(correaa) problem with icpc 2022.3.0.8751
include/multi/adaptors/fftw/test/moved.cpp:	#if not defined(__INTEL_COMPILER)  // TODO(correaa) problem with icpc 2022.3.0.8751
include/multi/adaptors/fftw/test/moved.cpp:	#if not defined(__INTEL_COMPILER)  // TODO(correaa) problem with icpc 2022.3.0.8751
include/multi/adaptors/fftw/test/moved.cpp:	#if not defined(__INTEL_COMPILER)  // TODO(correaa) problem with icpc 2022.3.0.8751

include/multi/adaptors/cufft.hpp:#ifndef __INTEL_COMPILER
include/multi/adaptors/cufft.hpp:#ifndef __INTEL_COMPILER
include/multi/adaptors/blas/dot.hpp:#if not defined(__CUDACC__) or not defined(__INTEL_COMPILER)
include/multi/adaptors/lapack/geqrf.hpp:#if not __INTEL_COMPILER
include/multi/detail/tuple_zip.hpp:#if defined(__INTEL_COMPILER)  // this instance is necessary due to a bug in intel compiler icpc
include/multi/array_ref.hpp:	#if not defined(__NVCC__) and not defined(__NVCOMPILER) and not defined(__INTEL_COMPILER)
include/multi/array_ref.hpp:#if not((defined(__INTEL_COMPILER)) or defined(__NVCC__))
include/multi/array_ref.hpp:	#if not defined(__INTEL_COMPILER) and not defined(__NVCOMPILER) and not defined(__NVCC__)
include/multi/array_ref.hpp:	#if not defined(__NVCC__) and not defined(__NVCOMPILER) and not defined(__INTEL_COMPILER)
include/multi/array_ref.hpp:#if defined(__GNUC__) and (not defined(__INTEL_COMPILER))
include/multi/array_ref.hpp:// #if defined(__INTEL_COMPILER)
include/multi/config/DEPRECATED.hpp:#if not defined(__INTEL_COMPILER)
include/multi/config/DEPRECATED.hpp:#if not defined(__INTEL_COMPILER)
include/multi/config/UNREACHABLE.hpp:#if defined(__GNUC__) || defined(__clang__) || defined(__INTEL_COMPILER) || defined(__NVCC__)
include/multi/array.hpp:	#if not defined(__NVCC__) and not defined(__INTEL_COMPILER)
include/multi/array.hpp:	#if not defined(__NVCC__) and not defined(__INTEL_COMPILER)
include/multi/array.hpp:	#if not defined(__NVCC__) and not defined(__NVCOMPILER) and not defined(__INTEL_COMPILER)

test/layout.cpp:#if defined(__INTEL_COMPILER) or (defined(__GNUC__) and (__GNUC__ < 6))
test/layout.cpp:#if defined(__INTEL_COMPILER) or (defined(__GNUC__) and (__GNUC__ < 6))
test/initializer_list.cpp:#if defined(__INTEL_COMPILER) or (defined(__clang__) and (__clang_major__ >= 10))  // doesn't work on gcc
test/reextent.cpp:	#if not defined(__INTEL_COMPILER) and not defined(__NVCOMPILER)
```

**Pull request merged**
