### PR TITLE
Split EinsplineAdoptor.h into SplineAdoptorBase.h and BsplineSet.h and delete dead code

### PR DESCRIPTION
**Pull request by PDoakORNL**
As I'm working on moving the CUDA code from EinsplineSetExtended to BsplineSet and reading through code I'm reorganizing files and removing some dead code where it is obvious it should happen.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by PDoakORNL** [comment]
Warning: Force rebased

**Comment by PDoakORNL** [comment]
Will do

**Comment by PDoakORNL** [comment]
Force rebase onto develop

**Pull request merged**
