### PR TITLE
Input File from convert4qmc

### PR DESCRIPTION
**Pull request by anbenali**
- Fix Generic Input File for begginers mode according to conversation with P. Kent.
- Fix bug in Input file: 
      -No optimization block when No Jastrow present; 
      -Fix Comment about ECP if no ECP is present; 

-Removed tag "-writewfJonly" for writing only one set of files. 
- Added Tag "-production" that will use more efficient parameters for production runs;
         -Only one file is generated depending if "-noJastrow" tag is added.

### CODE REVIEW

**Comment by markdewing** [comment]
Okay to test

**Comment by prckent** [comment]
- Renamed example QMCPACK input files to \*.qmc.in\*.xml to distinguish from \*.in\* files used by other applications
- J2 is not created if there is only 1 electron
- J2 u-u terms are only created if there are at least two electrons of one spin 
- J3 is not added unless there are at least 2 atoms
- Commented out the forced logging in src/Numerics/GaussianBasisSet.h::addGaussian and putBasisGroupH5. Separate log functions should be created and used if needed.

**Comment by prckent** [comment]
- Fixed J3 creation rule
- Increased print threshold for HDF5 suggestion to 4000 orbitals * basis functions (in earlier commit)

**Comment by prckent** [comment]
@ye-luo Make a note in the PR reviewers wiki

**Pull request merged**
