### PR TITLE
CODECOV_TOKEN as env

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add CODECOV_TOKEN as an environment variable from GitHub Actions secrets.
From the codecov [docs](https://docs.codecov.com/docs/quick-start). 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
N/A

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — DISMISSED** [review]
LGTM.

Would be nice to know what we are missing if anything from v4, but getting something working takes priority.

**Comment by williamfgc** [comment]
v4 can't find the coverage file when. [uploading](https://github.com/QMCPACK/qmcpack/actions/runs/8714774464/job/23905565382#step:8:50). I wonder if something changed with the path fixes in codecov.yaml. The env variable probably didn't make any difference.

**Comment by prckent** [comment]
Got a rate limit error this time. Merge and keep an eye on it?

**Comment by williamfgc** [comment]
The strange thing is that we are following their [docs](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) as indicated by the error message.

**Review by prckent — APPROVED** [review]
Will merge.

Coverage is not working but at least we will have green check marks while a fix is worked on.

**Comment by williamfgc** [comment]
Opened related issue on [codecov-action#1379](https://github.com/codecov/codecov-action/issues/1379)

**Pull request merged**
