### PR TITLE
Speed up reference Ewald sums with OpenMP

### PR DESCRIPTION
**Pull request by markdewing**
First attempt to address #2158

Also add a timer.   Some of the investigation was done with additional timers, and most of the time is spent in the k-space sum.

Convert the triangular loop to a square loop so the OMP collapse clause will work.

If the triangular loop is left in place, and the OMP is placed only on the outer loop, load balancing becomes an issue - the final iteration will be the most time consuming.

This has only been lightly tested.

### CODE REVIEW

**Comment by markdewing** [comment]
I'm getting 4.5x speedup on 6 threads for the NiO a16-e192 problem.    Larger problems are taking too long to get timings for the serial code.

**Comment by prckent** [comment]
Perhaps greater OpenMP speedups will be possible with a flattened loop and explicit "triangle indexing" to avoid the need for the dynamic schedule.

**Comment by prckent** [comment]
@ye-luo OK. Earlier I had the following but did not check timings:

```
 real_t ve2 = 0.0;
 #pragma omp parallel for reduction(+:ve2)
 for(size_t k=0; k<N*(N-1)/2; k++)
   {
      size_t i = k/N, j = k%N;
      if(j<=i) i = N-i-2, j=N-j-1;
        {
          real_t qq = Q[i]*Q[j];
          ve2 += qq*ewaldSum(R[i]-R[j],a,tol/qq);
        }
   }
```

**Comment by prckent** [comment]
@ye-luo OK

**Pull request merged**
