### PR TITLE
Fix typo tparm -> tparam

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix typo for doxygen and also adjust all other occurrence.

## What type(s) of changes does this code introduce?
- Code style update (formatting, renaming)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Start testing in-house

**Review by prckent — COMMENTED** [review]
You picked up the variable optparm as well. Change back, leave?

**Comment by ye-luo** [comment]
> You picked up the variable optparm as well. Change back, leave?. I am ok with changing.

That is intended. I also don't like abbreviate "parameter" as "parm" but "param".

**Comment by ye-luo** [comment]
Start testing in-house

**Review by prckent — APPROVED** [review]

**Pull request merged**
