### PR TITLE
Update multi 231223

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
Trying a different strategy than  #4881 . Please test.

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
I am trying to reproduce the error locally, I can't compile with the current flags.
I get `lto-wrapper: fatal error: could not find accel/nvptx-none/mkoffload in /usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/ (consider using ‘-B’)`

Any ideas?

```
cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DMPIEXEC_EXECUTABLE=mpirun -DBUILD_AFQMC=ON -DENABLE_CUDA=ON -DQMC_GPU_ARCHS=sm_61 -DENABLE_OFFLOAD=ON -DQMC_COMPLEX=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DQMC_DATA=/scratch/ci/QMC_DATA_FULL ..
 2029  cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DMPIEXEC_EXECUTABLE=mpirun -DBUILD_AFQMC=ON -DENABLE_CUDA=ON -DQMC_GPU_ARCHS=sm_61 -DENABLE_OFFLOAD=ON -DQMC_COMPLEX=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DQMC_DATA=/scratch/ci/QMC_DATA_FULL .. --fresh
 2030  make deterministic-unit_test_afqmc_wfn_factory_ham_chol_uc_wfn_rhf deterministic-unit_test_afqmc_prop_factory_ham_chol_uc_wfn_rhf deterministic-unit_test_afqmc_estimators_ham_chol_uc_wfn_rhf
```

```
$ make
...
[ 11%] Linking CXX executable test_dualallocators
cd /home/correaa/qmcpack/build.offload/src/Containers/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_dualallocators.dir/link.txt --verbose=1
/usr/bin/mpicxx  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native -foffload=nvptx-none -foffload-options="-lm -latomic" -foffload-options=nvptx-none="-misa=sm_61" -O2 -g -DNDEBUG CMakeFiles/test_dualallocators.dir/test_dual_allocators_ohmms_containers.cpp.o -o test_dualallocators   -L/usr/lib/x86_64-linux-gnu/stubs  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial -lrt ../../Message/libcatch_main.a ../libcontainers.a libcontainer_testing.a ../../Utilities/for_testing/libutilities_for_test.a ../../Platforms/CPU/libplatform_cpu_LA.a ../../Platforms/OMPTarget/libplatform_omptarget_LA.a ../../Platforms/CUDA/libplatform_cuda_LA.a /usr/lib/x86_64-linux-gnu/libcusolver.so /usr/lib/x86_64-linux-gnu/libcublas.so /usr/lib/x86_64-linux-gnu/libculibos.a /usr/lib/x86_64-linux-gnu/libcublasLt.so /usr/lib/x86_64-linux-gnu/libcusparse.so /usr/lib/x86_64-linux-gnu/libnvJitLink.so ../../Utilities/libqmcutil.a ../../io/hdf/libqmcio_hdf.a ../../Message/libmessage.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libpthread.a /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.a -lm ../../io/OhmmsData/libqmcio_xml.a ../libcontainers.a ../../Platforms/libplatform_runtime.a ../../Platforms/CPU/libplatform_cpu_runtime.a /usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so /usr/lib/x86_64-linux-gnu/libmkl_sequential.so /usr/lib/x86_64-linux-gnu/libmkl_core.so -lm -ldl -lm -ldl ../../Platforms/OMPTarget/libplatform_omptarget_runtime.a ../../Platforms/CUDA/libplatform_cuda_runtime.a ../../Platforms/Host/libplatform_host_runtime.a /usr/lib/x86_64-linux-gnu/libcudart.so ../../Utilities/libcxx_helpers.a ../../Utilities/libqmcrng.a -lrt /usr/lib/x86_64-linux-gnu/libxml2.so -lcudadevrt -lcudart_static -lrt -lpthread -ldl 
lto-wrapper: fatal error: could not find accel/nvptx-none/mkoffload in /usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/13/:/usr/libexec/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/13/:/usr/lib/gcc/x86_64-linux-gnu/ (consider using ‘-B’)
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [src/Containers/tests/CMakeFiles/test_dualallocators.dir/build.make:135: src/Containers/tests/test_dualallocators] Error 1
make[2]: Leaving directory '/home/correaa/qmcpack/build.offload'
make[1]: *** [CMakeFiles/Makefile2:3590: src/Containers/tests/CMakeFiles/test_dualallocators.dir/all] Error 2
make[1]: Leaving directory '/home/correaa/qmcpack/build.offload'
make: *** [Makefile:146: all] Error 2
```

**Comment by correaa** [comment]
got it, I think installing `sudo apt install gcc-offload-nvptx` and changing architecture to one of the valid values fixed the compilation: `sudo apt install gcc-offload-nvptx`,  `cmake ... -DQMC_GPU_ARCHS=sm_70`

**Comment by correaa** [comment]
Now I am getting a different error:

```
make VERBOSE=1
...
[ 11%] Linking CXX executable test_dualallocators
cd /home/correaa/qmcpack/build.offload/src/Containers/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_dualallocators.dir/link.txt --verbose=1
/usr/bin/mpicxx  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native -foffload=nvptx-none -foffload-options="-lm -latomic" -foffload-options=nvptx-none="-misa=sm_70" -O2 -g -DNDEBUG CMakeFiles/test_dualallocators.dir/test_dual_allocators_ohmms_containers.cpp.o -o test_dualallocators   -L/usr/lib/x86_64-linux-gnu/stubs  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial -lrt ../../Message/libcatch_main.a ../libcontainers.a libcontainer_testing.a ../../Utilities/for_testing/libutilities_for_test.a ../../Platforms/CPU/libplatform_cpu_LA.a ../../Platforms/OMPTarget/libplatform_omptarget_LA.a ../../Platforms/CUDA/libplatform_cuda_LA.a /usr/lib/x86_64-linux-gnu/libcusolver.so /usr/lib/x86_64-linux-gnu/libcublas.so /usr/lib/x86_64-linux-gnu/libculibos.a /usr/lib/x86_64-linux-gnu/libcublasLt.so /usr/lib/x86_64-linux-gnu/libcusparse.so /usr/lib/x86_64-linux-gnu/libnvJitLink.so ../../Utilities/libqmcutil.a ../../io/hdf/libqmcio_hdf.a ../../Message/libmessage.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libpthread.a /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.a -lm ../../io/OhmmsData/libqmcio_xml.a ../libcontainers.a ../../Platforms/libplatform_runtime.a ../../Platforms/CPU/libplatform_cpu_runtime.a /usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so /usr/lib/x86_64-linux-gnu/libmkl_sequential.so /usr/lib/x86_64-linux-gnu/libmkl_core.so -lm -ldl -lm -ldl ../../Platforms/OMPTarget/libplatform_omptarget_runtime.a ../../Platforms/CUDA/libplatform_cuda_runtime.a ../../Platforms/Host/libplatform_host_runtime.a /usr/lib/x86_64-linux-gnu/libcudart.so ../../Utilities/libcxx_helpers.a ../../Utilities/libqmcrng.a -lrt /usr/lib/x86_64-linux-gnu/libxml2.so -lcudadevrt -lcudart_static -lrt -lpthread -ldl 
lto1: error: ‘-fcf-protection=full’ is not supported for this target
```

**Comment by ye-luo** [comment]
> Now I am getting a different error:
> 
> ```
> make VERBOSE=1
> ...
> [ 11%] Linking CXX executable test_dualallocators
> cd /home/correaa/qmcpack/build.offload/src/Containers/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_dualallocators.dir/link.txt --verbose=1
> /usr/bin/mpicxx  -fopenmp -finline-limit=1000 -fstrict-aliasing -funroll-all-loops -Wno-deprecated -Wvla -Wcomment -Wmisleading-indentation -Wmaybe-uninitialized -Wuninitialized -Wreorder -Wno-unknown-pragmas -Wno-sign-compare -Wsuggest-override -ffast-math -march=native -foffload=nvptx-none -foffload-options="-lm -latomic" -foffload-options=nvptx-none="-misa=sm_70" -O2 -g -DNDEBUG CMakeFiles/test_dualallocators.dir/test_dual_allocators_ohmms_containers.cpp.o -o test_dualallocators   -L/usr/lib/x86_64-linux-gnu/stubs  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial -lrt ../../Message/libcatch_main.a ../libcontainers.a libcontainer_testing.a ../../Utilities/for_testing/libutilities_for_test.a ../../Platforms/CPU/libplatform_cpu_LA.a ../../Platforms/OMPTarget/libplatform_omptarget_LA.a ../../Platforms/CUDA/libplatform_cuda_LA.a /usr/lib/x86_64-linux-gnu/libcusolver.so /usr/lib/x86_64-linux-gnu/libcublas.so /usr/lib/x86_64-linux-gnu/libculibos.a /usr/lib/x86_64-linux-gnu/libcublasLt.so /usr/lib/x86_64-linux-gnu/libcusparse.so /usr/lib/x86_64-linux-gnu/libnvJitLink.so ../../Utilities/libqmcutil.a ../../io/hdf/libqmcio_hdf.a ../../Message/libmessage.a /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/x86_64-linux-gnu/libpthread.a /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.a -lm ../../io/OhmmsData/libqmcio_xml.a ../libcontainers.a ../../Platforms/libplatform_runtime.a ../../Platforms/CPU/libplatform_cpu_runtime.a /usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so /usr/lib/x86_64-linux-gnu/libmkl_sequential.so /usr/lib/x86_64-linux-gnu/libmkl_core.so -lm -ldl -lm -ldl ../../Platforms/OMPTarget/libplatform_omptarget_runtime.a ../../Platforms/CUDA/libplatform_cuda_runtime.a ../../Platforms/Host/libplatform_host_runtime.a /usr/lib/x86_64-linux-gnu/libcudart.so ../../Utilities/libcxx_helpers.a ../../Utilities/libqmcrng.a -lrt /usr/lib/x86_64-linux-gnu/libxml2.so -lcudadevrt -lcudart_static -lrt -lpthread -ldl 
> lto1: error: ‘-fcf-protection=full’ is not supported for this target
> ```

Our CI uses clang for OpenMP offload not gcc.

**Comment by correaa** [comment]
Do you know how the cmake line has to be different to offload to clang?

`cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DMPIEXEC_EXECUTABLE=mpirun -DBUILD_AFQMC=ON -DENABLE_CUDA=ON -DQMC_GPU_ARCHS=sm_61 -DENABLE_OFFLOAD=ON -DQMC_COMPLEX=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DQMC_DATA=/scratch/ci/QMC_DATA_FULL ..`

**Comment by ye-luo** [comment]
No difference.

**Comment by correaa** [comment]
Ah, it must be some environment variable to force mpicxx to use clang, no?

**Comment by ye-luo** [comment]
> Ah, it must be some environment variable to force mpicxx to use clang, no?

Correct. MPI wrappers are configured with clang.

**Comment by correaa** [comment]
ok, since I can reproduce the problem with OFFLOAD=OFF, I am going to use that for now, for bisecting QMCPACK (instead of bisecting Multi).

**Comment by ye-luo** [comment]
> ok, since I can reproduce the problem with OFFLOAD=OFF, I am going to use that for now, for bisecting QMCPACK (instead of bisecting Multi).

If you don't need offload, you may use gcc as the host compiler.

**Comment by correaa** [comment]
Yes, exactly.

This time I bisected QMCPACK for fixed Multi: 
```
2ed906cc7a6b3d7c91f109ac7fd21552e1ba7a89 is the first bad commit
commit 2ed906cc7a6b3d7c91f109ac7fd21552e1ba7a89
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Mon Nov 13 12:05:14 2023 -0800

    take into account const source types

 src/AFQMC/Memory/device_pointers.hpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
