### PR TITLE
Add AFQMC ComplexIntegrals flag

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Addresses half of #2448 by adding Hamiltonian/ComplexIntegral dataset to AFQMC hamiltonian files.

## What type(s) of changes does this code introduce?

- Bugfix
- New feature
- Documentation content changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

macbook, python 3.7.7

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed. **Assuming afqmctools unit tests are enabled**
- Yes Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by fdmalone** [comment]
The tutorials don't contain input files. The user has to generate them from scratch. Error handling in QMCPACK will be handled separately.

**Comment by ye-luo** [comment]
I guess we can treat complex as default if this variable is not provided in the h5.

**Comment by prckent** [comment]
Querying the size of the data is simple and logical.
if the size is 2zeta => complex, 1zeta =>real, anything else = error, corrupt file.

**Comment by fdmalone** [comment]
As is this shouldn't break anything, as the flag isn't read yet in QMCPACK. I imagine a multi stage exception handling has to occur: 1) test in the first instance if the flag is present and test this against the ValueType, and then 2) except if the reading fails. If the flag isn't present we potentially have slightly less information to log.

**Comment by prckent** [comment]
Is there a reason for the hamil.h5 -> afqmc.h5 rename in the docs?

**Comment by fdmalone** [comment]
They were inconsistently named in the original PR (mismatch between h5dump and what I pasted in latex). I just made them consistent.

**Comment by fdmalone** [comment]
Give me a minute. Turns out the afqmctools unit tests are failing (for potentially unrelated reasons.)

**Comment by fdmalone** [comment]
Ok. They are failing on develop too. Unrelated to current PR, I'll fix on a separate PR.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
