### PR TITLE
Nexus: fix syntax warnings

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

More recent python versions now generate syntax warnings (de-linting).  Fix the few that exist so as not to scare off users.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Workstation

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
This will need a non-ORNL person to merge.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]

**Review by markdewing — APPROVED** [review]

**Pull request merged**
