### PR TITLE
Add batched EnergyDensityEstimator short statistical integration test

### PR DESCRIPTION
**Pull request by PDoakORNL**
This adds an application level short test for the batched EnergyDensityEstimator

However on my system the test fails because after 250 blocks the paticle moves start moving out of the period cell.  The legacy energy estimator doesn't check that the coordinate to cell mappings land in the grid, but I now bound check this access so the test fails.  Even if i don't I segfault eventually because overflow writes are occurring.

These out of bounds particles are pretty rare but it seems certain at least on my test system that they will occur in a run the size of the short run.

This seems to point to a likely bug in the particle moves. I will explore further tomorrow.

This PR though make it possible to run the EnergyDensityEstimator with the full app which was actually impossible without the fix to the virtual write function.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

dgx 2

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by prckent** [comment]
Good catch. In the QMC simulation the particles are allowed to move anywhere, so any code looking to handle periodic images needs to do so and handle the out of bound case appropriately. Unless the fix is trivial, I suggest to just fix the batched code.

**Comment by prckent** [comment]
Would you like this merged? It would at least start appearing in the nightlies.

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
