### PR TITLE
QE converter update

### PR DESCRIPTION
**Pull request by kgasperich**
## Proposed changes

Added a new patch for QE v6.7.0
Since the last supported version (6.4.1), QE has stopped using iotk for xml I/O.  Most of the changes in this PR are just replacing the iotk calls with equivalent functions from [FoX](http://homepages.see.leeds.ac.uk/~earawa/FoX/) (FoX is already used elsewhere in QE, so this doesn't introduce any new dependencies).

Replaced `ruotaijk` with `rotate_grid_point` (and added a call to `scale_sym_ops`).
See [https://gitlab.com/QEF/q-e/-/commit/6147076521a62437068100e6fa5a36898061a482](https://gitlab.com/QEF/q-e/-/commit/6147076521a62437068100e6fa5a36898061a482) for details.

## What type(s) of changes does this code introduce?

- Updated converter patch for compatibility with latest version of QE

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — CHANGES_REQUESTED** [review]
Thanks for the patch. Needs a bit change of process.
Why do we need the file
external_codes/quantum_espresso/pw2qmcpack.f90?

**Comment by kgasperich** [comment]
> Why do we need the file
> external_codes/quantum_espresso/pw2qmcpack.f90?
I was just keeping this around until everything else is verified to be working (at some point it was easier to work with it directly instead of generating it by applying the patch, but we can remove it).

**Comment by prckent** [comment]
Thanks Kevin. I am currently rebuilding the software stack on the machine I normally do testing of QE on. When completed I'll do a test build of QE 6.7.0 with this patch and run the workflow tests.

**Comment by ye-luo** [comment]
@kgasperich could you rebuild a new PR
I updated the code with CMake connected to pw2qmcpack and made a release.
https://github.com/ye-luo/q-e/releases/tag/v6.7.0%2Bpw2qmcpack
Please mention the CMake way in `download_and_patch_qe6.7.0.sh` as the release note.

**Comment by prckent** [comment]
Reopening so I have something to work with for the next hour.

**Comment by prckent** [comment]
Successfully tested this PR. The workflow tests are still running, but so far all have passed.

If we are going to encourage use of the cmake configure method for QE, I'll work on using it in the nightlies. Will translate "    ./configure CC=mpicc MPIF90=mpif90 F77=mpif90 BLAS_LIBS=-lopenblas LAPACK_LIBS=-lopenblas  --with-scalapack=no --with-hdf5=`spack location -i hdf5@1.12.0`" to cmakespeak.

**Comment by prckent** [comment]
Spoke too soon:
```
The following tests FAILED:
        203 - qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16 (Failed)
        204 - qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-kinetic (Failed)
        205 - qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-samples (Failed)
        206 - qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-localecp (Failed)
        229 - qe-LiH-unpolarized-no-collect-np-16-12-12-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16 (Failed)
        230 - qe-LiH-unpolarized-no-collect-np-16-12-12-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-kinetic (Failed)
        231 - qe-LiH-unpolarized-no-collect-np-16-12-12-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-samples (Failed)
        232 - qe-LiH-unpolarized-no-collect-np-16-12-12-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-localecp (Failed)
        237 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16 (Failed)
        238 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-kinetic (Failed)
        239 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-samples (Failed)
        240 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-localecp (Failed)
        242 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16 (Failed)
        243 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-kinetic (Failed)
        244 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-samples (Failed)
        245 - qe-LiH-polarized-np-16-12-6-nk-16-4-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-localecp (Failed)
        250 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16 (Failed)
        251 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-kinetic (Failed)
        252 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-samples (Failed)
        253 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-localecp (Failed)
        255 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16 (Failed)
        256 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-kinetic (Failed)
        257 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-samples (Failed)
        258 - qe-LiH-polarized-no-collect-np-16-12-12-nk-16-3-3-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16-localecp (Failed)
```
Errors are of the following flavor. Note that I did not reverify with QE v6.4.1, so there is a chance this is issue on my system.
```
203: Maxmimum number of Gvecs 14749
203:   Using meshsize=                68                64                64
203:   vs input meshsize=                68                64                64
203: MEMORY 9 MB allocated for the coefficients in 3D spline orbital representation
203: Start transforming plane waves to 3D B-Splines.
203: Fatal Error. Aborting at SplineSetReader Failed to read band(s) from h5!
203:
203: --------------------------------------------------------------------------
203: MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
203: with errorcode 1.
203:
203: NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
203: You may or may not see output from other processes, depending on
203: exactly when Open MPI kills them.
203: --------------------------------------------------------------------------
38/91 Test #203: qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-x-vmc_hf_noj-1-16 ............................***Failed    1.20 sec
```

**Comment by ye-luo** [comment]
Yes. the same there https://github.com/ye-luo/q-e/pull/1

**Pull request closed without merging**
