### PR TITLE
Bump to llvm 18 in sulfur CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Bump from LLVM 16 to 18 in sulfur CI for CUDA+AFQMC+Offload configurations

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
sulfur, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]
Thanks. Lets hope this combination proves reliable.

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
ldd a good idea

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Update: the LLVM 18 got picked up correctly but converter tests are failing not actually qmcpack runs. Trying to reproduce it locally. It can be an issue caused by LLVM 18 around the libffi handling.

**Comment by williamfgc** [comment]
Test this please after installing `libffi-devel`

**Comment by ye-luo** [comment]
The remaining seems to be a test tolerance issue.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Here is the summary of what I found, since LLVM 18. libffi is optional as long as not using offload host. When libffi is not found when the offload-to-host plugin is loaded, a warning is issued and triggered converter test script to fail at https://github.com/QMCPACK/qmcpack/blob/1af5bfa699bca034f4b8b6ee90772ec958f5ba65/tests/converter/converter_test.py#L94. Since it is not the first occurrence, I will propose a change to the behavior of our script.

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
