### PR TITLE
Clean up utils directory

### PR DESCRIPTION
**Pull request by jtkrogel**
Remove old utility scripts that are no longer in use.

Addresses #962.

### CODE REVIEW

**Comment by ye-luo** [comment]
Just realized that utils/ConfigureScripts.pl is still needed.

**Comment by jtkrogel** [comment]
Restored.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Since the CI will not be back until Thur, I will not approve at the moment and let people figure out if there is anything in two days.

**Pull request merged**
