### PR TITLE
Add pw2qmcpack patch for QE 6.3

### PR DESCRIPTION
**Pull request by ye-luo**
The 5.3 patch is kept since the 6.2.1 patch has not been released in the past.
Compared to 6.2.1 patch, 6.3 patch adds the atomicnumber tag in the ion section of ptcl.xml file generated by pw2qmcpack to avoid NLPP satinity check failure.
Currently pw2qmcpack doesn't provide the input blocks for QMCPACK and hopefully this will be added in the near future.

### CODE REVIEW

**Comment by ye-luo** [comment]
@prckent I added a line of printout `Example configure: ./configure --with-hdf5=path_to_hdf5_include_and_lib`
Currently pw2qmcpack fails at runtime if HDF5 flags are not set, we can actually throw error at compile time and point users to read the full instruction in the manual. Does this solution sounds better?

**Comment by prckent** [comment]
We should throw an error at compile time - it is very frustrating to have pw2qmcpack build but then fail to operate. This could be addressed in a later PR but is a nice feature to include in v3.5.0. What do you think?

**Comment by ye-luo** [comment]
Now an error is given at compilation
`HDF5 flag neither enabled during configure nor added manually in make.inc`

**Comment by prckent** [comment]
We should check this e.g. on oxygen before the release, but since it can't break  current implementations I am happy to merge.

**Pull request merged**
