### PR TITLE
Set offload mandatory in ctest

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
OpenMP may offload to CPU when GPUs are not available. Set `OMP_TARGET_OFFLOAD=mandatory` to stop false positive test results.

## What type(s) of changes does this code introduce?
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora
## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
If one of the cdash reports has this error, can you please link it?

**Comment by ye-luo** [comment]
https://cdash.qmcpack.org/CDash/testDetails.php?test=22249675&build=356125
Is not the actual failure but the failure running on host.
https://cdash.qmcpack.org/CDash/testDetails.php?test=22300641&build=356125
is the expected behavior.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Pull request merged**
