### PR TITLE
Fix walker initialization in batched drivers when the request number is smaller than the carry-over

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
When the number of requested walkers is higher than the number of walkers from the previous section,
the remaining walkers are initialized as the gold copy which has a walker configuration from before any QMC section runs, namely far from equilibrium. It is much better to initialize them by repeating the walker configurations of previous QMC section.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — DISMISSED** [review]
Agreed.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> Aside: we could consider adding an input flag for whether to renormalize the population to the target population at the start of a section. Could make the logic in different scenarios easier for the user and for us.

Please wait for my next PR and after that. We can decide what behavior to choose.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
>Please wait for my next PR and after that. We can decide what behavior to choose.
Will do.
There is also #4483

**Pull request merged**
