### PR TITLE
Add deterministic test for 1rdm estimator

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

This PR is to add deterministic tests for 1rdm estimator on 1x1x1 diamond. VMC/DMC with single threaded and DMC with multiple MPI/threads tests are added. 
References were generated in intel Xeon workstation and tests were passed on both real/complex build.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
gcc 8.3.0+MKL is not working for me (real, full precision). Slightly larger tolerances are likely needed. Intel variants appear to be working.

**Comment by Hyeondeok-Shin** [comment]
I checked logs for failed CI and it seems not only for J2 and random. Tolerances for all 1rdm have increased for gcc.

**Review by prckent — APPROVED** [review]
Confirmed OK with gcc10+MKL.

**Pull request merged**
