### PR TITLE
Make sure converter leaks are marked as failures with ASAN/LSAN

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Currently `converter-*` tests leak memory, but they are not marked as failures by `ctest` when running with asan/lsan sanitizers
Needed for implementing asan/lsan on deterministic tests
Similar to #3202
Related to #3312
Fixes to follow

## What type(s) of changes does this code introduce?

- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
Ubuntu 20.04, should pass CI as leaks are not checked

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — DISMISSED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Please take a look at the GitHub Actions self-hosted CI failure. I cancelled ALCF ones to expedite other PRs.

**Comment by williamfgc** [comment]
Thanks @ye-luo , let's see what's going on. It seems those tests have been failing.

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
