### PR TITLE
Fix allp move with MP. No need for recomputePsi.

### PR DESCRIPTION
**Pull request by ye-luo**
Address the nightly test failure.

### CODE REVIEW

**Comment by prckent** [comment]
For future reference, what is the sensitivity to mixed-precision here? What should we be on the lookout for? Why is the call to recomputePsi() dangerous? Would it not be better long term to fix this function instead?

**Comment by ye-luo** [comment]
In all electron move, every proposed move only calls evaluateLog which compute WF from scratch and doesn't need the walker buffer (size 0 as print out). recomputePsi recomputes SD inversion by checking out the buffer, redoing inversion and updating the buffer. So there is a segfault.

To me, fixing this function seem hiding developer mistakes to me. Better to have a crash and identify the real problem.

**Comment by prckent** [comment]
So recomputePsi should check is the buffer is allocated, or simply abort. Presumably other functions have the same problem.

I think the higher level problem here is that the contract / responsibilities between the driver and walker classes is not clear. Agree?

**Comment by ye-luo** [comment]
I agree. I guess at the beginning, QMCPACK didn't have so many variants in methods and didn't define the responsibilities so clear.

When I added recomputePsi, having it working as I need is the first priority. I was even not very happy to add recomputePsi because I had thought I only need to add WF routines instead of driver routines.
As we keep cleaning up the code on the ANL branch, we changed the way to handle recompute because recomputePsi has too much overhead. It has been deprecated.

**Comment by prckent** [comment]
I'll merge this pragmatically: this is by far the fastest way to get the allp driver working. The proviso is that we we need to fix the logic / contract between the drivers and walker classes.

**Pull request merged**
