### PR TITLE
Update Summit build recipe

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
For SummitPlus

## What type(s) of changes does this code introduce?
- Documentation or build script changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Summit

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
```
The following tests FAILED:
         10 - deterministic-unit_test_message_mpi (Failed)
         30 - deterministic-unit_test_wavefunction_trialwf (Failed)
         31 - deterministic-unit_test_wavefunction_sposet (Failed)
         39 - deterministic-unit_test_estimators (Failed)
         40 - deterministic-unit_test_estimators_mpi (Failed)
         45 - deterministic-unit_test_new_drivers_mpi-r3 (Failed)
         46 - deterministic-unit_test_new_drivers_mpi-r4 (Failed)
         47 - deterministic-unit_test_new_drivers_mpi-r16 (Failed)
         97 - deterministic-restart-8-2 (Failed)
         98 - deterministic-restart-8-2-restart (Failed)
        103 - deterministic-restart_batch-8-2 (Failed)
        104 - deterministic-restart_batch-8-2-restart (Failed)
        106 - deterministic-restart_batch-8-2-exists-qmc_short_batch.s000.config.h5 (Failed)
        107 - deterministic-restart_batch-8-2-exists-qmc_short_batch.s000.random.h5 (Failed)
        113 - deterministic-restart_dmc-8-2 (Failed)
        114 - deterministic-restart_dmc-8-2-restart (Failed)
        119 - deterministic-restart_dmc_disable_branching-8-2 (Failed)
        120 - deterministic-restart_dmc_disable_branching-8-2-restart (Failed)
        125 - deterministic-save_spline_coefs-8-2 (Failed)
        126 - deterministic-save_spline_coefs-8-2-restart (Failed)
        127 - deterministic-save_spline_coefs-8-2-check (Failed)
        598 - deterministic-ensemble_blocks_LiH_ae-vmc_msdj-4-1 (Failed)
        600 - deterministic-ensemble_blocks_LiH_ae-vmc_msdj-5-1 (Failed)
        601 - deterministic-LiH_ae_msdj_legacy-vmc-estimator-sh_coeff-4-4 (Failed)
        602 - deterministic-LiH_ae_msdj_legacy-vmc-estimator-sh_coeff-4-4-check (Failed)
        603 - deterministic-LiH_ae_msdj_batched-vmc-estimator-sh_coeff-4-4 (Failed)
        604 - deterministic-LiH_ae_msdj_batched-vmc-estimator-sh_coeff-4-4-check (Failed)
        784 - deterministic-ensemble_blocks_LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-4-1 (Failed)
        786 - deterministic-ensemble_blocks_LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-5-1 (Failed)
```
MPI (np>=3) test failure are caused by my settings. np=2 cases are all good.
all the failure in wavefunction unit tests are small numerical issues. No alarm.
estimator test failure are known https://github.com/QMCPACK/qmcpack/issues/4857

**Comment by prckent** [comment]
For future reference, noting the deterministic-unit_test_estimators bus error on macos CI, similar to #4287 . Lets keep an eye on it.

**Comment by prckent** [comment]
The test failures are similar to what I got with the updated build script and development LLVM earlier this month. Mostly issues with test configuration and jsrun. Given the uniqueness of these problems to Summit and Summit's current status, I don't think it makes sense to spend time on those.

**Pull request merged**
