### PR TITLE
Nexus: add test for analysis of QE NSCF data

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Add a test for analysis of band structure data from QE.

## What type(s) of changes does this code introduce?

- Other (please describe): a new test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by jtkrogel** [comment]
Anyone able to review this?

**Comment by prckent** [comment]
I have updated the branch, which will trigger the CI.

**Comment by prckent** [comment]
Is this OK with QE6.4.1? I noticed that the nscf reference output is with QE 6.3.

**Comment by jtkrogel** [comment]
It should be fine, though I have not made an explicit update for 6.4.1.  Occasionally, the tests should be updated, but any deficiencies would be in a gradual loss functionality (output parsing), but no stability penalty will be incurred to Nexus in the presence of divergence.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
