### PR TITLE
Add mw_ WithSpin APIs to SlaterDet

### PR DESCRIPTION
**Pull request by camelto2**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

While I was profiling some runs on spinor calcualtions, I noticed that a few spinor calculations were going through single walker APIs where I expected they would use mw_. Turns out I forgot to add mw_ WithSpin APIs to both SlaterDet as well as DiracDeterminant so everuthing was always falling back to single walker. They were only added to DiracDeterminantBatched, which isn't being used in CPU builds since I am not building with ENABLE_OFFLOAD. 

This PR adds the appropriate APIs to SlaterDet first. Will add something to DiracDeterminant in the future, but falling back to the single walker should be fine for now. 

Additionally, when I was looking at unit tests, I noticed there isn't actually a unit test specfically for SlaterDet, or at least I didn't find anything.  I made a simple unit test to make sure that the mw_ APIs get used correctly by creating some dummy DiracDeterminants for testing. Before adding the new mw_ WithSpin APIs this test appropriately fails. After adding the WithSpin APIs, it passes. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
m1 mac

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by camelto2** [comment]
some tests were failing because I moved an implementation from the .h to the .cpp and forgot to remove the override keyword. Fixed now

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by camelto2** [comment]
Failing test for CUDA offload builds were using MatrixDelayedUpdateCUDA, which has a throw because mw_evalGradWithSpin has not been implemented yet. These were only added to MatrixDelayedUpdateOMPTarget. I added an ifdef guard on the failing test to not run that one if we have ENABLE_CUDA. 

Need to remove once MatrixDelayedUpdateCUDA is updated.

**Comment by ye-luo** [comment]
Could you add a github issue documenting the TODO?

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
