### PR TITLE
Nexus: Handle pickle protocols between python versions

### PR DESCRIPTION
**Pull request by kayahans**
## Proposed changes

Handles the pickle (https://docs.python.org/3/library/pickle.html) protocol differences that can arise due to using different python versions, (such as using multiple computers having different python versions, but sharing the same filesystem). In the current code, if python 3.8 is used to generate pickle (.p) files, nexus uses protocol 5. If python 3.7 is used to rerun the same script, protocol 5 is not accessible in that python version (https://docs.python.org/3/library/pickle.html#data-stream-format)

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Andes, Summit

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
Please add exception handling on the pickle5 import and print a message about why it is needed if the import fails.

The mixed python situation is fairly common. e.g. Old system python, user installed recent python.

**Comment by prckent** [comment]
While tweaking this code, add some error handling on the open call? Or is the file always guaranteed to be there and readable at this point?

**Comment by kayahans** [comment]
Import error exception is added, please check. File is always guaranteed to be there and readable per nexus workflows.

**Review by prckent — APPROVED** [review]
LGTM

I tweaked the message since there are many ways to install python modules and pip might not be the relevant one.

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
