### PR TITLE
[WIP] Retry Codecov upload CI step

### LINKED ISSUE #4346: CI coverage run fails quite frequently
**Describe the bug**
The CI coverage run fails quite frequently due to failure at uploading the coverage report.
https://github.com/QMCPACK/qmcpack/actions/runs/3584668210/jobs/6031638171
The error was
```
2022-11-30T16:30:04.284Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
```
Can we make the upload stage try multiple times if not successful.

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Uses retry-action
Tries 5 times with 1 minute delays until step fails
Fixes #4346 

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must work with GitHub Actions runners

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Let's see if this works first

**Comment by ye-luo** [comment]
We saw coverage failure again yesterday https://github.com/QMCPACK/qmcpack/runs/10521263590

**Comment by ye-luo** [comment]
Another failure https://github.com/QMCPACK/qmcpack/actions/runs/3968480354/jobs/6801699286
@williamfgc any progress?

**Comment by williamfgc** [comment]
@ye-luo this option is a dead end, we can close this PR. What I can try is repeating the step manually in the GitHub Actions pipeline configuration. It might not help if codecov is down and it's been [spotty](https://status.codecov.com/).

**Pull request closed without merging**
