### PR TITLE
Nexus: Display memory of child processes

### PR DESCRIPTION
**Pull request by markdewing**
Currently the polling output only shows the memory of the python process running Nexus.  Show the sum of the memory used by that process and all of its child processes.

### CODE REVIEW

**Comment by prckent** [comment]
Will wait for Jaron's review before approving.

**Comment by jtkrogel** [comment]
This looks fine.  The original code was pulled from somewhere online, I'm not sure where I found it first.  I have found the original source and this is probably a good time to note it.  Please add this to memory.py prior to commit:

########################################################################
# The following is adapted from
#   http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/286222
# Python Cookbook, by Jean Brouwers
########################################################################

Do we need to add more?  This piece of code is distributed through the PSF license:
https://en.wikipedia.org/wiki/Python_Software_Foundation_License
https://docs.python.org/2/license.html

**Comment by jtkrogel** [comment]
OK, that rendered poorly.  I meant:

`########################################################################`
`# The following is adapted from`
`#   http://aspn.activestate.com/ASPN/Cookbook/Python/Recipe/286222`
`# Python Cookbook, by Jean Brouwers`
`########################################################################`

**Comment by markdewing** [comment]
Don't commit this yet, I've messed up the history while trying to clean it up.

**Comment by markdewing** [comment]
I can't seem to fix this branch the way I want.  I'm going to close the PR and open another one on a different, cleaner branch.

**Pull request closed without merging**
