### PR TITLE
Extract run_qmc to separate module

### PR DESCRIPTION
**Pull request by markdewing**
Generalize the run_qmc function to an arbitrary number of electrons and extract it to a separate module.
Future validation code will use different wavefunctions and we want to reuse the run_qmc function.

The implementation of psi in the wavefunction needs to be split into two parts.  For generality, calling from run_qmc uses an array for all the electron positions.  Autograd is easier to use if each position is a separate argument.  The solution is to make psi a wrapper that extracts individual positions and calls the internal implementation.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- N/A. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Aside: if you did Gaussian distributed moves to compute delta/the new trial position, run_qmc would be doing conventional VMC.

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Pull request merged**
