### PR TITLE
Fix incorrect handling of orthogonalisation matrix when lindep present.

### PR DESCRIPTION
**Pull request by fdmalone**
X should be a list of numpy arrays of dimension [M,NMO_PK[K]]. Previously nmo_pk wasn't accounted for when generating orbital products.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by fdmalone** [comment]
Looks like a DMC test is failing?

**Comment by ye-luo** [comment]
The CUDA code has memory bugs triggering random failures. I will trigger another CI run.

**Comment by ye-luo** [comment]
Test this please.

**Comment by prckent** [comment]
@ye-luo Any ideas about the memory problems with the CUDA build?

**Comment by ye-luo** [comment]
It was showing up in the PBC coulomb term. I feel this is related to restart tests failure with CUDA as well. The localECP term share pieces with PBC coulomb.
https://cdash.qmcpack.org/CDash/testDetails.php?test=6628596&build=89232

**Pull request merged**
