### PR TITLE
Fuse J2OrbitalSoA and J2OMPTarget as TwoBodyJastrow

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
When offload was first introduce in J2, I copied J2OrbitalSoA as J2OMPTarget.
When I did J1, I found it better to just implement offload inside J1 rather than creating a new class by copying.
In this PR, I basically removed J2OrbitalSoA and renamed J2OMPTarget to TwoBodyJastrow.

I also rename two legacy CUDA classes by adding CUDA in the file names.
OneBodyJastrowOrbitalBspline -> OneBodyJastrowCUDA
TwoBodyJastrowOrbitalBspline -> TwoBodyJastrowCUDA

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thanks Ye. Happy to merge once the sanitizer check passes.

This is a consistent simplification to J1 and an improvement in the naming. It also saves ~900 lines.

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@prckent all the CI issues have been addressed.

**Review by prckent — APPROVED** [review]

**Pull request merged**
