### PR TITLE
Refine cmake dependence

### PR DESCRIPTION
**Pull request by ye-luo**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

In modern CMake, dependency between targets are critical. This PR reorganize the dependency of QMCPACK internal targets.
```
MISC -v
  qmcutils -> qmcbase -> qmcwfc -> qmcham -> qmcdrivers -> qmc -> qmcpack.
                einspline -> ^    formic_utils-> ^          afqmc -> ^
                                                qmcutils -> ^
```
MISC is a temporary solution, will be reduced to nothing after further cleaning.
It is still not perfect and will need to rearrange source files in the future.

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?
My workstation w/ w/o MPI and CUDA
## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Noticed that QMCDriverFactory.h/cpp should be moved from QMCApp folder to QMCDrivers.
The current layout caused extra dependency of qmc on qmcdriver target.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Put this PR on hold. Found the root cause of the CUDA issue. FindCUDA probably has bugs and need to workaround it.

**Comment by grahamlopez** [comment]
> Found the root cause of the CUDA issue. FindCUDA probably has bugs and need to workaround it.

This might be a good cause to investigate significantly upping our cmake version requirement. CUDA support specifically was substantially approved sometime in the cmake version 3.13 / 3.14 timeframe.

**Comment by ye-luo** [comment]
Our CI is using 3.15. FindCUDA is deprecated. We need to investigate CUDA as a language.

**Comment by grahamlopez** [comment]
> FindCUDA is deprecated. We need to investigate CUDA as a language.

I Agree. This is where the improvements have come.

**Comment by PDoakORNL** [comment]
I haven’t tried CUDA as language for six months or so. It’s time for someone to try again, but I think that will be easier with the other moderninzation

**Comment by grahamlopez** [comment]
> I think that will be easier with the other moderninzation

Agreed.

**Comment by prckent** [comment]
Based on the conversation above, I marked this as [Hold]

**Comment by ye-luo** [comment]
@prckent It is ready for another review now

**Pull request merged**
