### PR TITLE
Add batched VMC/DMC deterministic tests for a multiple number of walkers & MPI ranks & threads

### LINKED ISSUE #2889: batched VMC/DMC determinstic tests
det_qmc_short_vmcbatch.in.xml
current configuration.
1 walker but with VMC no drift only.
Desired configuration
1 walker, VMC no dirft, VMC with drift and then DMC, in total 3 sections.

qmc_short_vmcbatch_dmcbatch.in.xml
det_qmc_short_sdbatch_vmcbatch_mwalkers.in.xml
current configuration.
2 walkers with 2 sections of VMC no drift.
Desired configuration
16 total walkers with VMC no dirft, VMC with drift and then DMC, in total 3 sections.
Needs these run cases, MPI ranks - threads
2 - 2
2 - 3 // uneven walker distribution in crowds.
1 - 4
1 - 16

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

Close #2889 

Add deterministic test for batched VMC/DMC for a multiple number of walkers & MPI ranks & threads.
Tests use 16 total walkers with 1-4, 1-16, 2-2, 2-3 MPI ranks & threads.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon, intel19 compiler

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — COMMENTED** [review]
Hyeondeok - I don't believe that we have any statistical tests for the batched code run in these configurations. Did you happen to check that the results are OK vs e.g. the 1 mpi - 16 thread ones? I think that this is worth doing before we bake in these deterministic tests.

**Comment by Hyeondeok-Shin** [comment]
Statistical tests are performed with the inputs long-diamondC_2x1x1_pp-vmc_sdj-1-16 and long-diamondC_2x1x1_pp-dmc_sdj-1-16.

1. long-diamondC_2x1x1_pp-vmc_sdj-1-16

Local energy 
- batched : -21.66806356 +- 0.00023425
- legacy    : -21.66829300 +- 0.00023000

2. long-diamondC_2x1x1_pp-dmc_sdj-1-16

Local energy
 - batched : -21.84977045 +- 0.00380067
 - legacy   : -21.84497500 +- 0.00287900

These batched long statistical tests are all passed in ctest with the references from the legacy.  I can add this statistical tests after this PR.

**Comment by prckent** [comment]
@Hyeondeok-Shin I suggest to add just the "awkward" 2 mpi and 3 threads statistical tests next. We can't cover too many possibilities in the statistical tests because of the overall time that they take to run.

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Please wait my review.

**Review by ye-luo — APPROVED** [review]
My request of changes are addressed.

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
