### PR TITLE
GPU Complex Implementation

### PR DESCRIPTION
**Pull request by atillack**
Integrated GPU complex code in current branch and added necessary changes to build script so that -DQMC_COMPLEX=1 can be used in conjunction with -DQMC_CUDA=1 to compile the complex GPU version.

The code passes ctest -R short for mixed precision complex GPU code. Non-mixed precision complex currently fails and is next on the list. As a sanity check, the code passes ctest -R short for CPU complex, real float/double and double/double GPU. All test were performed on Rhea with GCC5.3 and CUDA 8.0.44.

### CODE REVIEW

**Comment by prckent** [comment]
Manually running tests on oxygen with Intel 2015+CUDA+Complex

**Comment by ye-luo** [comment]
@atillack Please briefly listing all the changes made through this change.

**Comment by atillack** [comment]
@ye-luo Sure, here is a short synopsis, if needed Ying Wai can probably compile a longer list next week:
- this commit merges Ying Wai's SVN complex GPU branch to the current development branch
- the general approach was to write new CUDA kernel calling functions for the now std::complex arguments (in PhaseFactors.cu, determinant_update.cu, PhaseFactors.cu, BsplineJastrowCuda.cu, BsplineJastrowCudaPBC.cu, etc...) and either adjust the existing CUDA kernels (in case all arguments are std::complex) or write new ones with mixed arguments (e.g. when positions were used in conjunction with complex wavefunctions)
- typically, to make rewriting (and rereading) easier the thrust::complex extensions to CUDA were used were feasible
- Some of the Hamiltonian code had to be touched in order to merge fixes from the CPU complex implementation (e.g. ConservedEnergy.h for flux) and fix the NonlocalECP calculations (along with EinsplineSetCuda.cpp and PhaseFactors.cu).
- Also, along with the NonlocalECP fix I was able to undo the changes to the einspline code that were needed in earlier development versions
- In this version, I changed all HACK_COMPLEX compiler directives to QMC_COMPLEX directives and incorporated some of the little (logical) fixes for data types that we had in the development version that also apply to the regular GPU code (e.g. CudaGradType) - they are necessary for the complex code since CudaGradType will be complex and not just CUDA_PRECISION.

**Comment by prckent** [comment]
Background info: HACK_COMPLEX #defines were originally added by me to mark (approx) all locations where the code would need updating for complex and to get it to compile.

**Comment by markdewing** [comment]
Small formatting point: A number of lines have trailing whitespace.  Could you remove it?  
Unfortunately, this doesn't show up in the online diff display (though that may be a settings option).

**Comment by ye-luo** [comment]
@atillack your short synopsis is enough for the moment.
@markdewing Can we do it right before the merge? There are still big changes on the way.

**Comment by markdewing** [comment]
Yes, the trailing whitespace removal can be done later.

**Comment by prckent** [comment]
Tests using Intel2015+Complex+CUDA on oxygen pass (I will ignore the 1 flux failure):

99% tests passed, 1 tests failed out of 196

Label Time Summary:
Link h5                     =   0.09 sec (14 tests)
QMCPACK                     = 7282.29 sec (28 tests)
QMCPACK-checking-results    =   8.40 sec (115 tests)
Quantum ESPRESSO            = 281.17 sec (20 tests)
unit                        =  25.50 sec (11 tests)

Total Test time (real) = 7598.76 sec

The following tests FAILED:
        193 - qe-atomO-polarized-no-collect-np-16-0-16-nk-1-0-1-atomO_pp-vmc_sdj-1-16-flux (Failed)

**Comment by prckent** [comment]
The complex CUDA code generates many new warnings. @atillack These need to be resolved. They all appear related:

Affected files are
qmcpack/src/QMCWaveFunctions/PhaseFactors.cu
qmcpack/src/QMCWaveFunctions/Fermion/determinant_update.cu

Warnings repeated for every instantiation BS size:

/home/pk7/projects/qmc/git_QMCPACK_andreas/qmcpack/src/QMCWaveFunctions/PhaseFactors.cu(792): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)
          detected during instantiation of "void phase_factor_kernel<T,T2,BS>(T *, T *, T2 **, T2 **, int) [with T=float, T2=thrust::complex<float>, BS=32]"
(951): here


/home/pk7/projects/qmc/git_QMCPACK_andreas/qmcpack/src/QMCWaveFunctions/PhaseFactors.cu(792): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)
          detected during instantiation of "void phase_factor_kernel<T,T2,BS>(T *, T *, T2 **, T2 **, int) [with T=double, T2=thrust::complex<double>, BS=32]"
 

/home/pk7/projects/qmc/git_QMCPACK_andreas/qmcpack/src/QMCWaveFunctions/Fermion/determinant_update.cu(230): warning: __shared__ memory variable with non-empty constructor or destructor (potential race between threads)
          detected during:
            instantiation of "void update_inverse_core1<T,BS>(const T *, const T *, const T *, T *, T *, int, int, int) [with T=thrust::complex<float>, BS=128]"
(431): here
            instantiation of "void update_inverse_kernel1<T,BS>(T **, int *, int, int, int, int, int, int, int) [with T=thrust::complex<float>, BS=128]"

**Comment by atillack** [comment]
@prckent Those warnings are to be taken seriously and we have: The solution is to have __syncthread() calls after the shared memory initialization (or at least after the first value gets assigned). Annoyingly, even after fixing the actual issues the compiler warns about, the compiler still issues those warnings.

A fix that the compiler won't cry about would be to get rid of *all* shared thrust::complex variables by either turning them to regular ones which would involve rewriting the kernels or by going away from thrust::complex completely. This could be achieved by either going to cuComplex (needs a rewrite of the kernel and is not particularly readable code) or the model that einspline uses which is to treat a complex<float/double> array as a float/double array and to take care of real and imaginary parts separately in the kernels (even bigger kernel rewrite and kernel reusability as well as readability will suffer).

I didn't want to implement a "cheating" solution, which is to silence the warnings by piping them to /dev/null (which is where they technically belong, but I believe in freedom of speech - even for compilers).

**Comment by atillack** [comment]
@markdewing The trailing whitespace should probably be a separate pull request - just for fun I went over the entire code with:

find . -type f -name '*.cpp' -exec sed --in-place 's/[[:blank:]]*$//' {} \+
find . -type f -name '*.cu' -exec sed --in-place 's/[[:blank:]]*$//' {} \+
find . -type f -name '*.hpp' -exec sed --in-place 's/[[:blank:]]*$//' {} \+
find . -type f -name '*.h' -exec sed --in-place 's/[[:blank:]]*$//' {} \+
find . -type f -name '*.txt' -exec sed --in-place 's/[[:blank:]]*$//' {} \+

This reliably removes the trailing whitespaces (and leaves comments untouched) but this will also change 1,600 files ...

**Comment by prckent** [comment]
@atillack , @markdewing We are going to clang-format the source within a few months, so don't worry

**Comment by prckent** [comment]
@atillack Check with Jeff Larkin. If nvcc is being over zealous it is a bug for NVIDIA to fix in their tools. Perhaps there is a subtlety the compiler knows about.

**Comment by atillack** [comment]
@prckent Good point, I will.

**Comment by jefflarkin** [comment]
@atillack Let's look this over together next week. Just drop by my office and we'll project it up on the wall.

**Comment by atillack** [comment]
@jefflarkin Sounds good! I'll provide the coffee ;-)

**Comment by markdewing** [comment]
About the whitespace - I meant that the lines being added or changed in this PR should have the trailing whitespace removed.   The general problem of cleaning the entire codebase is for another time. I generally dislike large-scale formatting changes (One exception,  we might be moving to using clang-format to apply a consistent formatting, which would be the right time to get the whitespace fixed as well, if clang-format doesn't already do that)

**Comment by grahamlopez** [comment]
Yep. Clang format will take care of trailing whitespace.

________________________________

**Comment by ye-luo** [comment]
1, Tests are not covering all the code changes. I will manually run extra tests next week. It will probably take me a few days next week.
2, I saw quite a few places to reduce the code changes (no need to largely duplicated the code).
3, I run the benchmarks with K80 and the performance looks reasonable, thumb up.
4, However, I spot the memory used by the splines  is doubled. In a supercell calculation, the spline is already in complex. So it should stay the same. So I need to read the handling of splines.
5, I need to read the phase factor and Slater update routines currently showing warnings.
6, The recomputing of matrix inversion seems good.

**Comment by ye-luo** [comment]
Corrected my self. The memory was correct. Ye

**Comment by ye-luo** [comment]
1) done. Jastrow optimization is recovered for both real and complex.
2) done. Minimized code base.
4) phase factor is optimized, gain 5% speed whole run. Removed the shared memory use. Therefore the warning is gone. As Andrea pointed out, thrust::complex in shared memory is the problem.
5) fixed the non-mixed precision implementation. Memory handling and inversion are fixed.

In addition,
a) determinant_update remain untouched. Needs to solve the thrust issue. Otherwise only safe to run 32 threads per block. Have performance impact on the determinant update. I saw syncthreads after declaring shared thrust::complex but didn't believe they solved the problem. Needs cleanup. @atillack @jefflarkin perhaps have better solution after investigation.
b) The handling of psi_ratios/psi_ratios_real is not my taste. Currently the drives/nonlocalecp  are polluted for that reason, I prefer to have always realtype at the driver level, but handle the complex to real inside TrialWavefunction_CUDA.

**Comment by prckent** [comment]
All tests (Intel2015+Complex+CUDA) still pass with Ye's revised commit.

**Comment by atillack** [comment]
Fixed determinant_update.cu compile warnings after talking with Jeff Larkin.

- The fix is to use the bulk::unitialized_array<> class included with Thrust for shared Thrust::complex variables.
- In order to still have a performant implementation I also linearized 2D and 3D shared arrays.

I will go over PhaseFactors.cu tomorrow.

**Comment by ye-luo** [comment]
I cleaned up a bit the unused code in PhaseFactors.cu. All the shared thrust::complex were removed in earlier commit.

**Comment by ye-luo** [comment]
1, I have not reviewed the determinant_update yet. In a quick scan, I saw things I don't understand and I will use the comment feature to ask questions individually.
2, psi_ratios/psi_ratios_real can be resolved quickly.
3, Passing the test can only be the lowest requirement. The segfault I fixed last night didn't show up in the tests. I'm running a NiO calculation to see if the energy agrees.

**Comment by atillack** [comment]
@ye-luo: Absolutely agreed. I am doing some more testing (and potential cleanup) here as well.

**Comment by atillack** [comment]
@ye-luo: Just a short heads up on the DMC fix - this error was not introduced with this pull request but came from the main branch.

**Comment by ye-luo** [comment]
@atillack No. The main branch is correct.
The main branch code recycles R_host for Grad. No need an extra resize.
In the new code, Grad_host is introduced because Grad needs to be in complex. So a resize is missing.

**Comment by atillack** [comment]
@ye-luo: You're right. Mea culpa.

**Comment by prckent** [comment]
Tests pass well-enough:
1 flux failure in complex, by 4 sigma.
1 flux failure and a non-local ecp failure in the real code, 5.97 sigma and 3.2 sigma respectively.
I am assuming that these failures are stochastic; they appear consistent with what we occasionally see from the CPU implementation.

**Comment by atillack** [comment]
@prckent I also get the occasional flux failure (but nothing worse) that is not reproducible when I rerun the failed test with a different random number seed. As far as I can tell, this is indeed stochastic.

**Comment by ye-luo** [comment]
1, I did long VMC checks,
cplx  NiO-fcc-S8-vmc  -2966.748515 +/- 0.001434   101.388878 +/- 0.095791   0.0342    
real  NiO-fcc-S8-vmc  -2966.746719 +/- 0.001538   101.423127 +/- 0.088639   0.0342    
cplx  NiO-fcc-S8-vmc  -2966.745499 +/- 0.001528   101.200342 +/- 0.074841   0.0341    
real  NiO-fcc-S8-vmc  -2966.746421 +/- 0.001459   101.303803 +/- 0.067295   0.0341  
2, psi_ratios/psi_ratios_real low priority. Leave it in the current way.
3, Reroute inverse update to faster routines, 10% whole run speed-up.

**Comment by ye-luo** [comment]
Review completed. Agree to merge.

**Comment by prckent** [comment]
Rerunning tests before approving.

**Comment by prckent** [comment]
Tests passed except for two flux failures:
Intel2015+Complex+CUDA: qe-LiH-unpolarized-np-16-16-2-nk-16-2-2-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-16-flux
Intel2015+CUDA: short-monoO_1x1x1_pp-vmc_sdj-1-16-flux

Assuming these are stochastic.

Will approve the PR. 

Thanks for all the discussion and updates to this one.

**Pull request merged**
