### PR TITLE
Update Multi 231219

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Only 1 file change?

**Comment by correaa** [comment]
It is a draft (now). I want to make sure that everything is working in little steps.

**Comment by correaa** [comment]
can you test this to make sure that things work before updating multi?

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> can you test this to make sure that things work before updating multi?

I'm confident it is unnecessary but I triggered the CI.

**Comment by correaa** [comment]
Thank you for triggering the test.
Now I am going to start a bisection and when the first test fail I am going to reproduce locally.

First try is from

```
commit b279025b500e20fe7b711fa15e168a4a0680d7e0
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Thu Oct 26 06:41:09 2023 +0000

    Revert "Merge branch 'subarray_mctor_protected' into 'master'"
    
    This reverts merge request !689
```

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
I bisected multi and this is the commit that fails with the current version QMCPACK

```
e8cb4abafa6c19691a5122bdc0ad92a957e953e6 is the first bad commit
commit e8cb4abafa6c19691a5122bdc0ad92a957e953e6
Author: Alfredo Correa <alfredo.correa+work@gmail.com>
Date:   Sat Dec 2 19:35:42 2023 -0800

    do not leak

 include/multi/array_ref.hpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Pull request closed without merging**
