### PR TITLE
Enable CI jobs on rhea to compile/run out of /tmp

### PR DESCRIPTION
**Pull request by grahamlopez**

### CODE REVIEW

**Comment by grahamlopez** [comment]
please hold on this: I thought of something else to test that might give a little bit more advantage

**Comment by prckent** [comment]
I watched the build in jenkins - it was significantly faster.

When you update, please add the date+time to the "starting new test for..." sections.

**Comment by grahamlopez** [comment]
> When you update, please add the date+time to the "starting new test for..." sections.

will do

**Comment by grahamlopez** [comment]
Okay, I'm out of ideas for right now; it's ready on my side.

**Comment by grahamlopez** [comment]
Oops, scratch that. Another update is coming.

**Comment by grahamlopez** [comment]
test this please

**Comment by prckent** [comment]
Protect against any existing content in /tmp/${BUILD_TAG}-src? i.e.
if [ -e /tmp/${BUILD_TAG}-src ]; then
rm -r -f /tmp/${BUILD_TAG}-src
fi
cp -r {BUILD_DIR}/qmcpack-src /tmp/${BUILD_TAG}-src

**Comment by grahamlopez** [comment]
> rm -r -f /tmp/${BUILD_TAG}-src

It's a good idea

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
Pending the successful runs this time, I'm releasing this to be merged. I'll try to keep thinking about further possible ways to improve

**Pull request merged**
