### PR TITLE
Fix MSD on BGQ

### PR DESCRIPTION
**Pull request by ye-luo**
1, Workaround the MSD bug on BGQ with Clang.
2, Add quantum package input/output of C2.
3, Add a C2 long test

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Why is this bug triggered on BGQ/BGClang? Is there a fix in the works? What about regular CLANG? Can the code be written a different way to avoid the #ifdefs?

**Comment by ye-luo** [comment]
1, Need to look at regular Clang.
2, ifdef=true should always work. But I prefer the cleaner ifdef=false code path.

**Comment by prckent** [comment]
Please check CLANG. I would expect a subtle bug on our side if that fails.

**Comment by markdewing** [comment]
What is the failure mode?  The added unit test failing?  I tried clang 4 and 5 on x86_64 and neither failed the unit test.

**Comment by ye-luo** [comment]
@markdewing Neither BGClang and x86 clang failed the unit test.
I had thought I could catch something and wrote the unit test but it didn't help. I just leave it there.
I still don't understand why these lines failed on BGQ. I caught them by printf.

**Comment by ye-luo** [comment]
x86 Clang 3.8 was giving the right answer without the workaround.

**Comment by prckent** [comment]
@markdewing Are you happy if we merge as is? i.e. With an ifdef code path for bgq?

**Comment by markdewing** [comment]
Yes, I'm okay with an ifdef code path for bgq.   It might be nice if the comment said more about the failure mode (in this case I think it is giving wrong answers?)

**Comment by ye-luo** [comment]
I added more detail about the failure.
@markdewing has verified that x86 with Clang 4.0 is also correct.

**Pull request merged**
