### PR TITLE
Add deterministic label to converter tests

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Add deterministic test labels to non-QMCPACK executable tests. Activates converters and Nexus in our CI testing. (These tests are all fast to run.) We are encouraging use of 'ctest -L deterministic' for installation and CI, so this will result in increased coverage.

Note that qe-* tests are not labeled because these are not fully deterministic - e.g. QE might pick a different phase.

Might trigger https://github.com/QMCPACK/qmcpack/issues/3092 . Will exclude ntest_nexus_qdens in ci if so.

Might also hit sanitizer issues in the converters. We'll see.

Also, exclude vscode config files from git.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen, gcc10.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Added rsync to Dockerfile ; many nexus tests need rsync is available.

**Comment by prckent** [comment]
Lots of new-to-me nexus errors. Will remove nexus for now. I'll note that nexus currently uses the source directory and wonder if that could be an issue?
```
        Start 1659: ntest_nexus_pwscf_analyzer
729/759 Test #1659: ntest_nexus_pwscf_analyzer ....................................................................***Failed    0.97 sec
Test name     : pwscf_analyzer
Test sublabel : test_analyze
Test exception: "NexusError: path to QE data does not exist
              path provided: /__w/qmcpack/qmcpack/nexus/tests/unit/test_pwscf_analyzer_output/test_analyze/scf_output"
Test backtrace:
  File "/__w/qmcpack/qmcpack/nexus/bin/nxs-test", line 478, in run
    self.operation()
  File "/__w/qmcpack/qmcpack/nexus/bin/nxs-test", line 1322, in pwscf_analyzer
    nunit('analyze')
  File "/__w/qmcpack/qmcpack/nexus/bin/nxs-test", line 349, in nunit
    run_external_unit_test(test_name,unit_test)
  File "/__w/qmcpack/qmcpack/nexus/bin/nxs-test", line 388, in run_external_unit_test
    unit_test()
  File "/__w/qmcpack/qmcpack/nexus/tests/unit/test_pwscf_analyzer.py", line 37, in test_analyze
    pa = PwscfAnalyzer(scf_path,'scf.in','scf.out')
  File "/__w/qmcpack/qmcpack/nexus/lib/pwscf_analyzer.py", line 96, in __init__
    self.error('path to QE data does not exist\npath provided: {}'.format(path))
  File "/__w/qmcpack/qmcpack/nexus/lib/generic.py", line 491, in error
    error(message,header,exit,trace,logfile=self._logfile)
  File "/__w/qmcpack/qmcpack/nexus/lib/generic.py", line 128, in error
    raise NexusError(msg)

Test status: fail
```

**Comment by prckent** [comment]
(Adds about 1500 lines of coverage by just running the converter tests.)

**Review by ye-luo — APPROVED** [review]

**Comment by williamfgc** [comment]
@prckent the Docker container was rebuilt with rsync, see [here](https://hub.docker.com/r/williamfgc/qmcpack-ci/tags?page=1&ordering=last_updated). Thanks.

**Comment by prckent** [comment]
Thanks. FYI, I have the qmcpack id at docker, so we might transition to using that at some point.

**Comment by williamfgc** [comment]
@prckent sounds good, please feel free to add me to the organization. My DockerHub id is the same as GitHub: williamfgc   I'll be happy to migrate the container to the project area.

**Pull request merged**
