### PR TITLE
Protect the available thread count against library calls changing it

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fixes https://github.com/QMCPACK/qmcpack/issues/4510

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
OrangePi5
## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by ye-luo** [comment]
UtilityFunctions.hpp actually contain utility classes. @PDoakORNL Do you prefer changing it or not.

**Review by prckent — COMMENTED** [review]
* Why is this for linear algebra only? I think the code is general but the current use is restricted to linear algebra since OpenBLAS is the only library we have found that misbehaves (is buggy) in this way (changing the thread count of the calling process).

* I prefer OMPThreadCountProtector as the name since it is more specific and nearly fully describes what this class does.

**Comment by ye-luo** [comment]
> * Why is this for linear algebra only? I think the code is general but the current use is restricted to linear algebra since OpenBLAS is the only library we have found that misbehaves (is buggy) in this way (changing the thread count of the calling process).
> 
>     * I prefer OMPThreadCountProtector as the name since it is more specific and nearly fully describes what this class does.

ThreadCountProtector is a template class with Executor::OPENMP as one of the template parameter values. Thus its name should avoid OMP and it can be extended to other threading mode if needed following the design of Concurrency.
For this reason, LAThreadProtect is wrapper which restrict its use to LA and we don't need to propagate HAVE_OPENBLAS definition via config.h globally.

**Comment by ye-luo** [comment]
if you prefer LAThreadProtector can be renamed to LAOMPThreadCountProtector as it is coded to use OpenMP.

**Comment by prckent** [comment]
Depending on where the OMP coding is, could be ThreadCountProtector or OMPThreadCountProtector, your call. The LA part of the current name seems unneeded since it is not restricted to linear algebra. This is some defensive programming to protect us from misbehaving libraries - if HDF5 or libXML2 behaved similarly we could use the same code.

**Comment by ye-luo** [comment]
The LA part is intended for fine-grain control and has interaction with macros and CMake. Activate the protection or not is a compile time decision and I try to keep it contained inside LAThreadProtector.cpp. Adding HDF5ThreadProtector wrapping on top of ThreadCountProtector is cheap. However if three libraries share exactly the same implementation and only HDF5 library that needs the protection, it will cause paying the price at every place using this shared implementation even if there is no need to pay the cost around libxml or LA. So right now ThreadCountProtector is shared at lower level but shim layer LAThreadProtector is specialized.

**Review by PDoakORNL — APPROVED** [review]
This looks good to me

**Comment by PDoakORNL** [comment]
Just for the record I think this is an insane thing for a library to just do. Can we file a bug on openBLAS?

**Comment by ye-luo** [comment]
> Just for the record I think this is an insane thing for a library to just do. Can we file a bug on openBLAS?

We did.
https://github.com/xianyi/OpenBLAS/issues/3940

**Comment by ye-luo** [comment]
> The LA part is intended for fine-grain control and has interaction with macros and CMake. Activate the protection or not is a compile time decision and I try to keep it contained inside LAThreadProtector.cpp. Adding HDF5ThreadProtector wrapping on top of ThreadCountProtector is cheap. However if three libraries share exactly the same implementation and only HDF5 library that needs the protection, it will cause paying the price at every place using this shared implementation even if there is no need to pay the cost around libxml or LA. So right now ThreadCountProtector is shared at lower level but shim layer LAThreadProtector is specialized.

@prckent make sense?

**Review by prckent — DISMISSED** [review]

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by PDoakORNL** [comment]
`UtilityClasses` would be more correct. `ScopedThreadCounts` would be more descriptive. It really doesn't seem like making two files is helpful.  I don't think its essential for merging this.

**Comment by prckent** [comment]
Test this please

**Pull request merged**
