### PR TITLE
Keep RPATH/RUNPATH at make install and add Polaris recipe

### LINKED ISSUE #4181: Clang dangling-else warning
**Describe the bug**
```
/home/yeluo/opt/qmcpack/src/Particle/ParticleIO/XMLParticleIO.cpp:277:15: warning: add explicit braces to avoid dangling else [-Wdangling-else]
              app_debug() << "    " << d_in[old_idx] << " : " << old_idx << " -> " << new_idx << std::endl;
              ^
/home/yeluo/opt/qmcpack/src/Platforms/Host/OutputManager.h:77:3: note: expanded from macro 'app_debug'
  else                                   \
  ^
1 warning generated.
warning: <unknown>:0:0: loop not vectorized: the optimizer was unable to perform the requested transformation; the transformation might be disabled or specified as part of an unsupported transformation ordering [-Wpass-failed=transform-warning]
1 warning generated.
/home/yeluo/opt/qmcpack/src/Particle/ParticleIO/XMLParticleIO.cpp:277:15: warning: add explicit braces to avoid dangling else [-Wdangling-else]
              app_debug() << "    " << d_in[old_idx] << " : " << old_idx << " -> " << new_idx << std::endl;
              ^
/home/yeluo/opt/qmcpack/src/Platforms/Host/OutputManager.h:77:3: note: expanded from macro 'app_debug'
  else                                   \
  ^
```
caused by app_debug as a macro.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
For ALCF polaris
Also address Clang warnings. Close #4181. There is one warning remaining but resolved in #4168 already.

## What type(s) of changes does this code introduce?
- Documentation changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Polaris

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
Please add a mention in the installation part of the manual (search optimization)

**Comment by ye-luo** [comment]
> Please add a mention in the installation part of the manual (search optimization)

I added an entry to the manual pointing to the script. I'm trying to avoid replicating the content and maintain two copies.

**Comment by ye-luo** [comment]
Update: I found a new issue that make install doesn't keep RUNPATH and causes picking up OS installed OpenBLAS at run. So keep RUNPATH at install.

**Review by prckent — APPROVED** [review]
As we update other HPC machines, I think we should change the mentions of build recipes to be similar to what you have done here.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
