### PR TITLE
Fix units in qdens-radial and add documentation

### PR DESCRIPTION
**Pull request by aannabe**
## Proposed changes

While I was trying to compare the charge densities obtained from `pwscf` versus `qmcpack`, I noticed that the charge density object in `qdens-radial`  uses `change_distance_units` to go from (e/Bohr^3) to (e/Ang^3) so that the overall integrated charge density is equal to N_e. Although the right density is obtained, I believe this is due to a double error, one in the definition of `change_distance_units` and one in the usage. In addition, the `change_distance_units` seems to be incorrectly transforming the grid points, thus `change_density_units` must be called instead (leaving the grid points untouched).

In addition to the above changes, `plot_radial_density` was modified to show the density units and a documentation section was added for `qdens-radial` thus closing #3590. The documentation text was borrowed from qmc-workshop_2021 with some minor modifications.

## What type(s) of changes does this code introduce?

- Bugfix
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

NERSC/Perlmutter. All nexus tests are passing in Perlmutter. However, `qdens-radial` test is failing for me on Debian. The failure is due to a difference in charge(error) of 2e-16(1e-13) between output and reference. Perhaps #3092 is related.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Comment by aannabe** [comment]
Can #3590 be closed? Is anything else to be added in that regard?

**Comment by prckent** [comment]
I think you can go ahead and close it. A new issue can be made if needed.

**Pull request merged**
