### PR TITLE
Fix T-move in legacy CUDA

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Broken since #3246 another case can be protected by override keyword.
https://cdash.qmcpack.org/CDash/testDetails.php?test=14149053&build=221767
@prckent We don't have deterministic test covering T-move. So only performance tests expose the issue.

1. The fix revert unique_ptr to raw pointers in SPOSet legacy CUDA APIs. all the raw pointers are treated as references.
2. All the HIP touches are only for cleaning up.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- Yes
When running HIP, "-O3 -ffast-math" 
```
The following tests FAILED:
        337 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-kinetic (Failed)
        345 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-flux (Failed)
        346 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-mpc (Failed)
        381 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-totenergy (Failed)
        419 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-totenergy (Failed)
        515 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-localecp (Failed)
        523 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-potential (Failed)
        526 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-nonlocalecp (Failed)
        539 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-kinetic (Failed)
        552 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-potential (Failed)
        555 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-nonlocalecp (Failed)
```
Needs to adjust tolerance.

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
@ye-luo Since you have a hip build and most people do not, please can you increase the test tolerances? It will be fastest for you.

@Hyeondeok-Shin So we need a t-moves test for a spline orbital DMC run. Maybe add a variant of `deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1` ?
( There are some existing tests dimer tests with tmoves, but these use gaussian basis so don't help CUDA since Gaussians are not supported. And the spline NiO_a4_e48 based one can't be run in CI since it uses a large file via QMC_DATA. )

**Comment by Hyeondeok-Shin** [comment]
I can add deterministic test to cover T-moves for the spline. diamond_1x1x1 sounds enough for me.

**Comment by ye-luo** [comment]
@prckent tried my best to update references. I have turned on nightly tests since last night. I will revisit tomorrow if I missed some places.

**Comment by prckent** [comment]
Thanks. It is an iterative process to set the tolerances.

**Review by prckent — DISMISSED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Pull request merged**
