### PR TITLE
Nexus: Adding crowds_serialize_walkers tag to dmc input list

### PR DESCRIPTION
**Pull request by kayahans**
## Proposed changes

Adds the crowds_serialize_walkers tag to the dmc input list in nexus.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
macOS Monterey 12.6.3, Python 3.9.13
## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by kayahans** [comment]
I have missed adding the write type in the first commit. It should now write yes/no rather than True/False.

**Comment by prckent** [comment]
Since this is motivated by #4648, I'll note that crowds_serialize_walkers will little influence CPU performance but will, in general, destroy GPU performance. So this debugging flag should be used with care until we have a fix for #4648.

**Comment by markdewing** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
