### PR TITLE
VMC support for L2 potentials

### PR DESCRIPTION
**Pull request by jtkrogel**
Add VMC support for L2 potentials.  DMC support to come in a later PR.  Full details (manual entry, etc) to come following publication.  Reviewers: please route questions through Slack.

### CODE REVIEW

**Comment by ye-luo** [comment]
Is ECPComponentBuilder.L2.cpp a better name than ECPComponentBuilder.3.cpp?

**Comment by ye-luo** [comment]
Okay to test

**Comment by prckent** [comment]
Since we want to get rid of the files with extra periods, use ECPComponentBuilder_L2.cpp

**Comment by jtkrogel** [comment]
Rename complete.  Ready for merge?

**Comment by ye-luo** [comment]
Please create an issue to track the documentation

**Pull request merged**
