### PR TITLE
Rc 3171

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

v3.17.1 release candidate

## What type(s) of changes does this code introduce?

- Bugfix
- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Nightly CI only

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Review by ye-luo — CHANGES_REQUESTED** [review]
Change my mind. Shout this go into a 3.17.x release branch in stead of `main`? Or we may not even need `main`

**Comment by prckent** [comment]
main is less brainwork for me. Can make a support/v3.17.x branch whenever needed.

**Review by ye-luo — APPROVED** [review]
OK. Let us deal with a support branch at a later point.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Review by markdewing — APPROVED** [review]

**Pull request merged**
