### PR TITLE
Add tests for Dirac matrix classes.

### PR DESCRIPTION
**Pull request by markdewing**
Test the inverse, determinant, and determinant update in the DiracDeterminantBase
and DiracMatrix classes.

The gen_inverse.py script is included to generate the data for the tests.

### CODE REVIEW

**Comment by ye-luo** [comment]
Can we build the test on ValueType to capture real/complex FP/MP?

**Comment by prckent** [comment]
@ye-luo Happy with the revised version?

**Comment by ye-luo** [comment]
Good to merge. I assume mark has checked complex+MP manually.

**Comment by markdewing** [comment]
Yes, I checked complex plus mixed precision.

**Pull request merged**
