### PR TITLE
[ppconvert] avoid use of tuple in the interface in Blitz interface

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 21.10

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
You will have to resolve the conflict (?)

**Comment by correaa** [comment]
I don't understand how the conflict appeared, I made a clean clone and a full update of my fork to make this change. Worst case scenario I will start over.

**Comment by prckent** [comment]
@correaa Perhaps rebuild this?

**Comment by correaa** [comment]
I will start over. I don't understand how the conflict happened.

**Pull request closed without merging**
