### PR TITLE
Document attribute condition in particleset attrib.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
more documentation

## What type(s) of changes does this code introduce?
- Documentation changes
### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
none
## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
macos build is failing to find HDF5. Likely a CI update needed. I consider this PR safe to merge given the changes and coverage in other builds.

**Review by prckent — APPROVED** [review]

**Pull request merged**
