### PR TITLE
Nexus: add QMCPACK excitation input

### PR DESCRIPTION
**Pull request by jtkrogel**
Add ability to specify single determinant excitation input to QMCPACK via Nexus.

This is supported via a new "excitation" keyword to generate_qmcpack.  Both xml input types (plain index: "-216 +217" and band index: "6 36 6 37") are supported.  The user specifies the up or down determinant as follows:
```
qmc = generate_qmcpack(
    ...
    excitation = ('up','-216 +217'),
    ...
    )

qmc = generate_qmcpack(
    ...
    excitation = ('down','6 36 6 37'),
    ...
    )
```

As with the original QMCPACK input, the burden is on the user to determine the appropriate orbital indices for the desired excitation.  Future Nexus commits may relieve this burden.

### CODE REVIEW

**Comment by prckent** [comment]
Is there an ETA for documentation in the QMCPACK manual for this feature?

**Comment by jtkrogel** [comment]
Hard to estimate ETA precisely, but it will be added at the same time all other inputs to generate_qmcpack are documented.  I'm working first on examples with documentation to follow.

**Comment by jtkrogel** [comment]
Given the discussion in #577, is "excitation" a better keyword name?

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
'excitation' is better than 'excite'

**Comment by jtkrogel** [comment]
OK, I will make this change.

**Pull request merged**
