### PR TITLE
Fix tensor test

### PR DESCRIPTION
**Pull request by mmorale3**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Modified unit test to avoid operator assignment with initializer lists to multi arrays.
This has problems in intel compilers. Construction from initializer lists works, so using that instead.

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- Yes

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by mmorale3** [comment]
This should fix the compilation issues in intel19.
Will fix clang10 issues in another PR.

**Comment by ye-luo** [comment]
@mmorale3 alcf-intel-CUDA is still failing. Please open the full log and search for error. You may miss some of them due to massive warnings.

**Comment by mmorale3** [comment]
I was using 19.1 on LLNL. WIll send a fix soon.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
alcf-intel-CUDA now pass. Once the clang gets fixed. We will mark both of them as required.

**Pull request merged**
