### PR TITLE
Add debug mode configuration to CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add a debug mode configuration job to CI 
Expect to capture asserts
Need to observe runtimes on GitHub Actions CI
Related to #3691 and #3696 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests) CI

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must pass GitHub Actions CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Why is this related to #3696? I think we can merge this one independently. Remove WIP?

**Comment by williamfgc** [comment]
@ye-luo there is a `static_assert` failure reported in [this comment](https://github.com/QMCPACK/qmcpack/issues/3696#issuecomment-1003206370). I'll remove the WIP. Thanks!

**Comment by ye-luo** [comment]
> @ye-luo there is a `static_assert` failure reported in [this comment](https://github.com/QMCPACK/qmcpack/issues/3696#issuecomment-1003206370). I'll remove the WIP. Thanks!

Maybe that is gone already with the latest update of "multi"

**Review by ye-luo — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
