### PR TITLE
Add main branch to GitHub Actions CI target

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add `main` branch as a target for GitHub Actions CI runners

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
I don't know how CI configurations are propagated. Could you make a new PR starting from main, adding these two lines of change and PR to the main branch?

**Comment by prckent** [comment]
@ye-luo sorry, missed your comment. Decided to force merge this.

**Comment by ye-luo** [comment]
@prckent No problem. git knows how to handle identical changes. @williamfgc could you still make a PR changing the main?

**Comment by williamfgc** [comment]
@ye-luo let me rebase off main and do a PR.

**Pull request merged**
