### PR TITLE
Fix sposet_indices missing construction in OrbitalImages.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
A simpler alternative to https://github.com/QMCPACK/qmcpack/pull/4617

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
@Paul-St-Young does this fix the broken feature?

**Comment by Paul-St-Young** [comment]
@ye-luo yes, this does fix orbimg est
Thank you!

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Pull request merged**
