### PR TITLE
Make changes to rely on ADL get instead of std::get in AFQMC

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Namely restore part of #5228 without update of multi.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
This is the list of errors I see in the CI so far:

- [macos (macOS-GCC14-NoMPI-Real)](https://github.com/QMCPACK/qmcpack/pull/5239#logs)
	 36 - deterministic-unit_test_estimators (Bus error)
https://github.com/QMCPACK/qmcpack/actions/runs/11962263609/job/33350271019?pr=5239#step:7:2073

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@correaa AFQMC update seems good.

**Comment by correaa** [comment]
ok, so it is possible to merge then? I will keep working on the side to make the complex afqmc work with newer versions of Multi. But at least I can keep developing Multi without breaking the real version (and the rest of the code).

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
After this PR and those related to it on Thursday, the nightly tests are clear.

**Pull request merged**
