### PR TITLE
Add deterministic test for solid 'diamondC_2x1x1_pp' and add scalars for deterministic test for molecule 'LiH_dimer_pp'.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Add some deterministic tests for the full precision build. 

1. Add deterministic test for scalars 'ionion', 'localECP', 'nonlocalECP', and 'flux' on a molecule 'LiH_dimer_pp' testset for more detailed test. 

2. Add deterministic tests for a solid 'diamondC_2x1x1_pp' testset.

References were obtained from AoS/real/full precision build with clang-4.0 in BG/Q. Tests were passed with gcc 8.2.1 and intel 19.0.2.187 in my workstation, but it needs more feedbacks from other compilers and machines.

Hyeondeok Shin

### CODE REVIEW

**Comment by ye-luo** [comment]
det_qmc_short_vmc_dmc_reconf.in.xml Is it necessary to keep the one for reconfiguration? It is not correct at the moment and may cause false alarm.

**Comment by Hyeondeok-Shin** [comment]
Thanks for the comments. 'det_qmc_short_vmc_dmc_reconf.in.xml' is removed and the step has changed. Please let me know there is still a problem I have to update.

**Comment by prckent** [comment]
LGTM

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
