### PR TITLE
Nexus: Fix the qdens-radial test

### PR DESCRIPTION
**Pull request by aannabe**
## Proposed changes

The Nexus `qdens-radial` test is passing for me when running on a NERSC machine, but it's failing on my Linux laptop. Upon inspection, the test is failing due to float comparison with many significant digits, which is a problematic thing to do:

Laptop:
```
Cumulative Value of C Species at Cutoff 0.6 is: 1.1078267486386277+/-0.0016066467832022906
```

NERSC:
```
Cumulative Value of C Species at Cutoff 0.6 is: 1.1078267486386275+/-0.0016066467833404942
```

In practice, we don't need 16 digits after decimal for charge densities. So I changed the `qdens-radial` output to have 8 digits after decimal and updated the reference data for the tests. After this change, all tests are passing for me locally and on NERSC.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

NERSC, Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]
Thanks for investigating this. It has been a problem from time to time in various nightly tests etc.   Your modifications are an indirect way of adding a tolerance to 8 digits. This works for me and I agree with the reasons you give.

**Comment by jtkrogel** [comment]
An alternative (direct) way is to add the absolute tolerance to the equality check:

```
assert(text_eq(out,out_ref,atol=1e-8))
```

**Comment by aannabe** [comment]
Added the tolerance explicitly.

**Review by prckent — APPROVED** [review]
Thanks Gani

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
