### PR TITLE
Refactor Factory functions to return std::unique ptr

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

As suggested in #4125, this updates various factory functions to return `std::unique_ptr<T>`.

~I also moved construction of `wOut` to be earlier in the construction of` QMCDriverNew`.~

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

local workstation: Ubuntu 20.04

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — DISMISSED** [review]
LGTM

**Review by PDoakORNL — DISMISSED** [review]
this is a pretty obvious inconsistency in the API so its good to fix.  I personal prefer to use the templated `UPtr<T>` type alias from `type_traits/template_types.hpp` But I don't think we really have consensus on that.

**Comment by ye-luo** [comment]
@quantumsteve some builds are failing.

**Comment by quantumsteve** [comment]
> @quantumsteve some builds are failing.

I reverted the last commit changing the construction of `HDFWalkerOutput`. Hoping the builds pass again 🤞

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
