### PR TITLE
Update default optimizer to OneShiftOnly.

### LINKED ISSUE #19: Defaults for linear optimization are required
Reported by: jtkrogel

Set sensible defaults for as many input parameters as possible for the "linear" optimizer.  Preferable to complete prior to the school as newcomers (or veterans!) shouldn't have to turn many knobs.  If this is not simple to do then the optimizer should either be fixed or very detailed explanations/examples of driving the optimizer should be included in the manual.

### PR DESCRIPTION
**Pull request by ye-luo**
Manual is updated as well.
closes #19

### CODE REVIEW

**Comment by jtkrogel** [comment]
It doesn't have to be part of this PR, but it would be nice if a complete/functional '<qmc> ... </qmc>' listing was provided for each of quartic, adaptive, and OneShiftOnly in the manual.  Right now the user has to assemble one based on the instructions, but it would be more convenient to have a copy/paste-able example for each.

**Comment by prckent** [comment]
@jtkrogel Agreed

I will mandate full & functional sections for oneshift and adaptive shift before merging this PR.

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
@eneuscamman I added the VMC part in for the adaptive optimizer. The optimizer aborts with some error. Could you check what is missing? The optimizer should be fine since the nightly H4_ae is good.

**Comment by ye-luo** [comment]
Full optimization sections have been added in the manual.

**Comment by prckent** [comment]
Thanks Ye and Eric.

**Pull request merged**
