### PR TITLE
Remove Base from (Multi)DiracDeterminantBase

### PR DESCRIPTION
**Pull request by PDoakORNL**
Small rename refactor.

### CODE REVIEW

**Comment by ye-luo** [comment]
I should say this also to myself.
Could you please hold the temptation to change class names vastly?
This may introduce large interference with on going works. Please add the proposed name change in #861 then fix them when we do the whole code formatting.

**Comment by prckent** [comment]
I am happy with this change - at least when the CI passes. We are all going to have to skill up and deal with much larger changes than this. If we completely avoid interfering with ongoing works we will never succeed in making the large changes that the code base needs. Of course, changes that might be painful for WIPs should be well advertised via Slack or direct contact with the developers. 

We still have quite a few "bases" to remove/update, and still a few "orbitals" that are wavefunctioncomponents, OMP naming is inconsistent etc.

**Comment by PDoakORNL** [comment]
Paul and Ye you got this in email which you didn't read

End of CPU build
```
16/17 Test #16: deterministic-unit_test_drivers .........   Passed    0.63 sec
      Start 17: deterministic-unit_test_qmcapp
17/17 Test #17: deterministic-unit_test_qmcapp ..........   Passed    0.71 sec

100% tests passed, 0 tests failed out of 17

Label Time Summary:
quality_unknown    =  15.44 sec (16 tests)
unit               =  15.74 sec (17 tests)

Total Test time (real) =  16.83 sec
Traceback (most recent call last):
  File "/home/bgl/blocking_qsub", line 126, in <module>
    main()
  File "/home/bgl/blocking_qsub", line 74, in main
    stream_file(output_stream)
  File "/home/bgl/blocking_qsub", line 108, in stream_file
    line = f.readline()
IOError: [Errno 116] Stale file handle
+ cp /ccs/home/bgl/openshift-ci/workspace/qmcpack-rhea@2/jenkins-qmcpack-rhea-675.o465204 ../
+ cp /ccs/home/bgl/openshift-ci/workspace/qmcpack-rhea@2/jenkins-qmcpack-rhea-675.o465204 ../
++ wc -l
++ grep '100% tests passed, 0 tests failed out of [0-9]*' ../jenkins-qmcpack-rhea-675.o465204
+ '[' 3 -eq 4 ']'
Build step 'Execute shell' marked build as failure
Setting status of dad1266b7496336a08ff71d4f7eff0263f2f37fd to FAILURE with url http://miniqmc-ci.openshift.lb.ccs.ornl.gov/job/qmcpack-rhea/675/ and message: 'Build finished. '
Using context: qmcpack rhea
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Sending email to: doakpw@ornl.gov lopezmg@ornl.gov kentpr@ornl.gov markdewing@gmail.com yeluo@anl.gov
```
*CPU PASSED*

GPU checkout output
```
Test project /ccs/home/bgl/openshift-ci/workspace/qmcpack-rhea-gpu@2/build
      Start  1: deterministic-unit_test_ohmmspete
 1/17 Test  #1: deterministic-unit_test_ohmmspete .......   Passed    0.29 sec
      Start  2: deterministic-unit_test_numerics
 2/17 Test  #2: deterministic-unit_test_numerics ........   Passed    0.33 sec
      Start  3: deterministic-unit_test_utilities
 3/17 Test  #3: deterministic-unit_test_utilities .......   Passed    0.37 sec
      Start  4: deterministic-unit_test_einspline
 4/17 Test  #4: deterministic-unit_test_einspline .......   Passed   11.66 sec
      Start  5: deterministic-unit_test_spline2
 5/17 Test  #5: deterministic-unit_test_spline2 .........   Passed    0.31 sec
      Start  6: deterministic-unit_test_ohmmsdata
 6/17 Test  #6: deterministic-unit_test_ohmmsdata .......   Passed    0.29 sec
      Start  7: deterministic-unit_test_io
 7/17 Test  #7: deterministic-unit_test_io ..............   Passed    0.37 sec
      Start  8: deterministic-unit_test_lattice
 8/17 Test  #8: deterministic-unit_test_lattice .........   Passed    0.29 sec
      Start  9: deterministic-unit_test_particle
 9/17 Test  #9: deterministic-unit_test_particle ........   Passed   11.84 sec
      Start 10: deterministic-unit_test_particleio
10/17 Test #10: deterministic-unit_test_particleio ......   Passed    0.32 sec
      Start 11: deterministic-unit_test_wavefunction
11/17 Test #11: deterministic-unit_test_wavefunction ....   Passed   12.24 sec
      Start 12: deterministic-unit_test_hamiltonian
12/17 Test #12: deterministic-unit_test_hamiltonian .....   Passed   20.75 sec
      Start 13: deterministic-unit_test_type_traits
13/17 Test #13: deterministic-unit_test_type_traits .....   Passed    0.29 sec
      Start 14: deterministic-unit_test_particle_base
14/17 Test #14: deterministic-unit_test_particle_base ...   Passed    0.32 sec
      Start 15: deterministic-unit_test_estimators
15/17 Test #15: deterministic-unit_test_estimators ......   Passed   10.89 sec
      Start 16: deterministic-unit_test_drivers
16/17 Test #16: deterministic-unit_test_drivers .........   Passed   11.98 sec
      Start 17: deterministic-unit_test_qmcapp
Traceback (most recent call last):
  File "/home/bgl/blocking_qsub", line 126, in <module>
    main()
  File "/home/bgl/blocking_qsub", line 74, in main
    stream_file(output_stream)
  File "/home/bgl/blocking_qsub", line 108, in stream_file
    line = f.readline()
IOError: [Errno 116] Stale file handle
+ cp /ccs/home/bgl/openshift-ci/workspace/qmcpack-rhea-gpu@2/jenkins-qmcpack-rhea-gpu-672.o465205 ../
+ cp /ccs/home/bgl/openshift-ci/workspace/qmcpack-rhea-gpu@2/jenkins-qmcpack-rhea-gpu-672.o465205 ../
++ wc -l
++ grep '100% tests passed, 0 tests failed out of [0-9]*' ../jenkins-qmcpack-rhea-gpu-672.o465205
+ '[' 3 -eq 4 ']'
Build step 'Execute shell' marked build as failure
Setting status of dad1266b7496336a08ff71d4f7eff0263f2f37fd to FAILURE with url http://miniqmc-ci.openshift.lb.ccs.ornl.gov/job/qmcpack-rhea-gpu/672/ and message: 'Build finished. '
Using context: qmcpack rhea (gpu)
Email was triggered for: Failure - Any
Sending email for trigger: Failure - Any
Sending email to: doakpw@ornl.gov lopezmg@ornl.gov kentpr@ornl.gov markdewing@gmail.com yeluo@anl.gov
```
*GPU PASSED*

Of course since the details link doesn't actually work and no one reads the jenkins emails unless they are pissed of you didn't see this.  
I have other projects as well which require concentration, this presents an inaccurate picture of my PR's.

I need to change these class names to make my refactor look consistent. That's important because it forces important reviews of future PR's into less superficial directions.
The only reason to reject this PR once the CI reports properly is to push the work of keeping long lived branches, your own or others onto me.
Total consistency is not the point of the exercise and I imagine would only get me "You changes 100's of files I cant' review this" response.
We have agreed to try and have small reviewable PR's.

**Comment by PDoakORNL** [comment]
Ok ok I need to restart my private CI, I'm in to much of a rush for rhea and jenkins.

**Comment by PDoakORNL** [comment]
Making a force update.  So if you've pulled this branch expect an issue

Also seeing a failure not related to my changes as far as I can tell but possiblity C++14 and clang 6
Or oxygen's blas/lapack combination.

CPU with QMC_PRECISION_MIXED=1 and QMC_COMPLEX=1 fails
```
  Distance table for similar particles (A-A):
    source/target: elec
    Using structure-of-arrays (SoA) data layout
    Distance computations use orthorhombic periodic cell in 3D.


  Distance table for dissimilar particles (A-B):
    source: ion  target: elec
    Using structure-of-arrays (SoA) data layout
    Distance computations use orthorhombic periodic cell in 3D.


  Distance table for similar particles (A-A):
    source/target: ion
    Using structure-of-arrays (SoA) data layout
    Distance computations use orthorhombic periodic cell in 3D.

  Sigma=2.366552359
  Sigma=2.366552359
  Clone CoulombDerivHandler.
debug evaluateSR_AA     -0.02283659019    -0.02283657156     1.1422825e-07
debug evaluateSR_AA      0.02283658646     0.02283656783  -1.388313962e-07
IonIon Force
    -0.02283659019    -0.02283657156     1.1422825e-07
     0.02283658646     0.02283656783  -1.388313962e-07

ERROR Broken real spherical quadrature for 50-point rule.

ERROR   Should be zero:  -1.86185e-06

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Pull request merged**
