### PR TITLE
Add statistical integraton and deterministic test for positron

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

This PR is to add statistical integration test and deterministic tests of positron for both SD and MSD wavefunction.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

 - No

## What systems has this change been tested on?
 Workstation

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by shivupa — APPROVED** [review]

**Comment by shivupa** [comment]
Thanks Hyeondeok!

This PR implements a deterministic test for PsH which covers most of the relevant machinery for multi-component calculations. 

The calculations are without a Jastrow factor, but if desired I can add that in a follow up PR.

**Review by shivupa — APPROVED** [review]

**Comment by ye-luo** [comment]
Can we have tests created for the batched drivers?

**Review by ye-luo — CHANGES_REQUESTED** [review]
Block PR as we wait for tests created for batched drivers.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
Still needs non-ANL approval.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thanks Hyeondeok.

Would like to learn how the wavefunctions were created and reference data produced.

**Comment by prckent** [comment]
Quick note: looking at the nightlies, so far these have been robust. They are passing on every build except for amdclang offload. On one hand this is not a surprise, but interestingly there is a NaN https://cdash.qmcpack.org/CDash/testDetails.php?test=26602545&build=419702 in the statistics even though the run appears to complete OK https://cdash.qmcpack.org/CDash/testDetails.php?test=26602541&build=419702 . This could be an issue on the QMCPACK side.

**Pull request merged**
