### PR TITLE
Add ValueAlias for ValueType reconstruction

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Add a helper class for Value type reconstruction.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Review by PDoakORNL — APPROVED** [review]
I don't see a problem with this but I guess I don't understand why its needed. 

I always have assumed that classes and functions would be templated on Value since that basically determines everything except what the full precisions is.
If a derived type is complex definite and you have an indeterminant type  I always assumed its type would be determined via
```
std::complex<RealAlias<T>> var;
// or
std::complex<FullPrecReal> var_full_prec;
```

What am I not seeing here?

**Comment by ye-luo** [comment]
> I don't see a problem with this but I guess I don't understand why its needed.
> 
> I always have assumed that classes and functions would be templated on Value since that basically determines everything except what the full precisions is. If a derived type is complex definite and you have an indeterminant type I always assumed its type would be determined via
> 
> ```
> std::complex<RealAlias<T>> var;
> // or
> std::complex<FullPrecReal> var_full_prec;
> ```
> 
> What am I not seeing here?

Value is not complex definite. QTBase and QTFull relies on ifdef. To have full template, I tries not ot rely on QTFull but promote precision but to derive FullPrecValue based on Value using ValueAlias.

**Comment by PDoakORNL** [comment]
This is why I thought we would need `Value` and `FullPrecValue` or `FullPrecReal` for value/precision templating. I'm unclear on how if you have only a Real or a Value type coming into a function how you can discover whether it is reduced or full precision and what the full precision is without some global type alias.

This is why `WaveFunctionTypes.hpp` looks like it does, but I'll wait and see how this is used.

**Comment by ye-luo** [comment]
`WaveFunctionTypes<VALUE, VALUE_FP>` needs to consistently put value types. If one use `WaveFunctionTypes<VALUE, REAL_FP>` it breaks. With added reconstruct capability, it can be changed to `WaveFunctionTypes<VALUE, FP_PREC>` and internally derive `VALUE_FP` as `ValueAlias<FP_PREC, VALUE>`.

**Comment by PDoakORNL** [comment]
I get you now.  I agree that `<VALUE, FP_PREC>` is better. And now I see what you are after here.

**Comment by prckent** [comment]
Test this please

**Pull request merged**
