### PR TITLE
ESHDF python class and GPAW converter

### PR DESCRIPTION
**Pull request by tiihonej**
A generic python class to handle ESHDF files for QMCPACK. The class is presently used by a new GPAW converter, which implements tools to either read a GPAW restart file (.gpw) or convert live calculator objects to ESHDF. This is resubmission of PR #3617 that went stale. 

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?

- New feature
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Thanks for submitting the fresh PR Juha. I have (re)triggered the tests, however since gpaw isn't installed in the test infrastructure problems will only occur if there is major breakage. Therefore we just need to agree that the docs are sufficiently updated and that there are no obvious inconsistencies (etc.) to merge. Python dependencies are currently broken in many of the nightlies due to problems with using spack, so this will need to be fixed first before adding gpaw. 

Are the previous reviewers/commenters happy?

**Comment by ye-luo** [comment]
This is just a resubmission of what I approved.

**Comment by tiihonej** [comment]
Indeed. Seems all the tests pass now, although the nightlies probably don't even run those added in this PR.

**Review by prckent — COMMENTED** [review]
Q. Should it not be gpaw2qmcpack for consistency with pw2qmcpack? 

(Sorry, just spotted this possible inconsistency when I was about to approve.)

**Review by prckent — APPROVED** [review]
On reflection, since we also have convert4qmc, I think this should go in.

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
@tiihonej this PR complete https://github.com/QMCPACK/qmcpack/issues/3490?

**Pull request merged**
