### PR TITLE
Initial unit tests for effective core potentials.

### PR DESCRIPTION
**Pull request by markdewing**
Move the Ylm.h file to Numerics and add some tests for it.
The default test checks a few values.  There is code that can test over
a wider range a values, but it is disabled by default.  This more extensive code
may be useful to run a new platform or under new conditions, but doesn't need to
be run as frequently as normal unit tests.  Eventually this kind of testing
should get moved to its own category.

The initial ECP tests use existing validation code for the spherical quadrature rules.
In order to make the function more testable, a return value is used to indicate
success or failure. The call to abort the program upon failure is moved higher
in the call chain.

The output to indicate the program in resize_warrays was removed - it doesn't
seem useful, and it clutters the output.

Add a few simple unit tests in Numerics for the vector sin/cos evaluation in e2iphi.h
and for the vector viewer.

### CODE REVIEW

**Comment by ye-luo** [comment]
1, I saw the constraints were further relaxed from 5 (I did) to 7. Is it because the mixed precision build?
2, On ANL branch, I split the quadrature routines from ECP to Numerics. Some conflict should appear when merge but easy to solve.
3, Clang currently gives warning about some routines when the template class is specialized D=1.

**Comment by markdewing** [comment]
1. The tolerance increased on the check to allow the one of the higher integration rules to pass.  This was on the full precision build.
2. The changes should not be too hard to integrate with the ANL branch changes.
3. Fixed.

**Comment by prckent** [comment]
I am happy to merge. @ye-luo Any objections?

**Comment by ye-luo** [comment]
+1

**Pull request merged**
