### PR TITLE
Clean up around BsplineAllocator.hpp and MultiSpline.hpp

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
1) reduce MultiSpline::create_spline template parameters
2) Make MultiSpline::copy_spline a free function.

## What type(s) of changes does this code introduce?
- Other (please describe): code refactoring.

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
This basically looks good to me, in that it improves the existing `c` code.  I think that from a compilation standpoint `copy_spline` MSDT & SSDT type mixing is more open than the member function copies, if their are constraints those should be documented and perhaps handled at compile time.

**Comment by ye-luo** [comment]
Actually I still need to relocate `copy_splines`. Is that OK if I add "MSDT & SSDT" constraints in my next PR? I will add static_assert making sure they are float types.

**Review by PDoakORNL — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
