### PR TITLE
Nexus: tests for simulation module

### PR DESCRIPTION
**Pull request by jtkrogel**
Add tests for the `simulation` module.  This module is the most central to Nexus workflow representation and execution.  As such, it is the most heavily tested.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Ready for merge.

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
@jtkrogel Please solve the merge conflict. Otherwise the CI fix on develop cannot be applied on PR branch.

**Comment by jtkrogel** [comment]
Should be good now.

**Pull request merged**
