### PR TITLE
HDF5 wavefunctions for AFQMC

### PR DESCRIPTION
**Pull request by fdmalone**
Enables reading of HDF5 format wavefunctions in AFQMC and updates tools appropriately. Old style plain text wavefunctions will be removed entirely in the future.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
This broke several unit tests in the cuda-experimental build:
```
The following tests FAILED:
	  3 - deterministic-unit_test_afqmc_slaterdeterminantoperations (Failed)
	  7 - deterministic-unit_test_afqmc_wfn_factory_ham_chol_uc_wfn_rhf (Failed)
	  8 - deterministic-unit_test_afqmc_prop_factory_ham_chol_uc_wfn_rhf (Failed)
	  9 - deterministic-unit_test_afqmc_estimators_ham_chol_uc_wfn_rhf (Failed)
```

**Comment by fdmalone** [comment]
I'll have a look

**Comment by mmorale3** [comment]
All the tests are passing now on LLNL.

**Pull request merged**
