### PR TITLE
Flip the sign of einspline twist input

### LINKED ISSUE #1386: Inconsistent twist directions between electron gas and einspline wavefunctions
**Sympton**: electron gas momentum distribution n(k) is wrong at fractional twist (i.e. not 0 or 0.5)
**Direct cause**:  `MomentumEstimator::putSpecial` subtracts the twist vector from kpoint grid, whereas `HEGGrid::create_kpoints` adds the twist vector to the kpoint grid.
**Root cause**: einspline wavefunction puts negative sign in front of kgrid?

I found this bug when trying to calculate the momentum distribution n(k) of the homogeneous electron gas (HEG) at a fractional twist e.g. (0.3, 0.0, 0.0). I realized that the `MomentumEstimator` *subtracts* the twist vector from the Gamma-point kgrid
`       ikpt[0]=i-twist[0];
        ikpt[1]=j-twist[1];
        ikpt[2]=k-twist[2];`
whereas the electron gas orbital builder *adds* the twist to the Gamma-point kgrid
`PosType k(i0+tw[0],i1+tw[1],i2+tw[2]);`

If I add the twist to kgrid in `MomentumEstimator`, then n(k) becomes correct. (see figure below).
I have also attached a tiny example (2 electrons)  [short.zip](https://github.com/QMCPACK/qmcpack/files/2871113/short.zip), which could be added as a short test for the bug in question.
heg-nk

Of course, the current `MomentumEstimator` is correct when used with einspline wavefunction, so I think the bigger question is: why does einspline wavefunction negate the twist direction?

Unfortunately, I am not sure how exactly the einspline wavefunction sets up the kgrid and the twist vectors, because the wavefunction construction is quite complicated. File potentially involved:
- EinsplineSetBuilderCommon.cpp
- EinsplineSetBuilder_createSPOs.cpp
- EinsplineSetBuilderESHDF.fft.cpp
- EinsplineSetBuilder.h
- EinsplineSetBuilderOld.cpp
- EinsplineSetBuilderReadBands_ESHDF.cpp
- EinsplineSet.cpp
- EinsplineSet.h
- Bspline*?

In my opinion, adding twist to a positive kgrid is the intuitive option, so I am tempted to change `MomentumEstimator` and the einspline wavefunction. On the other hand, changing `HEGGrid` is a lot easier. How should I proceed?

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
h5 from DFT has [0 0.5 0.25]
Before this PR, we input `twist="0.0   -0.5  -0.25"`
```
Super twist #0:  [   0.00000   0.00000   0.00000 ]
Super twist #1:  [  -0.00000   0.50000  -0.25000 ]
  Using supercell twist 1:  [  -0.00000   0.50000  -0.25000]
```
Now we should input  `twist="0.0 0.5  0.25"` as DFT.
```
Super twist #0:  [   0.00000   0.00000   0.00000 ]
Super twist #1:  [   0.00000   0.50000   0.25000 ]
  Using supercell twist 1:  [   0.00000   0.50000   0.25000]
```
This change breaks backward compatibility. Tools generating input for QMCPACK should be updated.

The fix in splines is in the builders, updating all the spline implementation is to much more involving. Thus kept the old sign.
We may change that after delete EinsplineSet but that doesn't affect users.

I also changed the convention in MomentumEstimator.
closes #1386.

I also deleted code that was commented out.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by jtkrogel** [comment]
I will review/comment here, but likely not until tomorrow.

**Comment by ye-luo** [comment]
Test this please

**Comment by jtkrogel** [comment]
The sign issue is only partly an input problem.  Does this just change the sign on the input, but retain the inverted sign internally during orbital construction or evaluation?

If the inverted sign is retained internally, this is a problem because a Bloch state with inverted wavevector exists in the wavefunction.  The actual wavevector of the Bloch state is probed with the momentum distribution, and this can result in no signal in the case of inconsistency.

**Comment by ye-luo** [comment]
The issue of momentum distribution is a pure input problem.
Because orbital saves the twist to ParticleSet and then momentum distribution reads from it.
However ElectronGasBuilder and EinsplineSetBuilder doesn't store the twist in the same convention. By flipping the sign in EinsplineSetBuilder, momentum distribution always take twists in the usual DFT convention.
Note that EinsplineSetBuilder is an object different from EinsplineSet. Momentum distribution doesn't and shouldn't know what underlying SPOSet is.

About EinsplineSet/BsplineSet internal. kPoints are stored as -twist with some additional lattice shift. When evaluating an orbital. A bloch state is `e^(i twist r)u(r)`. u(r) is the spline orbital. Because kPoints carries opposite sign. The evaluation function computes `e^(- i k r)`. See https://github.com/QMCPACK/qmcpack/blob/d69bce8c77060d69d35f78861e501a6408c3cfee/src/QMCWaveFunctions/BsplineFactory/SplineC2C.cpp#L185

How is u(r) is constructed. It is first fft from planewave coefficient. Then it is rotated. Rotating a phase doesn't change the physics of orbital itself and there is neither phase imposed from QE. The rotation angle determination is empirical and it needs to evaluate orbitals and there seems to be a sign flip see `einspline_helper.hpp`. but as long as rotation doesn't change physics, it should not hurt. Change it requires updating unit test references.

We need to anatomize the overall issue and take incremental steps.

**Comment by jtkrogel** [comment]
Probably best to have a quick chat/call on this.

**Comment by ye-luo** [comment]
Test this please

**Review by jtkrogel — APPROVED** [review]
LGTM.  It seems that Einspline* and Momentum* were correcting for the inverted sign independently, so this changes here should not affect the functioning of n(k) estimators.

The changes here should fix #1386.  Someone should rerun the inputs provided in that issue and check after this PR goes in.

**Pull request merged**
