### PR TITLE
Manual conversion up to page 232

### PR DESCRIPTION
**Pull request by jbatson5**
## Proposed changes

This PR adds conversion of the manual for RTD up to page 223. It also adds a /figs directory for all the images in the manual. PDFs used for figures have been converted to jpg or png files. Building fresh returns ~20 warnings, but none are breaking; most refer to cross-references for sections that don't yet exist or duplicate citations (unavoidable, it seems). 

## What type(s) of changes does this code introduce?

- Documentation content changes

### Does this introduce a breaking change?

- No

### CODE REVIEW

**Comment by prckent** [comment]
Just a couple of typos. However, there could well be others with a similar pattern and origin that I missed.

**Comment by jbatson5** [comment]
Most recent commit fixes the typos and adds a little bit more conversion. Didn't add new files so as to not get too far behind develop. Actual conversion is up to ~260 now.

**Comment by prckent** [comment]
Thanks John. Looks good.

**Comment by prckent** [comment]
OK to test

**Pull request merged**
