### PR TITLE
Add a dummy return to reduce Clang warning.

### PR DESCRIPTION
**Pull request by ye-luo**

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Just for the record, why aren't we using pure virtual functions here?

**Comment by ye-luo** [comment]
This routine is implemented only in SoA distance tables. No plan to add for the old AoS ones unless this is really needed. If the AoS ones are accessed, the code should stop to catch developer attention.

**Comment by prckent** [comment]
Separate PRs for separate updates please! I don't want us to get in the habit of mixing updates. Next time this happens from core developers I will close the PR. Branches and PRs are cheap.

**Pull request merged**
