### PR TITLE
Opt momentum estimator

### PR DESCRIPTION
**Pull request by ye-luo**
The computation inside momentum estimator has been optimized by rearranging the calculation and reusing data. This is effective for both AoS and SoA.
The evaluateRatiosAlltoOne of J1,J2,J3 with SoA has also been optimized by using specialized implementation.

The test case I used is VO2 48 atom cell. 400 electron. On titan, 2 MPI per node and 8 thread per MPI.
When using 128 samples, I saw huge speed up.
No estimator, 1.564921 sec
With 128 samples, 28.948585 sec
Optimized code with 128 samples, 4.872676 sec.

@kylanpaa Please verify that
- [x] real is good.
- [x] complex is good.

### CODE REVIEW

**Comment by prckent** [comment]
@ye-luo , @kylanpaa please work together to add a test for this estimator.

@ye-luo  please describe in detail for which system these timings come from (same comment as for #609 )

**Comment by kylanpaa** [comment]
The tests at eos indicate that both real and complex are good and significant speed-up is evident. The test case was R phase of VO2 with 50 electrons and 2x1x1 twist grid for both real and complex. Additionally, long VMC runs were performed with 3x1x1 twist grid using the complex SoA code. Comparison of the 3x1x1 results with those from the older implementation coincide properly. The 3x1x1 results are shown in the attachment, where on the left one has the spherically averaged momentum distributions (new and old in the same plot) and on the right the deviation of the results in units of 1sigma (the red dashed line is a normalized Gaussian).

[nk_tests2.pdf](https://github.com/QMCPACK/qmcpack/files/1604475/nk_tests2.pdf)

**Comment by ye-luo** [comment]
@kylanpaa What is the size of the h5 orbital file of VO2?
@prckent I have no experience dealing with h5 output from estimators. Can we have extra hands to help with the test?

**Comment by prckent** [comment]
First we need a small/quick reliable test. Unfortunately custom check code may be needed for the h5.  Perhaps we should add the small NiO cell as we discussed to the performance tests and use that wavefunction?

**Comment by jtkrogel** [comment]
Why not just add the n(k) estimator to existing real/complex diamond test runs?  Then we just need to write an additional post-processing script.

I am planning to operate in this way for coming estimator tests in general (i.e. add to existing integration tests to avoid eventually very long test times).  

I can do this for n(k) now and later for others.  It will require a different kind of test (a formalized version of what Ilkka is showing in his attached pdf) to judge significance for a large number of values simultaneously.

**Comment by kylanpaa** [comment]
I think it would be good to merge the n(k) tests with the diamond case as @jtkrogel suggests. 

@ye-luo In my tests the wave function files are 56Mb for 2x1x1 and 79Mb for 3x1x1.

**Comment by prckent** [comment]
OK, lets add the test based on the existing carbon diamond wavefunctions. Since this will take a little while to prepare, I propose to merge this PR and that we add the test in a later PR very shortly. Note that the set of estimators that are not supported by the CUDA code will have to have their own dedicated run.

**Pull request merged**
