### PR TITLE
Move the ownership of lattice to ParticleSetPool

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Before this change, the are many copies lattice objects (cell vectors and other meta data) around the code.
In a simulation ParticleSetPool owns the initial copy by parsing the input XML, then all the ParticleSet makes a copy.
There are other additional copies around.

This PR introduces SimulationCell class which contains a few cell related objects which were previously directly defined in ParticleSet. The SimulationCell owned by ParticleSetPool is now the single source of truth. All the ParticleSets own a const reference of SimulationCell which is checked in at the constructor of ParticleSet.

There are many benefits of having one SimulationCell and all the others are references. 
1. No need to track if the data is up-to-date. More friendly to future structural optimization
2. Lattice accessed via ParticleSet becomes const (read-only).

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Q. Did you verify that everything in sandbox is OK? We don't have complete CI coverage there.

Very happy to see this cleanup in the design. To be consistent with my comments on other PRs, even with these changes that affect so many files, we should have sufficient coverage in the CI.

**Comment by prckent** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
> Q. Did you verify that everything in sandbox is OK? We don't have complete CI coverage there.

Sanbox is fixed accordingly. I still would like to have one build on CI. So put up https://github.com/QMCPACK/qmcpack/issues/3743

**Pull request merged**
