### PR TITLE
Set recompute period in performance tests to once every QMC section

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Set the recompute periodic explicitly in the performance tests so that full & mixed precision builds do the same number of matrix inversions. (Mixed precision default is every block vs every 10 for full precision builds.) This changes addresses a couple of recent queries where the code has been profiled by users using the default settings.

Due to the few steps per block in the performance tests the existing settings result in a skew towards matrix inversion in profiles, performance analysis etc. In real/performance focused runs the number of steps per block would be larger than the e.g. 5 used for the DMC sections. A side effect is that some of the mixed precision performance tests will now show closer to real-world speedup.

Also added end of lines to a couple of the files for consistency.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- Yes

New mixed precision results should not be compared to old mixed precision results in terms of overall runtime.

## What systems has this change been tested on?

gcc14 mpi nightly configuration, sulfur.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
FYI. Just noticed that https://github.com/QMCPACK/qmcpack/pull/4109 didn't touch batched drivers and the default for FP is 0.

**Comment by prckent** [comment]
Will update this PR based on our discussion (one recompute per QMC section) and then check the defaults today.

Good catch on 4109 -- it might explain a few of the oddities we have seen in large runs. Not all of them though.

**Comment by prckent** [comment]
Also updated the NiO README

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
