### PR TITLE
Correctly handle NULL pivot in getr[f|i]Batched

### PR DESCRIPTION
**Pull request by jakurzak**
Right now, hipblas?getrfBatched() and hipblas?getriBatched() routines do not allow for passing NULL for the pivot vector.
I.e., right now, hipBLAS does not follow cuBLAS semantics.
The issue is being resolved, i.e., cuBLAS semantics are being implemented.
In the meantime, the problem is resolved in the CUDA2HIP wrappers by calling appropriate rocBLAS routines.

### CODE REVIEW

**Comment by prckent** [comment]
Start testing in-house

**Comment by prckent** [comment]
Thanks for this update Jakub. Clearly this is an improvement and good to hear that the HIP semantics are going to be worked on. As I recall this doesn't change the HIP pass/fail rate in our current test set?

**Comment by jakurzak** [comment]
It is not the greatest API design to switch functionality in a numerical routine by passing a nullptr instead of an array.
So, rocSOLVER separates the routines by names (rocsolver_sgetrf_batched vs rocsolver_sgetrf_npvt_batched).
However, HIP being a portability layer, it's better to closely follow cuBLAS semantics than to try to fix its problems.
So, hipBLAS will follow the cuBLAS nullptr semantics.
It will be a while, tough, before the fix makes it to a ROCm release, therefore the workaround in the CUDA2HIP wrappers.
No, unfortunately this fix does not change the pass/fail rate in the test set.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Confirmed that this builds on spock. I got the standard test failure pattern with a full precision build:
```
The following tests FAILED:
        403 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-kinetic (Failed)
        404 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-totenergy (Failed)
        405 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-eeenergy (Failed)
        407 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-potential (Failed)
        409 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-localecp (Failed)
        410 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-nonlocalecp (Failed)
        411 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-flux (Failed)
        413 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-kinetic (Failed)
        414 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy (Failed)
        415 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-eeenergy (Failed)
        417 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-potential (Failed)
        419 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-localecp (Failed)
        420 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-nonlocalecp (Failed)
        421 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-flux (Failed)
        423 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-kinetic (Failed)
        424 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-totenergy (Failed)
        425 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-eeenergy (Failed)
        427 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-potential (Failed)
        429 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-localecp (Failed)
        430 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-nonlocalecp (Failed)
        431 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-flux (Failed)
        433 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-kinetic (Failed)
        434 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-totenergy (Failed)
        435 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-eeenergy (Failed)
        437 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-potential (Failed)
        439 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-localecp (Failed)
        440 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-nonlocalecp (Failed)
        442 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-kinetic (Failed)
        443 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-totenergy (Failed)
        444 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-eeenergy (Failed)
        446 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-potential (Failed)
        448 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-localecp (Failed)
        449 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-nonlocalecp (Failed)
        521 - ntest_nexus_simulation_module (Failed)
Errors while running CTest
```

**Comment by prckent** [comment]
Good news update. I ran a full precision complex build, and just about everything passed on spock. This includes the delayed update tests that were failing previously. Nightlies show the same result https://cdash.qmcpack.org/CDash/viewTest.php?onlypassed&buildid=231286 . 

```
ctest -j 16 -L deterministic --output-on-failure
...
The following tests FAILED:
         25 - deterministic-unit_test_wavefunction_determinant (Failed)
         42 - converter_test_He_sto3g (Failed)
         44 - converter_test_Be_ccd (Failed)
         45 - converter_test_O_ext (Failed)
         47 - converter_test_HCNp (Failed)
         48 - converter_test_aldet1 (Failed)
         49 - converter_test_aldet5 (Failed)
         50 - converter_test_aldet6 (Failed)
         51 - converter_test_HDF5_FeCO6 (Failed)
         52 - converter_test_HDF5_Be_ccd (Failed)
         53 - converter_test_Bi_dirac (Failed)
         56 - converter_test_LiH_pyscf (Failed)
         57 - converter_test_LiH_pyscf_UHF (Failed)
         58 - converter_test_LiH_qp (Failed)
         59 - converter_test_C4_MSD_excited (Failed)
        540 - ntest_nexus_simulation_module (Failed)
Errors while running CTest
```

**Comment by prckent** [comment]
I made a determinant only version of the diamond 2x1x1 tests, to remove any considerations of the Jastrow factor from the remaining bug. The new test failed with the real build, supporting our hypothesis that something to do with the spline orbitals &/or determinant inverse and update is wrong.

**Comment by prckent** [comment]
The bug is in the initial inverse of the double precision matrices with the real builds for diamond 2x1x1. Either the code in and around cublas_inverse has a hard to spot plumbing error or the cublasDgetrfBatched-cublasDgetriBatched sequence is giving incorrect numbers (see cuda_inverse.cu) .  I have checked the input and resultant inverse matrices: in the complex case the HIP build gives almost identical results to the CUDA. However, for real builds, while the input matrices are accurate, the inverse is different. For diamond 2x1x1 deterministic tests, the matrices are 8x8 and the batch size is 1.

**Comment by jakurzak** [comment]
Thanks for narrowing it down @prckent. Let me hit the inverse routines with some more tests.

**Pull request merged**
