### PR TITLE
Nexus: Initialization of nblocks_exclude

### PR DESCRIPTION
**Pull request by mcbennet**
Setting initialization value to -1 (as it was before #1941),
given that #1956 resolved the underlying issue of the warning.

### CODE REVIEW

**Comment by markdewing** [comment]
I'm a little concerned about reverting this, given how it failed last time.
It looks like -1 is used as a sentinel to indicate that nblocks_exclude was not set from the command line(?).   But it's also a valid array index.
Would an initial value of 'None' be better?  That would at least trigger an error at the point of use if the variable was not set differently.

**Comment by jtkrogel** [comment]
I believe `nblocks_exclude` is set by calling `equlibration_length` in the event it is not set by the user.  See `DatAnalyzer.__init__` in `qmcpack_quantity_analyzers`.  If I recall correctly, this was the call that was originally problematic in #1946 

If desired, one could back this up by adding `assert(nbe>=0)` in a number of places where `nblocks_exclude` is accessed and used.

**Comment by mcbennet** [comment]
The initial value of `nblocks_exclude` was not the cause of the failure that was reported in #1941 .
By chance I originally changed its initial value to zero and saw the the warning was suppressed, which led me to believe that the variable wasn't being set correctly after initialization. However, after further digging, it has been found that the code behaves correctly (in the case of `nblocks_exclude=-1`) and attempts to set `nblocks_exclude` through `equilibration_length` -- however, within `equilibration_length` the code was failing when attempting to call `random.randint` due to a scoping issue.

**Comment by markdewing** [comment]
Maybe at least check nbe after it should be set in DatAnalyzer.__init__

**Comment by prckent** [comment]
I await further comment here before merging

**Comment by markdewing** [comment]
okay to test

**Comment by mcbennet** [comment]
In hindsight, it appears that the assertion after `DatAnalyzer.__init__` is not needed.
`equilibration_length` can not return a value that is non-negative.

**Comment by jtkrogel** [comment]
I think this is fine.  At this point we are speculating about the potential for buggy behavior.  I suggest we merge this PR and revisit if any such behavior is observed down the road.

**Comment by markdewing** [comment]
To be more general, the assertion could be moved to after the if-block.  That way it would catch the case that `equilibration` is `None`.   In the language of contracts, this is ensuring a postcondition about nblocks_exclude after `DatAnalyzer.__init__` executes.

**Pull request merged**
