### PR TITLE
Update multi

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update multi to the current working version https://gitlab.com/correaa/boost-multi/-/commit/03f140657c25698fd730fc56562a89bb4dd3fd75 

## What type(s) of changes does this code introduce?

- New feature (memory resource with default alignment)
- Refactoring (no functional changes, no api changes)
- Other (please describe): dependency

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 20.04

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please.

**Review by ye-luo — CHANGES_REQUESTED** [review]
Need to sort out a few things.
1. What is the current delta compared ot upstream version?
2. Can the git subtree handle the update? Which is the usual way we update multi.
3. Some build folders in the PR.

**Comment by correaa** [comment]
This was a problematic PR, it was replaced by another one https://github.com/QMCPACK/qmcpack/pull/2898
which I think it addresses you points. 
I didn't understand the question about the delta

**Comment by ye-luo** [comment]
> This was a problematic PR, it was replaced by another one #2898
> which I think it addresses you points.
> I didn't understand the question about the delta

Our subtree is not identical to upstream. I'm wondering how much difference is still left after your update.

**Pull request closed without merging**
