### PR TITLE
Capture ASAN LSAN failures in converter_test.py

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Detect at the Python level convert4qmc executable leaks and report them as errors. 
#3326 didn't address the issue completely, changes needed at how `converter_test.py` handles errors.

## What type(s) of changes does this code introduce?

- Bugfix (possible at the Python level)
- Refactoring
- Testing changes

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
Ubuntu 20.04, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
solves part of  #3249
`converter test should fail`

**Comment by williamfgc** [comment]
@ye-luo both tests on #3249 fail CI on sulfur with a similar error message as in #3325 . Let me see if the fix propagates, otherwise I'll dig deeper. I'm glad we are catching all these on CI.

**Comment by williamfgc** [comment]
@ye-luo I accidentally closed my local branch. I will mark this as WIP until we figure out those errors.

**Comment by ye-luo** [comment]
WIP should be good to park this PR as we are fixing #3249

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
