### PR TITLE
Complete the VGH routines of the Spline SPO SoA implementation

### PR DESCRIPTION
**Pull request by ye-luo**
This PR completes the VGH routines in
QMCWaveFunctions/BsplineFactory/Spline{C2C,C2R,R2R}Adoptor.h
The goal is to make it work correctly such that I can remove the AoS implementation.
This SoA spline implementation is always used regardless of AoS or SoA build.
Related to  #200 #420 #653

ToDo:
- [x] add VGH routine check in the unit test. @markdewing I didn't find any check on spline SPO val/grad/lap/hess. Do we have any?
- [x] Remove QMCWaveFunctions/Spline{C2X,R2R}Adoptor.h (AoS) which all fully reimplemented as SoA.
- [x] Since SoA implementation of spline has been used for more than half a year. Infrastructure to AoS can be cleaned up.
- [x] Check backflow calculation with SoA spline in AoS build. Update error handling. use_old_spline is still needed for the optimization. Routines for third derivatives are still not implemented.
- [x] check bccH_2x2x2 and bccH_3x3x3 vmc runs.

### CODE REVIEW

**Comment by markdewing** [comment]
There are V/G/H spline tests in spline2/tests.   There are no tests at the Spline*Adoptor level

**Comment by ye-luo** [comment]
I think it is necessary to check Spline*Adoptor level and make sure that phases are applied correctly.

**Comment by ye-luo** [comment]
This is ready for review and merging.

**Comment by prckent** [comment]
Q. How do the bands end up in a different order in the CUDA code?

**Comment by jtkrogel** [comment]
I assume this will have no impact on e.g. particle-hole creation bookkeeping in terms of einspline*.dat and xml input.

**Comment by ye-luo** [comment]
The particle-hole creation is sorted out before this.

**Comment by prckent** [comment]
Not important for this PR, but how hard would it be to get rid of this CPU vs GPU divergence?

**Comment by ye-luo** [comment]
The phase calculation CUDA kernel needs to adopt a consistent ordering.

**Comment by ye-luo** [comment]
Can we merge this?

**Pull request merged**
