### PR TITLE
Afqmc real unit tests

### PR DESCRIPTION
**Pull request by fdmalone**
I enabled unit testing for real afqmc builds and added molecular calculation input. Currently the long and short AFQMC tests are broken. I'll fix these in a subsequent PR and add long/short tests for the real build. Some old afqmc tests with real hamiltonians are a bit out dated so I temporarily disabled them.

AFQMC can be added to the real build CI tests, but should not be enabled if QMC_CUDA is also enabled.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
@fdmalone Will you reroute ENABLE_CUDA before the release. I don't feel good asking people to change flags from release to release.

**Comment by prckent** [comment]
Release candidate will be made tomorrow...

**Comment by fdmalone** [comment]
@ye-luo you mean swap QMC_CUDA for ENABLE_CUDA?

**Comment by ye-luo** [comment]
@fdmalone QMC_CUDA -> ENABLE_CUDA.

**Comment by fdmalone** [comment]
@ye-luo ok, I'll send out a separate PR for this in a minute. QMC_CUDA is still used in the main CMakeList, I'll extract the portions relevant to AFQMC and leave the rest as is?

**Comment by ye-luo** [comment]
QMC_CUDA is still in use and is intended only for the real-space CUDA code.
AFQMC related portion needs to be connected to ENABLE_CUDA.
The mixed precision handling of ENABLE_CUDA is different from QMC_CUDA. @mmorale3 probably knows what needs to be changed exactly.

**Pull request merged**
