### PR TITLE
Remove MuffinTin and NUBspline 

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Remove MuffinTin which was integrated in the obsolete EinsplineSet class.
And thus managed to remove all traces of NUBspline in the entire repo.
~20k lines removed including unused test code from einspline.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Start testing in-house

**Comment by prckent** [comment]
Thanks Ye! I think we have both been itching to remove this code. I think we should take a careful look at the coverage  in  the remaining files - some of the test codes you are  removing could potentially be used to get better coverage. They also could work as unit tests. (Written before the CI coverage has run)

**Comment by prckent** [comment]
@PDoakORNL Is there anything you would  like to keep?

**Comment by ye-luo** [comment]
> Thanks Ye! I think we have both been itching to remove this code. I think we should take a careful look at the coverage in the remaining files - some of the test codes you are removing could potentially be used to get better coverage. They also could work as unit tests. (Written before the CI coverage has run)

We should not use any evaluation functions from einspline. So a lot of test cores are irreverent. Right now we only keep the data structure and the value to spline coefficients construction routine, they should have been covered by `spline2/tests` or `einspline/tests`. So safe to remove.

**Comment by ye-luo** [comment]
The hole project metric increased.
`codecov/project Successful in 1s — 43.12% (+1.13%) compared to 59e65c8`

**Comment by prckent** [comment]
Stesting testing in-house

**Comment by prckent** [comment]
Start testing in-house

**Review by prckent — APPROVED** [review]

**Pull request merged**
