### PR TITLE
Fix missing header

### PR DESCRIPTION
**Pull request by correaa**
**Describe the bug**

Missing header `<cstdint>` in `qmcpack/src/Platforms/OMPTarget/ompBLAS.cpp`  for compilation with GCC 13.2

https://gitlab.com/correaa/boost-multi/-/jobs/5346169350#L1644

**To Reproduce**

With debian:testing and GCC 13.2:

```bash
$ cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DBUILD_AFQMC=1 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=Debug -DMPIEXEC_PREFLAGS="--allow-run-as-root;--bind-to;none" ..
$ make
```

**Expected behavior**

Compilation should work

**System:**

Docker image with debian:testing

### CODE REVIEW

**Comment by correaa** [comment]
@ye-luo  this time with qmcpack as the upstream repository

**Review by ye-luo — DISMISSED** [review]
Can only be merged after #4795

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by correaa** [comment]
fixed in my docker CI image https://gitlab.com/correaa/boost-multi/-/jobs/5366301331

**Pull request merged**
