### PR TITLE
Added section on simulationcell to the manual.

### PR DESCRIPTION
**Pull request by jptowns**
Added section detailing simulationcell to the manual, and updated qmcpack_manual.pdf.

### CODE REVIEW

**Comment by ye-luo** [comment]
A comment. Not clear if git can handle pdf better than svn. Generally pdf files are binary files and hard to construct delta and compare. Since git buffer everything locally, each manual update brings 1.7MB which is still not negligible.
As a user replying on released versions, using the manual consistent with the release is a must.
As a user/developer using the develop branch, building latex should not be a problem.
So I personally prefer the manual pdf file updated during release.
What do you think @prckent ?

**Comment by prckent** [comment]
@ye-luo Graham is going to comment on the PDF issue. It is certainly convenient to link to the most recent version in the repo. This is what we do currently.  You have a good point about the delta. If we rely on users to build the PDF we should take care not to use any exotic LaTeX packages.

@jptowns Not your problem! We'll merge this updated tex after taking a decision on the PDF. Keeping it in the Git was my original preference.

**Comment by grahamlopez** [comment]
@jptowns It looks like your develop branch is out of date. This can be fixed easily enough. Find me on slack and we'll get you set up

**Comment by jptowns** [comment]
Thanks @grahamlopez for helping me get my git repo pointed in the right direction!

**Comment by grahamlopez** [comment]
ugh. I made a mistake in the help, and the pdf file didn't get included. I'll fix this in another PR

**Pull request merged**
