### PR TITLE
Remove ENABLE_SOA and reduce SoA/AoS references

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Remove majority of AoS and SoA references. Cmake reports ENABLE_SOA unused after this patch.

Largely completes https://github.com/QMCPACK/qmcpack/issues/2506 . 

Also removes ORNL OIC script, which is a long gone machine.

## What type(s) of changes does this code introduce?

- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- No. Users of ENABLE_SOA=0 need to use QMCPACK v3.9.x

## What systems has this change been tested on?

nitrogen. llvmdev cpu build. Ran all 623 deterministic tests, saw no new warnings.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
@jtkrogel Please have an eye on the test_label python script.

**Comment by prckent** [comment]
The test_label script is the last place where there are many aos and soa references. More could be done, but I didn't touch beyond hardwiring the build type.

**Comment by ye-luo** [comment]
I meant @jtkrogel to review the change from @PDoakORNL . Sorry for the confusion.

**Review by jtkrogel — APPROVED** [review]
This LGTM, including the changes to the the labeling script.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this again

**Pull request merged**
