### PR TITLE
disable value_squared in h5

### PR DESCRIPTION
**Pull request by Paul-St-Young**
Addressing #504, do not print wrong values in `value_squared`. This will roughly cut the size of the stat.h5 file in half. User can code `<a^2>` as a separate column in the observable that calculates `<a>`.

This is NOT a full removal of `value_squared`. Other candidates to consider for removal:
1. `EstimatorManager::SquaredAverageCache` is mostly unused now. However the first entry for local energy is still used to calculate variance. 
2. nexus has some dependencies on `value_squared` in "qmcpack_quantity_analyzers.py". I do not have examples for most of the functions that use `value_squared`. @jtkrogel please take a look.
I did fix `ScalarsHDFAnalyzer.analyze_local`, because it is used to analyze optimized wavefunction.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Nexus will need other modifications.  A fair amount of the touches to value_squared are done in the context of twist averaging both collectables and scalar data.  I will download your QMCPACK modifications and make the required changes to Nexus.  Cases like this add priority to having more explicit tests for Nexus.

**Comment by prckent** [comment]
@jtkrogel Do you plan to make a separate PR in the next day or so?

**Comment by jtkrogel** [comment]
I can make a separate PR.  It should probably go in before this one to avoid breakage.

**Comment by prckent** [comment]
Before merging I would like to summarize the new situation and correct if needed:

- These changes disable the I/O of (incorrect) squared values
- value^2 are still tracked in memory via EstimatorManageBase.h/.cpp
- The internal weighting of value^2 is wrong/inconsistent and needs to be rethought/reimplemented.

(Will edit the above based on comments received)

**Comment by grahamlopez** [comment]
okay to test

**Comment by jtkrogel** [comment]
Working on companion PR for Nexus now.

**Comment by jtkrogel** [comment]
@Paul-St-Young please revert commits relating to Nexus in this PR.

**Comment by jtkrogel** [comment]
See companion PR #567

**Pull request merged**
