### PR TITLE
Nexus: Allow non spin-specific occupations in case of noncollinear

### PR DESCRIPTION
**Pull request by mcbennet**
## Proposed changes

Allow user to run with noncollin as true and use a non spin-specific occupation.

## What type(s) of changes does this code introduce?
Small change

- Other (please describe): Small change

### Does this introduce a breaking change?

- nxs-test is failing on rmg_input before and after my change?

## What systems has this change been tested on?
Summit

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by jtkrogel** [comment]
I recommend we track down the failing test first and then merge following a PR with the fix.

**Comment by jtkrogel** [comment]
Please open a new issue detailing the test failure.

**Comment by ye-luo** [comment]
#2958 was opened for tracking the test failure.

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
OK to test

**Pull request merged**
