### PR TITLE
Remove QMC_CUDA usage in AFQMC.

### PR DESCRIPTION
**Pull request by fdmalone**
Following #1496 I've replaced QMC_CUDA with ENABLE_CUDA in the AFQMC code. I've also removed AFQMC_MIXED_PRECISION in favour of MIXED_PRECISION used in mainline QMCPACK.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
@fdmalone any problem?

**Comment by fdmalone** [comment]
@ye-luo Should be good to go now.

**Comment by ye-luo** [comment]
This will be merged tomorrow since the nightlies need QMC_CUDA

**Pull request merged**
