### PR TITLE
Manual for PBC gaussians for gamma Kpoint

### LINKED ISSUE #720: Add manual documentation of periodic Gaussians and PySCF support
Describe how to use #706 including a worked example.

### PR DESCRIPTION
**Pull request by anbenali**
Manual for  Periodic Gaussian orbitals using Pyscf. 

close #720

### CODE REVIEW

**Comment by ye-luo** [comment]
The added contents need to be redistributed by leaving the pyscf part to the tools and moving LCAO and PBC gauassian to SPO section with proper pointers to the pyscf part. The high level description of QMC wavefunction and spline SPOs are redundant and just remove.

**Comment by prckent** [comment]
I am happy with a separate chapter for now - this is what I told @anbenali to submit, so I take the blame. We can consider what to do later once the implementation is refined. I removed the spline part which duplicated content and labels.

**Comment by ye-luo** [comment]
OK to merge now. Improvements needed later.

**Comment by prckent** [comment]
OK to test

**Pull request merged**
