### PR TITLE
Remove bug tag on ion-ion deterministic test for a graphene.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

As the related ion-ion bug had fixed (See #2137), tag on bug-deterministic-grapheneC needs to be rearranged. Two tests (z10 & z30) are now passing ewald check with larger LR_dim_cutoff, so the bug tag has removed and they moves to the deterministic test section.

This deterministic tests are now testing ion-ion for two different LR handler. z10 is for the default optimized break up and  z30 is for the Ewald3D handler. (See #2190)
Ion-ion references are generated in QMCPACK 3.9.1, and they're all passing with the intel 18 compiler on Intel Xeon.    

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Other (please describe): Adding test.

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

 Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1-ionion failed.

No deterministic tests can fail.

**Comment by Hyeondeok-Shin** [comment]
This test is still passing in my branch. I'm now working to find the reason.

**Comment by Hyeondeok-Shin** [comment]
It seems CPU dependency has increased as increasing LR_dim_cutoff. This table shows ion-ion references from the same gcc 8.2 compiler but different computing node.


LR_dim_cutoff | login node | compute node | Diff
-- | -- | -- | --
10 | 14.003313 | 14.00331301 | 1E-08
20 | 14.00447033 | 14.00411253 | 0.0003578
30 | 14.00274806 | 14.00274287 | 5.19E-06
40 | 14.00270343 | 14.00270671 | 3.28E-06

We can see that this values are from the same binary but different in large LR_cutoff. So tolerance needs to be increased to do deterministic test for the large cutoff.

**Comment by prckent** [comment]
Strange to only have 5 digits of accuracy for LR_dim_cutoff=20. Perhaps there is some incorrect usage of single precision maths?

**Comment by prckent** [comment]
Also strange to have different results of course! I think this points to a bug.

**Comment by Hyeondeok-Shin** [comment]
@prckent It could be. I'd like to keep this PR as the blocked until receiving additional comments from the other reviewers. I'm not sure whether increased tolerance makes sense or not.

**Comment by Hyeondeok-Shin** [comment]
As talked in #2472, deterministic test with opt-breakup for quasi 2D system is not available because of numerical instability. We do not know the exact reference of the deterministic test for opt-breakup for now.
So opt-breakup is replaced to the Ewald3D and test is passing with different CPUs now.

**Comment by Hyeondeok-Shin** [comment]
@prckent I think it is good to merge if CI passes.

**Comment by prckent** [comment]
No need to hold the PR (now approved, sorry for delay), but one missing determinstic test is that we check the code correctly gives an error when opt-breakup is used with bad parameters &/or at an unstable geometry. i.e. This test would have expect fail set , as per the check for real code with complex twists.

**Comment by prckent** [comment]
Test this please

**Pull request merged**
