### PR TITLE
WIP: add rebase job

### PR DESCRIPTION
**Pull request by walshmm**
## Proposed changes
In reference to issue: https://github.com/QMCPACK/qmcpack/issues/3862
This pr contains configuration for a job to automatically rebase a PR granted the PR body contains the phrase:

!-> Feel free to automatically rebase this PR. <-!

Things that still need to be added:
- ~~Check that the PR is approved~~
- Check that the PR passes all tests
- ~~Check that the PR is set to automerge~~

Questions I have:
- ~~How do people feel about the dependency on a third party github action? (https://github.com/cirrus-actions/rebase)~~
-- added to external codes
- Would this be effective against pr's made from a fork?  Does the fork owner need to grant perms for their branch to be auto rebased? 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Documentation changes (soon)
- Other (please describe): Github Actions Pipeline Changes

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- No. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Too big a potential attack surface for me to grant it access to my repo.  I wouldn't like use it but at minimum the action must be in a repo we control.

**Comment by walshmm** [comment]
> Too big a potential attack surface for me to grant it access to my repo. I can't see myself using it but at minimum the action must be in a repo we control.

The action code is a short .sh script with an MIT License, would I be able to just copy it to the external_codes directory?  Or is there a more appropriate place?

**Comment by PDoakORNL** [comment]
I would think yes copy it to external codes.

**Comment by walshmm** [comment]
Unsurprisingly the sh script has received a permission denied, what would I have to do to grant it perms?  I imagine someone other than me would have to review its contents first.

**Comment by walshmm** [comment]
Sorry for the absolute ton of commits, the only way to test is by pushing for github actions to pick up the jobs, but anyway.

This should be in a functional/ready to be used/tested state, I've been using this [pr](https://github.com/walshmm/qmcpack/pull/11) on my fork to perform appropriate tests.

The catch with this action is that it requires write permissions, and those are only granted to certain actions.  As a cautionary step, actions with these write permissions use code in the base branch to execute the job, meaning you will not be able to test *this* PR but will need to clone the branch and setup a pr similar to the one I linked above if you would like to test the functionality without merging it into develop.

A couple notes about setting up the test pr, you will need to add your clone to the list of base branches [here](https://github.com/walshmm/qmcpack/blob/github_actions_automatic_rebase/.github/workflows/ci-github-action-auto-rebase.yaml#L4-L10) and [here](https://github.com/walshmm/qmcpack/blob/github_actions_automatic_rebase/external_codes/github_actions/trigger-rebase-on-push.sh#L3) so that the job on your fork will pick them up.

Another note, since I've only tested this on my fork I'm uncertain of how branches from external repos/forks will interact with this script.

**Comment by prckent** [comment]
What currently happens if there are multiple PRs with review approval and set to automerge? Do we rebase them all (implying more CI load than truly needed)?

Do you only check required tests? It is not usual for one of the coverage tests to fail due to a slight but acceptable reduction in coverage.

How do you/should we handle the (re)triggering of our self-hosted CI? This currently needs "test this please" from an approved user.

**Comment by walshmm** [comment]
@prckent 
> What currently happens if there are multiple PRs with review approval and set to automerge? Do we rebase them all (implying more CI load than truly needed)?

Currently yes, they will all rebase and on push to develop/main they will rebase again.  I imagine we can mitigate this by checking all open pr's and only rebasing if its the oldest to be set to automerge. Though this would also require it to pass tests or be skipped for consideration else it would hold up passing pr's that came after.

> 
> Do you only check required tests? It is not usual for one of the coverage tests to fail due to a slight but acceptable reduction in coverage.

It does not currently take into account the status of tests, it simply will auto-rebase given automerge is enabled.  
I can experiment with the "needs" property on the jobs to see if we can have it run only with successful test runs(though these are in different events and a different yml file), otherwise may have to mess more with the github api.   This may also be hard to test on a fork,  i'll have to look into how to configure some other test jobs to show up.

Alternatively the user/script can disable autorebase upon failure(perhaps?). The trick here is mainly ensuring autorebase gets triggered before it automatically gets merged due to passing jobs, but not over-rebasing because its failed or incomplete with tests.

> 
> How do you/should we handle the (re)triggering of our self-hosted CI? This currently needs "test this please" from an approved user.

What do you mean?  Triggering it again after a rebase?  This may tie into the above work.  I imagine we will still want the explicit "test this please" initially from an auth'd user for security purposes, automatically rerunning these jobs for trusted pr owners *may* be fine but automatically for a new contributor may open an avenue for them to commit code after the initial review and get it running on our selfhosted runners without an additional review.  I dont think theres a way of getting around manual review/triggering in that case.


These changes would introduce a fair bit more complexity to the script.  Would it be possible to make these future enhancements?  The current script hasnt been used "in the wild" yet, so I'm not sure the magnitude of the impact its jobs will have(should be less than most other jobs, its just a pull and rebase, no building no tests), but additional complexity may make it more liable to fault/maintain.

**Comment by prckent** [comment]
> Would it be possible to make these future enhancements?

Yes. I was just asking questions. The last couple of days would have been good to have this "live" - numerous approved PRs in need of merging.

**Comment by walshmm** [comment]
Clean version of work here was merged

**Pull request closed without merging**
