### PR TITLE
Align two body Jastrow input behavior.

### PR DESCRIPTION
**Pull request by ye-luo**
For issue #282 #20 
1) uu, ud(du) : uu=dd, ud=du
2) uu : uu=dd=ud=du
3) ud(du) : only justified for 1 up + 1 down case, uu=dd=ud=du, uu/dd are not used in the calculation.
4) uu, ud(du), dd : uu, dd, ud=du

I may miss some useful cases.

checked uu, ud, dd case, optimization is correct.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
Will not merge before @jtkrogel has given OK

**Comment by grahamlopez** [comment]
@ye-luo I checked the logs and do not think these errors are due to a CI issue, but they come awfully close behind the changes that I made. If you think it is CI, let me know.

**Comment by prckent** [comment]
Thanks for the update. Will wait for @jtkrogel to comment.

**Comment by jtkrogel** [comment]
I will try to get to this later today; tomorrow latest.

**Comment by jtkrogel** [comment]
Having trouble compiling w/ C++11 requirements on old hardware; will revisit Monday.

**Comment by jtkrogel** [comment]
Wanted to test this in the context of the HEG, but it aborts with:
Fatal Error. Aborting at  LatticeParser::put 
   Mixed boundary is supported only when a lattice is specified!

qmcpack-3.1.1 runs fine, though this problem may have been introduced in an intermediate PR

I am switching to diamond to check the aspects specific to jastrows.

**Comment by prckent** [comment]
I thought the HEG was previously broken <v3.1.1, but apparently not. Another example of why we need integration tests to catch breakage. HEG example needed.

**Comment by jtkrogel** [comment]
Attaching brief HEG input: non-interacting (exact) 14 electron HEG.  Correct values: total energy = 1.743642 Ha, variance = 0.0 Ha^2.

[heg_input.zip](https://github.com/QMCPACK/qmcpack/files/1293205/heg_input.zip)

**Comment by jtkrogel** [comment]
Optimization is broken when I add  "dd" to J2.  If "dd" is added, then no channels get optimized.  Examples for an 8 atom cell of diamond at the gamma point are below (variance minimization):

uu and ud provided, starting from zero (works fine, as expected)
> opt_chk_uu_ud_zero/opt  series 0  -43.809766 +/- 0.023100   8.114731 +/- 0.093576   0.1852 
opt_chk_uu_ud_zero/opt  series 1  -45.081493 +/- 0.007395   1.146053 +/- 0.017251   0.0254 
opt_chk_uu_ud_zero/opt  series 2  -45.098565 +/- 0.007294   1.165662 +/- 0.021433   0.0258 
opt_chk_uu_ud_zero/opt  series 3  -45.103963 +/- 0.007382   1.102451 +/- 0.020122   0.0244 
opt_chk_uu_ud_zero/opt  series 4  -45.103722 +/- 0.011777   1.278885 +/- 0.122633   0.0284 
opt_chk_uu_ud_zero/opt  series 5  -45.100754 +/- 0.009056   1.161853 +/- 0.033183   0.0258 

uu, ud, dd provided, starting from zero (jastrow never updated during opt)
>opt_chk_uu_ud_dd_zero/opt  series 0  -43.834661 +/- 0.023206   8.170701 +/- 0.105085   0.1864 
opt_chk_uu_ud_dd_zero/opt  series 1  -43.824147 +/- 0.019127   8.337835 +/- 0.121052   0.1903 
opt_chk_uu_ud_dd_zero/opt  series 2  -43.817835 +/- 0.022784   8.352350 +/- 0.106175   0.1906 
opt_chk_uu_ud_dd_zero/opt  series 3  -43.815059 +/- 0.025500   8.295861 +/- 0.098922   0.1893 
opt_chk_uu_ud_dd_zero/opt  series 4  -43.797835 +/- 0.022669   8.263269 +/- 0.098202   0.1887 
opt_chk_uu_ud_dd_zero/opt  series 5  -43.815853 +/- 0.020414   8.230306 +/- 0.109035   0.1878 

uu, ud, dd provided with dd zero, uu set to ud from prior opt, ud set to uu from prior opt (jastrow never updated during opt)
>opt_chk_uu_ud_dd/opt  series 0  -44.889259 +/- 0.010117   2.272494 +/- 0.029804   0.0506 
opt_chk_uu_ud_dd/opt  series 1  -44.856943 +/- 0.010910   2.263470 +/- 0.028268   0.0505 
opt_chk_uu_ud_dd/opt  series 2  -44.866186 +/- 0.010074   2.287438 +/- 0.030888   0.0510 
opt_chk_uu_ud_dd/opt  series 3  -44.888234 +/- 0.010914   2.226399 +/- 0.032879   0.0496 
opt_chk_uu_ud_dd/opt  series 4  -44.860199 +/- 0.010032   2.241454 +/- 0.027115   0.0500 
opt_chk_uu_ud_dd/opt  series 5  -44.880152 +/- 0.011854   2.215179 +/- 0.029220   0.0494

**Comment by ye-luo** [comment]
@jtkrogel Could you provide the input section for all these three cases?

**Comment by jtkrogel** [comment]
Here are the pseudos, scf input, and qmcpack opt input for all the cases above.

[input_cases.zip](https://github.com/QMCPACK/qmcpack/files/1293562/input_cases.zip)

**Comment by ye-luo** [comment]
@jtkrogel I only checked the middle case. Could you check the three cases?

**Comment by ye-luo** [comment]
"Mixed boundary is supported only when a lattice is specified" This is fixed.
But I got the same error "ERROR   HEG Invalid Shell"as v3.1.1 real build. @jtkrogel did you use complex or real build?

**Comment by ye-luo** [comment]
HEG with the complex SoA build gives me 1.743642 Ha.

**Comment by jtkrogel** [comment]
HEG works fine in v3.0.0 and v3.1.1 in real and complex (just ran them).  You will have to remove "spo_dm" from the input file (included this on accident).

**Comment by ye-luo** [comment]
Checked. HEG is fine in current develop.

**Comment by jtkrogel** [comment]
I've rechecked the optimization cases and they look fine now.  I've also played with permutations of Jastrow factor components in the input file, etc., and these check out.

+1 for merge

**Pull request merged**
