### PR TITLE
[WIP] Dummy change to trigger CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Just a dummy change to trigger and test CI on self-hosted runners implemented in #3258 

## What type(s) of changes does this code introduce?

- New feature
- Testing changes (e.g. test new CI checks for GPU builds and tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Sulfur, must run on GitHub Actions CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Test this please

**Comment by williamfgc** [comment]
Hitting the first issue, actions must be enabled in the repo.

**Comment by williamfgc** [comment]
Test this please

**Comment by williamfgc** [comment]
Second issue: there is a test failure with the complex build (due to floating point error, I believe) that is not getting reported. It's a good thing as we are testing failed statutes on CI, but this needs to be fixed.

**Comment by prckent** [comment]
@williamfgc  Legacy CUDA looks stable on cdash, but clearly there are some problems lurking. Make an issue as needed.

**Comment by ye-luo** [comment]
Is it possible to introduce another phrase "Test in-house please"? Both  "Test in-house please" and "Test this please" should trigger the self-hosted CI.

There is a list of authorized contributor on jenkins side. Everyone on the list doesn't need the trigger phrase.
If I use "Test this please" the Jenkins side got repeated. So I'd like to have "Test in-house please" to trigger the self-hosted CI only.

**Comment by williamfgc** [comment]
@ye-luo thanks for providing feedback. Sure, I'll work on that. Also, should the check be `startWith("Test in-house please")`? Using `contains` can be sneaky. I'm planning another change as well since the failure reporting is showing as pending.

**Comment by ye-luo** [comment]
Use "Start testing in-house" for "startWith" should be good.

**Comment by prckent** [comment]
@ye-luo Why are you interested in the second phrase? The self-hosted CI is not a bottleneck, but there can be other motivations.

**Comment by ye-luo** [comment]
@prckent I updated my comments above.

**Comment by ye-luo** [comment]
github issues got picked up as an PR.
https://github.com/QMCPACK/qmcpack/actions/runs/984036686

**Comment by ye-luo** [comment]
`mkdir: cannot create directory ‘qmcpack-build’: File exists`
build folder folder should never be reused.

https://github.com/QMCPACK/qmcpack/runs/2946193509?check_suite_focus=true

**Comment by ye-luo** [comment]
I have difficulty to see CMake command line used in CI. `set -x` can be helpful in tests/test_automation/github-actions/ci/run_step.sh

**Comment by williamfgc** [comment]
@ye-luo thanks for the feedback

> actually it seems all comments get picked up.

Yes, GitHub Actions listens to all the `issue_comment` events. In PR #3266 those now would be marked as skipped (but reported) and can be easily filtered out in the Actions tab, logs are retained for 90 days. The PR check `Details` link should always be pointing at the actual check, the latter required some workaround as the `issue_comment` action always points at the `default` branch, not the PR branch (I guess those are GitHub Actions design decisions). 

> build folder folder should never be reused in CI.

Good catch. Agree, I'll work on checking for the directory existence when configuring. 

> set -x can be helpful in tests/test_automation/github-actions/ci/run_step.sh

Done in PR #3266. 

Once PR #3266 is merged I'd like to test the secrets-based check for authorized users and the magic words on this PR (we can always rebase). It might take another iteration to get this CI running to our expectations.

**Comment by godoywf** [comment]
Test this please

**Comment by williamfgc** [comment]
Verified that my evil twin @godoywf couldn't trigger the entire workflow, it's marked as "passed" in the [GitHub Actions logs](https://github.com/QMCPACK/qmcpack/runs/2954446909?check_suite_focus=true) since the workflow is actually doing its job in terms of authorization. It also doesn't trigger a status check from an unauthorized user on this PR as expected.

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by williamfgc** [comment]
Closing this dummy PR as it was only meant to test the workflow for self-hosting CI.

**Pull request closed without merging**
