### PR TITLE
Add msd tests

### PR DESCRIPTION
**Pull request by ye-luo**
C2 molecule. 20 sec on my desktop. VMC only

### CODE REVIEW

**Comment by grahamlopez** [comment]
OK to test

**Comment by ye-luo** [comment]
@prckent How much longer is good? 20mins(60x)?

**Comment by jtkrogel** [comment]
I've typically made the long test 10x longer than short, aiming for about 5min for long.

**Comment by prckent** [comment]
After discussing with @ye-luo , we'll merge now and add the long test next week.

**Comment by jtkrogel** [comment]
Possible to add a reasonable length DMC test as well?

**Comment by ye-luo** [comment]
@jtkrogel Yes. That is the next step.

**Comment by prckent** [comment]
What would a DMC run test that the VMC test does not? Why is there a concern that a DMC run is needed? i.e. In what way is a VMC test not sufficient?

**Comment by ye-luo** [comment]
VMC with Drift is largely identical to DMC. I think VMC is sufficient. We need to leave DMC tests on lighter test cases.

**Pull request merged**
