### PR TITLE
Nexus: enable radial density analysis

### PR DESCRIPTION
**Pull request by jtkrogel**
This PR contains tool to support analysis of the momentum distribution.  Just basic reading/plotting capabilities so far.  More to follow.

### CODE REVIEW

**Comment by jtkrogel** [comment]
This should be merged now.  It is already used in production analysis for the ABOx project.

Moreover some of the symmetry related updates are needed for new development related to RMG support.

**Comment by ye-luo** [comment]
Do we have documentation or example for users?

**Comment by prckent** [comment]
@ye-luo Good question. We can't keep adding features to Nexus with no docs or mention.

**Comment by prckent** [comment]
I made https://github.com/QMCPACK/qmcpack/issues/2716 for docs discussion.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
