### PR TITLE
Update references of deterministic test for CUDA mixed precision for the nitrogen

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Update reference of deterministic test for CUDA mixed precision build by adding sampled outputs from the nitrogen.  

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Hyeondeok - 

Thanks.

1. Did you create this reference data by looking at the cdash output? Both for the reference value and error bar? 
2. Did you notice any major discrepancies or large sources of variability? I am always nervous about potentially hiding a problem with these updates, although this is one reason why we have the longer statistical tests.

**Comment by Hyeondeok-Shin** [comment]
@prckent 
 1. Yes, these data from the output at the cdash 
  2. I check all outputs from mixed precision build in nitrogen, and these outputs are close enough to old reference with ~ 1e-5 tolerance. I'm not sure about the longer statistical test, but tolerance in nitrogen seems good enough as the mixed precision.

**Comment by prckent** [comment]
Running these I still got some failures. Rerunning now and will post results. Perhaps the CUDA kernels are "too unreliable".

**Comment by prckent** [comment]
Example run 1:
```
1725:--- START build_gcccuda Thu Apr 16 12:30:21 EDT 2020
4905:86% tests passed, 30 tests failed out of 210
4918:    26 - deterministic-unit_test_hamiltonian (Failed)
4919:   363 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-totenergy (Failed)
4920:   366 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-potential (Failed)
4921:   368 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1-localecp (Failed)
4922:   401 - deterministic-diamondC_1x1x1_pp-dmc_sdj-1-1-localecp (Failed)
4923:   406 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-totenergy (Failed)
4924:   409 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-potential (Failed)
4925:   411 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-localecp (Failed)
4926:   425 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-totenergy (Failed)
4927:   428 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-potential (Failed)
4928:   430 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-localecp (Failed)
4929:   453 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-1-totenergy (Failed)
4930:   456 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-1-potential (Failed)
4931:   458 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-1-localecp (Failed)
4932:   462 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-totenergy (Failed)
4933:   465 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-potential (Failed)
4934:   467 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-localecp (Failed)
4935:   471 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-3-totenergy (Failed)
4936:   474 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-3-potential (Failed)
4937:   476 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-3-localecp (Failed)
4938:   565 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-localecp (Failed)
4939:   570 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy (Failed)
4940:   573 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-potential (Failed)
4941:   575 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-localecp (Failed)
4942:   580 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-totenergy (Failed)
4943:   583 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-potential (Failed)
4944:   585 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-localecp (Failed)
4945:   599 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-totenergy (Failed)
4946:   602 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-potential (Failed)
4947:   604 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-localecp (Failed)
```

**Comment by prckent** [comment]
Example run 2:
```
1725:--- START build_gcccuda Thu Apr 16 13:39:42 EDT 2020
3458:89% tests passed, 23 tests failed out of 210
3471:   374 - deterministic-diamondC_1x1x1_pp-vmc_sdj_excited-1-1-totenergy (Failed)
3472:   377 - deterministic-diamondC_1x1x1_pp-vmc_sdj_excited-1-1-potential (Failed)
3473:   379 - deterministic-diamondC_1x1x1_pp-vmc_sdj_excited-1-1-localecp (Failed)
3474:   401 - deterministic-diamondC_1x1x1_pp-dmc_sdj-1-1-localecp (Failed)
3475:   406 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-totenergy (Failed)
3476:   409 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-potential (Failed)
3477:   411 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1-localecp (Failed)
3478:   416 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-totenergy (Failed)
3479:   419 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-potential (Failed)
3480:   421 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-localecp (Failed)
3481:   425 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-totenergy (Failed)
3482:   428 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-potential (Failed)
3483:   430 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1-2-localecp (Failed)
3484:   462 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-totenergy (Failed)
3485:   465 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-potential (Failed)
3486:   467 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1-2-localecp (Failed)
3487:   570 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy (Failed)
3488:   575 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-localecp (Failed)
3489:   580 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-totenergy (Failed)
3490:   583 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-potential (Failed)
3491:   585 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-localecp (Failed)
3492:   593 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-potential (Failed)
3493:   595 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-localecp (Failed)
```

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
I suggest we take these updates and keep an eye on the results.

There is clearly still some variability. The new reference values will hopefully increase the reliability. 

While unproven speculation, I think that we are seeing the variability in one or more of the CUDA legacy kernels here, i.e. the long undiagnosed minor bug/problem with them.

**Pull request merged**
