### PR TITLE
Fix commented out code in AFQMC.

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Fixes a bug I introduced during HIP merge where I commented out some code.

@ye-luo Somehow this passed the CI which is a little troubling because the unit tests should have failed? 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

lassen

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
So how did this get past the CI? 

@fdmalone What is the exact test that should have broken?

**Comment by fdmalone** [comment]
deterministic-unit_test_afqmc_numerics and deterministic-unit_test_afqmc_slaterdeterminantoperations

**Comment by mmorale3** [comment]
they fail when I run ctest in LLNL

**Comment by mmorale3** [comment]
not sure how the CI passed

**Comment by fdmalone** [comment]
Are the unit tests being run under the CI? From https://jenkins-ci.cels.anl.gov/job/QMCPACK-CI-GNU-CUDA/label=skylake-only,type=Complex-enable-CUDA/275/console I can't see any ctest output. The intle failure error says something about a license being unavailable (icpc: error #10052: could not checkout FLEXlm license)

**Comment by ye-luo** [comment]
These CI nodes have no GPU. We only compile the code but don't run anything.

**Comment by ye-luo** [comment]
Test this please

**Comment by fdmalone** [comment]
I had a false sense of security. Will unit test before PR in future.

**Pull request merged**
