### PR TITLE
Increase statistical test tolerances

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Increase many short statistical tests so they pass more reliably. Based on iterating builds on nitrogen2 with gcc nompi configuration.

The orbital optimization and multideterminant tests have suspicious failures and are not touched here. Results from longer runs will need to be carefully checked.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen2, gcc no mpi openblas nightly config.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Added proposed fix for https://github.com/QMCPACK/qmcpack/issues/4345

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Interesting if this reoccurs:

GCC9-MPI-CUDA-AFQMC-Real
```
The following tests FAILED:
	877 - deterministic-ensemble_blocks_LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-3-1 (SEGFAULT)
Error: Process completed with exit code 8.
```

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
