### PR TITLE
Update multi array library

### PR DESCRIPTION
**Pull request by fdmalone**
Updates boost multi array library and AFQMC routines accordingly.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by mmorale3** [comment]
This will not go through with gcc5.3, it needs gcc6.0.
I'm working with Alfredo on a fix, but it is a problem right now.

**Comment by ye-luo** [comment]
@mmorale3 Should we mark this PR WIP and wait?

**Comment by mmorale3** [comment]
Yes

**Pull request closed without merging**
