### PR TITLE
fix afqmc walkerset pointer traits

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Fixes pointer traits that ultimately make the code incompatible with Multi constness.

## What type(s) of changes does this code introduce?

- Bugfix
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — DISMISSED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@correaa CUDA CI builds were failing.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
I'm not sure what the problem is with coverage; it seems to be a problem with codecov.io.

**Comment by ye-luo** [comment]
> I'm not sure what the problem is with coverage; it seems to be a problem with codecov.io.

That is not an issue. Are you able to verify the ROCM build on your side? All the past builds failed since you updated multi.

**Comment by correaa** [comment]
To this extent, yes, https://gitlab.com/correaa/boost-multi/-/jobs/5725358844
(this test was failing on my side, too, until I corrected some misplaced HIP macros in Multi)

**Comment by ye-luo** [comment]
> To this extent, yes, https://gitlab.com/correaa/boost-multi/-/jobs/5725358844 (this test was failing on my side, too, until I corrected some misplaced HIP macros in Multi)

OK. I will hold triggering CI on AMD until you send a green light.

**Comment by correaa** [comment]
I am confident it will pass now; the ROCm code is only included when a uniquely named macro (MULTI_*) is defined.

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
well, I was wrong, sorry. This will be more work than I assumed.

**Comment by correaa** [comment]
Can you test again, please? I have a hard time reproducing a ROCm environment and I am more confident now that it is fixed.

**Comment by prckent** [comment]
Test this please

**Comment by correaa** [comment]
now it compiles. 

any idea of what can be special about the two failing tests with V100 and offload?

**Comment by ye-luo** [comment]
> now it compiles.
> 
> any idea of what can be special about the two failing tests with V100 and offload?

The failing code paths only exist in the complex builds.

**Comment by correaa** [comment]
yes. one semantic difference between complex and real is that complex numbers are (unfortunately) initialized to zero and perhaps that is the operation that is failing (due to a bug or something else).

**Comment by correaa** [comment]
good idea.

I think it will be fail initially due to other changes, but it will be good to start from there. 

Please be patient, I was able to set up an environment with offloading yet;
trigger the test when you can.

**Pull request closed without merging**
