### PR TITLE
Fix TMDLA in batched DMC driver runs

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix a bug reported by Yasmine@UCL.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora

## Checklist
- Yes/No. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
What are your thoughts for a small test that would catch/reproduce this error? A new LCAO Ca atom test or is there an existing test you think we could modify?

**Review by prckent — APPROVED** [review]
Thanks for chasing this down Ye.

**Comment by ye-luo** [comment]
> What are your thoughts for a small test that would catch/reproduce this error? A new LCAO Ca atom test or is there an existing test you think we could modify?

I'd like to first try to adjust the existing Na based NLPP unit test.

**Pull request merged**
