### PR TITLE
Add documentation and test for eigensolver option.

### PR DESCRIPTION
**Pull request by markdewing**
Add a short test and documentation for the `eigensolver` option added in #4990 .

The existing tests cover the default `inverse` option.  The added test is a copy of optm-batch-OneShiftOnly-general.xml, but using the `general` eigensolver.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)
- Documentation or build script changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
Do we have a deterministic or unit test for these?

It would be good to test the code path in CI and at least check we handle the option correctly.

**Comment by markdewing** [comment]
Do you want a deterministic test to check that the right code path is being followed?
A unit test for that would be difficult, but a deterministic test that checks for the right strings in the output could work.

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
`Fatal Error. Aborting at QMCDriverFactory::createQMCDriver : method="linear_batch" is not safe with CPU mixed precision. Please use full precision build instead.` Hmm. Wasn't aware of this one. CMakeLists just needs protecting.

Coverage uploads failed due to rate limits.

**Comment by markdewing** [comment]
The other option is to add "not safe with CPU mixed precision" to the passing regular expression list.  Do you have a preference between this and guarding the CMake?

**Comment by prckent** [comment]
The latter one (WILL FAIL) seems simplest and also checks that the code bails as expected.

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Pull request merged**
