### PR TITLE
Fix LCAO mixed precision code bugs

### PR DESCRIPTION
**Pull request by ye-luo**

### CODE REVIEW

**Comment by prckent** [comment]
@markdewing I would be happier with the three fixes here split up into distinct PRs. What do you think?

1. The water energy update
2. The mixed precision fixes
3. The buggy Intel compiler workaround. @ye-luo Do you have a reproducer for this bug? We could just catch the bad compiler version in the Cmake and print a "don't use this!". Is it a problem that occurs at a specific level of optimization or a problem that persists regardless of setting?

**Comment by ye-luo** [comment]
@prckent I can reproduce this bug easily on my desktop. The effect of this bug is fatal, a bunch of NaN in the calculation and then the code stops. It is not a numerical issue but seems like wrong code generation. C++11 off is the key to hit the bug. Intel 15 & 16 works well but not 17 u1.

No one really read the cmake output unless it stops. But I don't want to stop using the most recent version of compilers. Intel 17 initial is even worse.

**Comment by prckent** [comment]
OK, seems reasonable to put the fix in this way. Are we 200% sure that this is a compiler bug and not a more subtle problem with swap_rows?

**Comment by ye-luo** [comment]
This is the only place using swap_rows and swap_cols is never used. It can be either a compiler bug or bad c++ code. However, every other compiler is fine with this code but intel no c++11 case. For the moment, I consider it a compiler bug but I will hand it to Intel folks to look at it and it will take way longer time. The routine is very very simple only a few lines to replace it and nothing looks suspicious to me but Intel folks may have better clue.

**Comment by markdewing** [comment]
@prckent @ye-luo All the logically separate changes are in separate commits, so that is good.   However, it does seem like unrelated changes in single PR (well, maybe they all affect the same test case?).    This does make it harder to review - looking at the 'Files Changed' for the review shows all the changes from all the commits.  Looking at individual commits made it clearer which file changes were related.   In the future this change would be better as separate PR's.

**Comment by jtkrogel** [comment]
For the H2O reference, does the old version used to generate the reference agree with the current version when run at a higher precision?

**Comment by grahamlopez** [comment]
RE: Mark's and Paul's comments about logically separate fixes in separate PRs: another advantage in addition to easier (better) code reviews, if a change needs to be reverted in the future, we can unmerge a single PR without also having to undo the other changes.

**Comment by ye-luo** [comment]
@jtkrogel The value is higher than it should be since the day it was introduced. See the history.
screenshot from 2017-01-20 09 05 57

**Comment by jtkrogel** [comment]
OK.  It would be nice if there was an easy way to pull all the test output for each test, to make plots vs. time, etc.

**Comment by ye-luo** [comment]
If we can get the test result value hooked with cdash, we might see the energy change over time instead of just fail/pass and execution time.

**Comment by prckent** [comment]
OK note to @ye-luo : please split distinct contributions and fixes into separate PRs in future. This helps the review process and helps traceability (e.g. the water fix is a trivial "yes" and could be done quickly).

**Pull request merged**
