### PR TITLE
Push cuda to arch namespace

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Moves qmc_cuda namespace to generic arch namespace. This a step towards portability. Requires #2409 to be merged first.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

lassen (~summit)

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by mmorale3** [comment]
These look like mixed changes, but they were all pushed in the last PR.
Because I didn't know how long the release was going to hold things up, 
I had to continue working on top of the branch that was waiting to be PRed.
There are only 2 new commits on top of the already merged branch.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
#2409 has been merged.

**Comment by fdmalone** [comment]
Sorry, a commit got left out in the original pr.

**Pull request merged**
