### PR TITLE
Cleanup license file

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Remove the historical and confusing disclaimers about code covered by licenses other than the main UIUC/NCSA one. We have gone through the repository and removed or replaced historical sources thought to be covered by other licenses.

This PR does not attempt to update the main license. However I'll note that the developed by text  is certainly not current and the URL given is no longer valid. We'll have to consult about how to amend it in future. 

Added after initial PR: based on discussion below, removed the development history text from the NEXUS license file as well.

## What type(s) of changes does this code introduce?

- Bugfix
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

None. Docs only.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Comment by jtkrogel** [comment]
Similar cleanup warranted for Nexus license file?

**Comment by prckent** [comment]
@jtkrogel Your call - trimming the "development started at UIUC" text would probably help automatic license recognition, but the issues with references to GPL thankfully don't apply in your case.

**Comment by jtkrogel** [comment]
It is fine with me.  Comments about history do not need to be mixed with license content.

**Comment by prckent** [comment]
OK, I'll push an edit here.

**Review by jtkrogel — APPROVED** [review]
Thanks

**Pull request merged**
