### PR TITLE
output long-range Jastrow coefficients

### PR DESCRIPTION
**Pull request by Paul-St-Young**
Tangentially related to #1640, this PR outputs coefficients in `kSpaceJastrow` to file.
Functions designed to mimic the way `RadialJastrowBuilder` outputs "J1.*.dat" and "J2.*.dat".

### CODE REVIEW

**Comment by ye-luo** [comment]
Could you make a unit test for `kSpaceJastrow`? Although the RPA one uses it inside. A separate unit test is better.

More of just a question: Does the one and two body share data or they are quite separate? I have a feeling that it is better to have them in separate classes.

**Comment by Paul-St-Young** [comment]
OK, I will think of a unit test.

Regarding your question, my impression is that the one- and two-body parts do not share data. I am not sure why they are not separated classes, although I did not make this class. @rcclay probably knows this better.

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
