### PR TITLE
Remove pseudopotentials directory

### LINKED ISSUE #39: Vet/fix pseudopotential database
Reported by: jtkrogel

Current (BFD) pseudopotentials were included using files converted from 2011 (perhaps as early as 2009).  These converted PPs are untested.

I recently tried the C UPF PP from the database but could not converge graphene in Quantum Espresso.  I had converted the PP myself at some other point with ppconvert and it works fine (seemingly).

The pseudopotentials in the database need to be tested.  At the very least they should be regenerated with the current version of ppconvert and searched for differences.

### PR DESCRIPTION
**Pull request by jtkrogel**
The pseudopotentials directory contains misleading/poor projectors for some potentials, is not comprehensive, and is too large (MB-wise) to keep in the main repo.

Beyond this, the intended home for pseudopotentials is now [www.pseudopotentiallibrary.org](url).

If anyone is aware of a reason we should keep these here, please comment now.

Closes #39

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by jtkrogel** [comment]
I searched for these and I do not see any.  So far the policy for tests has been to include all the files you need locally (at least somewhere within tests).  We appear to have succeeded at this.

**Comment by ye-luo** [comment]
The PP reading tests in the Hamiltonian unit test make the CI fail.

**Comment by jtkrogel** [comment]
Correct.  This is deep in src rather than tests.  I will see if it can be rerouted to another existing file.

**Comment by jtkrogel** [comment]
Should be fixed now.  Unit tests now pass on my local machine.

**Comment by ye-luo** [comment]
I found the following.
```
$ find -name "*.xml" -exec ls -l {} \; | grep ^l |grep pseudopotentials
lrwxrwxrwx 1 yeluo yeluo 39 Apr  8 22:05 ./molecules/FeCO6_b3lyp_pyscf/C.BFD.xml -> ../../../pseudopotentials/BFD/C.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 39 Apr  8 22:05 ./molecules/FeCO6_b3lyp_pyscf/O.BFD.xml -> ../../../pseudopotentials/BFD/O.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 40 Apr  8 22:05 ./molecules/FeCO6_b3lyp_pyscf/Fe.BFD.xml -> ../../../pseudopotentials/BFD/Fe.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 39 Apr  8 22:05 ./molecules/C2_pp/C.BFD.xml -> ../../../pseudopotentials/BFD/C.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 39 Apr  8 22:05 ./molecules/FeCO6_b3lyp_gms/C.BFD.xml -> ../../../pseudopotentials/BFD/C.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 39 Apr  8 22:05 ./molecules/FeCO6_b3lyp_gms/O.BFD.xml -> ../../../pseudopotentials/BFD/O.BFD.xml
lrwxrwxrwx 1 yeluo yeluo 40 Apr  8 22:05 ./molecules/FeCO6_b3lyp_gms/Fe.BFD.xml -> ../../../pseudopotentials/BFD/Fe.BFD.xml
```
We probably need a pseudopotentials folder under tests in order not to have them randomly.

**Comment by prckent** [comment]
I agree to put a pseudopotentials_for_tests folder under tests.

**Comment by jtkrogel** [comment]
How's that?

**Comment by ye-luo** [comment]
It seems very good. I'm running all the short tests now. If nothing is caught, I will approve and merge the PR.

**Comment by ye-luo** [comment]
I saw the following error.
```
Adding Nexus example tests
Error copying directory from "/sandbox/opt/cleanup/jtkrogel/nexus/examples/qmcpack/pseudopotentials" to "/sandbox/opt/cleanup/jtkrogel/build_real/nexus/examples/qmcpack/pseudopotentials".
-- Configuring done
```
/sandbox/opt/cleanup/jtkrogel is my local folder cloning your branch.

**Comment by jtkrogel** [comment]
Some pseudopotentials in Nexus examples were apparently symlinked to the pseudopotentials folder.  I copied the appropriate files in.  

Everything in Nexus should work independently of qmcpack, i.e. only links within nexus and below are allowed.

**Pull request merged**
