### PR TITLE
test PR, add a space to nexus readme

### PR DESCRIPTION
**Pull request by jtkrogel**

### CODE REVIEW

**Comment by prckent** [comment]
Good test commit and PR.

**Comment by prckent** [comment]
For "real" developments, please try to use an informatively named branch.

**Comment by jtkrogel** [comment]
My "dev" branch is intended for one-liner updates and so forth.  Seems a bit heavy handed to create a new branch for each change of this nature.

Longer term purposeful feature/topic branches will be created and used for "macro" development.

**Comment by grahamlopez** [comment]
We might need to test how this works with GitHub. If you update a branch that has a PR against it, it may just resubmit the same PR, instead of allowing a new one

**Comment by jtkrogel** [comment]
OK, I will try making another small change on jtkrogel:dev and see how it goes with another PR.

**Pull request merged**
