### PR TITLE
Fix the traditional multi determinant implementation

### PR DESCRIPTION
**Pull request by ye-luo**
The slow implementation is broken by the changes over the years.
This PR introduces tests and fixed the code.
Also myG/L and myG/L_temp are removed from DiracDeterminantBase because DiracDeterminantBase only operates on one spin while G/L are over all the electrons. They are in the wrong place.
Change error handling std::cerr + abort() to throw std::runtime_error. More friendly to debuggers.

### CODE REVIEW

**Comment by jtkrogel** [comment]
This may merit wider discussion in a GitHub issue.  I am aware that C++ exceptions were intentionally avoided in the past, but I am fuzzy on the logic/details.  Could be fine either way in general, but a discussion is worthwhile.

Probably does not need to affect the limited use in this PR for now.

**Comment by markdewing** [comment]
With C++ exceptions - how do they work within MPI?   Does an unhandled exception terminate the program, or cause it to hang?

**Comment by markdewing** [comment]
On my laptop, OpenMPI and MPICH both terminate the program with an unhandled C++ exception.

**Comment by ye-luo** [comment]
Please comment on #125.

**Comment by ye-luo** [comment]
@prckent in those error messages, the function helps very little since the error is from heavily templated areas. Printing function names doesn't add value. Grepping the full error message is anyway needed.

**Pull request merged**
