### PR TITLE
Update multi

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 23.10

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
> I see an error in the CI of a missing file. Please rerun if this is a false positive. Otherwise, it can be merged.

That was a glitch in the CI system.

**Comment by correaa** [comment]
Do you mean that is related to the changes (update multi) in this PR?

**Comment by ye-luo** [comment]
> Do you mean that is related to the changes (update multi) in this PR?

unrelated to your change.

**Comment by prckent** [comment]
If CI GPU jobs fail between Saturday evening-Monday evening, it is often because the longer weekend (vs nightly) tests are running. The nightlies we run on weeknights tie up the GPUs for much less time, so this problem is much less likely to occur. A rerun of the tests just now passed.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
The gcov failures were failures on upload to codecov, something we see from time to time.

**Pull request merged**
