### PR TITLE
Remove nonlocalpp and use_nonlocalpp_deriv in docs and tests

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
doc/tests update following #4194

## What type(s) of changes does this code introduce?
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by lshulen** [comment]
I like the changes, but find the wording in methods.rst a bit awkward. 

``nonlocalpp`` and ``use_nonlocalpp_deriv`` are obselete options and will be treated as invalid options in future releases.
    Please remove from the input files. The current code behaves as if given both ``yes`` in old releases.

I would suggest a change along the lines of:  "nonlocalpp" and "use_nonlocalpp_deriv" are obsolete and will be treated as invalid options (will trigger application abort?) in future releases.  From this point forward, the code behaves as prior versions of qmcpack did when both were set to true.

**Comment by ye-luo** [comment]
> I like the changes, but find the wording in methods.rst a bit awkward.
> 
> `nonlocalpp` and `use_nonlocalpp_deriv` are obselete options and will be treated as invalid options in future releases. Please remove from the input files. The current code behaves as if given both `yes` in old releases.
> 
> I would suggest a change along the lines of: "nonlocalpp" and "use_nonlocalpp_deriv" are obsolete and will be treated as invalid options (will trigger application abort?) in future releases. From this point forward, the code behaves as prior versions of qmcpack did when both were set to true.

Thank you @lshulen I have updated the text.

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
