### PR TITLE
Require MPI communicator to be passed to MPIObjectBase

### PR DESCRIPTION
**Pull request by ye-luo**
@anbenali paid the price of issue #859 and was not able to run ensemble jobs.

In this PR, MPIObjectBase is no more allowed to grab the WORLD communicator by default and the communicator pointer must be passed through the class hierarchy. The unsafe initCommunicator is also no more allowed (removed) and ReportLevel is also removed. We have too many similar printing controls like ReportLevel.

One set of changes is in real-space QMC drivers. The second set of changes is in all the builder classes derived from SPOSetBuilder. The communicator must be passed through constructors.

Although I don't like the use of pointer in MPIObjectBase, I cannot do large change at the moment since MPIObjectBase is used in both real-space QMC and AFQMC.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Shouldn't this PR follow resolution of #1103?

**Comment by prckent** [comment]
We should get in the habit of committing the tests first or including them in the PR.

**Comment by ye-luo** [comment]
@prckent Constructing such test is non-trivial. The checking mechanism in our testing system doesn't handle ensemble run. However, this fix is immediately needed for runs.

**Comment by jtkrogel** [comment]
Actually, I think this is easily done in the testing system.  Just make a diamond test via ensemble with 4 identical input files listed in the ensemble input.

It should pass the same reference check as the original 16x1 or 4x4 test.  All that is needed is to make check_scalars.py support ensemble averaging like qmca does.

**Comment by ye-luo** [comment]
@jtkrogel This is not a strong test. The old code can also pass this. I need to mix Gaussian and spline and check results individually.

**Comment by jtkrogel** [comment]
I'm actually more concerned about the original case, i.e. that innovations to mpi could crash our current way of doing it, so I would favor including a test first (separate PR) that the current code passes, and then use it to confirm nothing has changed with this PR.

**Comment by ye-luo** [comment]
Let me explain the whole story.
MPIObjectBase constructor has a mechanism adding a default communicator OHMMS::Controller which is WORLD. The old code SPOSetBuilder class has MPIObjectBase as a base class without giving the communicator. When LCAOrbitalBuilder(derived from SPOSetBuilder) tries to build up the basisset and orbitals for different molecules in an ensemble run. The MPI calls via WORLD from the calculation of different molecules can not match due to different basisset and orbitals. Not only the size of message but also the number of calls may differ. Some metadata can be in wrong size and trigger segmentation fault.

The real situation is even worse. When I run an ensemble job mixing Gaussian and Spline. Both Spline and Gaussian hangs. This indicates even in the spline WF part, WORLD is used in some places. Our spline ensemble job runs in the past because WF are similar for each calculation and the MPI calls match by luck.

After the fix is applied, the communicator must be explicitly managed. There is no change to the non-ensemble job. For an ensemble run, each sub run must follow the communicator passed in QMCMain.

**Comment by jtkrogel** [comment]
Definitely sounds shady and worth fixing.

**Comment by ye-luo** [comment]
ReportLevel was an internal state (rank 0 has 1 and 0 otherwise).
SetReportLevel is to set ReportLevel into a different value. I didn't see a case using a different value but just passing the value in.
ReportLevel is used to tell some functions to print or not.
I don't see a value of this rarely used state machine.

Putting rank()==0 is simple and more understandable.

**Comment by prckent** [comment]
Good to remove internal state.

**Pull request merged**
