### PR TITLE
[Do not merge] Add offload in rocm CI

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
I got a unit test [failure](https://cdash.qmcpack.org/testSummary.php?project=1&name=deterministic-unit_test_wavefunction_trialwf&date=2024-09-26) on my RadeonVII but it works fine on MI50.

Our CI machine is the only one I can find with the same GPU. So cross check if it is specific to this GPU or just my setting.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation or build script changes
- Other (please describe):

### Does this introduce a breaking change?

- Yes
- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
This will need to be retriggered after I have rebooted nitrogen to fix ROCm driver

**Comment by prckent** [comment]
Driver updated on nitrogen

**Comment by ye-luo** [comment]
So the same failure reproduce on Nitrogen.

**Pull request closed without merging**
