### PR TITLE
Enable batched determinant with CUDA without OMPTarget

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Review after https://github.com/QMCPACK/qmcpack/pull/4966

code path used to be under `defined(ENABLE_OFFLOAD) && defined(ENABLE_CUDA)`
are available to `defined(ENABLE_OFFLOAD)`

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Would you like to see this path in any of the nightlies?

**Comment by prckent** [comment]
Can you run CUDA compute sanitizer/memcheck on this?

**Comment by ye-luo** [comment]
Need to debug the issue.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
It seems the failure is unrelated to the amdgpu driver. Still have a hard time reproducing the failure locally.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> To help decide how to handle this, can you try on Frontier? If the problem occurs on all AMD GPUs we should look carefully for a missed sync, warp width assumption or similar HIP/CUDA difference.

Frontier was happy
```
$ ctest -R deter -j 32
...
100% tests passed, 0 tests failed out of 1032

Label Time Summary:
QMCPACK                     = 3552.20 sec*proc (98 tests)
QMCPACK-checking-results    = 276.62 sec*proc (872 tests)
coverage                    = 779.81 sec*proc (10 tests)
deterministic               = 4107.23 sec*proc (1028 tests)
quality_unknown             = 4107.23 sec*proc (1028 tests)
unit                        = 278.16 sec*proc (48 tests)
```

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
OK. The problem is on my side. Our rocm  in CI doesn't turn on offload but I was testing with offload turned on. Now I can reproduce the issue and will fix the code.

**Comment by ye-luo** [comment]
With a bit more prototyping, I realized that "Enable batched determinant with CUDA without OMPTarget" is not the optimal way to maximize portability. It should be implemented as using OMPTarget plus vendor drop-ins. Having only OMPTarget managing memory ensures consistent memory management.

**Comment by ye-luo** [comment]
When I tried to connect `DualAllocator` https://github.com/QMCPACK/qmcpack/blob/37354368e3aec18030463ef2d6be8392b20d6940/src/Platforms/DualAllocatorAliases.hpp#L25
which is currently not used when offload is on, I realized that our current choice using OMPallocator is way more portable and I will stick to it.

**Pull request closed without merging**
