### PR TITLE
Fix 1316 High failure rate of C diamond 2x1x1 

### PR DESCRIPTION
**Pull request by PDoakORNL**
So here's my Fix for #1316 .  This seems to take care of the test with intel2018 on oxygen although I have a few more build combo's to test. I don't think there is a real bug behind this failure but just some issues with the testing harness.  Also I took a look at the Long tests.  They are now "correct" as far as I can say and long_dmc now has a chance of passing but with the settings that run has and what seem to me to be autocorrelation issues its passing totalenergy is going to require good luck.

I wrote a quick script to output refdata for the CMakeLists.txt file for the tests, I'm not clear whether qtest would do this for you or how it works, but in this case if you run the script on the ref files and the output you get from the tests in this commit you should in fact get these values.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Will review, but may be a bit.  Thanks in advance for patience.

**Comment by prckent** [comment]
Given the upcoming revisit of all the test reference data by @jtkrogel , Jaron should comment here if there is any issue.

For the updated long VMC section, keep 256 walkers since this allows for parallelization (OMP threads, GPU). 100 warmup steps in the VMC section is enough to generate inputs for DMC. If you do this you don't need to specify samples (we need to rename that keyword)

**Comment by PDoakORNL** [comment]
So when the manual says you'll get 1 vmc walker per thread per rank minimum so set walkers to 1 for a VMC walker initialization for DMC that is incorrect?

**Comment by prckent** [comment]
The statement "Setting walkers=1 in the VMC block ensures there will be only one VMC walker per execution thread. " in the lab 2 is correct. We updated the vmc method description in section 10.1 "Variational Monte Carlo", around page 124 or so, to be more precise. The walker keyword specifies walkers per MPI task. (What needs to happen here is eventually a new set of keywords with the normalization specified, which would solve https://github.com/QMCPACK/qmcpack/issues/8 )

**Comment by PDoakORNL** [comment]
I guess the issue there is the test mostly still fails on totenergy, I think because the error bar is unrealistically small from the test run due to autocorellation.  If I'm understanding the relation in DMC between blocks, time_step, and steps.  The long dmc test run already takes 20 minutes on oxygen

**Comment by jtkrogel** [comment]
The autocorrelation should be accounted for, provided your gold reference run is long enough (autocorrelation time (qmca --sac) saturates).  20 min is a bit long for the test.

**Comment by ye-luo** [comment]
```
ctest -j 16 -R short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj
Test project /sandbox/opt/cleanup/PDoak/build_real_SoA
    Start 674: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16
1/8 Test #674: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16 ...............   Passed   26.90 sec
    Start 675: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-kinetic
    Start 676: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-totenergy
    Start 677: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-eeenergy
    Start 678: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-potential
    Start 679: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-ionion
    Start 680: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-localecp
    Start 681: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-nonlocalecp
2/8 Test #675: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-kinetic .......   Passed    0.02 sec
3/8 Test #678: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-potential .....   Passed    0.02 sec
4/8 Test #680: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-localecp ......   Passed    0.02 sec
5/8 Test #676: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-totenergy .....   Passed    0.03 sec
6/8 Test #677: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-eeenergy ......   Passed    0.03 sec
7/8 Test #679: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-ionion ........   Passed    0.03 sec
8/8 Test #681: short-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-nonlocalecp ...   Passed    0.04 sec
```
```
$ ctest -j 16 -R long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj
Test project /sandbox/opt/cleanup/PDoak/build_real_SoA
    Start 682: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16
1/8 Test #682: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16 ...............   Passed  116.44 sec
    Start 683: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-kinetic
    Start 684: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-totenergy
    Start 685: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-eeenergy
    Start 686: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-potential
    Start 687: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-ionion
    Start 688: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-localecp
    Start 689: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-nonlocalecp
2/8 Test #685: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-eeenergy ......   Passed    0.04 sec
3/8 Test #687: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-ionion ........   Passed    0.04 sec
4/8 Test #689: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-nonlocalecp ...   Passed    0.04 sec
5/8 Test #684: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-totenergy .....   Passed    0.05 sec
6/8 Test #686: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-potential .....   Passed    0.04 sec
7/8 Test #688: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-localecp ......   Passed    0.04 sec
8/8 Test #683: long-diamondC_2x1x1_pp_kpts-vmc_gaussian_sdj-1-16-kinetic .......   Passed    0.05 sec
```

The long test takes 2 mins. Did you forget to set the -j when you ran on oxygen?

**Comment by PDoakORNL** [comment]
I've been going around about the dmc test. Which we've gotten cut down below 20 minutes now.  That's about as good as its going to get for now.  So I think we should merge this and see how it does in the nightlies.

**Pull request merged**
