### PR TITLE
Update docs with Intel19 jobs

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Update CI docs with Intel19 jobs
Test newly added Intel19 jobs on CI
Related to #3639 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
sulfur, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by williamfgc** [comment]
There are several errors with `Intel19-MPI-CUDA-AFQMC-Complex` , rerunning.

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by prckent** [comment]
Mentioned in passing: not that we ever want to break or drop compiler support if there are easy fixes, but if the current version of the Intel compiler works, our support rules allow us to mandate that version.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
