### PR TITLE
Use fixed width 64 bit integer for binary string conversion

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix nightly test failure on raspberry-pi.
"long int" is only 32 bit on ARM aarch64.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Ye-raspberrypi

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Did you miss a change?
```
Real-Mixed-enable-CUDA/src/QMCTools/QMCGaussianParserBase.cpp:962:26: error: type-id cannot have a name
    std::vector<unsigned int64_t> Val_alpha, Val_beta;
                         ^~~~~~~
```

**Comment by ye-luo** [comment]
> Did you miss a change?
> 
> ```
> Real-Mixed-enable-CUDA/src/QMCTools/QMCGaussianParserBase.cpp:962:26: error: type-id cannot have a name
>     std::vector<unsigned int64_t> Val_alpha, Val_beta;
>                          ^~~~~~~
> ```

It seems showing up only on the CI machine with Clang. Anyway, it was unused code and just got removed.

**Comment by ye-luo** [comment]
@prckent readthedocs seems having issue fetch the repo but I think we can just ignore since no docs are touched by this PR. Do you know how to trigger readthedocs to retry a build if it happens in the future? Our usual way only affects Jenkins.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
rtd issue is odd since the qmcpack manual was ok but the nexus one was not. Hopefully a transient issue at rtd.

**Pull request merged**
