### PR TITLE
Reorganize GitHub Actions

### PR DESCRIPTION
**Pull request by williamfgc**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes
Reorganize GitHub Actions from discussion in PR #3069
Enable real and complex builds
Attempt to merge real and complex code coverage reports in codecov
Unify coverage and sanitizer matrices

## What type(s) of changes does this code introduce?

- Refactoring: GitHub Actions CI
- Testing changes: add complex and real CI builds

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must work on GitHub Actions

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted (NA)
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Bugs found! Complex ubsan failures:

```
The following tests FAILED:
	 20 - deterministic-unit_test_wavefunction_trialwf (Failed)
	 21 - deterministic-unit_test_wavefunction_sposet (Failed)
```

Please can you add --output-on-failure to the ctest invocation next update.

**Comment by williamfgc** [comment]
@prckent it's interesting as I can reproduce locally with clang, but not with gcc. I'll compare warnings and try to find the root cause. In the meantime, do we want to disable `ubsan` for complex builds to merge this for the coverage reports? Let me know.

**Comment by prckent** [comment]
@williamfgc I suggest to disable for now. It looks like the test is simply failing with this complex build under ubsan. ubsan is not reporting a problem (?). The deviation from the check value is too large to explain via slightly different numerics, so I suspect a non-obvious bug in the test.

@ye-luo Have you ever seen this?

**Review by prckent — APPROVED** [review]

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
