### PR TITLE
Abort if Jastrow species not in ParticleSet

### PR DESCRIPTION
**Pull request by jtkrogel**
Addresses #113.

Guards have been added to Jastrow builders to prevent the code from running if requested Jastrow species are not present in the corresponding ParticleSet.  Previously, the code might silently ignore the input and simply drop the offending Jastrow terms.

The new code was tested explicitly for all species terms in 1 (bspline), 2 (bspline), and 3 (polynomial) Jastrows in the NiO test case.  All abort/error messages have the same form.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
The default values for especies1 and especies2 are both "u", which is correct in this case.

To move away from reliance on default behavior (and non-reading behavior), 'especies="u"' should be replaced with 'especies1="u" especies2="u"'.

**Comment by prckent** [comment]
OK. Please add a bug/issue. This is a place where there I think there should be no default and we should abort if the jastrow is not fully specified.

**Comment by ye-luo** [comment]
I tweaked the code and made the error printing together if both electron species are wrong in J2 and JeeI. Users should see more error with fewer runs.
Regarding JeeI, I agree with @jtkrogel we should enforce specify both eSpecies1 and eSpecies2 even they are the same.
In general we need to enhance our xml parsing classes.

**Comment by ye-luo** [comment]
All 8 CI builds checked on bora.
gcc 6.2 and cuda 10
CPU and GPU with real aos, cplx aos, real soa MP, cplx soa MP

**Pull request merged**
