### PR TITLE
Remove WFOpt support in legacy CUDA

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Remove WFOpt feature in legacy CUDA basically remove QMCCostFunctionCUDA class. Related CUDA kernels are not touched.

## What type(s) of changes does this code introduce?
- Other (please describe): Removing feature.

### Does this introduce a breaking change?
- Yes

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Somehow no documentation is updated in this PR :-)  Did we simply skip describing this explicitly in our existing docs? Are any examples affected?

**Comment by ye-luo** [comment]
@prckent Update docs and tests.

**Comment by ye-luo** [comment]
@prckent Does this look OK now?

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
