### PR TITLE
Enable HDF5 output for SkAllEstimator

### PR DESCRIPTION
**Pull request by jtkrogel**
This PR enables HDF5 (stat.h5) output for SkAllEstimator.  It also adds the walker weight to the estimator for consistency with other estimators in the context of DMC.

Outputted S(k) values from SkAllEstimator were checked for agreement against StaticStructureFactor and kpoint output was added to the latter class as well.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
The modulus needs to be included.  Will add shortly.

**Comment by jtkrogel** [comment]
Ready for review.

**Comment by jtkrogel** [comment]
I have only checked that VMC values match to high precision between the estimators.  I can run a short DMC if desired.

**Comment by prckent** [comment]
OK. So long as we know that the weight was not being subtly added elsewhere.

**Comment by prckent** [comment]
Do you need @rcclay to review this?

**Comment by jtkrogel** [comment]
As far as I know the weight is not used consistently throughout the code.  Weighted and unweighted values should converge in the large population limit.  This way is more correct though.

I would prefer to have his review since he is the original author of this code, but it may not be strictly necessary.

**Comment by prckent** [comment]
Will wait for @rcclay then.

**Comment by prckent** [comment]
If you know of anything unweighted, please make an issue since it is almost certainly a bug (IMO).

**Comment by prckent** [comment]
Thanks Ray. Merging.

**Pull request merged**
