### PR TITLE
remove global namespaces blitz and std

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Remove the use of global namespace in source of ppconvert (`using namespace blitz / std; `).
This will help refactor the code.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Review by prckent — APPROVED** [review]
I verified that the ppconvert_does_not_crash test is still OK after these changes.

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
The gold file also matches numerically.

**Pull request merged**
