### PR TITLE
Nexus: detect and handle dependencies

### PR DESCRIPTION
**Pull request by jtkrogel**
Addresses #1792.

With this PR, Nexus now has the ability to determine versions of module dependencies present on the host machine and appropriately inform the user about the status of their Nexus installation.  

Currently supported versions of dependencies are set by a 2 year policy.  The 2 year policy has been used to set supported versions of dependencies based on today's date.  Once set, the supported versions are fixed, but these may be updated with each release.

### CODE REVIEW

**Comment by jtkrogel** [comment]
Example log output for an old system (Ubuntu 14.04).  NumPy is present and Nexus core workflow features of Nexus work on this machine.

```
_____________________________________________________

                     Nexus 1.8.0

        (c) Copyright 2012-  Nexus developers

                     Please cite:
  J. T. Krogel Comput. Phys. Commun. 198 154 (2016)
     https://doi.org/10.1016/j.cpc.2015.08.012
_____________________________________________________
          
            

Checking for Nexus dependencies on the current machine...

  Nexus dependencies available on current machine:
    python2      = 2.7.13      (required)
    numpy        = 1.11.3      (required)
    scipy        = 0.18.1      (optional)
    h5py         = 2.6.0       (optional)
    matplotlib   = 2.0.0       (optional)
    pydot        = 1.0.28      (optional)
    pycifrw      = (unknown)   (optional)
  
  Nexus dependencies needed for full functionality:
    python2      = 2.7.13     (required)
    numpy        = 1.13.1     (required)
    scipy        = 0.19.1     (optional)
    h5py         = 2.7.1      (optional)
    matplotlib   = 2.0.2      (optional)
    pydot        = 1.2.3      (optional)
    spglib       = 1.9.9      (optional)
    seekpath     = 1.4.0      (optional)
    pycifrw      = 4.3.0      (optional)
  
  Required dependencies are present, but some are unsupported.
    Core workflow features may still work.
    Please install updated versions if problems are encountered.
  
  Required dependencies in need of user check or update:
    numpy version 1.11.3 is outdated.  Update to 1.13.1 or greater.
  
  Some optional dependencies are missing or merit an update.
    These modules are not needed for core workflow operation.
    Optional features related to outdated modules may still work.
    Please install updated versions if problems are encountered.
  
  Optional dependencies that are missing:
    spglib     is missing.  Install 1.9.9 or greater.
    seekpath   is missing.  Install 1.4.0 or greater.
  
  Optional dependencies benefitting from user check or update:
    pycifrw    version is unknown.  Check for 4.3.0 or greater.
    scipy      version 0.18.1 is outdated.  Update to 0.19.1 or greater.
    h5py       version 2.6.0 is outdated.  Update to 2.7.1 or greater.
    matplotlib version 2.0.0 is outdated.  Update to 2.0.2 or greater.
    pydot      version 1.0.28 is outdated.  Update to 1.2.3 or greater.

```

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
Example output on a more updated machine (Ubuntu 18.04):

```
_____________________________________________________

                     Nexus 1.8.0

        (c) Copyright 2012-  Nexus developers

                     Please cite:
  J. T. Krogel Comput. Phys. Commun. 198 154 (2016)
     https://doi.org/10.1016/j.cpc.2015.08.012
_____________________________________________________
          
            

Checking for Nexus dependencies on the current machine...

  Nexus dependencies available on current machine:
    python2      = 2.7.15      (required)
    numpy        = 1.15.4      (required)
    scipy        = 0.19.1      (optional)
    h5py         = 2.7.1       (optional)
    matplotlib   = 2.1.1       (optional)
    pydot        = 1.2.3       (optional)
    spglib       = 1.11.2      (optional)
    seekpath     = 1.8.4       (optional)
    pycifrw      = (unknown)   (optional)
  
  Nexus dependencies needed for full functionality:
    python2      = 2.7.13     (required)
    numpy        = 1.13.1     (required)
    scipy        = 0.19.1     (optional)
    h5py         = 2.7.1      (optional)
    matplotlib   = 2.0.2      (optional)
    pydot        = 1.2.3      (optional)
    spglib       = 1.9.9      (optional)
    seekpath     = 1.4.0      (optional)
    pycifrw      = 4.3.0      (optional)
  
  All required Nexus dependencies are met.
    Core workflow features should work.
    Some optional features may not.
    See below for more information.
  
  Some optional dependencies are missing or merit an update.
    These modules are not needed for core workflow operation.
    Optional features related to outdated modules may still work.
    Please install updated versions if problems are encountered.
  
  Optional dependencies benefitting from user check or update:
    pycifrw    version is unknown.  Check for 4.3.0 or greater.
```

There are still some issues with determining the version of pycifrw.

**Comment by prckent** [comment]
Nexus dependencies needed for full functionality: -> Minimum versions needed for full functionality?

**Comment by jtkrogel** [comment]
When supported dependencies are in need of an update by developers, the supported versions according to the age policy can be found in the following way:
```
>>> import versions
>>> versions.policy_versions()

Nexus dependencies for 2 year policy:
  python2      = 2.7.13    (dated: 2016-12-17 , age: 2.7 years )
  numpy        = 1.13.1    (dated: 2017-07-06 , age: 2.2 years )
  scipy        = 0.19.1    (dated: 2017-06-23 , age: 2.2 years )
  h5py         = 2.7.1     (dated: 2017-09-01 , age: 2.0 years )
  matplotlib   = 2.0.2     (dated: 2017-05-10 , age: 2.2 years )
  pydot        = 1.2.3     (dated: 2016-10-06 , age: 2.9 years )
  spglib       = 1.9.9     (dated: 2016-12-14 , age: 2.7 years )
  seekpath     = 1.4.0     (dated: 2017-04-04 , age: 2.4 years )
  pycifrw      = 4.3.0     (dated: 2017-02-27 , age: 2.5 years )
```

**Comment by jtkrogel** [comment]
Nexus dependencies needed for full functionality: -> Currently supported versions of dependencies consistent with 2 year age policy.

**Comment by jtkrogel** [comment]
Perhaps the wording of the message can be improved.

**Pull request merged**
