### PR TITLE
Add test for k-space Jastrow

### PR DESCRIPTION
**Pull request by jtkrogel**
Addresses #579.  Long and short tests are added for the k-space Jastrow along with manual input entry, README file, and a small fix to Nexus I/O for this case.  

For the small (2 atom) diamond cell in the test, addition of the k-space Jastrow significantly reduces the variance and also lowers the total energy by about 4 mHa/atom.  See README for more detail.

The current version of QMCPACK passes the tests.

### CODE REVIEW

**Comment by ye-luo** [comment]
Do you know if the optimization works with current code? Just to know if the evaluateDerivative routine is correct or not.

**Comment by rcclay** [comment]
The e-e k-space jastrow passed the wavefunction tester the last time I checked.

**Comment by jtkrogel** [comment]
@ye-luo I just reran the optimization with 3.40 AoS and SoA.  Both work well.

Anything else needed for this PR?

**Comment by ye-luo** [comment]
No. Everything seems good and the testing time is reasonable. I will leave mark to handle the merge sequence.

**Pull request merged**
