### PR TITLE
PPCONVERT Use Numerics implementation of interpolation solver

### LINKED ISSUE #3045: Complete updating and cleanup of ppconvert
Complete the updating started with the removal of blitz.

Already discussed with @correaa . Creating this issue so that it can be attached to the release milestone.

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Remove NR code from Spline code in ppconvert

Closes #3045 

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
The PR is ready

**Comment by ye-luo** [comment]
Okay to test

**Review by prckent — APPROVED** [review]
Confirmed working via manual test.

**Comment by prckent** [comment]
Manual test = test run by hand

**Comment by correaa** [comment]
> Manual test = test run by hand. Just ctest. Our CI doesn't build ppconvert yet.

Really, I thought that `ppconvert` test was run by default. I also run it manually but only for a matter of convenience with `ctest -R ppconvert`.  I though that therefore `ctest` alone would eventually run that test.

**Pull request merged**
