### PR TITLE
[CTest] Lock GPUs resources exclusively

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes

GPU is a very limited resource. To avoid deterministic test congestion, I have to use "ctest -j1" to reduce concurrent tests. Unfortunately, thiss restrict using 1 core and potentially hide bugs in multi threaded scenarios. So changed to use a resource lock to allow testing in offload running only 1 test at time but unlimited CPU cores with "ctest -j16" safely. No need of N_CONCURRENT_TESTS=1 any more.

Expand add_unit_tst to support both serial and MPI case.

## What type(s) of changes does this code introduce?
- New feature
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Please also fix for legacy CUDA

**Comment by ye-luo** [comment]
> Please also fix for legacy CUDA

Fixed.

**Review by prckent — APPROVED** [review]
Thanks. Will allow us to use ctest -j big-number for GPU builds.

**Review by prckent — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Tests this please.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
