### PR TITLE
Manual updates cmake flags

### PR DESCRIPTION
**Pull request by jptowns**
Added CMake optional arguments MPIEXEC and MPIEXEC_NUMPROCS_FLAG to the manual under the installation section.

### CODE REVIEW

**Comment by prckent** [comment]
Are you planning on adding the CMakeLists.txt update to this PR?

**Comment by grahamlopez** [comment]
okay to test

**Comment by ye-luo** [comment]
I clicked details but I can't access the page. Is it only accessible from ORNL?

**Comment by grahamlopez** [comment]
@ye-luo For right now, it is only available at ORNL. This will hopefully change in the future. In the meantime, failing build  logs will get mailed to Mark and Paul (and me so I can debug Jenkins).

Everyone else, I'm still getting the final CI configuration tweaks settled, so ignore the CI messages on this PR for right now.

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by ye-luo** [comment]
@grahamlopez Could add me as a build log receiver?

**Comment by atillack** [comment]
I am fine with the addition to installation.tex.

At the same time, changing CMakeLists.txt to tell the user about these options when the defaults fail may be more useful.

**Comment by jptowns** [comment]
I did not include the updated CMakeLists.txt because specifying MPIEXEC solves the problem. I had assumed that people would much rather add to their build scripts than dig around in CMakeLists.txt.
Also, I'm not sure how general the problem I was experiencing is, so I was reticent to change the main CMakeLists.txt

**Comment by prckent** [comment]
I see now that the FindMPI module in CMake handles this https://cmake.org/cmake/help/latest/module/FindMPI.html

Updates to CMakeLists.txt are therefore not needed. 

+1

**Pull request merged**
