### PR TITLE
Fixes for all particle move VMC/DMC drivers

### PR DESCRIPTION
**Pull request by ye-luo**
Some left over fix for #754 and #755.
allp DMC Tmove is fixed in the driver with LogValue fix in Jastrow factors.
LogValue needs to be updated by acceptMove such that Psi.getLogPsi() returns the correct value at any time.  Unit tests are updated.
allp VMC failing in SoA is fixed by adding the missing neighbour list construction needed by NLPP. This is not exposed by bccH tests.
The allp VMC tests on diamond had too large time step. This is also fixed and they pass stably now.

### CODE REVIEW

**Comment by prckent** [comment]
Do these pass the long allp tests with AoS and SoA?

**Comment by ye-luo** [comment]
I didn't add long allp tests last time. Since the bugs are fixed, I will add the long tests and reply the question of @prckent.

**Comment by prckent** [comment]
Please add an issue describing the problem

**Comment by ye-luo** [comment]
Issue added.

**Pull request merged**
