### PR TITLE
Update multi 0.78

### LINKED ISSUE #3686: QMCPACK does not compile with Intel oneAPI 2021.2.0 and AFQMC
QMCPACK fails to compile with activated AFQMC using intel compiler and mpi, oneAPI 2021.2.0. Boost version 1.76.0

Error occurs both with release 3.11.0 and the dev version (9b2bef4605ec870003069048f66de0c70e9c8d74)

cmake command:
`cd build ;
cmake -DCMAKE_C_COMPILER=mpiicc -DCMAKE_CXX_COMPILER=mpiicpc -D QE_BIN=/path/to/QE/ -D HDF5_PREFER_PARALLEL=1 -DQMC_COMPLEX=1 -DINSTALL_NEXUS=1 -DBUILD_AFQMC=1  VERBOSE=1 ..`

The error reads:
```
[ 83%] Building CXX object src/AFQMC/CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o
cd /gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/build/src/AFQMC && /gpfs3/scratch/share/pj_crarm_abinitio/000_Modules/bin/intel_oneapi/mpi/2021.2.0/bin/mpiicpc -DADD_ -DENABLE_PHDF5 -DH5_USE_16_API -DHAVE_CONFIG_H -DHAVE_LIBBOOST -DHAVE_LIBHDF5 -DHAVE_MKL -DHAVE_MKL_VML -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -DUSE_MPI -DUSE_REAL_STRUCT_FACTOR -D_MPICC_H -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/build/src -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/catch -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/Utilities -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/mpi_wrapper -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/io -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/Containers -I/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/Platforms -isystem /gpfs3/projects/pj_crarm_abinitio/000_Modules/bin/boost/1.76.0_intel_oneapi/include -isystem /gpfs3/scratch/share/pj_crarm_abinitio/000_Modules/bin/intel_oneapi/mkl/2021.2.0/include -isystem /gpfs3/scratch/share/pj_crarm_abinitio/000_Modules/bin/hdf5/1.10.6_intel_oneapi_2021.2.0/include -isystem /usr/include/libxml2 -qopenmp -Wno-deprecated -restrict -unroll -ip -qopt-prefetch -ftz -xHost -O3 -DNDEBUG -std=c++17 -MD -MT src/AFQMC/CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o -MF CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o.d -o CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o -c /gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/AFQMCFactory.cpp
/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array_ref.hpp(706): error: a constexpr function cannot have a nonliteral return type "boost::multi::basic_array<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, boost::multi::layout_t<2L,
          boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>>"
  	auto operator~ (basic_array const& s) -> basic_array {return s.transposed();}
  	     ^
          detected during:
            instantiation of class "boost::multi::basic_array<T, D, ElementPtr, Layout> [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L, boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 1008
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(const boost::multi::basic_array<T, D, ElementPtr, Layout> &) &->boost::multi::basic_array<T, D, ElementPtr, Layout> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 990
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(boost::multi::basic_array<T, D, ElementPtr, Layout> &&) &&->boost::multi::basic_array<T, D, ElementPtr, Layout> & noexcept [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 933 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array.hpp"
            instantiation of "auto boost::multi::array<T, D, Alloc>::reextent(const boost::multi::array<T, D, Alloc>::extensions_type &)->boost::multi::array<T, D, Alloc> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, Alloc=qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>]" at line 1661 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp"

/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array_ref.hpp(1264): error: a constexpr function cannot have a nonliteral return type "std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>"
  	auto base(array_iterator const& s) -> element_ptr {return s.base();}
  	     ^
          detected during:
            instantiation of class "boost::multi::array_iterator<Element, 1L, Ptr> [with Element=qmcplusplus::afqmc::SPComplexType, Ptr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>]" at line 747 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp"
            instantiation of "boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>> boost::multi::copy_n(boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, Size, boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>>) [with T=qmcplusplus::afqmc::SPComplexType, Q1=qmcplusplus::afqmc::SPComplexType, Q2=const qmcplusplus::afqmc::SPComplexType,
                      Size=boost::multi::difference_type={std::make_signed_t<boost::mpi3::size_t={MPI_Aint={long}}>={boost::mpi3::size_t={MPI_Aint={long}}}}]" at line 812 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp"
            instantiation of "boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>> boost::multi::copy(boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>>) [with T=qmcplusplus::afqmc::SPComplexType, Q1=qmcplusplus::afqmc::SPComplexType, Q2=const qmcplusplus::afqmc::SPComplexType]" at line 111 of
                      "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_t::_(boost::multi::priority<3UL>, As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType,
                      1L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 115 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_t::operator()(As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L,
                      std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 1709
            [ 7 instantiation contexts not shown ]
            instantiation of "auto boost::multi::adl_copy_n_t::_(boost::multi::priority<2UL>, As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>, int64_t={long}, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L,
                      std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 58 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_n_t::operator()(As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>, boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}},
                      boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 1009
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(const boost::multi::basic_array<T, D, ElementPtr, Layout> &) &->boost::multi::basic_array<T, D, ElementPtr, Layout> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 990
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(boost::multi::basic_array<T, D, ElementPtr, Layout> &&) &&->boost::multi::basic_array<T, D, ElementPtr, Layout> & noexcept [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 933 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array.hpp"
            instantiation of "auto boost::multi::array<T, D, Alloc>::reextent(const boost::multi::array<T, D, Alloc>::extensions_type &)->boost::multi::array<T, D, Alloc> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, Alloc=qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>]" at line 1661 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp"

/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array_ref.hpp(1264): error: a constexpr function cannot have a nonliteral return type "shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>"
  	auto base(array_iterator const& s) -> element_ptr {return s.base();}
  	     ^
          detected during:
            instantiation of class "boost::multi::array_iterator<Element, 1L, Ptr> [with Element=qmcplusplus::afqmc::SPComplexType, Ptr=shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>]" at line 748 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp"
            instantiation of "boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>> boost::multi::copy_n(boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, Size, boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>>) [with T=qmcplusplus::afqmc::SPComplexType, Q1=qmcplusplus::afqmc::SPComplexType, Q2=const qmcplusplus::afqmc::SPComplexType,
                      Size=boost::multi::difference_type={std::make_signed_t<boost::mpi3::size_t={MPI_Aint={long}}>={boost::mpi3::size_t={MPI_Aint={long}}}}]" at line 812 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/Memory/SharedMemory/shm_ptr_with_raw_ptr_dispatch.hpp"
            instantiation of "boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>> boost::multi::copy(boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, boost::multi::array_iterator<Q1, 1L, shm::shm_ptr_with_raw_ptr_dispatch<Q2>>, boost::multi::array_iterator<T, 1L, shm::shm_ptr_with_raw_ptr_dispatch<T>>) [with T=qmcplusplus::afqmc::SPComplexType, Q1=qmcplusplus::afqmc::SPComplexType, Q2=const qmcplusplus::afqmc::SPComplexType]" at line 111 of
                      "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_t::_(boost::multi::priority<3UL>, As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType,
                      1L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 115 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_t::operator()(As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L, shm::shm_ptr_with_raw_ptr_dispatch<const qmcplusplus::afqmc::SPComplexType>>, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 1L,
                      std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 1709
            [ 7 instantiation contexts not shown ]
            instantiation of "auto boost::multi::adl_copy_n_t::_(boost::multi::priority<2UL>, As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>, int64_t={long}, boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L,
                      std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 58 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/./detail/../detail/adl.hpp"
            instantiation of "auto boost::multi::adl_copy_n_t::operator()(As &&...) const->decltype((<expression>)) [with As=<boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>, boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}},
                      boost::multi::array_iterator<qmcplusplus::afqmc::SPComplexType, 2L, std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>>>]" at line 1009
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(const boost::multi::basic_array<T, D, ElementPtr, Layout> &) &->boost::multi::basic_array<T, D, ElementPtr, Layout> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 990
            instantiation of "auto boost::multi::basic_array<T, D, ElementPtr, Layout>::operator=(boost::multi::basic_array<T, D, ElementPtr, Layout> &&) &&->boost::multi::basic_array<T, D, ElementPtr, Layout> & noexcept [with T=qmcplusplus::afqmc::SPComplexType, D=2L, ElementPtr=std::__detected_or_t<qmcplusplus::afqmc::SPComplexType *, std::__allocator_traits_base::__pointer, qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>>, Layout=boost::multi::layout_t<2L,
                      boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={boost::mpi3::size_t={MPI_Aint={long}}}}>]" at line 933 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/external_codes/boost_multi/multi/array.hpp"
            instantiation of "auto boost::multi::array<T, D, Alloc>::reextent(const boost::multi::array<T, D, Alloc>::extensions_type &)->boost::multi::array<T, D, Alloc> & [with T=qmcplusplus::afqmc::SPComplexType, D=2L, Alloc=qmcplusplus::afqmc::shared_allocator<qmcplusplus::afqmc::SPComplexType>]" at line 1661 of "/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/HamiltonianOperations/KP3IndexFactorization.hpp"

compilation aborted for /gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/src/AFQMC/AFQMCFactory.cpp (code 2)
make[2]: *** [src/AFQMC/CMakeFiles/afqmc.dir/AFQMCFactory.cpp.o] Error 2
make[2]: Leaving directory `/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/build'
make[1]: *** [src/AFQMC/CMakeFiles/afqmc.dir/all] Error 2
make[1]: Leaving directory `/gpfs3/scratch/share/pj_crarm_abinitio/share/qmcpack_develop/build'
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Closes #3686. The issue can be reproduced with Intel 2022.1 and updating to v0.78 addresses the issue.
Add  `external_codes/boost_multi/README` for recording subtree command line.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
dell-laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Thanks Ye. Very happy to merge this once the tests are passing.

**Comment by ye-luo** [comment]
The build failure from AFQMC should have been fixed now.

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by correaa** [comment]
If it still possible, please use the new directory structure in Multi, repo/include/multi .

**Comment by ye-luo** [comment]
> If it still possible, please use the new directory structure in Multi, repo/include/multi .

That will happen separately

**Pull request merged**
