### PR TITLE
Remove lingering noasan label for fixed tests

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Remove `noasan` labels as all unit tests should pass the ASAN/LSAN checks
Related to #3083 

## What type(s) of changes does this code introduce?

- Build related changes
- Testing changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 20.04, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Test in-house please

**Comment by williamfgc** [comment]
Start testing in-house

**Review by prckent — COMMENTED** [review]
LGTM. Needs a non-ORNL approval to merge.

**Comment by williamfgc** [comment]
@prckent it seems like the changes in #3317 are working for the self-hosted CI workflow. I'll wait for @ye-luo review. Thanks!

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
