### PR TITLE
MatrixDelayedUpdateCUDA supersedes MatrixUpdateCUDA for batched case

### LINKED ISSUE #2452: Improve and rename CUBLAS_inhouse
As mentioned in https://github.com/QMCPACK/qmcpack/pull/2423 this will be renamed to identify that we are only implementing "missing" functionality that we hope will be in future cuBLAS, e.g.  batched BLAS1 and BLAS 2 implementations. Functionality will also be appropriately commented.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
MatrixDelayedUpdateCUDA implements delayed update with fake accept for rejected moves to be used by DiracDeterminantBatched. MatrixUpdateCUDA is no more needed.
Unit tests expanded to check both with and without delayed update.

Closes #2452

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Summit. Ryzen-box (partial testing)

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Comment by ye-luo** [comment]
This PR is ready for review and merge.

**Comment by PDoakORNL** [comment]
unit tests for cublas_missing functions. Should be pretty easy to generate.

**Comment by ye-luo** [comment]
> unit tests for cublas_missing functions. Should be pretty easy to generate.

Yes. Working on them, I have some issue with TWF complex unit test but integration test works fine. Still working on it. So I'd like to add unit test at cuBLAS_missing_function level.

**Comment by ye-luo** [comment]
> Yes. Working on them, I have some issue with TWF complex unit test but integration test works fine. Still working on it. So I'd like to add unit test at cuBLAS_missing_function level. unit tests for cublas_missing functions. Should be pretty easy to generate.
It will be a separate PR to avoid blocking this PR.

**Comment by prckent** [comment]
@PDoakORNL Good point on the unit test for the missing functions. These can be ~completely standalone from QMCPACK code and are easy to get coverage on.

**Comment by PDoakORNL** [comment]
Is it too much to hope that these could be copied from a blas implementation with a compatible license?

**Comment by ye-luo** [comment]
> Is it too much to hope that these could be copied from a blas implementation with a compatible license?

I need alpha in vector of batch_size. I have not found one.

**Comment by prckent** [comment]
Since no one has voiced significant objections I would like to get this merged after reasonable resolution of the above minor comments.

**Comment by ye-luo** [comment]
> Will you be able to fully relocate
> src/QMCWaveFunctions/Fermion/delayed_update_helper.cu
> src/QMCWaveFunctions/Fermion/subtractOne.cuh
> src/QMCWaveFunctions/Fermion/matrix_update_helper.cu
> ...
> 
> and similar in #2520 ? delayed_update_helper.cu does not appear to be removed and is clearly out of place not being under Platform. However there might be Good Reasons For Now.

Platforms is for more fundamental things to interact with vendor runtime and libraries. delayed_update_helper.cu and matrix_update_helper.cu
are specific to the inverse determinant matrix update. So they should stay in Fermion
subtractOne.cuh maybe generic enough to stay under Platforms/CUDA. Need to have a look.

**Comment by PDoakORNL** [comment]
@prckent From a file, object, datastruction, and function  perspective definitely.  Directory wise though cmake is happier if files are arranged by build target so I think what @ye-luo is doing is sane.

**Comment by prckent** [comment]
Thanks Peter. Yes, we don't don't need to antagonize cmake. We should keep an eye on this as the batch code evolves.

**Pull request merged**
