### PR TITLE
Offload AO evaluateVGL and evaluateV routines

### PR DESCRIPTION
**Pull request by kgasperich**
## Proposed changes

This is a follow-up to #4780 to add batched V, VGL, VGLandDetRatioGrads for LCAOs.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- Yes
- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by kgasperich** [comment]
@ye-luo @anbenali it looks like this broke some of the old mw unit tests [here](https://github.com/kgasperich/qmcpack/blob/c57d7c45b538117e252d49c96fe04bd4163521ec/src/QMCWaveFunctions/tests/test_MO.cpp#L136-L461), but I wasn't able to figure out exactly what was going wrong (I tried updating the EtOH one to use mw_update for the electrons, but that didn't seem to fix it)

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Please remove the commented out code sections in a subsequent PR.

**Pull request merged**
