### PR TITLE
Change DMC population control to use population weight

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
In the population control trial energy formula, replace the population size N_pop after branching with population weight W_pop before the population adjustment in branching
Screenshot from 2023-03-11 11-09-28
N_pop approximately equals W_pop. Using weight should be more fundamental and works in both population control and fixed population cases.

## What type(s) of changes does this code introduce?
- Other (please describe): Adjust existing code.

### Does this introduce a breaking change?

- Yes
- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thank you. Removes a small approximation inversely proportional to the population size

**Comment by prckent** [comment]
Keep an eye on the short and long tests.

**Pull request merged**
