### PR TITLE
Update oxygen test scripts

### PR DESCRIPTION
**Pull request by prckent**
PGI2019 and boost version increases

### CODE REVIEW

**Comment by ye-luo** [comment]
What version of boost we should use in the nightlies? Minimum supported version or newer version?
I feel better testing the minimum version. If the current minimum version is not sufficient, we raise the minimum version.

**Comment by prckent** [comment]
I updated Boost as part of chasing down MPI wrapper and general AFQMC C++ breakage, warnings etc. etc.. I am not going to change this back on oxygen since it takes a bunch of human time that I don't have to chase dependencies. Please make another issue on the boost version.

**Comment by prckent** [comment]
What I think needs to happen on oxygen and elsewhere is a set of builds using "oldest supported" versions and "latest released and supported" versions.

**Comment by ye-luo** [comment]
@prckent Please comment what you observed on oxygen with 1.61. Error or warning?
There is no need to investigate why but just list what you observed.

More discussion for version at #1616

**Pull request merged**
