### PR TITLE
Enable MPI and AFQMC on sulfur CPU CI runs

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
github CI has a lot of NOMPI variants. It is less critical to have NOMPI variants in self-host run variants.
AFQMC requires MPI. So I modified `GCC11-NoMPI-MKL` to `GCC11-MPI-MKL-AFQMC`

## What type(s) of changes does this code introduce?
- Other (please describe): adjust CI

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
N/A

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Do not merge. It is expected to fail until https://github.com/QMCPACK/qmcpack/pull/5236 gets in.

**Comment by ye-luo** [comment]
Due to change to [.github/workflows/ci-github-actions-self-hosted.yaml](https://github.com/QMCPACK/qmcpack/pull/5237/files#diff-e80e6fd355b71e01718aec47ba603cd712ff38ad22fb5ee7e420a7c73561aff2) a force merge will be needed.

**Review by prckent — APPROVED** [review]
Since the CI is usually bottlenecked by GPU testing, we can add more CPU variants in future, if desired.

**Pull request merged**
