### PR TITLE
Adjust multi walker resource acquire/release API in TWF and Ham

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Adopt the same multiwalker resource management API as  #3015 for ParticleSet.
The benefit of added arguments is allowing managing views when resources are acquired and released.
It makes certain optimization possible.
Remove the resource redistribution in DMC T-moves. More static behavior should reduce potential bugs.

If something goes wrong, I should see segfault but both deterministic tests and performance tests (intended for T-moves) runs happily.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
start testing in-house

**Review by PDoakORNL — COMMENTED** [review]
I still think this is basically a good idea as I thought back with #3015 but since 
then I have many tests (which are still stranded in my WIP PR) which check the integrity of the single walker API's in the batch context i.e. called through DiracBatchedDeterminant.

This needs code like this

```c++
ResourceCollection res_col("test_determinant");
psi.createResource(res_col);
psi.acquireResource(res_col);
...
double logpsi = psi.evaluateLog(elec_);
...
  std::unique_ptr<TrialWaveFunction> psi_clone(psi.makeClone(elec_clone));

  elec_clone.update();

  res_col.rewind();
  psi.releaseResource(res_col);
  res_col.rewind();
  psi_clone->acquireResource(res_col);
  double logpsi_clone = psi_clone->evaluateLog(elec_clone);
...
  res_col.rewind();
  psi_clone->releaseResource(res_col);
  res_col.rewind();
  psi.acquireResource(res_col);
...
  RefVectorWithLeader<TrialWaveFunction> wf_ref_list(psi, {psi, *psi_clone});
...
TrialWaveFunction::mw_evaluateLog(wf_ref_list, p_ref_list);
...
```
Now I need to make a RefVectorWithLeader with the psi I want to use with the single walker API even though I'm not going to use it. Still if one can then avoid all the rewind's that would be nice.

I still think passing the resource to the functions is looking better compared these semantics.

**Review by PDoakORNL — APPROVED** [review]
After discussion this looks good to me.

**Comment by ye-luo** [comment]
start testing in-house

**Pull request merged**
