### PR TITLE
Patch macOS CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Address Homebrew and Python issues on macOS GitHub Actions runner

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must pass CI 

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Similar issue to [Homebrew/homebre-core#165793](https://github.com/Homebrew/homebrew-core/issues/165793)

**Comment by williamfgc** [comment]
Test this please

**Comment by prckent** [comment]
@williamfgc Are you OK to un-WIP this and have it merged? While macos builds are now fixed, this still seems like a healthy update that we would have to do at some point.

**Comment by prckent** [comment]
Test this please

**Comment by williamfgc** [comment]
@prckent removed WIP. Thanks!

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
