### PR TITLE
Add tests for orbital rotation for Be

### PR DESCRIPTION
**Pull request by markdewing**
Test case is a Be atom with an STO basis set.  Basis set and MO matrix are taken from https://github.com/QMCPACK/qmcpack/blob/develop/tests/molecules/Be_STO/partial_opt_Be_STO.wfnoj.xml

Python scripts compute reference values for the test cases:
 1. single determinant
 2. multi-determinant code path with one determinant (same values as 1)
 3. multi-determinant code path with two determinants

For ease of using autodiff, the skew-symmetric matrix that goes into the rotation matrix is constructed by a separate script (construct_rot.py) and hard-coded into the wavefunction scripts.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by markdewing** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
Thanks Mark. 

If I interpret this and the results of the test coverage correctly,  we should now have good confidence that the multidet rotations are OK. In terms of orbital optimization, we only have open the question of whether the correct/good algorithm is being used at the optimization level. Agree?


Small request: Please can you add some comments at the head of each *.py explaining their purpose & use. The idea is to make things clear to our future selves/a new developer. An overall README_rotation_tests.md would also work.

**Comment by markdewing** [comment]
For all-electron, I think that is correct.  For pseudopotentials, multideterminants need to used the older "non-batched" (not referring to the driver) algorithm.  There is an unimplemented code in the path for the "batched" (VirtualParticle) algorithm.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Pull request merged**
