### PR TITLE
Remove AFQMC statistical test

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

AFQMC statistical tests were developed when there was no CUDA code. These are failing on the cdash but shouldn't be run. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

lassen

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Why doesn't this work with CUDA?

**Comment by mmorale3** [comment]
The tests should work, but they are not properly setup right now.
For example, they are not being submitted using the same number of (active) gpus and mpi tasks per node, which is a requirement in afqmc. This just needs some cleaning.

**Comment by fdmalone** [comment]
Some of the Hamiltonians aren't implemented on GPUs (sparse). AFQMC also requires the number of MPI tasks to equal the number of devices, so I think they will never work as currently configured (I think they use 16 tasks if I remember properly).

In connection with this, assuming they did run, the number of walkers would differ from the benchmarks (there would be fewer walkers), so I wouldn't necessarily trust the statistics, at least it would be slightly different than what was expected for the CPU runs.

**Comment by mmorale3** [comment]
I asked Fionn to turn them off until we can fix this.

**Comment by prckent** [comment]
Sounds very reasonable.

**Comment by prckent** [comment]
Test this please

**Pull request merged**
