### PR TITLE
Fix ppconvert memory bugs and enable in testing

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Fix memory leaks in ppconvert (done by @williamfgc ). Enable in testing.

## What type(s) of changes does this code introduce?

- Bugfix
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

sulfur. gcc no mpi.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No, for ease of review. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
This is now ready for review. All the hard work was done by @williamfgc .

We discussed a separate PR to clang-format ppconvert. That was undone/not done here for ease of reviewing.

**Comment by markdewing** [comment]
What did the change from PRIVATE to PUBLIC do in `target_sources`?   Was there a build failure that it fixed?

**Comment by prckent** [comment]
PRIVATE->PUBLIC. Not critical, but hopefully readiness for future simplification and a large amount of code deletion.

**Review by markdewing — APPROVED** [review]

**Review by ye-luo — COMMENTED** [review]
Usually I would challenge any use of shared_ptr why not using unique_ptr and references and clean up ownership. But ppconvert just so low priority.

**Comment by williamfgc** [comment]
@ye-luo  I agree using `std::unique_ptr` is ideal, but requires a redesign. Currently, there are (deep) copy constructors (not possible with `std::unique_ptr`) and ownership scope is quite convoluted.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Start testing in-house

**Comment by williamfgc** [comment]
Fixes #3491

**Pull request merged**
