### PR TITLE
Portable Datasets and Groups check in h5py readers

### LINKED ISSUE #3366: Deterministic tests failing with Ubuntu21.10+gcc11+python3-h5py-serial2.10.0
**Describe the bug**
Bugs related to unsupported types read by Nexus using h5py 2.10.  
`"<class 'h5py._debian_h5py_serial._hl.dataset.Dataset'>"` and `"<class 'h5py._debian_h5py_serial._hl.group.Group'>"`

**To Reproduce**

1. `develop`
2. `cmake -GNinja -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -D QMC_MPI=0 -DCMAKE_CXX_FLAGS=-Werror ../qmcpack`
3. `ninja`
4. `ctest -L deterministic`

**Expected behavior**
Tests should pass. 

**System:**
Ubuntu 21.10+gcc11+python3-h5py-serial2.10.0-9build2 docker image on Ubuntu 20.04 host

**Additional context**
It seems like python3-h5py on debian adds different classes for dataset and groups (breaks the API)? 
It should be easy to fix by supporting these types on Nexus.
`"<class 'h5py._debian_h5py_serial._hl.dataset.Dataset'>"` and `"<class 'h5py._debian_h5py_serial._hl.group.Group'>"`

```
The following tests FAILED:
	891 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars-1-1-check (Failed)
	893 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars_sel-1-1-check (Failed)
	1434 - ntest_nexus_hdfreader (Failed)
	1463 - ntest_nexus_qmcpack_analyzer (Failed)
	1472 - ntest_nexus_qmcpack_simulation (Failed)
	1478 - ntest_nexus_qdens (Failed)
```

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes
Bug seen with python3-h5py2.10 + Ubuntu 20.10 + gcc-11 in which debian specific class types are picked up for Datasets and Groups.
In anticipation to adding gcc-11 on CI.
Fixes #3366 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 21.10 + gcc-11 + python3-h5py2.10 docker image on Ubuntu 20.04 host

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Obvious questions: what is "debian" doing in those entries? are we misusing an API? is this a bug in h5py? how big is the {set of random operating systems} we need to account for? doesn't this destroy the portability we are using hdf5 for? is it fixed/changed in h5py v3+?

**Comment by markdewing** [comment]
Could this be done by testing the type directly, rather than testing against the string name of the type?

```
if isinstance(v, h5py.Dataset):
    self.add_dataset(cur,k,v)
elif isinstance(v, h5py.Group):
    self.add_group(hcur, cur, k, v)
```

**Comment by williamfgc** [comment]
@prckent yes, it seems like the API is broken for the string name of the type. Ubuntu 21 `python3-h5py` depends on `python3-h5py-serial` which has a different [installed package directory structure](https://ubuntu.pkgs.org/21.04/ubuntu-universe-amd64/python3-h5py-serial_2.10.0-9build2_amd64.deb.html). I'll try to explore @markdewing approach for portability.

The Ubuntu 21 container can be run locally: `docker run -u user -it williamfgc/qmcpack-ci:ubuntu2110-serial /bin/bash`

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Impish Indri (development branch)
Release:	21.10
Codename:	impish
user@cced055c5f1d:~$ ls /usr/lib/python3/dist-packages/h5py*
/usr/lib/python3/dist-packages/h5py:
__init__.py  __pycache__  _debian_h5py_serial

/usr/lib/python3/dist-packages/h5py-2.10.0.egg-info:
PKG-INFO  dependency_links.txt  requires.txt  top_level.txt

/usr/lib/python3/dist-packages/h5py._debian_h5py_serial-2.10.0.egg-info:
PKG-INFO  dependency_links.txt  requires.txt  top_level.txt
```

**Review by markdewing — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Jaron is out this week.

Since this change is readily revertible, I think it is reasonable to merge now and make further improvements if/as needed.

**Pull request merged**
