### PR TITLE
Fix legacy CUDA + CUDA2HIP builds.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix linking issue.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
github-actions didn't start. Pushed a formatting commit.

**Review by prckent — APPROVED** [review]

**Pull request merged**
