### PR TITLE
Add manual for vmc_batch

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Adding manual for vmc_batch.
Using this PR to discuss styles.
I tried first having a separate section for `vmc_batch` parallel to `vmc`. It caused a lot of duplication and I frequently get lost which part I was reading/editing.
So I incorporate the additional tags of `vmc_batch` directly into the current `vmc` section.

## What type(s) of changes does this code introduce?
- Documentation changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
ryzen-box

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — COMMENTED** [review]
Good question. I prefer a dedicated table for the batched drivers. While duplicative of many of the options it makes it even clearer what we are officially supporting and what we encourage use of. I would like to guard against us supporting historical options.

**Review by prckent — APPROVED** [review]

**Review by prckent — COMMENTED** [review]
In the batched driver writeup, I have concerns about storeconfigs: its description is inconsistent with the old driver, and I am not sure of the status. Is it implemented and have we checked? Might be better to list as not ready or developmental.

**Comment by ye-luo** [comment]
What did you mean "inconsistent with the old driver"? I actually don't know the status of this option. It is captured by the input class and shows some use in the batched drivers but I have no clue if it works or not.

**Review by prckent — APPROVED** [review]
@ye-luo No problem. I pushed some minor edits.

**Comment by prckent** [comment]
And I broke the tables.

**Review by prckent — APPROVED** [review]
Tables are fixed.

**Comment by prckent** [comment]
OK to test

**Pull request merged**
