### PR TITLE
Add separated tolerance for r^2 == dr^2 check for the mixed precision…

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

 Currently wavefunction unit test is failing for mixed precision build on nitrogen and sulfur because double precision tolerance for r^2 == dr^2 check in test_hybridrep.cpp is too small for the mixed precision.
 This PR is to add separated tolerance for mixed precision build as the number between double and float. 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
If I am reading the failing tests correctly (e.g. clang10 complex mixed) we are getting "if (0<0)". Did you consider putting <= &/or using the single precision definition for epsilon?

**Comment by ye-luo** [comment]
How about hold this PR for a moment.
The current error is "0.0f < 0.0"
How about print "std::abs(r * r - dot(dr, dr))" and "std::numeric_limits<double>::epsilon()"?

**Comment by Hyeondeok-Shin** [comment]
@prckent I simply discussed with @ye-luo before making this PR and we agreed to use the number between single and double rather than the single precision. It is still hard to guess which number will be the best for nitrogen and sulfur so it seems the best to start with the number between single and double.

Putting <= instead of < sounds more safe to deal with the mixed precision. I'll change it.

**Comment by Hyeondeok-Shin** [comment]
std::abs(r * r - dot(dr, dr)) is checked for nitrogen and sulfur. its value is larger than I expected but still between single and double precision. Now mixed-precision tolerance is adjusted for them and ready to review.

**Comment by prckent** [comment]
Rather close to single precision epsilon, but I think we can run with it.

**Comment by prckent** [comment]
OK to test

**Pull request merged**
