### PR TITLE
ENABLE_CUDA CI script

### LINKED ISSUE #1499: Need CI for ENABLE_CUDA
We need a third CI configuration to test ENABLE_CUDA. It is basically replace QMC_CUDA with ENABLE_CUDA.

### PR DESCRIPTION
**Pull request by ye-luo**
Close #1499 
@grahamlopez Could enable this on the jenkins side.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
test this please

**Comment by ye-luo** [comment]
This intended to set up the CI. Merge after the release.

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
@ye-luo I think this is ready to go from the Jenkins side

**Comment by ye-luo** [comment]
just to avoid confusion. Could you label the new one as cuda2?

**Comment by ye-luo** [comment]
Or cuda-experimental

**Comment by grahamlopez** [comment]
done.

**Comment by markdewing** [comment]
test this please

**Pull request merged**
