### PR TITLE
Eliminate AoS code from src and tests

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Remove AoS code throughout the application.

AoS removed from following locations:

- [x] Main `src`
- [x] Unit tests
- [x] Integration tests

Items left for later PR's:
- Test labeling
- Test automation
- Top-level CMake
- Manual/README
- Reduce references to SoA generally

## What type(s) of changes does this code introduce?

- Refactoring
- Build related changes
- Documentation content changes

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test.

**Comment by ye-luo** [comment]
The PR is already big. I'd like to merge it rather than waiting for the uncompleted items. Manually checking CUDA will be needed.

**Comment by jtkrogel** [comment]
Fine with me.

**Comment by jtkrogel** [comment]
I've updated the title/description consistent w/ this.

**Comment by jtkrogel** [comment]
Should anyone else have a look at this point?

**Comment by ye-luo** [comment]
Need @prckent to run the GPU tests manually and he may add comments put him as a a reviewer.

**Comment by prckent** [comment]
I am enquiring about when nitrogen with its V100 card will return and will update here when I do. (Sulfur also has a V100 but the CUDA kernel module isn't installed and we should not install it before nitrogen returns given the WFH situation.)

**Comment by prckent** [comment]
The legacy CUDA build deterministic tests were run successfully on this branch by @markdewing . Thanks Mark.

**Comment by ye-luo** [comment]
@jtkrogel Could you make an issue of the residual action items?

**Pull request merged**
