### PR TITLE
Add afqmc estimators

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Adds new estimators for AFQMC including : two-particle reduced density matrix, generalised fock matrices for ekt, two-point correlation functions with user specified rotation matrices. Everything is quite experimental and testing is lacking but we want an intermediate check in before some heavy memory allocation work is done.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Quartz (intel xeon), lassen (~ summit) 

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Comment by fdmalone** [comment]
Test failures seem unrelated to AFQMC : 18/27 Test #20: deterministic-unit_test_drivers_mpi .........***Failed    0.46 sec ?

**Comment by prckent** [comment]
We will ignore the test failures from oxygen.

**Comment by prckent** [comment]
This will be merged tomorrow after the v3.9.2 release.

**Pull request merged**
