### PR TITLE
Backend Changes to Make PBC ACForces Correct

### PR DESCRIPTION
**Pull request by rcclay**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes
Closes issue #4583 

Series of backend changes to ensure Assaraf-Caffarel force estimators work in periodic boundary conditions at gamma and non-trivial twists.  Consists of 1.) updating force specific LCAO calls to correctly handle nonzero-twists, and 2.) fixing real/complex issues in the NonLocalECPComponent fast force evaluations.  Unit tests based on finite differences for NonLocalECP and Kinetic energy derivatives added for C-diamond at 1/4,1/4,1/4 kpoint. 

*Bug fixes for slower legacy implementation not added because of expected deprecation of these routines.*

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- New feature
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon, RHEL7

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by rcclay** [comment]
Mixed precision complex is having issues on the same kinetic energy force component I was having problems with in the full precision build.  Investigating.

**Comment by ye-luo** [comment]
> Bug fixes for slower legacy implementation not added because of expected deprecation of these routines.

Which routines of what classes were you referring to?

**Comment by rcclay** [comment]
@ye-luo Both NonLocalECPComponent::evaluateOneWithForces() functions.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
