### PR TITLE
 Update multi using release v0.80.1

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Something strange happened on the CI node
```
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 8.5.0
```

**Comment by ye-luo** [comment]
@correaa GNU and Clang both failed in compilation.

**Comment by correaa** [comment]
i see old code in the repository. i must be doing something wrong when updating my fork. i'll try again.

**Comment by correaa** [comment]
Some of the errors look like this:

```
CMake Error at /opt/rocm/hip/cmake/FindHIP.cmake:253 (message):
  Unable to find the clang compiler path.  Set ROCM_PATH or HIP_PATH in env
Call Stack (most recent call first):
  CMakeLists.txt:815 (find_package)
```

I am going to start over.

**Comment by ye-luo** [comment]
The rocm issue will go away when  #4270 is merged.

**Comment by correaa** [comment]
replaced by https://github.com/QMCPACK/qmcpack/pull/4272

**Pull request closed without merging**
