### PR TITLE
Nexus: Python 3 transition

### PR DESCRIPTION
**Pull request by jtkrogel**
Merge only after the 3.9.0 release.  ~~This PR depends on #2117.~~

With this PR, Nexus transitions totally to Python 3.  If the user attempts to execute Nexus with Python 2, the code aborts and prints instructions to use Python 3.

The process I followed in the transition was:

1. Update the code manually until all tests pass.  Main changes regard use of iteritems(), xrange(), sorted(), keys(), and values() and subtle differences between Python 2 and 3 regarding integer division (integer division now always returns real numbers) and string data types (strings are now all unicode, but some imported modules still proffer data only in ASCII). 

2. Inspect all recommendations made by the `2to3` automatic translation tool on the updated files and include a subset of the changes.  Not all recommendations were worthwhile (e.g. `2to3` is prone to over recommend conversion to lists during iteration), but a number of conversions missed in the manual pass were caught in untested portions of the code.

3. Change all executables and examples to invoke `#! /usr/bin/env python3` and update the versions module to reflect the change to Python 3.  This does not guarantee a successful first execution of Nexus in all environments, but there is no other option that does and at least the intent is abundantly clear.  Invoking a Python 3 interpreter manually with any input script should work fine.  During this process, an additional optional dependency on cif2cell was caught and added to `versions.py` as well as the manual.

4. Run the 2019 workshop examples and compare against the older reference data.  I could not run Quantum Package (the install on my laptop appears to have been broken sometime in the last 7 months), but all the other workflows run successfully.

Once 3.9.0 is in, merging this PR will allow everyone to road test Nexus with Python 3 for a while before the release of QMCPACK 4.0.0 and Nexus 2.0.0.

### CODE REVIEW

**Comment by jtkrogel** [comment]
I should mention: though merging must wait for the v3.9.0 release, the PR is complete and is ready for review now.

**Comment by markdewing** [comment]
What prevents this from running on python2?  Besides the explicit python3 interpreter in the #! lines?

**Comment by jtkrogel** [comment]
In `versions.py`:
```
# Require Python 3
if python_version_tuple()<('3','0','0'):
    print('\nNexus is compatible only with Python 3.\n  You attempted to run with Python version {}.\n  Please rerun with Python 3.\n'.format(python_version()))
    sys.exit(1)
#end if
```

**Comment by markdewing** [comment]
If that check is removed, what fails?

**Comment by jtkrogel** [comment]
At least two things: (1) changes in binary/ascii representation of strings, (2) `print` is now used as a local keyword in places in `qmcpack_input` (it is not a global keyword in Python 3). 

(1) will cause at least runtime errors for many file I/O operations, including use of the `execute` function which is used extensively to launch the simulation codes.

(2) will cause the interpreter to fail with a syntax error when `qmcpack_input` is imported, which should happen anytime `nexus` is imported.

**Comment by jtkrogel** [comment]
This should go in now, ahead of the new year.

@markdewing Please finish your review when you get a chance.

**Comment by ye-luo** [comment]
Please update #1290 after merging

**Comment by jtkrogel** [comment]
@prckent, is there a reason this PR should go on hold?

**Comment by prckent** [comment]
We had discussed not switching to Python 3 before the release. For efficiency lets discuss the release on Slack.

**Comment by prckent** [comment]
This will be decided on Monday when a few more people are back from holidays, but after discussing the situation it seems that the preferred route is to make this transition now, just ahead of the v3.9.0 release.

**Comment by jtkrogel** [comment]
Merge conflicts are fixed now.

**Comment by prckent** [comment]
Thanks.

While this PR doesn't have an approved review yet, based on the discussions above & elsewhere, I believe that there are no concerns with it. The PR will be merged >=2pm today unless a good reason for delay is presented.

People will likely need to update or reconfigure their software stack to install and run develop after this is in.

**Comment by jtkrogel** [comment]
This PR covers the Nexus transition to Python 3.  There are likely other outstanding needs for QMCPACK configuration via Python 3 that need separate PR's.

**Comment by prckent** [comment]
OK to test

**Pull request merged**
