### PR TITLE
Build ppconvert by default

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Per the title, always build ppconvert. Update docs appropriately, remove outdated readme.

## What type(s) of changes does this code introduce?

- Build related changes
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen, llvm+openmpi

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
My initial PR tripped a few problems with CUDA related builds and gcc warnings, the latter since the code was never cleaned. Working through them.

**Comment by prckent** [comment]
The Intel 19.1.3.20200925 compiler has no problem with this code, and unfortunately I don't have immediate access to the old 19.0.0 compiler used in the ALCF CI. Since gcc and llvm have no problem, I think we can assume that we have legal code.

**Comment by prckent** [comment]
Results of Intel compiler version bisection below. Used gcc@7.5.0 for c++ library. At least 19.0.3 is required.
```
19.1.2 GOOD
19.0.5 GOOD
19.0.3 GOOD
19.0.1 (untested, spack unable to fetch)
19.0.0 BAD
```

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
