### PR TITLE
Resolve noinline definition conflict between CUDA headerfiles and GCC 12 libraries

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix the include conflict described in #4761

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
Lets go with this brittle fix until/if it proves problematic.

Will approve after fix is confirmed.

**Comment by markdewing** [comment]
Interchanging the include files worked on my system.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Pull request merged**
