### PR TITLE
Update test pass-fail check

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Workaround #3200 by adding failure on presence of "ERROR" in output. Remove ERROR previously printed by optimizer which was really a warning.

## What type(s) of changes does this code introduce?

- Bugfix
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen, clang no mpi.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
@williamfgc need a few fixes in the CI.
1. Install libhdf5-dev in the docker image. Then non-MPI build can use the non-MPI hdf5.
2. build asan cases without MPI and test only unit test as other deterministic tests all fail asan.
3. current LSAN suppression seems needs to be reduced or probably removed if build qmcpack without MPI and run unit tests only. Since not all unit tests pass, we need to put a filter and keep the good ones running and enable more as we fix more.

**Comment by prckent** [comment]
@williamfgc This PR causes a few tests to fail in asan that were incorrectly passing. Since this has been the case for some time, please use your judgement on updating the tests run with asan as suggested by Ye. If some tests will soon be fixed by pending/upcoming PRs I think we can keep this PR around for a little bit as a canary.

**Comment by williamfgc** [comment]
@ye-luo @prckent sounds good, working on the request. For the most part I removed the tests, see #3083, that actually crash with `asan` (mostly due to leaks), those passing have leaks that cause no harm as the OS will take care of those (just like those from MPI/OpenMP).

I applied [lsan filters to C functions](https://github.com/QMCPACK/qmcpack/blob/develop/config/sanitizers/lsan.supp) with the goal to remove MPI/OpenMP-related failures only, but there is still those associated with the spline section in the source code (written in C).  I'll be happy to accommodate to @ye-luo request since the ultimate goal is to remove all failures (on a leak-by-leak basis) while preventing new ones.

**Comment by williamfgc** [comment]
@prckent @ye-luo please, please the list below of failed tests after running this PR using @ye-luo suggestion (no-MPI, no LSAN filters).  We have two options:

1. Be more restrictive today and label the tests (and `_check` dependent tests) below as `noasan`
2. Address leaks while still enabling `asan` and clang testing in non-critical tests and become more restrictive after that.

Both have value and trade-offs and the end result should be the same (full leak-free deterministic tests).
My only suggestion is to keep running `deterministic` tests (640), as unit only tests (20) have little coverage. Thoughts?

```
          34 - deterministic-unit_test_tools (Failed)
	132 - deterministic-heg_14_gamma-sjb-1-1 (Failed)
	136 - deterministic-heg_14_gamma-sjb-opt-1-1 (Failed)
	138 - deterministic-heg_14_gamma-sjb-opt_vmc-1-1 (Failed)
	277 - deterministic-LiH_pp-vmc_hf_noj-1-1 (Failed)
	287 - deterministic-LiH_pp-vmc_hf_sdj_xml-1-1 (Failed)
	297 - deterministic-LiH_pp-vmc_hf_sdj_hdf5-1-1 (Failed)
	414 - deterministic-He_ae-opt-1-1 (Failed)
	416 - deterministic-He_ae-opt_vmc-1-1 (Failed)
	418 - deterministic-He_ae-opt-batch-1-1 (Failed)
	420 - deterministic-He_ae-opt_vmc-batch-1-1 (Failed)
	427 - deterministic-Co_L2_std-vmc_dmc-1-1 (Failed)
	438 - deterministic-Co_L2_L2-vmc_dmc-1-1 (Failed)
	483 - deterministic-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-1 (Failed)
	698 - deterministic-diamondC_1x1x1_pp-vmc-estimator-density-1-1 (Failed)
	700 - deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1 (Failed)
	702 - deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-1-1 (Failed)
	704 - deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1 (Failed)
	706 - deterministic-diamondC_1x1x1_pp-vmc-noJ-estimator-1rdm-1-1 (Failed)
	708 - deterministic-diamondC_1x1x1_pp-vmc-J2-estimator-1rdm-1-1 (Failed)
	710 - deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-1-1 (Failed)
	712 - deterministic-diamondC_1x1x1_pp-vmc-estimator-momentum-1-1 (Failed)
	714 - deterministic-diamondC_1x1x1_pp-dmc-estimator-momentum-1-1 (Failed)
	716 - deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1 (Failed)
	727 - deterministic-diamondC_1x1x1_pp-vmc_sdj_excited-1-1 (Failed)
	738 - deterministic-diamondC_1x1x1_pp-vmc_sdj-meshf-1-1 (Failed)
	749 - deterministic-diamondC_1x1x1_pp-vmc_sdj_kspace-1-1 (Failed)
	760 - deterministic-diamondC_1x1x1_pp-dmc_sdj-1-1 (Failed)
	770 - deterministic-diamondC_1x1x1_pp-dmc_sdj_excited-1-1 (Failed)
	780 - deterministic-diamondC_1x1x1_pp-multi_dmc_sdj-1-1 (Failed)
	808 - deterministic-diamondC_1x1x1_pp-vmc-dmc-mwalkers_sdj-1-1 (Failed)
	845 - deterministic-diamondC_1x1x1_pp-vmc-dmc-multi_ts_sdj-1-1 (Failed)
	864 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars-1-1 (Failed)
	866 - deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars_sel-1-1 (Failed)
	868 - deterministic-diamondC_1x1x1_pp-param-grad-1-1 (Failed)
	977 - deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1 (Failed)
	988 - deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1 (Failed)
	998 - deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1 (Failed)
	1008 - deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1 (Failed)
	1017 - deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1 (Failed)
	1026 - deterministic-diamondC_2x1x1_pp-vmcbatch-mwalkers_sdj-1-1 (Failed)
	1045 - deterministic-diamondC_2x1x1_pp-vmcbatch-mwalkers_sdbatch_jas-1-1 (Failed)
	1064 - deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-1-4 (Failed)
	1091 - deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers-serialized_sdj-1-4 (Failed)
	1118 - deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdbatch_sdj-1-4 (Failed)
	1145 - deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdj-1-16 (Failed)
	1172 - deterministic-diamondC_2x1x1_pp-vmcbatch-dmcbatch-mwalkers_sdbatch_sdj-1-16 (Failed)
	1213 - deterministic-diamondC_1x1x1_pp-vmc_gaussian_sdj-1-1 (Failed)
	1238 - deterministic-diamondC_1x1x1-Gaussian_pp_MSD-1-1 (Failed)
	1269 - deterministic-diamondC_2x1x1-Gaussian_pp_MSD-1-1 (Failed)
	1298 - deterministic-diamondC_2x1x1_pp-vmc_gaussian_sdj-1-1 (Failed)
	1328 - deterministic-grapheneC_1x1_pp-vmc_sdj_z10-1-1 (Failed)
	1330 - deterministic-grapheneC_1x1_pp-vmc_sdj_z30-1-1 (Failed)
```

**Comment by prckent** [comment]
@williamfgc This is clear - we skip these failing tests only in asan with updated noasan labels. Then "we" work to reduce the number of tests with the noasan label. The unit test coverage can not be relied upon, and may not be for a long while - e.g. the high level drivers won't be testable separately without a great deal of work.

I would prioritize the list as follows:

1. deterministic-unit_test_tools  (unit test, simplest)
2. deterministic-LiH_solid_1x1x1_pp-gamma-vmc_hf_noj-1-1 (spline, vmc, simple determinant only wavefunction)
3. deterministic-diamondC_1x1x1_pp-vmc_sdj-1-1 (spline, vmc, but adds add single determinant+jastrow wavefunction "sdj" )
4. deterministic-diamondC_1x1x1_pp-dmc_sdj-1-1 (as above, but diffusion monte carlo)

Some of the other tests are likely to clean up as these start working. Other than for system size and number of steps, runs like number 3 and 4 are where most of the computing time goes. Hence knowing these are "clean" would be a significant step.

**Comment by ye-luo** [comment]
@williamfgc because of the label overwriting issue, a lot of unit tests failing asan are not listed in your run. wavefunction/hamiltonian/driver unit test should all fail asan. I would recommend doing unit test right now in asan CI. Not until we fix all unit tests, other integration tests under deterministic label always fail.

**Comment by prckent** [comment]
@ye-luo What label overwriting issue? I can't find anything relevant on GitHub. Please make an issue describing or link.

**Comment by ye-luo** [comment]
@prckent previously added labels are overwritten by 'noasan'
https://github.com/QMCPACK/qmcpack/pull/3081/files#r637120345
I need to use APPEND.

**Comment by prckent** [comment]
@williamfgc Please can you fix.

**Comment by prckent** [comment]
Once the label issue is fixed, I still like the idea of the -- now bigger -- exclusion list implemented via noasan labels. Seems easier to adjust as things start working. Once any test is running correctly with asan we need to run it with asan in the CI to avoid any relapse.

**Comment by williamfgc** [comment]
@prckent Sure do! OK, I'll work on the fix (that's probably me overwriting labels) and see what we get with unit tests. Thank you both for the guidance.

**Comment by ye-luo** [comment]
@prckent to put 'noasan' in all determinisitic tests right now might be messy I guess. The number of our unit tests is limited. I think we should turn on "-L unit" (~30 tests) and half should pass asan. The rest failing ones should be marked as `noasan` and we just run "-L unit -LE noasan" in CI to prevernt further breakage. One all the unit test nonasan are fixed, we can add deterministic tests and I would expect mostly good by then.

**Review by ye-luo — APPROVED** [review]

**Comment by williamfgc** [comment]
@quantumsteve just sharing @prckent list for addressing leaks [above](https://github.com/QMCPACK/qmcpack/pull/3202#issuecomment-849807649). Let's sync up next week.

**Pull request merged**
