### PR TITLE
Spack regression test update March 2020

### PR DESCRIPTION
**Pull request by naromero77**
## Proposed changes

Update Spack regression test script and include needed YAML files. Changes summarized below:
- Support AFQMC
- Support libflame and blis
- Fix support for QMCPACK 3.9.x 

## What type(s) of changes does this code introduce?

- Other (please describe): Spack regression test update

### Does this introduce a breaking change?

No

## What systems has this change been tested on?

Ubuntu Linux

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by rcclay** [comment]
OK to test.

**Comment by rcclay** [comment]
Oops.  Didn't realize there were issues with CI.  We'll retrigger when fixed.

**Comment by prckent** [comment]
@PDoakORNL good to put the CI files in their own directory. I'll move the integration test scripts and setup into their own directory as well. So we'll have tests/test_automation/type_of_testing/files

**Comment by prckent** [comment]
To avoid any confusion: we'll merge this once the files in the PR are moved to a new directory.

**Comment by naromero77** [comment]
I started working on this, but got interrupted. Will try to get it done today.

**Comment by naromero77** [comment]
@PDoakORNL Let me know what else is needed. Looks like I possibly interrupted something you were already doing with directory restructuring.

**Pull request merged**
