### PR TITLE
Mark most LRHandler evaluate functions const and clean up its usage in Coulomb

### PR DESCRIPTION
**Pull request by ye-luo**
Review after merging #3235

## Proposed changes
Before this PR, shared_ptr are used for long range handler and short range pair functions in Coulomb PBC AA class. In fact when particle sets are active, the shared_ptr is used as unique_ptr. The AB class use unique_ptr.

In this PR, all the evaluation functions of  long range handler and short range pair functions are defined const (thread-safe).
So a shared copy of long range handler and short range pair function can be used among all the walkers safely. Both makeClone functions become calling compiler generated copy constructor.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

I think Ray is tied up until next week. Wait or merge as convenient?

**Comment by ye-luo** [comment]
@prckent I added a few more override. Need another approval. All the changes are relatively low risk. We can merge as convenient. I subscribed @rcclay is more of sending him a notification.

**Comment by prckent** [comment]
An override too many / A virtual function too few according to the CI

**Comment by ye-luo** [comment]
> An override too many / A virtual function too few according to the CI

fixed now. Looks like a bug was surfaced but it doesn't affect anything as the function is disabled anyway.

**Review by prckent — APPROVED** [review]

**Pull request merged**
