### PR TITLE
Parallelize the filling of linear matrices

### PR DESCRIPTION
**Pull request by markdewing**
Parallelize the batch code version of fillOverlapHamiltonianMatrices function using ParallelExecutor.

The version in the non-batch code was parallelized with an omp parallel for over the `pm` loop.  There are no reduction variables or other sync needed because iterations are filling in different matrix entries.

Can be tested with #3372

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature
### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by PDoakORNL — DISMISSED** [review]
fillOverlapHamiltonianMatrices needs some documentation both at the base class level and briefly for this implementation.

I think a threaded test of this would be worthwhile.  I seems like it would be fairly easy to produce with code that could be shared with the existing test for the matrix filling.

Otherwise this looks good to me, it doesn't appear to be inside another threaded context.

**Comment by markdewing** [comment]
The test in #3372 checks the 1 and 2 thread cases.  The loop bounds can be extended for checking cases with more threads.

**Comment by prckent** [comment]
Looks to me like the comments have all been addressed. Propose to approve after #3372 is merged.

**Review by prckent — APPROVED** [review]
Approving since the comments appear to have been addressed (thanks Mark), and further revision wouldn't be difficult in a later PR or affect other ongoing work.

**Comment by prckent** [comment]
Start testing in-house

**Pull request merged**
