### PR TITLE
Raise CMake minimum to 3.21

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
3.21 (July 2021) is over 2 years old.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
need to address https://github.com/QMCPACK/qmcpack/issues/4846 first. Mark this PR draft.

**Comment by prckent** [comment]
For the record, is there anything specific in 3.21 that it is needed before other than a long list of general updates? Generally we try not to bump the minimum version without specific reason since it can add install burden.

**Comment by ye-luo** [comment]
> For the record, is there anything specific in 3.21 that it is needed other than a long list of general updates? Generally we try not to bump the minimum version without specific reason since it can add install burden.

I would like to use `cmake_path` new in 3.20 to handle path manipulation. 3.21 help us removing a few if in CMakeLists.txt.

**Comment by prckent** [comment]
@williamfgc Needs CI images updated

**Comment by prckent** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
https://github.com/QMCPACK/qmcpack/blob/develop/README.md needs an edit for the CMake version

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
> https://github.com/QMCPACK/qmcpack/blob/develop/README.md needs an edit for the CMake version

Updated

**Review by prckent — APPROVED** [review]

**Pull request merged**
