### PR TITLE
Manual edits from Charlie Horak

### PR DESCRIPTION
**Pull request by prckent**
Ongoing editing of the manual.

Push small changes/fixes directly to this branch e.g. using the handy GitHub web interface to do so. Please do not ask me to make small edits since this is incredibly time inefficient. Large edits or reverts can be discussed.

### CODE REVIEW

**Comment by ye-luo** [comment]
@prckent Did you check the compilation? Our CI doesn't check the manual compilation.

**Comment by prckent** [comment]
Yes. Needed to do a couple of minor fixes.

**Comment by ye-luo** [comment]
How to request changes like
`~\ref{}` to avoid line break after sections, figures, tables.
`~(\ref{})` extra bracket for equations?

**Comment by prckent** [comment]
I'll try a regex to fix these. They are throughout the manual.

**Comment by prckent** [comment]
- Done with edits. 
- Confirming that "latexmk -pdf qmcpack_manual.tex" still works

**Comment by prckent** [comment]
Pause

**Comment by prckent** [comment]
We need to check that none of the case sensitive inputs were changed.

**Comment by prckent** [comment]
Fixed. Reverted entries in backflow and reconfirmed that the LaTeX still builds. OK to merge.

**Pull request merged**
