### PR TITLE
Fix threading for descent and hybrid optimization

### PR DESCRIPTION
**Pull request by LeonOtis**
## Proposed changes

This is a fix for the failure of descent and hybrid method tests that @ye-luo notified me about. Some additional vectors are used to store values for different threads during the descent method iterations. With this change, I think the 1-16 cases for the descent and hybrid method tests should now pass.

## What type(s) of changes does this code introduce?

Bug fix
### Does this introduce a breaking change?
- No

## What systems has this change been tested on?

Savio and Lawrencium computing clusters

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Review by ye-luo — APPROVED** [review]
manually check tests. LGTM

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
The only failure was cased by CI setting. So just merge.

**Pull request merged**
