### PR TITLE
Math::FFTW3 and Math::BLAS_LAPACK should not be exposed inside modules

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
It is a CMake internal change, not affecting users.
Having FindMKL/FindFFTW modules directly accessing the global Math::BLAS_LAPACK and Math::FFTW3 goes against modularization. Thus change the behavior. Create a module specific target and make the global one depends on it.

PS: there are also minor changes replace set properties with corresponding target_ command.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Note: our FindFFTW3.cmake was not well written. Will need another pass.

**Review by quantumsteve — APPROVED** [review]
Improvement to FindMKL and FindFFTW.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
