### PR TITLE
Mixed precision check value in rotated SPOs  tests

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Deterministic unit Hamiltonian test is failing in gcc12 mixed precision real builds. Try setting a dedicated check value. Note that this test is passing with other compilers and with gcc12 mixed complex builds.

https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_hamiltonian_ham&date=2023-01-13

```
[0m-------------------------------------------------------------------------------
 [0mRotatedSPOs SplineR2R hcpBe values multi det
 [0m-------------------------------------------------------------------------------
 [0;37m/scratch/pk7/QMCPACK_CI_BUILDS/qmcpack/src/QMCHamiltonians/tests/test_RotatedSPOs_NLPP.cpp:38
...............................................................................

 [0m [0;37m/scratch/pk7/QMCPACK_CI_BUILDS/qmcpack/src/QMCHamiltonians/tests/test_RotatedSPOs_NLPP.cpp:167:  [0m [1;31mFAILED:
 [0m [0;36m  CHECK( elec.L[1] == ValueApprox(-0.4831061477045371) )
 [0mwith expansion:
 [1;33m  -0.4830868071 == Approx( -0.4831061477 )
 [0m
 [1;31m=== [0m [1;33m [0m [0;32m============================================================================ [0m
test cases:  24 [0;37m |  [0m [0;32m 23 passed [0m [0;37m |  [0m [1;31m1 failed [0m
assertions: 342 [0;37m |  [0m [0;32m341 passed [0m [0;37m |  [0m [1;31m1 failed [0m

```

## What type(s) of changes does this code introduce?

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

None. CI must run

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
