### PR TITLE
Move Rng out of QMCDriver base class.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Individual derived class should carry the know whether and how many RNGs to carry with.
I'm refactoring legacy drivers here and will later touch the batched drivers.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
I did wonder if we should move some of the rng handling to the base driver class, but that could be constraining for some future fancy driver.

**Comment by ye-luo** [comment]
I'm still debating within myself. It all comes down to the question what a QMCDriver base class is. Current implementation of QMCDriver is more of a common bits of VMC and DMC than a well abstracted base class. With the help of QMCDriverInterface, we are in a better position to sort out how to improve the abstraction.

On the legacy driver side, let me document the current implementation. VMC/DMC doesn't directly interact with `RandomNumberControl::Children`. Their constructors take a vector of RNGs which can be `RandomNumberControl::Children` or fake RNGs for unit tests. This is a good pattern that we probably will adopt in the batched drivers. CSVMC and RMC instead keep internal copies of RNGs which are copied from and back to `RandomNumberControl::Children` at the beginning and end of the driver run. I don't really feel comfortable with this behavior. WFOpt is a fancy/high-level driver now doesn't carry RNGs any more. All the patterns explored on the legacy side do help us figuring out good abstraction on the batched drivers.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
