### PR TITLE
On some platforms memory resource is has an alternate header and library

### PR DESCRIPTION
**Pull request by PDoakORNL**
## Proposed changes

Don't assume memory resource is just part of the stdlibc++ this will not be true on conservative distros or OSX up to at least Ventura.

Previous part of #4793.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
OSX Ventura laptop, ubuntu x86

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
It seems that this PR search for memory_resource but I don't see a consumer in the source code. Could you add a test showing how memory_resource is switchable?

**Comment by correaa** [comment]
If you are planning to use memory resources (static or polymorphic, PMR), Multi supports those. https://gitlab.com/correaa/boost-multi#polymorphic-memory-resources

The memory resource features have been painful to use so far because they were not provided in full until recently.

**Comment by PDoakORNL** [comment]
I don't need that header or care, but 3 years ago you added TestCxx17Library which requires it to be presented linkable.  My original fix was just to delete this library test but I figured there must be some reason for it.

**Comment by PDoakORNL** [comment]
Ah but yes multi is all over ::pmr just search for that.

**Comment by ye-luo** [comment]
I guess that check was introduced for AFQMC(indirectly multi)? @correaa any guide line how user code of multi should handle the availability of memory_resource?

**Comment by correaa** [comment]
Multi assumes `memory_resource` is available because it is a C++17 standard feature. It was a time when it was optional (when it was a C++14, C++1y library), but not anymore. If you have a platform QMCPACK needs to support that is not entirely C++17-ready, I can make it optional again, most likely by looking at the compiler version identifier in the headers.

**Comment by ye-luo** [comment]
@correaa you said multi works fine on OSX. What is the compiler you are testing?
@PDoakORNL you said memory_resource is a blocker for you. What compiler are you using?

**Comment by correaa** [comment]
> @correaa you said multi works fine on OSX. What is the compiler you are testing?

Did I say that? If so, I only anecdotally know that codes that use Multi were compiled and tested on Apple, https://gitlab.com/npneq/inq/-/issues/134 .

I don't have a machine to do tests on Apple, it would be lovely to have one for the gitlab CI (if some want to donate a gitlab runner machine).

Apple is enough case to consider optional support for memory_resource, it is not that hard, just ugly in the code.

**Comment by PDoakORNL** [comment]
I just updated compilers on homebrew again on OSX Venture I actually don't need this anymore. So sorry for the wasted time I think we can drop it.

**Comment by correaa** [comment]
> I just updated compilers on homebrew again on OSX Venture I actually don't need this anymore. So sorry for the wasted time I think we can drop it.

Cool, now I can say that, very anecdotally, Multi works on Apple clang  :)

@PDoakORNL
Can you do this on multi, in your Mac?

```
mkdir -p build && cd build
cmake ..
cmake --build .
ctest
```

This should, in particular, test PMRs 

 https://gitlab.com/correaa/boost-multi/-/blob/master/test/pmr.cpp

**Comment by PDoakORNL** [comment]
No that doesn't work at all.
```
clang: error: argument unused during compilation: '-Wnonportable-cfstrings' [-Werror,-Wunused-command-line-argument]
```

**Comment by correaa** [comment]
> No that doesn't work at all.
> 
> ```
> 
> clang: error: argument unused during compilation: '-Wnonportable-cfstrings' [-Werror,-Wunused-command-line-argument]
> 
> ```

thanks. what is the (apple) clang version?

**Comment by PDoakORNL** [comment]
apple clang 15.0.0
With the repo version of multi instead of the one in qmcpack I get this
```
   [  1%] Building CXX object CMakeFiles/allocator.cppx.dir/allocator.cpp.o
/usr/local/bin/mpic++ -DBOOST_PP_VARIADICS -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_NO_LIB -isystem /usr/local/include -std=c++14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=13.6 -Werror -Wall -Wextra -Wundef -fno-common -Wshadow -Wpedantic -Wdouble-promotion -Wmove -MD -MT CMakeFiles/allocator.cppx.dir/allocator.cpp.o -MF CMakeFiles/allocator.cppx.dir/allocator.cpp.o.d -o CMakeFiles/allocator.cppx.dir/allocator.cpp.o -c /Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/allocator.cpp
In file included from /Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/allocator.cpp:10:
In file included from /Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../array.hpp:13:
In file included from /Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/.././array_ref.hpp:14:
In file included from /Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../utility.hpp:9:
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../detail/layout.hpp:158:12: error: definition of implicit copy assignment operator for 'layout_t<1>' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
        constexpr layout_t(layout_t const&) = default;
                  ^
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../detail/layout.hpp:85:73: note: in implicit copy assignment operator for 'boost::multi::layout_t<1>' first required here
template<dimensionality_type D, typename SSize=multi::size_type> struct layout_t;
                                                                        ^
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../array.hpp:106:24: note: in implicit move assignment operator for 'boost::multi::layout_t<2>' first required here
                other.ref::layout_t::operator=({});
                                     ^
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../array.hpp:781:71: note: in instantiation of member function 'boost::multi::static_array<double, 2>::static_array' requested here
        array(array&& o, typename array::allocator_type const& a) noexcept : static_{std::move(o), a}{}
                                                                             ^
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/../array.hpp:782:30: note: in instantiation of member function 'boost::multi::array<double, 2>::array' requested here
        array(array&& o) noexcept : array{std::move(o), o.get_allocator()}{}
                                    ^
/Users/Shared/ornldev/code/qmcpack/external_codes/boost_multi/b-multi/test/allocator.cpp:34:3: note: in instantiation of member function 'boost::multi::array<double, 2>::array' requested here
                multi::array<double, 2>({0, 0}, 0),
                ^
1 error generated.
make[2]: *** [CMakeFiles/allocator.cppx.dir/allocator.cpp.o] Error 1
make[1]: *** [CMakeFiles/allocator.cppx.dir/all] Error 2
make: *** [all] Error 2
``` 
also get the same error with clang 16.0.6

**Comment by PDoakORNL** [comment]
But from the standpoint of QMCPACK and the afqmc unit tests if you use clang 16.0.6 we don't need this PR anymore. 

so I'm going to close it.

**Comment by correaa** [comment]
I understand the errors (primarily because I compile the unit test with all warnings on and warnings as errors), they are fixable. I need a Mac now. Let's continue here: https://gitlab.com/correaa/boost-multi/-/issues/143

**Comment by correaa** [comment]
> No that doesn't work at all.
> 
> ```
> clang: error: argument unused during compilation: '-Wnonportable-cfstrings' [-Werror,-Wunused-command-line-argument]
> ```

I don't understand where this option is coming from since I explicitly commented it https://gitlab.com/correaa/boost-multi/-/blob/master/test/CMakeLists.txt?ref_type=heads#L551

(Maybe you are not using the current version of Multi, but the version in QMCPACK)

**Pull request closed without merging**
