### PR TITLE
Add deterministic tests for excited state promotion

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
This is a part of the complete test list #1061 and may relevant to #740.

  Deterministic tests for the excited state are added to diamondC_1x1x1_pp and diamondC_2x1x1_pp testset. VMC & DMC tests are added and an electron at Gamma point is promoted.
  This test will provide a simple and quick statistical test for the excited state for a solid system.
   
  References are generated in Intel Xeon with gcc 6.2.0 and tests were passed with intel19 and clang 7.0 compiler.
  Tolerances for the mixed precision are preliminary set as the values for the ground state, and they will be adjusted after checking CDash if it is needed.

  Hyeondeok Shin

### CODE REVIEW

**Comment by prckent** [comment]
Thanks. Important to get some coverage of this functionality.

* Do we have integration tests for these? A quick grep in qmcpack/tests suggests not. Do you have the reference data to hand? We can create a new issue on this topic.
* (General point) When creating tests we should think about the code coverage. In this case a DMC test is not strictly necessary since the QMC drivers have no idea whether they are running a ground or excited state calculation. i.e. VMC should be enough. For some properties there might be a case to make that the DMC is more sensitive to mistakes in the wavefunction and hence a test is worthwhile. Now that we have them we should keep them.

**Comment by prckent** [comment]
Changed the PR name to be more accurate. This is important for writing the changelog.

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
Approving. At this point the CPU CI runs have passed, indicating that the CMakeLists.txt is not broken.

**Comment by ye-luo** [comment]
@prckent There is no statistical test in this PR. @Hyeondeok-Shin commented on the #1691 that these tests will be added in 1-2 days.

**Pull request merged**
