### PR TITLE
ORNL CADES support

### PR DESCRIPTION
**Pull request by prckent**
@kayahans Please check that I did not miss anything when I rebuilt this PR with a clean history.

(Replaces #1191 )

### CODE REVIEW

**Comment by ye-luo** [comment]
Please also add -DCMAKE_C_FLAGS="-xCOMMON-AVX512" -DCMAKE_CXX_FLAGS="-xCOMMON-AVX512" for the skylake processor because the complier generates AVX2 by default even on Skylake.

**Comment by prckent** [comment]
@PDoakORNL What are your thoughts on these modules? Using this script from my account picks up horrifically old software.

**Comment by ye-luo** [comment]
Since MKL is used, why fftw module is needed? If you have libsci loaded by default, unload it is necessary.

**Comment by kayahans** [comment]
@ye-luo is right, we can unload fftw. openmpi/3.0.0 is also apparently not used since PE-intel loads the following: 1) intel/16.0.1     2) openmpi/1.10.3   3) xalt/0.7.6       4) PE-intel/1.0

**Comment by prckent** [comment]
@kayahans Did you try to use Intel 2018?

**Comment by kayahans** [comment]
@prckent No, it was recommended in CADES website to use PE modules. Intel2018 was added late October after the update. I can try if you would like.

**Comment by kayahans** [comment]
As I remember now, it was because of this:
module load boost
Please load a programming environments (PE):
PE-gnu, PE-intel, or PE-pgi

**Comment by prckent** [comment]
Thanks. I am checking the installed options. gcc is also needed for the C++14 library.

**Comment by prckent** [comment]
(No more updates planned)

**Pull request merged**
