### PR TITLE
Fix link error in debug build with RunTimeManager

### PR DESCRIPTION
**Pull request by markdewing**
## Proposed changes
Add explicit template instantiations for RunTimeManager.

The release build works without these, but the debug build fails with a linker error.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
laptop, gcc and clang

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Could you fix also the header file `extern template` lines? It seems RunTimeManager are repeated but RunTimeControl are missing.

**Comment by markdewing** [comment]
It looks like we have no Debug builds in the CI or in the nightly testing?  That would have caught this issue.

**Comment by markdewing** [comment]
The `extern template` lines have been added for RunTimeControl, and the ones for RunTimeManager have been moved to immediately follow the class, as seems to be the pattern.

**Comment by prckent** [comment]
@markdewing Correct. There are no debug builds currently. What would be the most useful combination in your opinion?

**Pull request merged**
