### PR TITLE
Enable DiracDeterminantBatched<PlatformKind::SYCL>

### PR DESCRIPTION
**Pull request by ye-luo**
Review after #5042 being merged.
## Proposed changes
@jngkim contributed `QMCWaveFunctions/detail/SYCL/matrix_update_helper.cpp`
Currently there is no batched code path for the matrix inversion and I just connect the OMPTarget based class which runs inversion on host.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Many thanks Ye and @jngkim 

Any issues found with GPU inversion or is that the next step?

**Comment by ye-luo** [comment]
> Many thanks Ye and @jngkim
> 
> Any issues found with GPU inversion or is that the next step?

I would like to refactor all the GPU inversion classes before adding one for MKL. We currently choose either one-by-one or all batched based on the delayed update class choice. Two issues
1. all batched routine may need a lot of scratch space. We can probably subdivide a batch to blocks and do one block at a time. So enable certain degree of flexibility.
2. The host inverter and gpu inverter classes are integrated in to the DDB separately but we only choose one. I would like to do better C++ and hide the detail of inverters at the DDB level and also improve the APIs.

**Pull request merged**
