### PR TITLE
Fully functional converter for Real Kpoints from Pyscf

### PR DESCRIPTION
**Pull request by anbenali**
This is a fully working converter from Pyscf to QMCPACK generating a supercell from a series of Kpoints with real MO Coefficients.

The series of Kpoints are expanded in the converter to form a supercell  corresponding to the Kpoints used to converge the calculations. The choice of Kpoint must be such as the Kpoint generate real orbitals. The phase factor on the MO Coeffs is applied inside the converter. This feature will be moved to QMCPACK (parallel to what is done for the real space code) when Complex Orbitals are implemented. 

[WIP]: A working test case and the documentation will be provided ASAP.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Do we need/use the density fitting integral files df_ints.h5?

**Comment by ye-luo** [comment]
1. df_ints.h5 is big 14MB. Given the original input files provided here, can we generate this file if a README is provided? It seems not needed by QMCPACK for testing.
2. I'd like to have the manual reorganized in a separated PR to fix issue #996.

**Comment by anbenali** [comment]
That I don't know..

**Comment by prckent** [comment]
A fresh PR from a suitably cleaned branch will be needed - the large files need to have never been in the repo. Check with @ye-luo

**Comment by anbenali** [comment]
PR closed and resubmitted.

**Pull request closed without merging**
