### PR TITLE
Update AFQMC converter examples

### PR DESCRIPTION
**Pull request by Paul-St-Young**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Address #2851 

The only change worth a double-check is the added write permission to wavefunction HDF5 file
```
Wavefunction WavefunctionFactory::fromHDF5
-  if (!dump.open(filename, H5F_ACC_RDONLY))
+  if (!dump.open(filename, H5F_ACC_RDWR))
```

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
i7-8750H, Fedora 33 (gcc 10.2.1, python 3.9.1, h5py 3.1.0 )

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Could you say a bit more about H5F_ACC_RDONLY -> H5F_ACC_RDWR? if the change is not added, what is the behavior of the code? I'm wondering if some write failure error was not captured properly.

**Comment by Paul-St-Young** [comment]
Before the change, `afqmc.h5` is not edited during the run, so yes I agree there are write failures not being caught.
After H5F_ACC_RDONLY -> H5F_ACC_RDWR?, afqmc.h5/Wavefunction/PHMSD gets a new entry HamiltonianOperations/SparseTensor.

**Comment by ye-luo** [comment]
@mmorale3 what is your assessment on the write error capture issue?

**Comment by mmorale3** [comment]
An oversight on my end. Writing restart for hamiltonian objects was needed
at first, but by now is nearly irrelevant with the more
efficient choices. Only the sparse hamiltonian has a slow setup time and
could benefit for this. I might just disable this entirely.

**Comment by prckent** [comment]
We know from painful experience that an H5 opened for writing is at risk for fatal corruption if there is crash or similar issue ahead of the file being closed. Therefore e.g. mixing H5 inputs and outputs is not wise since you can lose input data as well as output data.

Should we live with this current RW situation and merge?

**Comment by Paul-St-Young** [comment]
Alternatively, we could disable Hamiltonian checkpoint simply by forcing `write_hdf=0` and revert to RDONLY for safety. Since @mmorale3 wants to disable this feature eventually, is it then acceptable to drop it from the tests?

**Comment by prckent** [comment]
Sounds good to me. User impact is tiny / zero  as far as I know.

**Comment by ye-luo** [comment]
Need a reproducer to look at the slipped error. Could you upload one?

**Comment by Paul-St-Young** [comment]
@ye-luo `examples/afqmc/05-N2_phmsd` is the example that hits the write failure.

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
@mmorale3 looks good to you?

**Comment by mmorale3** [comment]
Paul is working on a cleaner fix.

**Review by ye-luo — CHANGES_REQUESTED** [review]
Blocked as we are waiting for a cleaner fix.

**Comment by Paul-St-Young** [comment]
Instead of disabling `write_hdf` in each Hamiltonian object, I now disable it from `WavefunctionFactory.cpp`.
By passing an unopened restart file to `Hamiltonian::getHamiltonianOperations`, `write_hdf` is set to `false` by internal logic.

**Comment by Paul-St-Young** [comment]
After more discussions with @mmorale3, we think the entire wave function restart design needs a revamp. Right now, the user is supposed to set "restart_file" in the input, run once to generate HamiltonianOperators, then remove "restart_file" and change wavefunction file to the previously set "restart_file" in order to skip generation of the HamiltonianOperators. We want to move to a design where the user need not change the input in between runs.

Given the considerable amount of work that would entail, I move to close this PR; make a new one with just the Python changes; then create a dedicated PR for the restart issue.

Does this sound good to everyone?

**Comment by ye-luo** [comment]
You should always be able to repeat the "initial" run as you need.
wf_file="a.h5" precomptue_file="b.h5"
A run should check the existence of b.h5, if is not there, redo the precompute. If it is there, load it.
the a.h5 should not be touched.

**Comment by Paul-St-Young** [comment]
yes, that's the plan

**Review by prckent — COMMENTED** [review]
Closing this PR and then making a new one that just tackles the converter issues at e.g. https://cdash.qmcpack.org/CDash/viewTest.php?onlyfailed&buildid=185059 would be good.

**Pull request closed without merging**
