### PR TITLE
Initial SplineR2R offload

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Initial implementation.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
I feel like there is some coverage missing here that would be nice to have, although its in keeping with the spotty coverage throughout the SplineX2X files.  
The missing coverage for
`SplineR2R<ST>::mw_evaluateDetRatios()`
and one of the legs of the 
`const ST signed_one = (bc_sign & 1) ? -1 : 1;`
being my only real concern with this PR.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> I feel like there is some coverage missing here that would be nice to have, although its in keeping with the spotty coverage throughout the SplineX2X files. The missing coverage for `SplineR2R<ST>::mw_evaluateDetRatios()` and one of the legs of the `const ST signed_one = (bc_sign & 1) ? -1 : 1;` being my only real concern with this PR.

Both covered with the newly added unit test based on `LiH-x`.

**Review by PDoakORNL — APPROVED** [review]

**Pull request merged**
