### PR TITLE
Update spack version shield

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Fix non-updating spack version in README.md

## What type(s) of changes does this code introduce?

- Bugfix
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

GitHub

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by markdewing — APPROVED** [review]

**Comment by markdewing** [comment]
Test this please

**Review by ye-luo — CHANGES_REQUESTED** [review]
https://img.shields.io/spack/v/qmcpack.svg seems fine.
https://img.shields.io/spack/v/qmcpack seems wrong.

https://github.com/QMCPACK/qmcpack
https://github.com/QMCPACK/qmcpack/tree/prckent-patch-1
I always get 3.11.0.

**Comment by prckent** [comment]
This change was made because the old code was not working. The shields.io code was made today by _their tools_ and can be confirmed working via  preview.

**Comment by ye-luo** [comment]
> This change was made because the old code was not working and had not updated in months. The shields.io code was made today by _their tools_ and can be confirmed working via preview.

I was expecting to see 3.13.0. Do I miss something?

**Comment by prckent** [comment]
Interesting... now I don't. I still want to merge this and see what happens. We are using the preferred/default shields code now.

**Comment by ye-luo** [comment]
Let us get this in try this out. I tested with "private window" and got stochastic results...

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
