### PR TITLE
Nexus: add machines SuperMUC-NG and Tomcat3

### PR DESCRIPTION
**Pull request by jtkrogel**
Add support for job file generation on SuperMUC-NG at LRZ and Tomcat3.

### CODE REVIEW

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by jtkrogel** [comment]
Hold off on merge.  Updates likely needed.

**Comment by grahamlopez** [comment]
test this please

**Comment by jtkrogel** [comment]
Known issues are fixed.  OK to merge.

**Comment by jtkrogel** [comment]
Please move forward with merge.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
