### PR TITLE
updating scripts for new ci

### PR DESCRIPTION
**Pull request by grahamlopez**
This updates our current scripts for OLCF CI to use the new infrastructure.

### CODE REVIEW

**Comment by grahamlopez** [comment]
Old CI is expected to fail here, new CI expected to succeed. After this is merged, this will be the case for all following CI. At that point, I'll turn off the old (failing) robots.

**Comment by markdewing** [comment]
It appears the old CI failures prevent merging.  Do we need to turn of the protections temporarily, or is there some other way to merge this?

**Comment by grahamlopez** [comment]
I updated the scripts in place. It seems we have two choices:
1. The other choice would be to copy the scripts to have both the old and the new, merge the new scripts, then follow with another PR to remove the old scripts.
2. Disable protections to merge.

I don't mind either way.

**Comment by prckent** [comment]
I'll temporarily switch the protections.

**Pull request merged**
