### PR TITLE
Enable AFQMC by default with the MPI complex full precision build.

### LINKED ISSUE #1252: AFQMC not enabled in CI
Currently CI scripts on Rhea do not enable BUILD_AFQMC? Does anyone remember the history?
Consider AFQMC development will be more close to the main repo, we need to turn that on.

- [x] boost 1.61 needed in CI scripts. Rhea default is 1.58
- [ ] ~~update CI script to enable BUILD_AFQMC on complex builds.~~

### PR DESCRIPTION
**Pull request by ye-luo**
The default value can always be overridden via command line options.
closes #1252

### CODE REVIEW

**Comment by ye-luo** [comment]
Some painful chain reaction. AFQMC->boost::hana->gcc 6->cuda 9. Only CUDA 8 is available on rhea.

**Comment by ye-luo** [comment]
@mmorale3 @fdmalone is there AFQMC GPU code in the develop? Is QMC_CUDA reused to access AFQMC GPU code?

**Comment by mmorale3** [comment]
This is coming in the next 2 week or so. I’m moving code from miniAFQMC to the main code. In the process I’ll fix mixed precision and real builds. I’ll also stop using boost::hana, it was just for convenience.

**Comment by prckent** [comment]
@ye-luo Please file a ticket with OLCF requesting up to date software versions on rhea.

**Comment by fdmalone** [comment]
Why is the CPU build failing? I don't have access to the details.

**Pull request merged**
