### PR TITLE
Nexus: ensure weights and file order always match in qmca

### PR DESCRIPTION
**Pull request by jtkrogel**
Originally, `qmca` assumed files are provided in alphabetical order, which can cause user-provided per-twist weights to be mismatched with the target files.

In this PR, the user provided weights and files will always remain associated in the correct order (alphabetical internally, with no constraints on the user input).

@mcbennet will test.  Move to merge after his comments here.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
@mcbennet, the problem you refer to is fixed in #2118.  Please confirm.

**Comment by mcbennet** [comment]
Confirmed.

Using commit 5545802 of jtkrogel:nx_python3 branch yields the correct average.

**Comment by jtkrogel** [comment]
Hold on merge until #2118 is in.

**Comment by ye-luo** [comment]
@jtkrogel there is merge conflict needs to be resolved

**Comment by jtkrogel** [comment]
Done.

**Pull request merged**
