### PR TITLE
Update multi using release v0.80

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update Multi to the last release

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
Ok, I am doing my last set of test to save intel 19 but I am not very confident.
Acording to my tests, intel 2021/2022 should work.

For reference this below is the mysterious error in intel 19.

The line cited in the error `831 of multi/array_ref.hpp` doesn't have anything out of ordinary.
`is_convertible_v` is used create a multi "reference" instance, perhaps `is_convertible<>::value` will be more compatible and that is what I tried in my last push, but I don't know.

```
/opt/rh/gcc-toolset-9/root/usr/include/c++/9/type_traits(1336): error: class "std::__is_convertible_helper<<error-type>*** double **** false>" has no member class "type"
      : public __is_convertible_helper<_From*** _To>::type
                                                    ^
          detected during:
            instantiation of class "std::is_convertible<_From*** _To> [with _From=<error-type>*** _To=double *]" at line 2999
            instantiation of "const bool std::is_convertible_v [with _From=<error-type>*** _To=double *]" at line 831 of "/scratch/ci/actions-runner-2/_work/qmcpack/qmcpack/external_codes/boost_multi/multi/include/multi/./array_ref.hpp"
            instantiation of "auto boost::multi::basic_array<T*** D*** ElementPtr*** Layout>::at_aux(boost::multi::index={std::make_signed_t<boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={std::make_signed<std::size_t={unsigned long}>::type={std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__type={std::__match_cv_qualifiers<std::size_t={unsigned long}*** std::__make_signed_selector<std::size_t={unsigned long}*** true***
                      false>::__signed_type={std::__make_signed<unsigned long>::__type={signed long}}*** false*** false>::__type={std::__cv_selector<std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__signed_type={std::__make_signed<unsigned long>::__type={signed long}}*** false*** false>::__type={std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__signed_type={std::__make_signed<unsigned long>::__type={signed
                      long}}}}}}}}>={std::make_signed<boost::multi::size_type={std::make_signed_t<std::size_t={unsigned long}>={std::make_signed<std::size_t={unsigned long}>::type={std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__type={std::__match_cv_qualifiers<std::size_t={unsigned long}*** std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__signed_type={std::__make_signed<unsigned long>::__type={signed long}}*** false***
                      false>::__type={std::__cv_selector<std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__signed_type={std::__make_signed<unsigned long>::__type={signed long}}*** false*** false>::__type={std::__make_signed_selector<std::size_t={unsigned long}*** true*** false>::__signed_type={std::__make_signed<unsigned long>::__type={signed long}}}}}}}}>::type={std::__make_signed_selector<boost::multi::size_type={std::make_signed_t<std::size_t={unsigned
...
```

**Comment by correaa** [comment]
please test one more time

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
Intel compiler is happy now

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
Wow, the `std::is_convertible_v<T, F> -> std::is_convertible<T, F>::value` was really a wild guess.

**Comment by correaa** [comment]
technically, the version of multi here is not exactly a "release", so I am not done yet. I am going to release 0.80.1 in a few minutes for this.

**Pull request merged**
