### PR TITLE
Make short-bccH_1x1x1_ae-dmc_sdj-1-16 test longer

### PR DESCRIPTION
**Pull request by ye-luo**
See issue #241

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Shouldn't we update the expected standard error in CMakeLists.txt for this test (/2) ?

**Comment by ye-luo** [comment]
0.005 was still not very stable. Use 0.01 in both.

**Comment by prckent** [comment]
I would prefer to keep the timestep at 0.001 and lengthen the tests as originally suggested. This way we will still be able to refer to the test history.

**Comment by ye-luo** [comment]
Do we really need to refer to the test history?
Issue #241, the test was failing >20%.

**Comment by ye-luo** [comment]
@prckent All the dmc references are updated.

**Comment by prckent** [comment]
This update also removes the not needed or used parts of the Jastrow functions.

**Pull request merged**
