### PR TITLE
Fix CMake when CMAKE_BUILD_TYPE=None.

### PR DESCRIPTION
**Pull request by ye-luo**
Current [BGQ](https://cdash.qmcpack.org/CDash/viewConfigure.php?buildid=20409) builds are failing.
Add quotation marks around CMAKE_BUILD_TYPE.

Other changes are just putting all the commands in upper case as the rest of file.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Comment by grahamlopez** [comment]
test this please

**Pull request merged**
