### PR TITLE
Add deterministic test for HEG for complex orbital with the twist

### LINKED ISSUE #3104: Deterministic HEG test (low priority)
A deterministic test would help keep this code alive.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

Close #3104.

This PR adds deterministic test for HEG to cover non-backflow case and the complex orbital with the twist.
References are generated on Intel Xeon with Intel 19 compiler.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
 Workstation (Intel Xeon)

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Activated more testing just for data. The existing complex failure in the asan build suggests a different path was taken in the Monte Carlo.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
k+q space grid points are sorted by magnitude and then only the first 27 ones are picked to from SPO. Because of degeneracy, the 27th picked orbital is non-deterministic.

Change `twist="0.25 0.25 0.25"` to `twist="0.22 0.23 0.24"` resolves the issue. I think a degeneracy detector is missing in the heg orbital generation.

**Comment by Hyeondeok-Shin** [comment]
Thanks @ye-luo. Now CI passes

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thanks for working on this Hyeondeok

**Pull request merged**
