### PR TITLE
Replace the CUDA texture API with a device function.

### PR DESCRIPTION
**Pull request by jakurzak**
## Proposed changes

This PR removes the use of the texture API, which is deprecated in CUDA.
The tex1D() function with linear interpolation and clamping is replaced by a device function.

## What type(s) of changes does this code introduce?

Removing deprecated API calls.
Replacing tex1D() with a device function.

### Does this introduce a breaking change?

The change causes a small number of tests to fail by narrowly exceeding the tolerances.
This is unexpected as texture fetches are much less accurate then the code replacing them.
It is possible that the tolerances need to be adjusted - to be investigated.

## What systems has this change been tested on?

- AMD MI200
- NVIDIA A100

## Checklist

- up to date with the current state of 'develop'
- no clang formating - preserving the original formatting
- no new tests added - covered by existing tests
- no documentation added

### CODE REVIEW

**Review by PDoakORNL — DISMISSED** [review]
Unit test is missing, and would be a more straight forward way to insure correctness. We are satisified with testing indirectly through the test_coulomb*.cpp tests?

**Comment by prckent** [comment]
Removed the std:: which appears to resolve the compilation problem and allow the device math functions to be called, at least with CUDA.

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
I updated the test tolerances for a set of CUDA builds to get the tests passing. I suspect that most of the change is due to the different algorithm resulting in effectively changed referenced values. However none of the tolerances needed to be increased by much.

**Comment by prckent** [comment]
Test this please

**Comment by jakurzak** [comment]
This is what I'm getting right now on an MI250X and a Radeon 7 with ROCm 5.1.2:
[MI200_ROCm-5.1.2.txt](https:
[R7_ROCm-5.1.2.txt](https://github.com/QMCPACK/qmcpack/files/8755454/R7_ROCm-5.1.2.txt)
//github.com/QMCPACK/qmcpack/files/8755453/MI200_ROCm-5.1.2.txt)

**Comment by jakurzak** [comment]
This is what I'm getting right now on a Radeon 7 and an MI250X with ROCm 5.1.2:

- [R7_ROCm-5.1.2.txt](https://github.com/QMCPACK/qmcpack/files/8755473/R7_ROCm-5.1.2.txt)
- [MI200_ROCm-5.1.2.txt](https://github.com/QMCPACK/qmcpack/files/8755478/MI200_ROCm-5.1.2.txt)

**Comment by prckent** [comment]
All reasonable variation again. The NiO48 electron run is bigger than most of the other tests and therefore more prone to accumulating error.

**Comment by prckent** [comment]
Test this please

**Comment by jakurzak** [comment]
At this point, 0 failures on R7, 1 failure on MI250X:
[R7_ROCm-5.1.2.txt](https://github.com/QMCPACK/qmcpack/files/8766315/R7_ROCm-5.1.2.txt)
[MI250X_ROCm-5.1.2.txt](https://github.com/QMCPACK/qmcpack/files/8766316/MI250X_ROCm-5.1.2.txt)

**Comment by prckent** [comment]
Should be fixed now.

**Comment by prckent** [comment]
Note that other build types may need a similar process, but getting the default build handled in this PR is fine with me. I didn't see anything concerning in the builds I did with CUDA but there might still be a few edge cases.

**Comment by ye-luo** [comment]
Test this please

**Comment by jakurzak** [comment]
- mixed prec, real - all tests pass
- no mixed prec, real - all tests pass
- no mixed prec, complex - all tests pass
- mixed prec, complex - one failure:

R7:
```
183/231 Test #452: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy ............***Failed    0.03 sec
Tests for series 0
  Testing quantity: LocalEnergy
    reference mean value     : -19.35642193
    reference error bar      :   0.00001000
    computed  mean value     : -19.35639124
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00003000  (  3.00000000 sigma)
    deviation from reference :   0.00003069  (  3.06940000 sigma)
    error bar of deviation   :   0.00001000
    significance probability :   0.99785497  (gaussian statistics)
    status of this test      :   fail
```

MI250X:
```
183/231 Test #417: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy ............***Failed    0.02 sec
Tests for series 0
  Testing quantity: LocalEnergy
    reference mean value     : -19.35642193
    reference error bar      :   0.00001000
    computed  mean value     : -19.35637490
    computed  error bar      :   0.00000000
    pass tolerance           :   0.00003000  (  3.00000000 sigma)
    deviation from reference :   0.00004703  (  4.70270000 sigma)
    error bar of deviation   :   0.00001000
    significance probability :   0.99999743  (gaussian statistics)
    status of this test      :   fail
```

**Comment by ye-luo** [comment]
I ran some short statistical tests on a NVIDIA GPU.
```
$ ctest -R diamondC_2x1x1 -E "long|opt"
Test project /scratch/opt/cleanup/qmcpack/build_intel_legacy_cuda
      Start 340: short-diamondC_2x1x1_pp-vmc_sdj-1-16
 1/86 Test #340: short-diamondC_2x1x1_pp-vmc_sdj-1-16 .....................................   Passed   18.92 sec
      Start 341: short-diamondC_2x1x1_pp-vmc_sdj-1-16-kinetic
 2/86 Test #341: short-diamondC_2x1x1_pp-vmc_sdj-1-16-kinetic .............................   Passed    0.05 sec
      Start 342: short-diamondC_2x1x1_pp-vmc_sdj-1-16-totenergy
 3/86 Test #342: short-diamondC_2x1x1_pp-vmc_sdj-1-16-totenergy ...........................   Passed    0.05 sec
      Start 343: short-diamondC_2x1x1_pp-vmc_sdj-1-16-eeenergy
 4/86 Test #343: short-diamondC_2x1x1_pp-vmc_sdj-1-16-eeenergy ............................   Passed    0.05 sec
      Start 344: short-diamondC_2x1x1_pp-vmc_sdj-1-16-samples
 5/86 Test #344: short-diamondC_2x1x1_pp-vmc_sdj-1-16-samples .............................   Passed    0.05 sec
      Start 345: short-diamondC_2x1x1_pp-vmc_sdj-1-16-potential
 6/86 Test #345: short-diamondC_2x1x1_pp-vmc_sdj-1-16-potential ...........................   Passed    0.06 sec
      Start 346: short-diamondC_2x1x1_pp-vmc_sdj-1-16-ionion
 7/86 Test #346: short-diamondC_2x1x1_pp-vmc_sdj-1-16-ionion ..............................   Passed    0.05 sec
      Start 347: short-diamondC_2x1x1_pp-vmc_sdj-1-16-localecp
 8/86 Test #347: short-diamondC_2x1x1_pp-vmc_sdj-1-16-localecp ............................   Passed    0.06 sec
      Start 348: short-diamondC_2x1x1_pp-vmc_sdj-1-16-nonlocalecp
 9/86 Test #348: short-diamondC_2x1x1_pp-vmc_sdj-1-16-nonlocalecp .........................   Passed    0.05 sec
      Start 349: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16
10/86 Test #349: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16 ......................   Passed   21.69 sec
      Start 350: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-kinetic
11/86 Test #350: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-kinetic ..............   Passed    0.08 sec
      Start 351: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-totenergy
12/86 Test #351: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-totenergy ............   Passed    0.08 sec
      Start 352: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-eeenergy
13/86 Test #352: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-eeenergy .............   Passed    0.08 sec
      Start 353: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-samples
14/86 Test #353: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-samples ..............   Passed    0.08 sec
      Start 354: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-potential
15/86 Test #354: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-potential ............   Passed    0.08 sec
      Start 355: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-ionion
16/86 Test #355: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-ionion ...............   Passed    0.07 sec
      Start 356: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-localecp
17/86 Test #356: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-localecp .............   Passed    0.08 sec
      Start 357: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-nonlocalecp
18/86 Test #357: short-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-16-nonlocalecp ..........   Passed    0.08 sec
      Start 358: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16
19/86 Test #358: short-diamondC_2x1x1_hybridrep_pp-vmc_sdj-1-16 ...........................   Passed    1.98 sec
      Start 359: short-diamondC_2x1x1_pp-dmc_sdj-1-16
20/86 Test #359: short-diamondC_2x1x1_pp-dmc_sdj-1-16 .....................................   Passed  829.50 sec
      Start 360: short-diamondC_2x1x1_pp-dmc_sdj-1-16-totenergy
21/86 Test #360: short-diamondC_2x1x1_pp-dmc_sdj-1-16-totenergy ...........................   Passed    0.08 sec
      Start 361: short-diamondC_2x1x1_pp-dmc_4r_sdj-1-4
22/86 Test #361: short-diamondC_2x1x1_pp-dmc_4r_sdj-1-4 ...................................   Passed  280.86 sec
      Start 362: short-diamondC_2x1x1_pp-dmc_4r_sdj-1-4-totenergy
23/86 Test #362: short-diamondC_2x1x1_pp-dmc_4r_sdj-1-4-totenergy .........................   Passed    0.07 sec
      Start 363: short-diamondC_2x1x1_pp-dmc-reconf_sdj-1-16
24/86 Test #363: short-diamondC_2x1x1_pp-dmc-reconf_sdj-1-16 ..............................   Passed   77.62 sec
      Start 364: short-diamondC_2x1x1_pp-dmc-reconf_sdj-1-16-totenergy
25/86 Test #364: short-diamondC_2x1x1_pp-dmc-reconf_sdj-1-16-totenergy ....................   Passed    0.08 sec
      Start 365: short-diamondC_2x1x1_pp-dmc-dla_sdj-1-16
26/86 Test #365: short-diamondC_2x1x1_pp-dmc-dla_sdj-1-16 .................................   Passed  785.50 sec
      Start 366: short-diamondC_2x1x1_pp-dmc-dla_sdj-1-16-totenergy
27/86 Test #366: short-diamondC_2x1x1_pp-dmc-dla_sdj-1-16-totenergy .......................   Passed    0.09 sec
      Start 367: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16
28/86 Test #367: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16 .............................   Passed   19.01 sec
      Start 368: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-kinetic
29/86 Test #368: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-kinetic .....................   Passed    0.05 sec
      Start 369: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-totenergy
30/86 Test #369: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-totenergy ...................   Passed    0.05 sec
      Start 370: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-eeenergy
31/86 Test #370: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-eeenergy ....................   Passed    0.05 sec
      Start 371: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-samples
32/86 Test #371: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-samples .....................   Passed    0.05 sec
      Start 372: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-potential
33/86 Test #372: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-potential ...................   Passed    0.05 sec
      Start 373: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-ionion
34/86 Test #373: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-ionion ......................   Passed    0.05 sec
      Start 374: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-localecp
35/86 Test #374: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-localecp ....................   Passed    0.05 sec
      Start 375: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-nonlocalecp
36/86 Test #375: short-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-nonlocalecp .................   Passed    0.05 sec
      Start 376: short-diamondC_2x1x1_pp-dmc_sdj_excited-1-16
37/86 Test #376: short-diamondC_2x1x1_pp-dmc_sdj_excited-1-16 .............................   Passed  795.30 sec
      Start 377: short-diamondC_2x1x1_pp-dmc_sdj_excited-1-16-totenergy
38/86 Test #377: short-diamondC_2x1x1_pp-dmc_sdj_excited-1-16-totenergy ...................   Passed    0.08 sec
      Start 394: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1
39/86 Test #394: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1 ..............................   Passed    1.83 sec
      Start 395: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-kinetic
40/86 Test #395: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-kinetic ......................   Passed    0.05 sec
      Start 396: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-totenergy
41/86 Test #396: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-totenergy ....................   Passed    0.04 sec
      Start 397: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-eeenergy
42/86 Test #397: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-eeenergy .....................   Passed    0.05 sec
      Start 398: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-samples
43/86 Test #398: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-samples ......................   Passed    0.04 sec
      Start 399: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-potential
44/86 Test #399: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-potential ....................   Passed    0.04 sec
      Start 400: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-ionion
45/86 Test #400: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-ionion .......................   Passed    0.05 sec
      Start 401: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-localecp
46/86 Test #401: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-localecp .....................   Passed    0.04 sec
      Start 402: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-nonlocalecp
47/86 Test #402: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-nonlocalecp ..................   Passed    0.05 sec
      Start 403: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-flux
48/86 Test #403: deterministic-diamondC_2x1x1_pp-vmc_sdj-1-1-flux .........................   Passed    0.04 sec
      Start 404: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1
49/86 Test #404: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1 ......................   Passed    1.72 sec
      Start 405: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-kinetic
50/86 Test #405: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-kinetic ..............   Passed    0.05 sec
      Start 406: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy
51/86 Test #406: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy ............   Passed    0.04 sec
      Start 407: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-eeenergy
52/86 Test #407: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-eeenergy .............   Passed    0.05 sec
      Start 408: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-samples
53/86 Test #408: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-samples ..............   Passed    0.04 sec
      Start 409: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-potential
54/86 Test #409: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-potential ............   Passed    0.05 sec
      Start 410: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-ionion
55/86 Test #410: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-ionion ...............   Passed    0.04 sec
      Start 411: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-localecp
56/86 Test #411: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-localecp .............   Passed    0.05 sec
      Start 412: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-nonlocalecp
57/86 Test #412: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-nonlocalecp ..........   Passed    0.04 sec
      Start 413: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-flux
58/86 Test #413: deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-flux .................   Passed    0.05 sec
      Start 414: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1
59/86 Test #414: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1 ...............   Passed    1.74 sec
      Start 415: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-kinetic
60/86 Test #415: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-kinetic .......   Passed    0.05 sec
      Start 416: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-totenergy
61/86 Test #416: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-totenergy .....   Passed    0.04 sec
      Start 417: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-eeenergy
62/86 Test #417: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-eeenergy ......   Passed    0.04 sec
      Start 418: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-samples
63/86 Test #418: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-samples .......   Passed    0.04 sec
      Start 419: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-potential
64/86 Test #419: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-potential .....   Passed    0.04 sec
      Start 420: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-ionion
65/86 Test #420: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-ionion ........   Passed    0.04 sec
      Start 421: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-localecp
66/86 Test #421: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-localecp ......   Passed    0.04 sec
      Start 422: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-nonlocalecp
67/86 Test #422: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-nonlocalecp ...   Passed    0.05 sec
      Start 423: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-flux
68/86 Test #423: deterministic-diamondC_2x1x1_pp-delayed_update-vmc_sdj-1-1-flux ..........   Passed    0.04 sec
      Start 424: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1
69/86 Test #424: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1 ..............................   Passed    1.70 sec
      Start 425: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-kinetic
70/86 Test #425: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-kinetic ......................   Passed    0.04 sec
      Start 426: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-totenergy
71/86 Test #426: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-totenergy ....................   Passed    0.04 sec
      Start 427: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-eeenergy
72/86 Test #427: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-eeenergy .....................   Passed    0.04 sec
      Start 428: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-samples
73/86 Test #428: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-samples ......................   Passed    0.04 sec
      Start 429: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-potential
74/86 Test #429: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-potential ....................   Passed    0.04 sec
      Start 430: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-ionion
75/86 Test #430: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-ionion .......................   Passed    0.05 sec
      Start 431: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-localecp
76/86 Test #431: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-localecp .....................   Passed    0.05 sec
      Start 432: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-nonlocalecp
77/86 Test #432: deterministic-diamondC_2x1x1_pp-dmc_sdj-1-1-nonlocalecp ..................   Passed    0.04 sec
      Start 433: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1
78/86 Test #433: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1 ......................   Passed    1.70 sec
      Start 434: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-kinetic
79/86 Test #434: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-kinetic ..............   Passed    0.04 sec
      Start 435: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-totenergy
80/86 Test #435: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-totenergy ............   Passed    0.04 sec
      Start 436: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-eeenergy
81/86 Test #436: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-eeenergy .............   Passed    0.04 sec
      Start 437: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-samples
82/86 Test #437: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-samples ..............   Passed    0.04 sec
      Start 438: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-potential
83/86 Test #438: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-potential ............   Passed    0.05 sec
      Start 439: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-ionion
84/86 Test #439: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-ionion ...............   Passed    0.04 sec
      Start 440: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-localecp
85/86 Test #440: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-localecp .............   Passed    0.05 sec
      Start 441: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-nonlocalecp
86/86 Test #441: deterministic-diamondC_2x1x1_pp-dmc_sdj_excited-1-1-nonlocalecp ..........   Passed    0.04 sec

100% tests passed, 0 tests failed out of 86

Label Time Summary:
QMCPACK                     = 41924.47 sec*proc (14 tests)
QMCPACK-checking-results    =   3.76 sec*proc (72 tests)
cause_unknown               = 14545.66 sec*proc (5 tests)
deterministic               =  10.58 sec*proc (48 tests)
intermittent_stat_fail      = 14545.66 sec*proc (5 tests)
quality_unknown             = 41928.23 sec*proc (86 tests)
unstable                    =   1.86 sec*proc (29 tests)

Total Test time (real) = 2842.94 sec
```

**Comment by ye-luo** [comment]
@jakurzak I updated deterministic-diamondC_2x1x1_pp-vmc_sdj_excited-1-1-totenergy tolerance.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Review by prckent — APPROVED** [review]

**Pull request merged**
