### PR TITLE
nexus: add makov payne correction, make plotting robust

### PR DESCRIPTION
**Pull request by jtkrogel**
Add ability to calculate the first order Makov-Payne correction for any cell.  Supported in new function 'makov_payne' in structure.py.

Also improve robustness of plotting generally, including tools like qmca.  Previously plots would fail in some environments (e.g. Titan at OLCF) due to default backend issues.  This is now fixed.  Fix contributed by Kayahan Saritas.

### CODE REVIEW

**Comment by prckent** [comment]
Are there any plans to add more recent schemes?

**Comment by prckent** [comment]
ok to test

**Comment by jtkrogel** [comment]
I don't have direct plans, but I am open to suggestions.

**Comment by prckent** [comment]
e.g. The Feysoldt defect alignment scheme or its various extensions. Ganesh, Ram must have opinions.

**Pull request merged**
