### PR TITLE
Update sycl include

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Kill a few warning when using sycl
1. `--dpcpp` option is gone
2. sycl header file changed namespace by replacing CL with sycl. CL namespace is deprecated.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
sunspot

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
LGTM

**Pull request merged**
