### PR TITLE
Update more short test error bars

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Address more of the ongoing short test statistical failures

See cdash for current failures

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

None

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
(Wait - I'll add some NiO ones to clear the NiO-a4 tests.)

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
`short-H4-RHF-orb-opt-16-1-totenergy` the RHF case is known broken. https://github.com/QMCPACK/qmcpack/issues/4476
Please do not touch.

short-C4_md-ae-excited-qp-vmc-1-16-totenergy was mentioned but I don't see any change related to it.

I have difficulty to review this PR. Could you break it up?

I saw bccH and NiO_a4 largely OK. Could you make a separate PR for them?

**Comment by prckent** [comment]
I'll break this up this time, but it is a bunch of work for a 17 line change.

I'll delete the H4 case. The one to study is the DMC case. The other cases are reasonable deviations from the old reference error bars, nothing obviously abnormal. Meanwhile the opt then DMC run totally fails. Could be a simple handoff problem between the drivers.

**Comment by ye-luo** [comment]
In this case, the time consuming part is clicking links on cdash to understand what the issues are and how bad the statistics are in each case, not really the changes.

**Comment by prckent** [comment]
Changed my mind -- I don't have the time to break these up. I have removed the list and the H4 change. These are all modest changes.

**Comment by prckent** [comment]
Adding a reminder than H4 opt-dmc is totally broken as noted in https://github.com/QMCPACK/qmcpack/issues/4476 
The other optimization failures on cdash associated with H4 appear to be "reasonable" statistical variation. This doesn't prove the implementation is OK but the results are clearly not wildly wrong or showing signs of outliers.

**Review by ye-luo — APPROVED** [review]
LGTM. bccH and NiO are modest adjustment. The only large change is the variance in the case of diamondC but error bars of variance are naturally less reliable.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
