### PR TITLE
Add description of performance tests to manual

### LINKED ISSUE #165: Running of performance tests not in manual
Descriptions needed, similar to tests/performance/NiO/readme.

### PR DESCRIPTION
**Pull request by prckent**
Closes #165

### CODE REVIEW

**Comment by ye-luo** [comment]
Wait a second. Let me take the chance to make the dmc heavier in perf tests.

**Comment by ye-luo** [comment]
Done.

**Comment by ye-luo** [comment]
@prckent Do we need to delete the last paragraph in 2.10 since it has been moved to 2.7.2?

**Comment by prckent** [comment]
@ye-luo This is too heavy. Please change to 3 blocks of 5 steps and push the change again. This is still a three fold increase in cost (runtime). We *do* need more than 1 step per block to dilute the determinant recalculation, so I am OK with 5.

**Comment by prckent** [comment]
@ye-luo No, we don't want to delete the last paragraph of 2.10. This duplication is intentional. I will add a pointer back to 2.7.2 though.

**Comment by prckent** [comment]
@ye-luo Actually I can't think of a good reason for 3 blocks. 2 preferred. This is only twice the cost of now but better distributed into 2 blocks.

**Comment by prckent** [comment]
After discussion we'll try the 5 blocks for now.

**Comment by ye-luo** [comment]
Now on oxygen Intel2017-Release build, performance-NiO-cpu-S32-J3-1-16 takes 6m 23s
DMC 51.329s->217.103s

**Comment by prckent** [comment]
Acceptable. Even with the long tests that we run weekly, overall execution times for the tests (viewable in the advanced view) are 3h30min for Intel2017-Release and 4h for Intel2017-Complex.

**Pull request merged**
