### PR TITLE
AFQMC: Add energy estimator with different Hamiltonian (from propagation)

### PR DESCRIPTION
**Pull request by mmorale3**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Small change to allow the use of a different Hamiltonian (from the one used for propagation)
in the energy evaluation.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Quartz, Lassen

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Documentation has been added

### CODE REVIEW

**Comment by prckent** [comment]
Are you setup with clang format?

**Comment by mmorale3** [comment]
No

**Review by ye-luo — COMMENTED** [review]
LGTM
Do you prefer @mmorale3 format the source code before merging?

**Review by ye-luo — APPROVED** [review]
@mmorale3 will format the whole AFQMC folder in a later PR.

**Comment by prckent** [comment]
Thanks @mmorale3 for the future reformat. We are overdue to reformat the codebase again.

**Pull request merged**
