### PR TITLE
Rename EstimatorManager EstimatorManagerBase.  

### PR DESCRIPTION
**Pull request by rcclay**
This is pull request 1/3 to resolve issue #214.  This renames EstimatorManager to EstimatorManagerBase, and updates all references to EstimatorManager in the code to EstimatorManagerBase.  While just a rename for now, the next pull request will split current functionality between a derived class EstimatorManager and EstimatorManagerBase.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by grahamlopez** [comment]
@rcclay Here's the CI error:
```
Adding example tests for QMCPACK
-- Configuring done
CMake Error at src/QMCDrivers/CMakeLists.txt:131 (ADD_LIBRARY):
  Cannot find source file:

    ../Estimators/EstimatorManagerBase.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
```

**Comment by rcclay** [comment]
Whoa.  Is CI up and running?

**Comment by rcclay** [comment]
Forgot that EstimatorManagerBase wasn't version controlled since I added it.  I dumb.  That should fix it.

**Comment by jtkrogel** [comment]
Looks OK to me.

**Pull request merged**
