### PR TITLE
Nexus: support AMD nodes on Cori

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Allow user to submit jobs to new AMD nodes on Cori.

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Review by markdewing — DISMISSED** [review]

**Comment by djstaros** [comment]
Can someone please also change the write_job_header function to include AMD nodes and merge this change?

**Comment by jtkrogel** [comment]
@djstaros I clearly didn't read far enough down in the file.  Better now?

**Comment by djstaros** [comment]
@jtkrogel Yes, great. Thanks!

**Review by markdewing — APPROVED** [review]

**Pull request merged**
