### PR TITLE
Rename base classes

### PR DESCRIPTION
**Pull request by ye-luo**
The following base classes are renamed to reflect the physics and their use and be concise.
OrbitalBase -> WaveFunctionComponent
OrbitalBuilderBase -> WaveFunctionComponentBuilder
SPOSetBase -> SPOSet

As part of #861.

### CODE REVIEW

**Comment by prckent** [comment]
I suggest we only merge after v3.5.0 is released, which should happen this week.

**Comment by ye-luo** [comment]
If someone needs to update their branches currently diverged, there is no difference merge before or after 3.5 release.
If someone feels more comfortable to start with a released version, merge now is better than after.
Since we may produce 3.5.1. It has to be delayed even after that. Not good...
@prckent What is the main reason to merge after v3.5.0?

**Comment by prckent** [comment]
We can flag the upcoming changes in the release notes.

**Comment by ye-luo** [comment]
Why not just merge? It is much simpler.

**Comment by PDoakORNL** [comment]
This is developer level change not visible from the user level correct? I don't see why we should delay.  It's certainly going to complicate continued work on my branch.

**Comment by ye-luo** [comment]
8 builds {real,cplx} {AoS,SoA} {full precison, mixed precision} are good with BGClang and Intel compilers.

**Comment by ye-luo** [comment]
CI checks CPU builds with GNU and CUDA AoS builds with GNU.
I manually checked CUDA SoA build real and complex.
Everything is fine.

**Comment by ye-luo** [comment]
If we want to keep the history as linear as possible, this can only be merged after master is merged back to develop.

**Pull request merged**
