### PR TITLE
Add QMC_DATA to nitrogen CI

### LINKED ISSUE #3819: Add QMC_DATA reference inputs to self-hosted CI
**Is your feature request related to a problem? Please describe.**
https://github.com/QMCPACK/qmcpack/issues/3818 made it through CI since there are several sets of tests that need "large" inputs that are not run if QMC_DATA and the necessary files are not setup. 

**Describe the solution you'd like**
Since we have no storage concerns for self-hosted CI, configure QMC_DATA for these runs. 

**Describe alternatives you've considered**

**Additional context**

A full set of files are locally on sulfur:/scratch/pk7/QMC_DATA_FULL . CI could use a copy of this data, not the current files. Today CI only really needs one of the NiO files, but it is easy to envisage us adding a deterministic molecular run in future based on the molecular performance tests to cover a large open boundaries case.

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add `QMC_DATA` directory to nitrogen CI tests, (QMC_DATA is already present).
Fixes #3819 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
must pass nitrogen CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Review by prckent — CHANGES_REQUESTED** [review]
Unless I misunderstood, QMC_DATA_DIR is only set conditional on the host being sulfur

**Comment by williamfgc** [comment]
@prckent great catch, this was my oversight. Thanks!

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]
nitrogen CI has picked up QMC_DATA in the configure step

**Pull request merged**
