### PR TITLE
Wave function (ionic) derivative unit tests

### PR DESCRIPTION
**Pull request by rcclay**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds unit tests for the ionic wave function and Hamiltonian derivatives.  I have included checks for single slater w/ and w/o jastrows, and MSD w/ and w/o Jastrows.  For MSD wave functions, the code is not implemented, but the reference derivatives have been calculated and corresponding checks have been included but commented out.  

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
Assuming CI passes.

**Review by prckent — CHANGES_REQUESTED** [review]
Very minor request: rename test_derivs as something more specific e.g. test_ion_electron_derivatives or something similar you are happy with.

**Comment by rcclay** [comment]
Looks like one of the kinetic energy derivatives in mixed precision is a tad off.  Is there a way to increase the test tolerance for the mixed precision builds, or should I disable the new checks for mixed precision?

**Comment by ye-luo** [comment]
> Looks like one of the kinetic energy derivatives in mixed precision is a tad off. Is there a way to increase the test tolerance for the mixed precision builds, or should I disable the new checks for mixed precision?

Use epsilon() see
https://github.com/QMCPACK/qmcpack/blob/65ee46c54d2fe16441e9d13c65aa670035cc7707/src/QMCWaveFunctions/tests/test_TrialWaveFunction_diamondC_2x1x1.cpp#L464

**Comment by rcclay** [comment]
OK!  @prckent I've added some function calls in the unit test (just checking for crashes) that should touch a lot more of the derivative code.  I've also tweaked the tolerances in various tests, so this should all hopefully pass the CI now.

**Pull request merged**
