### PR TITLE
Nitrogen nightly script updates

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Small updates to record the current working version.

The nompi builds work with these updates by using a serial HDF5 package.

Built with spack version:
git log|head
commit 27bd4a5cdd478dd5d05706cbb634d18c4e96cd54
Author: Thomas Kluyver <takowl@gmail.com>
Date:   Fri Mar 13 14:05:31 2020 +0100

## What type(s) of changes does this code introduce?

- Bugfix
- Build related changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

nitrogen

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Yes/No. Code added or changed in the PR has been clang-formatted
- NA. Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
oxygenCI/gpu failed for PR-unrelated reason.

**Comment by prckent** [comment]
This failed in deterministic-unit_test_hamiltonian as part of the full precision GPU build. We either have an unreliable test or unreliable hardware since no application source code was modified here.

I will retrigger the CI.

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Another failure.

build_gcccuda_full will run the same test on oxygen "independently" in the next hour or two and report to cdash. We can see if the failure occurs there as well. It did not run yesterday due to the Intel MPI configuration problem/hang.

**Comment by prckent** [comment]
There appears to be a bug in CUDA compiled unit_test_hamiltonian, could be the underlying code or could be the test. On nitrogen the complex build failed https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_hamiltonian&date=2020-03-25 but the regularly nightlies passed.
```
[0m-------------------------------------------------------------------------------
 [0mCoulomb PBC AB CUDA BCC H
 [0m-------------------------------------------------------------------------------
 [0;37m qmcpack/src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp:101
 [0m...............................................................................

 [0;37m qmcpack/src/QMCHamiltonians/tests/test_coulomb_CUDA.cpp:189:  [0m [1;31mFAILED:
 [0m [0;36m  REQUIRE( local_energy[0] == Approx(-2.219665062) )
 [0mwith expansion:
 [1;33m  -2.2122131981 == Approx( -2.219665062 )
 [0m
```

**Comment by PDoakORNL** [comment]
I notice that the value is one of two things. either one that is close enough to pass or one in the the -2.212 area.  I believe this sort of behavior from the legacy CUDA has been observed in the past.

**Comment by PDoakORNL** [comment]
I restarted the CI again for gpu but I think if it fails we should just merge.  This has nothing to do with this PR.

**Comment by prckent** [comment]
Third time is the charm.

**Pull request merged**
