### PR TITLE
Add deterministic test for batched VMC with multiple walkers.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This PR is to add deterministic test on diamond 2x1x1 for batched VMC driver with multiple walkers. 
Tests with batched determinant class and without it are added.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
 Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
@Hyeondeok-Shin helped me to make those two tests to cover batched drivers and batched single determinant.

**Comment by ye-luo** [comment]
Okay to test

**Comment by prckent** [comment]
I think this would be our longest deterministic test: 2 walkers, twice 3 equilibration, 3 steps x 3 blocks with "2" substeps. Where have they been tested? It would be good to see   mixed complex cpu and mixed complex offload which are probably most likely to have the largest numerical deviations.

**Comment by Hyeondeok-Shin** [comment]
@prckent It was tested in Intel Xeon workstation and time for the test is almost similar with the other VMC or DMC deterministic tests for diamond 2x1x1 (~ 1 sec).  3 blocks & 3 steps & 2 substeps & 3 warmupsteps are the unified setting we've been used for the deterministic tests so far.  Because other tests are already using the same number of steps and blocks, I think it seems enough but I can give exception if it is needed.

**Review by prckent — APPROVED** [review]
Lets try it, assuming the CI obliges.

**Comment by prckent** [comment]
Test this please

**Pull request merged**
