### PR TITLE
Add ProjectData ref member to WaveFunctionPool from QMCMain

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Propagate `ProjectData` information from top QMCMain to WaveFunctionPool as a const references member
Needed to pass complex/real info at runtime
Modified unit tests accordingly which is most of the current PR work
Related to #3411 #4099

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 22, must pass CI variants

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
If passing `complex/real` is the need, please pass a bool not the whole ProjectData.

**Comment by williamfgc** [comment]
@ye-luo just thinking ahead if we move more compile-time configurations to runtime variants to ProjectData: e.g. Mixed precision, AFQMC (?). It's also currently done for `QMCDriver`.

**Comment by ye-luo** [comment]
QMCDriver depends on ProjectData because ProjectData holds the counter of QMC runs 000, 001. It is different story from all the pools.

**Comment by prckent** [comment]
The two options intended to be made compile time are QMC_COMPLEX and QMC_MIXED_PRECISION, with QMC_COMPLEX being the most useful and requiring the most work, particularly around the spline handling. AFQMC is a feature flag not a numerics flag and will remain a compile time option.

**Comment by ye-luo** [comment]
We could create a struct with all the flags inside ProjectData and pass it to pools instead of the whole ProjectData.

**Comment by williamfgc** [comment]
I've been thinking more about options and one could be just having two bool members (the scope) as part of the pool classes to keep it simple. ProjectData will only be at the Pool constructor level so we know it can only come from it Thoughts? 

```
WavefunctionPool(const ProjectData& project_data, ...) : is_complex_(project_data.IsComplex() ), is_half_precision_(project_data.isHalfPrecision(), ...
```

**Comment by ye-luo** [comment]
With a struct for flags, we don't need change these APIs again when adding or removing flags happens.
The global mixed precision control may go away.
PS: it is called mixed precision not half precision. Also make sure make the stored flags in pools marked const.

**Comment by williamfgc** [comment]
> With a struct for flags, we don't need change these APIs again when adding or removing flags happens.
The struct would be something like `struct RuntimeOptions { bool is_complex_; bool is_mixed_precision_; }`?  Would a `std::array<bool, 2>` be sufficient? Technically, break API but these are not going to change very often (if ever). Thoughts?

**Comment by ye-luo** [comment]
> > With a struct for flags, we don't need change these APIs again when adding or removing flags happens.
> 
> The struct would be something like `struct RuntimeOptions { bool is_complex_; bool is_mixed_precision_; }`? Would a `std::array<bool, 2>` be sufficient? Technically, breaks API due to the number of elements, but these are not going to change very often (if ever). Thoughts?

`struct RuntimeOptions { bool is_complex_; bool is_mixed_precision_; }` is my choice. With `std::array<bool, 2>` , it is unclear about the meaning of bool switches.
Pass RuntimeOptions by value and mark its object as a const member in Pool classes. Since we use struct and keep member public, here is no need to put the underscore at the end of variable names.

**Comment by PDoakORNL** [comment]
I think from our API perspective the struct RuntimeOptions is a fine way to minimize significant change to the API. I'd argue that  adding elements to the struct is only an ABI break. We offer zero assurance that there will be binary level compatibility between different modules with different commits of the code.

This is basically just a really light input class.

**Comment by PDoakORNL** [comment]
What I'm trying to get a feel for is how do we deal with the eventual issue that we have many API's essentially defined by Real and Value currently hidden by the fact that they derive from QMCTraits and that has preprocessor swapping of type aliases.   We need to dispatch based on that.
So somehwhere there will be many:
```
  if ( RuntimeOptions.isMixed)
     someMagicType = std::make_unique<ParticleSet<float,double>>;
  else
     someMagicType = std::make_unique<ParticleSet<double,double>>;
```
I guess `SomeMagicType` could be a variant.

In other codes I've done something like the following:

```
enum class RTO {
FLOAT
DOUBLE,
COMPLEX,
DOUBLE_COMPLEX
}

RTO runtime_options;
...
//Input is parsed
//based on that runtime options gets a enum value that can be decoded at runtime to a particular statically typed code path. 
runIt = [&](auto& qmc_main) {
   qmc_main.execute(cur)
...
};

switch runtime_options {
   case rto::FLOAT:
       QMCMain<float, double> qmcmain;
       runIt(qmcmain);
       break;
...
   case rto::DOUBLE_COMPLEX:
       QMCMain<double, std:;Complex<double>> qmcmain;
       runIt(qmcmain);
       break;
}
```

**Comment by ye-luo** [comment]
> So I think this idea is fine, but I'm trying to get a feel for is how do we deal with the eventual issue that we have many API's essentially defined by Real and Value currently hidden by the fact that they derive from QMCTrait.
> 
> So I think somewhere there will be many:
> 
> ```
>   if ( RuntimeOptions.isMixed)
>      someMagicType = std::make_unique<ParticleSet<float,double>>;
>   else
>      someMagicType = std::make_unique<ParticleSet<double,double>>;
> ```
> 
> I guess `SomeMagicType` could be a variant.
> 
> In other codes I've done something like the following:
> 
> ```
> enum class RTO {
> FLOAT
> DOUBLE,
> COMPLEX,
> DOUBLE_COMPLEX
> }
> 
> RTO runtime_options;
> ...
> //Input is parsed
> //based on that runtime options gets a enum value that can be decoded at runtime to a particular statically typed code path. 
> runIt = [&](auto& qmc_main) {
>    qmc_main.execute(cur)
> ...
> };
> 
> switch runtime_options {
>    case rto::FLOAT:
>        QMCMain<float, double> qmcmain;
>        runIt(qmcmain);
>        break;
> ...
>    case rto::DOUBLE_COMPLEX:
>        QMCMain<double, std:;Complex<double>> qmcmain;
>        runIt(qmcmain);
>        break;
> }
> ```
> 
> Which I know we're trying to avoid.

A second thought. Do we really need to make the whole particleSet template or maybe we can just make ParticleSet::R as a variant between Vector<float> and Vector<double>.

**Comment by williamfgc** [comment]
@ye-luo approach is what I'd follow. Preferably, only certain affected member functions (if private even better as all templates would be in one translation unit) would follow this pattern instead of an entire class. It would difficult putting them in containers

**Comment by PDoakORNL** [comment]
Well I'm interested in what that will end up looking like.  This is a pretty general issue.  Template parameters extended up to the scope of main is not really what is desired.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
