### PR TITLE
remove deprecated functions update Multi

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Update multi and remove use of deprecated functions.
Also finding likely bugs in asserts of original code.

## What type(s) of changes does this code introduce?

- Bugfix
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 22.04

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by correaa** [comment]
please merge if test pass (i am stopping here for now because i see a rocm test failing and i am not sure if it is false positive)

**Comment by ye-luo** [comment]
> please merge if test pass (i am stopping here for now because i see a rocm test failing and i am not sure if it is false positive)

The failure (Timeout) was likely the sporadic failure from ROCm runtime libraries.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]
LGTM

**Pull request merged**
