### PR TITLE
Make PyscfToQmcpack.py python3 compatible

### PR DESCRIPTION
**Pull request by aannabe**
make PyscfToQmcpack python3 compatible

### CODE REVIEW

**Comment by prckent** [comment]
Any idea what is going on in the "Strange If Statement"? Why do we even print a message?...

**Comment by anbenali** [comment]
It should be straight forward and the if statement was there before we
could handle complex. I am rewriting and cleaning  a bit that converter but
will get back to it once my mother leaves next week... between baby sitting
and mother sitting I am a bit overwhelmed:)

**Comment by prckent** [comment]
@aannabe  Nice to have such a simple upgrade to Python3. Happy to merge.

**Comment by ye-luo** [comment]
Does python 2 complain? or we don't need python 2 in this case.

**Comment by markdewing** [comment]
Good point @ye-luo , the code needs 'from __future__ import print_function' to be most compatible between Python 2 and 3.
 
The change probably works under Python 2 without that, but it prints a tuple containing the string.    Which may not be a problem in this case.  
Adding the import will make it easier to avoid accidentally adding Python 2 print statements.

**Comment by markdewing** [comment]
okay to test

**Pull request merged**
