### PR TITLE
Raise GCC minimum to 9

### PR DESCRIPTION
**Pull request by ye-luo**
Need to decide if we'd like to merge this before or after release.
Needed by #4235

## Proposed changes
It is way beyond 2-year rule.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
bora, theta

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Certainly overdue.

Note that the two year rule would even allow us to require v10. https://gcc.gnu.org/releases.html We could require v9 now since we need it and shortly after the release bump to v10.

**Comment by ye-luo** [comment]
https://github.com/QMCPACK/qmcpack/actions/runs/3049860570
shows the need of updating CI.
GCC8 -> GCC9
Clang add --gcc-toolchain pointing to the GCC installation.
Intel add GCC bin to path.

**Comment by ye-luo** [comment]
If possible, I would like to stay with gcc9 for a while.

**Comment by ye-luo** [comment]
> https://github.com/QMCPACK/qmcpack/actions/runs/3049860570 shows the need of updating CI. GCC8 -> GCC9 Clang add --gcc-toolchain pointing to the GCC installation. Intel add GCC bin to path.

@williamfgc could you update those settings on ornl-CI?

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]

**Pull request merged**
