### PR TITLE
Remove opt buffer

### PR DESCRIPTION
**Pull request by ye-luo**
deprecate usebuffer as discussed in #433.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by markdewing** [comment]
Can the DataSetForDerivatives member in Walker.h be removed, or not yet?

**Comment by ye-luo** [comment]
Thanks for the reminder. Updated.

**Comment by ye-luo** [comment]
@jtkrogel Does nexus have usebuffer settings?

**Comment by jtkrogel** [comment]
There is no default use of usebuffer in Nexus that will affect general users.  Users can provide usebuffer to Nexus (just as to QMCPACK), and the user requested value will show up in the generated input file.  

There are defaults for usebuffer in qmcpack_workflows, which essentially only I use at this point, and they should remain for now.

I assume that after this change, usebuffer input will simply be ignored within QMCPACK.  Probably better to issue a non-aborting warning w.r.t. the deprecated parameter.

**Comment by ye-luo** [comment]
I would like to use the general mechanism for detecting unused input param/arguments when we deal with XML input validation.

**Pull request merged**
