### PR TITLE
Fix CUDA gcc 13 conflict

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Resolve an issue similarly to https://github.com/QMCPACK/qmcpack/pull/4814

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Does this show up in our nightlies or CI?

**Comment by ye-luo** [comment]
This issue surfaced when I upgrade epyc-server to ubuntu 24.04 which has gcc 13.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
For the record, which cmake configuration line?

**Comment by ye-luo** [comment]
```cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DENABLE_OFFLOAD=ON -DENABLE_CUDA=ON ..```

**Review by prckent — APPROVED** [review]

**Pull request merged**
