### PR TITLE
add occupation reading to LCAOSpinorBuilder

### PR DESCRIPTION
**Pull request by camelto2**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

This adds parsing of <occupation mode="ground/excited/table"> to the LCAO Spinor Builder. This is necessary as I'm working on a converter for DIRAC to occupy the appropriate spinors for closed shell ground states. The ordering in the output from dirac is based on the symmetry of the states, and not energy ordered like most SCF codes. So if you parse the output in the order that they print the spinors (which is the most straightforward), then the normal "ground" occupation doesn't give you the state you want because they aren't energy ordered. So, the ability to have "excited" is necessary for the time being. This makes sure I can occupy the desired spinors. The converter will come later, as well as some potential changes to the multideterminant code to make multideterminants with spinors work. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
my workstation, gcc9.2

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by camelto2** [comment]
following up with a unit test for the excited occupation read

**Comment by ye-luo** [comment]
Okay to test.

**Review by ye-luo — APPROVED** [review]
LGTM. @rcclay good to go?

**Review by rcclay — APPROVED** [review]
LGTM

**Pull request merged**
