### PR TITLE
Update afqmctools options

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Updates afqmctools options to optionally use density fitting integrals if they exist in checkpoint file. Before it would default to using. 

## What type(s) of changes does this code introduce?

- Bugfix
- [X] New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Documentation content changes
- Other (please describe):

### Does this introduce a breaking change?

- Yes
- [X] No

## What systems has this change been tested on?

LC

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
What is "LC"?

**Comment by fdmalone** [comment]
Livermore Computing

**Comment by prckent** [comment]
@fdmalone What is the config? Do you have a URL? ("RHEL 4 with python3 from latest spack")

**Pull request merged**
