### PR TITLE
Add deterministic test for FeCO6

### LINKED ISSUE #3822: Deterministic test needed for short-FeCO6
**Is your feature request related to a problem? Please describe.**
Given #3820, this is a straightforward way to avoid repeats and also adds a much less trivial molecular case to our test set that is run in CI.

**Describe the solution you'd like**
Add deterministic tests for FeCO6

**Describe alternatives you've considered**

Test another non-trivial molecule - but we have the files for FeCO6 already. H2O dimer also exists but has fewer species.

**Additional context**

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

Close #3822 .

Add deterministic test for FeCO6 to catch related issue (eg. #3820) in CI.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Intel Xeon workstation

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Perhaps try with a different set of electron positions/random seed? Or with a single walker? There are large differences in some of the failing tests. Hopefully bad luck and not a threading issue.

**Comment by prckent** [comment]
Test this please

**Comment by Hyeondeok-Shin** [comment]
Now all mixed precision tests should be passed.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thanks Hyeondeok

**Comment by prckent** [comment]
Test this  please

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
