### PR TITLE
BSD compatibility

### PR DESCRIPTION
**Pull request by correaa**
This patch should allow to use the library in BSD, or non-linux environments.

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

https://github.com/QMCPACK/qmcpack/issues/2323

## What type(s) of changes does this code introduce?

- Bugfix
- New feature

compatibility with BSD

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

in Linux, I don't have a BSD to test this.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by correaa** [comment]
In particular if it works with BSD.

**Comment by markdewing** [comment]
okay to test

**Comment by correaa** [comment]
What does it mean "All checks have failed"? The link "Details" doesn't go anywhere.

**Comment by markdewing** [comment]
The link should work for the alcf-gnu6-mkl18 one
The error is
"""
In file included from /sandbox/jenkins-ci/workspace/QMCPACK-CI-GNU6-MKL18/label/skylake-only/type/Real-Mixed-SoA/src/Message/Communicate.cpp:28:0:
/sandbox/jenkins-ci/workspace/QMCPACK-CI-GNU6-MKL18/label/skylake-only/type/Real-Mixed-SoA/external_codes/mpi_wrapper/mpi3/shared_communicator.hpp: In constructor ‘boost::mpi3::shared_communicator::shared_communicator(const boost::mpi3::communicator&, boost::mpi3::communicator_type, int)’:
/sandbox/jenkins-ci/workspace/QMCPACK-CI-GNU6-MKL18/label/skylake-only/type/Real-Mixed-SoA/external_codes/mpi_wrapper/mpi3/shared_communicator.hpp:48:6: error: ‘shared’ is not a member of ‘boost::mpi3::communicator_type’
   if(communicator_type::shared==t){
      ^~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/qmcutil.dir/Message/Communicate.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/qmcutil.dir/all] Error 2
"""

**Comment by correaa** [comment]
Ok, thanks. There is an enum to be updated as well. It is better if we
synchronize the versions.

 Qmcpack should have a fork of bmpi3 that is the supported version, i can
push automatically to it.

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
ornl-vm-CI/cpu failing indicates one of the cpu build combination is not working. At this time we believe the CI to be working/correct.

**Comment by correaa** [comment]
When I click in the "Details" link nothing happens. It doesn't forward me to the results of the check.

**Comment by PDoakORNL** [comment]
I'm working on the firewall exceptions.  You might or might not be able to get through to the details if you are "on" a DOE network.

GCC 9.2.0 Real and Complex mixed fail tests.  Looks to have nothing to do with the PR specifically.  Looks fishy, i.e. corruption perhaps only slightly related to the contents here.  I will take a look tomorrow. You should have gotten logs sent to you @correaa check your junk mail folder.
```
/var/lib/jenkins/workspace/vm_cpu/src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp:31

...............................................................................


/var/lib/jenkins/workspace/vm_cpu/src/QMCWaveFunctions/tests/test_kspace_jastrow.cpp:119: FAILED:

  REQUIRE( logpsi_real == Approx(-4.4088303951) )

with expansion:

  0.0 == Approx( -4.4088303951 )


    ---------------------------------------------------------

                       cusp variable A: 3.0000000000

                        soft cutoff R0: 0.0623999983

    sigmoidal expansion coefficients B: 0.3000000119 0.2000000030 0.4000000060

                    hard cutoff radius: 6.0000000000

                                 Opt_A: no

                                Opt_R0: yes

                                 Opt_B: yes

===============================================================================

test cases:  35 |  33 passed | 2 failed

assertions: 866 | 864 passed | 2 failed
```

**Comment by prckent** [comment]
This looks to be a bug in the kspace jastrow with mixed precision, that or the test of it. It works elsewhere, but I agree with Peter that the likely thing is that the new testing environment has caused the bug to surface. Suspiciously logpsi is exactly zero (0.0) when it should be ~-4.4088303951.

**Comment by prckent** [comment]
Given our understanding of the test failure, I'll merge this. We will check the nightlies in the morning for consistency with the hypothesis.

**Pull request merged**
