### PR TITLE
Fix nexus install path.

### LINKED ISSUE #3720: The 'install' target fails to install nexus but still succeeds
It prints this:
```
-- Install configuration: "RELEASE"
install error: problem encountered, see output below
out: b''
err: b'cp: /usr/local/bin/eshdf: Permission denied\ncp: /usr/local/bin/nxs-redo: Permission denied\ncp: /usr/local/bin/nxs-sim: Permission denied\ncp: /usr/local/bin/nxs-test: Permission denied\ncp: /usr/local/bin/qdens: Permission denied\ncp: /usr/local/bin/qdens-radial: Permission denied\ncp: /usr/local/bin/qmc-fit: Permission denied\ncp: /usr/local/bin/qmca: Permission denied\n'
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmcpack.settings
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmcpack
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/convert4qmc
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmc-extract-eshdf-kvectors
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmc-get-supercell
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmc-check-affinity
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/convertpw4qmc
-- Installing: /disk-samsung/freebsd-ports/science/qmcpack/work/stage/usr/local/bin/qmcfinitesize
```

It looks like it attempts to install into ```$PREFIX```, not ```$DESTDIR$PREFIX```, so it would always fail to install into the stage directory.

Another bug is that the above error gets lost and install succeeds. This masks the problem.

rev. 0297e8705
OS: FreeBSD 13

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
fixes #3720
Prevent path being translated at CMake step.
The desired path will show up in `build/cmake_install.cmake` and become effective at make install.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Start testing in-house

**Comment by prckent** [comment]
Interesting unrelated CI failure?

**Comment by ye-luo** [comment]
> Interesting unrelated CI failure?

Error shows
```
cudaAssert: cudaErrorMemoryAllocation out of memory*** file /scratch/ci/actions-runner/_work/qmcpack/qmcpack/src/Platforms/CUDA/CUDAallocator.hpp*** line 278
```

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
LGTM

**Pull request merged**
