### PR TITLE
Sulfur CI upgrade to LLVM 15 rc3

### LINKED ISSUE #4211: Update CI Clang to 15
**Is your feature request related to a problem? Please describe.**
Clang 15.0.0-rc3 addressed a few issues of Clang 14.
1. 14 has non-deterministic behaviors which caused bad code generation. Namely less reliable CI.
2. 15 now supports linking static archives with device code in it.

So need to update ORNL CI to use clang 15 and also remove USE_OBJECT_TARGET

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes
Upgrade from LLVM 14 to LLVM 15-rc3 on sulfur and migrate CI
Remove USE_OBJECT_TARGET option
Needs to be merged to execute the new CI workflow
Related to #4128 
Closes #4211

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
sulfur, must pass CI

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
I'll merge this by hand.

**Comment by ye-luo** [comment]
When I grep 14 in both files. I saw more hits.

**Comment by prckent** [comment]
If looks like this worked, with LLVM15 found and used during the configure & build. However I do see references to LLVM 13 in the PATH that should be cleaned up. 
https://github.com/QMCPACK/qmcpack/runs/8076237562?check_suite_focus=true#step:7:29

**Comment by prckent** [comment]
I have updated the branch protections to require these jobs and to not require the old jobs. Further additions and removals may be needed.

**Pull request merged**
