### PR TITLE
Update mpi3

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Unblocks NVHPC 24.5 making cpu-only builds

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
No concerns, but for reference, which version and source did you use for Boost-mpi3? By eye I did not spot the corresponding hash.

@correaa Any comments?

**Comment by correaa** [comment]
It seems that Ye did the tree update with an untagged version. Do you want make a tag and update the tree?

**Comment by prckent** [comment]
Consistently using tagged versions would be better.  Is it convenient to make one now?

**Comment by ye-luo** [comment]
I did a subtree update. See commit log
```
    Squashed 'external_codes/mpi_wrapper/mpi3/' changes from 7f82048b19..a9e19abead
```
So using `a9e19abead`

**Review by prckent — APPROVED** [review]
Origin is clear.

**Pull request merged**
