### PR TITLE
Add mock-up mw_accept_rejectMove in MSD.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
To achieve optimal performance, these routines needs to be specialized. Continue #3830.
Stage this change from my back pocket to test the latest CI update.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Unfortunately the coverage report is confused, but Q. Which tests should hit these lines in CI? This is the sort of area where our testing should be very helpful. Do we need to add one to the to do list?

**Comment by ye-luo** [comment]
Let me add a unit test in this PR.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@prckent a unit test has been added and this PR is ready to go.

**Review by prckent — APPROVED** [review]
LGTM

I assume the codecov reports are confused by the various updates.

**Pull request merged**
