### PR TITLE
Implement AccelMatrixUpdateOMPTarget wrapper

### PR DESCRIPTION
**Pull request by ye-luo**
Review after #5024
## Proposed changes
AccelMatrixUpdateOMPTarget matches AccelMatrixUpdateCUDA implementation.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
eypc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — COMMENTED** [review]
Do you intend much more refactoring for omp target delayed update and connected code?

**Comment by ye-luo** [comment]
> Do you intend much more refactoring for omp target delayed update and connected code?

Actually this is the last omptarget bit. I already connected it to MatrixDelayedUpdateCUDA template and OMPTarget delayed update is fully working. I still need to rename/refactoring MatrixDelayedUpdateCUDA and DiracDeterminantBatched and remove MatrixUpdateOMPTarget to wrap up the work.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
Quick Q: Any spare bandwidth to add a test for the beta[ib] != 0 paths?

**Review by prckent — APPROVED** [review]
Thanks. Please expand the low level unit tests in subsequent PRs.

**Pull request merged**
