### PR TITLE
Allow empty particleset in the input

### PR DESCRIPTION
**Pull request by markdewing**
To handle #2224, allow an empty ParticleSet to be created if it has the special name "empty".
Replaces #2234 

Example input:
```
<particleset name="empty" random="no">
    <group name="u" size="0">
      <parameter name="charge">0</parameter>
    </group>
  </particleset>
```

### CODE REVIEW

**Comment by prckent** [comment]
The group is always required?

**Comment by markdewing** [comment]
I believe having one group is required.  I didn't try fixing the code so that no groups would work.

**Comment by kryczko** [comment]
When I try to run now I get the following error:
```
Fatal Error. Aborting at ParticleSet::resetGroups() Failed. ParticleSet 'empty' has group 'u' containing 0 particles. Remove this group from input!
```

**Comment by ye-luo** [comment]
After modifying your input by adding "empty" particleset and source="empty", I'm able to run with this branch. I'm afraid you were using a wrong branch. Once this PR gets merged, you can pull the develop. It should be easier for you.

Here is the modified input. You need to change txt to xml.
[qmcpack_in.txt](https://github.com/QMCPACK/qmcpack/files/4138823/qmcpack_in.txt)

**Pull request merged**
