### PR TITLE
Clean up wavefunction

### PR DESCRIPTION
**Pull request by ye-luo**
Apart from some internal interface name changes in J1 SoA, all the rest is only removing no more needed routines.
ratio(P,iat,G,L), logRatio
evaluateLog(P,buf)
dumpToBuffer, dumpFromBuffer

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Are any of these functions used at the higher build levels? Called by other historical code?

I very much agree with this cleanup. We should note here if some reimplementation might be needed in future to reactivate any features.

**Comment by ye-luo** [comment]
We are building at level 3 by default. 3 has the most features. 5 has been checked.
Most of these are only partially implemented. They are deprecated because either the name doesn't reflect the actual implementation and their role has been replaced by better routines.
evaluateLog(P,buf) is implemented everywhere but it is more flexible to use the way we have now
by calling evaluateLog(P) + updateBuffer(P,buf,false)

**Comment by prckent** [comment]
I am happy to merge but will wait until next week to allow others to comment.

**Pull request merged**
