### PR TITLE
Add tolerance option to check_traces.py

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

 Current deterministic test for traces check is failing in mixed-precision build because current tolerance (1e-8) is too small to handle numeric sensitivity on mixed precision build.
 This PR is to test for mixed precision build with separated tolerance of 1e-6, which is small enough as much to work as deterministic test. 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

 Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
It is not obvious to me that this is the best route. It adds build type dependencies to the test scripts. Why not increase the allowable error bar in each of the mixed precision tests? This requires changes in more places but keeps the comparison explicit, and provided the test is defined near the full precision one, it will be easy to see how it differs. Did you consider this option?

**Comment by Hyeondeok-Shin** [comment]
@prckent Do you mean separated tolerances for each of test for the mixed precision build? Actually, I didn't think about it because uniform 1e-6 tolerance seems enough to measure deterministic for me. If we need to see exact how it differ from the full precision I thought it would be enough to print actual difference whatever test failed or not. There is also another option increase tolerance as 1e-6 for both full and mixed precision build if we need to remove build type dependency in the test as much as possible. We need to hear from @jtkrogel about his preference to deal with the mixed precision.

**Comment by prckent** [comment]
@Hyeondeok-Shin Yes, lets get @jtkrogel view. If he thinks that this PR is fine, we can merge. This is not a big change and we can revise in future should it be necessary.

**Comment by jtkrogel** [comment]
All I would change is to swap out the added `--mixed_precision` flag for a `--tol` flag that defaults to 1e-8.  That way we just pass 1e-6 for mixed precision.

**Comment by Hyeondeok-Shin** [comment]
Now flag is replaced to --tol and ready for review.

**Comment by ye-luo** [comment]
Okay to test

**Pull request merged**
