### PR TITLE
Switch the base class of Jastrow CUDA implementations to SoA

### PR DESCRIPTION
**Pull request by PDoakORNL**
GPU Jastrows based on SoA jastrow orbital classes.  AoS implementation moved to tagged xAoS.y.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Can I get a verify?

**Comment by markdewing** [comment]
okay to test

**Comment by ye-luo** [comment]
@PDoakORNL What test did you do?
I feel there may be no need to list this as experimental.

**Comment by PDoakORNL** [comment]
Well it felt experimental back when I wrote that.  Will update.

**Comment by PDoakORNL** [comment]
I've only checked short. Was kind of hoping the nightlies would cover long, I guess I need to set up personal CI to grind along at all the tests. But will start long by hand now.

**Comment by ye-luo** [comment]
Make sure short-diamondC_1x1x1_pp-opt_sdj-1-16-XXX passes.

**Comment by PDoakORNL** [comment]
Ok but it seems like gambling. The short-diamondC_1x1x1_pp-opt_sdj-1-16-NonLocalECP [failed](https://cdash.qmcpack.org/CDash/testDetails.php?test=2688232&build=25477) for AoS CUDA in the last nightly build.

**Comment by ye-luo** [comment]
This is just one occurrence last night.

**Comment by ye-luo** [comment]
Runs well last night. Good job. https://cdash.qmcpack.org/CDash/viewTest.php?onlydelta&buildid=25552

**Pull request merged**
