### PR TITLE
Force PR 2/4:  NonLocalPP Hellman-Feynman Backend

### PR DESCRIPTION
**Pull request by rcclay**
This PR implements necessary functions to calculate the NonLocalPP contribution to Hellman-Feynman forces.  It also removes Chiesa's legacy implementation.  

**KNOWN ISSUES**

1. Does not work with QMC_COMPLEX = false.  Because of this, no effort has been made to get this code working in open boundary conditions.  By "doesn't work", I mean it yields numbers close but statistically significantly different from both the complex builds and quantum espresso, so it shouldn't be used.

2.  No attempt has been made to use virtual particle set evaluations.  This requires implementing a "ratioGrad" function for virtual particle sets in TrialWavefunction and all relevant WaveFunctionComponent objects.  Not hard, but also not a priority.

To validate, I used the same crystal coordinates and lattice constant as PR #1009, but I replaced the lithium BFD pseudopotentials with Na BFD.  This pseudo has s,p, and d channels, so after localization, nonlocal evaluation is done over s and p channels.  In line with Paul's suggestion, I used Hartree-Fock to compute the orbitals in QE (plane wave cutoff of 100Ry).  Thus, I assume that QE's estimates for local and non-local contributions to total force should be a decent benchmark.  I used the hybrid representation for orbitals.  

Here's what we get.  

Compopnent | QMC | HF | DIFF | ERR | Z
-- | -- | -- | -- | -- | --
FNL_0_0 | 0.00395 | 0.00435 | -0.00040 | 0.00010 | -4.03660
FNL_0_1 | 0.00612 | 0.00616 | -0.00004 | 0.00010 | -0.36929
FNL_0_2 | 0.00994 | 0.00987 | 0.00007 | 0.00010 | 0.70833
FNL_1_0 | 0.01392 | 0.01347 | 0.00044 | 0.00009 | 4.82783
FNL_1_1 | 0.01669 | 0.01598 | 0.00071 | 0.00009 | 7.68559
FNL_1_2 | -0.00326 | -0.00314 | -0.00012 | 0.00010 | -1.24242
FNL_2_0 | -0.02396 | -0.02341 | -0.00054 | 0.00010 | -5.65323
FNL_2_1 | 0.00900 | 0.00874 | 0.00026 | 0.00009 | 2.82522
FNL_2_2 | 0.01478 | 0.01440 | 0.00038 | 0.00010 | 3.79798
FNL_3_0 | -0.00279 | -0.00286 | 0.00007 | 0.00009 | 0.75371
FNL_3_1 | -0.01527 | -0.01498 | -0.00029 | 0.00010 | -2.96102
FNL_3_2 | -0.01555 | -0.01514 | -0.00042 | 0.00009 | -4.73864
FNL_4_0 | 0.00863 | 0.00856 | 0.00007 | 0.00009 | 0.73245
FNL_4_1 | -0.01775 | -0.01743 | -0.00032 | 0.00010 | -3.24770
FNL_4_2 | 0.01742 | 0.01698 | 0.00044 | 0.00009 | 4.75000
FNL_5_0 | -0.02073 | -0.02028 | -0.00045 | 0.00009 | -4.82234
FNL_5_1 | -0.00405 | -0.00406 | 0.00001 | 0.00009 | 0.07420
FNL_5_2 | -0.01377 | -0.01329 | -0.00048 | 0.00009 | -5.25275
FNL_6_0 | -0.00733 | -0.00722 | -0.00010 | 0.00009 | -1.18644
FNL_6_1 | -0.01094 | -0.01073 | -0.00021 | 0.00009 | -2.33180
FNL_6_2 | -0.00304 | -0.00295 | -0.00009 | 0.00009 | -1.00000
FNL_7_0 | 0.02335 | 0.02280 | 0.00055 | 0.00010 | 5.52778
FNL_7_1 | 0.01308 | 0.01263 | 0.00044 | 0.00010 | 4.62677
FNL_7_2 | -0.00806 | -0.00770 | -0.00037 | 0.00009 | -4.00000

Statistically significant differences between the two on a few force components, but the max error is +0.00071 Ha/bohr.  I suspect that this deviation can be improved by going to a higher order quadrature rule.  Or maybe this is not an ideal system to test with.  The pseudopotential radius is 3.475, whereas the nearest neighbor distance is 3.584.  Also this corresponding to a pressure of 80GPa.  Dialing back the lattice constant to something more reasonable, mainly by using the following cell but keeping the crystal coordinates the same:

> CELL_PARAMETERS {alat}
10.000 10.000  0.000
 0.000 10.000 10.000
10.000  0.000 10.000

We get the following:

Component | QMC | HF | DIFF | ERR | Z
-- | -- | -- | -- | -- | --
FNL_0_0 | -0.01382 | -0.01384 | 0.00003 | 0.00005 | 0.47056
FNL_0_1 | -0.00927 | -0.00935 | 0.00008 | 0.00005 | 1.55192
FNL_0_2 | -0.00028 | -0.00030 | 0.00002 | 0.00005 | 0.37255
FNL_1_0 | 0.00924 | 0.00928 | -0.00003 | 0.00005 | -0.65245
FNL_1_1 | 0.00884 | 0.00895 | -0.00011 | 0.00005 | -2.24306
FNL_1_2 | -0.00612 | -0.00615 | 0.00003 | 0.00005 | 0.51923
FNL_2_0 | -0.00686 | -0.00684 | -0.00003 | 0.00005 | -0.50923
FNL_2_1 | 0.00778 | 0.00785 | -0.00006 | 0.00005 | -1.36383
FNL_2_2 | 0.00713 | 0.00719 | -0.00006 | 0.00005 | -1.25532
FNL_3_0 | 0.00304 | 0.00310 | -0.00005 | 0.00004 | -1.19773
FNL_3_1 | -0.00567 | -0.00573 | 0.00006 | 0.00005 | 1.19848
FNL_3_2 | -0.00213 | -0.00221 | 0.00008 | 0.00004 | 1.90909
FNL_4_0 | 0.00844 | 0.00848 | -0.00004 | 0.00005 | -0.84571
FNL_4_1 | -0.00674 | -0.00677 | 0.00002 | 0.00005 | 0.46558
FNL_4_2 | 0.00758 | 0.00754 | 0.00005 | 0.00005 | 0.92000
FNL_5_0 | -0.00594 | -0.00595 | 0.00001 | 0.00005 | 0.24578
FNL_5_1 | 0.00213 | 0.00219 | -0.00005 | 0.00004 | -1.22605
FNL_5_2 | -0.00160 | -0.00163 | 0.00004 | 0.00004 | 0.86047
FNL_6_0 | 0.00209 | 0.00203 | 0.00006 | 0.00005 | 1.20913
FNL_6_1 | 0.00053 | 0.00052 | 0.00001 | 0.00004 | 0.15837
FNL_6_2 | -0.00441 | -0.00444 | 0.00003 | 0.00004 | 0.68182
FNL_7_0 | 0.00099 | 0.00096 | 0.00003 | 0.00005 | 0.54600
FNL_7_1 | 0.00059 | 0.00061 | -0.00002 | 0.00005 | -0.38580
FNL_7_2 | 0.00074 | 0.00075 | -0.00001 | 0.00005 | -0.21739

That looks pretty awesome to me.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
I don't see the derivatives with respect to ions in the WF of NLPP. Is because no Jastrow is used at the moment?

**Comment by rcclay** [comment]
@ye-luo This is just the Hellman-Feynman piece (dH/dR).  The Pulay-like contribution and other ZVZB terms will be handled in the future, basically when we start seriously implementing and testing ZVZB forces.

**Comment by jtkrogel** [comment]
Are these coming in PR 3/4, 4/4, or later on?

**Comment by ye-luo** [comment]
Do you think in the future it is better to separate all the force evaluation from the energy to its own estimator class?

**Comment by rcclay** [comment]
@jtkrogel Later on.  The current batch of PR's is targeting a working Hellman-Feynman implementation, which is a necessary prerequisite to anything fancier.  

@ye-luo I'm on the fence about it.  Originally, I was in favor of implementing separate estimators (which is how ForceChiesaPBC is done).  However, now I feel like it's a lot less coding effort to keep the derivatives associated with the observables.  Makes enabling/disabling certain contributions easier (turning on/off ion-ion, ion-electron, electron-electron, etc), and it makes it so that accessing derivatives from the existing Hamiltonian object will be pretty easy as well.  That being said, it would probably be ideal to separate off the force computation _within_ the observable off from the energy.  I really don't want to be calculating the forces every time a call to energy is made.

**Comment by ye-luo** [comment]
The evaluation will remain in NLPP but not together with energy I think. The estimator will be only a data collection or post-process engine after calling the force evaluation in NLPP. Let us talk about that F2F next week.

**Pull request merged**
