### PR TITLE
Refactor GitHub Actions CI to nightly conventions

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Adapt to nightly naming conventions
Update `run_step.sh` to build documentation for MPI and NoMPI cases
Needs to be merged to test self-hosted runners
TODO: update docs to trigger self-hosted CI
Needed by #3582
Related to #3402 

## What type(s) of changes does this code introduce?

- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Testing changes (e.g. new unit/integration/performance tests) CI

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
None, must pass current CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Interesting, I can't reproduce `-Werror` failures with gcc-9, but with gcc-10. I will do a PR with a fix.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
If this is ready for merge, [WIP] should be removed

**Comment by williamfgc** [comment]
@ye-luo the updated run_step.sh in this PR is conflicting with the `develop` yaml configuration file for self-hosted jobs (which won't trigger until merged).

**Comment by prckent** [comment]
I'll note that we aren't currently tagging MPI builds with MPI in the test name on cdash, as here, but I think that would be a good change. We can leave these as is.

**Comment by williamfgc** [comment]
@prckent I actually like the cdash naming better, makes run_step.sh more clear. Thanks!. Let me know how you and @ye-luo want to proceed. We can merge this and trigger CI again on a separate PR.

**Comment by prckent** [comment]
@williamfgc OK, strip the -MPI here. We can always revisit.

**Comment by williamfgc** [comment]
@prckent sorry, my bad. I'd like to keep `-MPI-` as I need some identification for exporting OpenMPI needed variables in run_step.sh. I was referring to the fact that self-hosted tests are a chicken-and-egg problem as those won't run properly until this PR is merged.

**Comment by prckent** [comment]
OK, understood.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
@williamfgc Will the CI ever pass or do we need to force merge this?

**Comment by williamfgc** [comment]
@prckent your assumption is correct, `self-hosted` CI won't work for this particular PR. Force merge is the trade-off for avoiding spurious use on self-hosted systems via PRs. Since this is my mess, I will make sure CI is working rather quickly.

**Comment by ye-luo** [comment]
I have to by remove all ALCF CI as required. The failure seems now affecting all instances.

**Comment by prckent** [comment]
Merging without CI. Will reenable after merge.

**Pull request merged**
