### PR TITLE
Rename initGPU to finalizeConstruction for more general use

### PR DESCRIPTION
**Pull request by ye-luo**
This is needed for my OpenMP offload.
Hooks finalizeConstruction in BsplineSet.h
PR separately for easy review.

### CODE REVIEW

**Comment by prckent** [comment]
Please add a description of what this function is responsible for. Then we will see about finding an improved name.

**Comment by ye-luo** [comment]
Here is what I put in SPOSet.h
```
  /** finalize the construction of SPOSet
   *
   * for example, classes serving accelerators may need to transfer data from host to device
   * after the host side objects are built.
   */
```

**Comment by prckent** [comment]
Ideally in a future refactor the need for this call would disappear, with one constructor/setup/initialization call actually doing all the setup & initialization. Any chance to get rid of it now? Given that there are no arguments to the call, why can it not be done earlier?

**Comment by ye-luo** [comment]
The initialization of spline takes 3 steps.
1. create the memory space for splines
2. initialize the values or read from pre dumped files.
3. GPU only. Transfer to the device.
Currently the builder is not aware of the accelerator. It calls finalizeConstruction in step 3 and let the implementation decide. If we need to have the builder aware of the GPU, both the builder and the object class needs to be GPU aware and way more lines of codes will be needed than only keep the lightweight GPU specialized code (step 1 and 3) all live in the object.

**Comment by prckent** [comment]
I was thinking about a possible merge of 2 and 3 perhaps 1-3 in future. No reason these could not be merged in improved overrall design. The builders should definitely not know any more than they do now - they are already too complex already for too little return :-)

**Pull request merged**
