### PR TITLE
add unit tests for derivatives of LRHandlers

### PR DESCRIPTION
**Pull request by Paul-St-Young**
As promised in #2041. This PR adds finite difference tests for `LRHandler`s.

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Ok test this

**Comment by prckent** [comment]
OK to test

**Comment by Paul-St-Young** [comment]
@rcclay `LRHandlerTemp` derivatives are not functional at the moment. `gcoefs` are never initialized.

**Comment by Paul-St-Young** [comment]
Also, I am not confident about the absolute correctness of `LRHandlerSRCoulomb`. It is correct to `~10^6` when compared to `Ewald3D`, which is fully validated against QE.

I have attached an example that shows the convergence of `LRHandlerSRCoulomb`.
[h2r190.zip](https://github.com/QMCPACK/qmcpack/files/3779433/h2r190.zip)
f4-h2-srcoul-ewald

**Comment by prckent** [comment]
Suggestion: add hard aborts whenever something is unimplemented. We have been burned before.

**Pull request merged**
