### PR TITLE
Nexus: add selected CI workflows

### PR DESCRIPTION
**Pull request by jtkrogel**
Enable selected CI workflows.  Multideterminant wavefunctions generated via Quantum Package can now be passed to QMCPACK with Nexus.  An example based on the all electron oxygen dimer was added for both Quantum Package and QMCPACK.

Remaining items include:
- [x] Add cusp correction to qmcpack workflow
- [x] Add Jastrow optimization to qmcpack workflow
- [x] Cleanup examples to include no local paths

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by jtkrogel** [comment]
@anbenali Please have a look over the examples (o2_selci.py and o2_selci_vmc.py) and confirm if they look right.

I've added possible postprocessing steps to shorten the QP workflows (like automatically performing four_idx_transform, save_natorb, or save_for_qmcpack upon request).  This shortens the QP parts of the QP to QMCPACK workflow from 8 job submissions to 4.

For the SCF part (with addition of four_idx_transform) gives:
```
  export OMP_NUM_THREADS=12
  
  source /home/j1k/apps/quantum_package/qp2-2.0.0-beta/quantum_package.rc
  
  mpirun -np 1 qp_run scf fci.ezfio >scf.out 2>scf.err
  
  echo "Write" > fci.ezfio/mo_two_e_ints/io_mo_two_e_integrals
  mpirun -np 1 qp_run four_idx_transform fci.ezfio >scf_fit.out 2>scf_fit.err
```  

For CIS:
```
  mpirun -np 1 qp_run cis fci.ezfio >cis_0.out 2>cis_0.err
  mpirun -np 1 qp_run save_natorb fci.ezfio
  mpirun -np 1 qp_run cis fci.ezfio >cis_1.out 2>cis_1.err
  mpirun -np 1 qp_run save_natorb fci.ezfio
  
  echo "Write" > fci.ezfio/mo_two_e_ints/io_mo_two_e_integrals
  
  mpirun -np 1 qp_run cis fci.ezfio >cis.out 2>cis.err
```

For initial FCI (with save_natorb and four_idx_transform):
```
  mpirun -np 1 qp_run fci fci.ezfio >fci0.out 2>fci0.err
  
  mpirun -np 1 qp_run save_natorb fci.ezfio >fci0_natorb.out 2>fci0_natorb.err
  
  echo "Write" > fci.ezfio/mo_two_e_ints/io_mo_two_e_integrals
  mpirun -np 1 qp_run four_idx_transform fci.ezfio >fci0_fit.out 2>fci0_fit.err
```

For the final FCI (with save_for_qmcpack):
```
  mpirun -np 1 qp_run fci fci.ezfio >fci.out 2>fci.err
  
  mpirun -np 1 qp_run save_for_qmcpack fci.ezfio >fci_savewf.out 2>fci_savewf.err
```

**Comment by anbenali** [comment]
Went through all files and gave modification directly to Jaron. Can be merged at the next update. 

Thanks Jaron

**Comment by jtkrogel** [comment]
Added modifications requested by @anbenali.  Ready to merge.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
