### PR TITLE
Fix detected memory leaks in deterministic-unit_test_estimators

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This deletes owning raw pointers that are currently leaking memory. 

This is part of #3083 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Ubuntu 20.04, clang 11

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes Code added or changed in the PR has been clang-formatted
- n/a This PR adds tests to cover any new code, or to catch a bug that is being fixed
- n/a Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

Formally needs a non-ORNL person to merge.

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
@quantumsteve are you ok with this suggested update? In my mind it falls in the nice to have but not essential category.
I do like the deleter suggestions in #3191 . Establishing cleaner unit tests seems a good principle since they are likely to undergo cut-and-paste copying.

**Comment by ye-luo** [comment]
When an exception is thrown, the delete will not be called and show up as leaks. We have unit tests actually testing exceptions. My mind changes from "nice to have" to "must have" over the years.

**Comment by quantumsteve** [comment]
@prckent I'm currently making the changes for this PR. I think the benefits @ye-luo mentions would require changes to TraceManger to use `std::make_unique` and return a `unique_ptr`.

**Comment by ye-luo** [comment]
@quantumsteve since you can delete, it seems that the ownership is not inside TraceManger. So probably just use unique_ptr only in the unit test without touching TraceManger right now.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
