### PR TITLE
update Golub

### PR DESCRIPTION
**Pull request by Paul-St-Young**
Trivial update to the campus cluster at University of Illinois Urbana-Champaign

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
Okay to test

**Comment by jtkrogel** [comment]
@Paul-St-Young please also update the corresponding test in tests/unit/test_machines.py.

The test failure message shows where:
```
nxs-test -v -R machines

 1/1 machines................................   Failed  2.44 sec
       subtest: test_import
       subtest: test_cpu_count
       subtest: test_options
       subtest: test_job_init
       subtest: test_job_time
       subtest: test_job_set_id
       subtest: test_job_get_machine
       subtest: test_job_set_environment
       subtest: test_job_clone
       subtest: test_job_serial_clone
       subtest: test_machine_virtuals
       subtest: test_machine_list
       subtest: test_machine_add
       subtest: test_machine_get
       subtest: test_machine_instantiation
       subtest: test_workstation_init
       subtest: test_workstation_scheduling
       subtest: test_supercomputer_init
       subtest: test_supercomputer_scheduling
       subtest: test_process_job
       subtest: test_job_run_command
Test name     : machines
Test sublabel : test_job_run_command
Test exception: "KeyError: ('golub', 'n1')"
Test backtrace:
  File "./nxs-test", line 478, in run
    self.operation()
  File "./nxs-test", line 993, in machines
    nunit('job_run_command')
  File "./nxs-test", line 349, in nunit
    run_external_unit_test(test_name,unit_test)
  File "./nxs-test", line 388, in run_external_unit_test
    unit_test()
  File "/home/j1k/repositories/nexus_user/nexus/tests/unit/test_machines.py", line 1273, in test_job_run_command
    ref_command = job_run_ref[name,jtype]
  File "/home/j1k/repositories/nexus_user/nexus/lib/generic.py", line 158, in __getitem__
    return self.__dict__[name]


0% tests passed, 1 tests failed out of 1

Total test time = 2.44 sec
```

You can print out the reference data for all machines by typing:
```
nxs-test -v -R machines --job_ref_table
```

The relevant updated reference data for Golub will be there.

**Comment by Paul-St-Young** [comment]
@jtkrogel sorry I missed the test system `nxs-test`. I will remember next time.
I just opened another PR #2264 to address this.

**Comment by jtkrogel** [comment]
No problem.  Thanks Paul.

**Pull request merged**
