### PR TITLE
Move the role of LCAO::setOrbitalSetSize to constructors

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
On the path to eventually remove SPOSet::setOrbitalSetSize. The size should be recorded in the constructor and not be allowed to change at a later point. Simplify the initialization logic.

## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by PDoakORNL — COMMENTED** [review]
This looks like a good step to me.
 
src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp:57 behavior seems special enough to me to deserve some testing coverage.

While the LCAOSpinorBuilder in general seems to have coverage its not straightforward enough that I could find where a unit test of this behavior would go. I think most of the coverage is coming from fairly integration tests like `test_spo_collection_input_LCAO_xml.cpp` Not bad to have but doesn't make adding a test for new code paths easy.

**Comment by ye-luo** [comment]
> This looks like a good step to me.
> 
> src/QMCWaveFunctions/LCAO/LCAOSpinorBuilder.cpp:57 behavior seems special enough to me to deserve some testing coverage.
> 
> While the LCAOSpinorBuilder in general seems to have coverage its not straightforward enough that I could find where a unit test of this behavior would go. I think most of the coverage is coming from fairly integration tests like `test_spo_collection_input_LCAO_xml.cpp` Not bad to have but doesn't make adding a test for new code paths easy.

I modified one of the test in `test_MO_spinor.cpp`

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by PDoakORNL** [comment]
test this please

**Review by prckent — APPROVED** [review]
Thanks for reviewing Peter.

This strategy will remove a significant source of danger, both in the user input and internally.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
