### PR TITLE
Fix legacy_cuda build

### LINKED ISSUE #3252: #3246 breaks legacy_cuda
**Describe the bug**
Caused by changes in SPOSet legacy CUDA APIs. `src/QMCWaveFunctions/EinsplineSet.h` was not updated accordingly.

Need to fix the code with `override` to prevent this happening again.

once fixed, all deterministic tests are expected to pass.

FYI my clang recipe.
```
cmake -DMAKE_C_COMPILER=clang -DMAKE_CXX_COMPILER=clang++ -DQMC_MPI=0  \
-DQMC_CUDA=1 -D CUDA_ARCH=sm_80 -D CUDA_HOST_COMPILER=`which gcc` ..
```
clang shoots warning once one `override` gets added and if there is any missing.

### PR DESCRIPTION
**Pull request by quantumsteve**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

This updates EinsplineSet.h with the correct function signatures so that the base class implementation is no longer called.

Fixes #3252 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- Yes
- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
More missing virtuals

**Comment by quantumsteve** [comment]
Looks like there's an existing type mismatch (`float` vs `double`) on some of the builds.
```
In file included from /sandbox/jenkins-ci/workspace/QMCPACK-CI-Clang12-AFQMC-Offload-CUDA/label/compute002.mcs.anl.gov/type/Real-Mixed-enable-CUDA/src/QMCWaveFunctions/EinsplineSetBuilderCommon.cpp:24:
In file included from /sandbox/jenkins-ci/workspace/QMCPACK-CI-Clang12-AFQMC-Offload-CUDA/label/compute002.mcs.anl.gov/type/Real-Mixed-enable-CUDA/src/QMCWaveFunctions/EinsplineSetBuilder.h:29:
/sandbox/jenkins-ci/workspace/QMCPACK-CI-Clang12-AFQMC-Offload-CUDA/label/compute002.mcs.anl.gov/type/Real-Mixed-enable-CUDA/src/QMCWaveFunctions/EinsplineSet.h:363:46: error: non-virtual member function marked 'override' hides virtual member function
                   RealValueVector_t& d2psi) override;
                                             ^
/sandbox/jenkins-ci/workspace/QMCPACK-CI-Clang12-AFQMC-Offload-CUDA/label/compute002.mcs.anl.gov/type/Real-Mixed-enable-CUDA/src/QMCWaveFunctions/SPOSet.h:229:16: note: hidden overloaded virtual function 'qmcplusplus::SPOSet::evaluateVGL' declared here: type mismatch at 3rd parameter ('qmcplusplus::SPOSet::ValueVector_t &' (aka 'Vector<float> &') vs 'qmcplusplus::EinsplineSetExtended::RealValueVector_t &' (aka 'Vector<double> &'))
 ```

**Comment by ye-luo** [comment]
The old code has an over sophisticated template scheme and override logic. 
```
evaluate(particleset& P, RealVector& psi)
evaluate(particleset& P, CompVector& psi)
```
Which one overrides the base class virtual depends on the build is real or complex. Even both APIs exist, the real one is only guaranteed to work when built real and vise versa.
It also only handles double precision. That is why mixed precision fails with clang. What it surprised me is why gcc is OK.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Put up a workaround using pre-processor.

**Review by prckent — CHANGES_REQUESTED** [review]
I would like to know what a cleaner solution would be ahead of merging any preprocessor workaround. I am not a fan of using the preprocessor when we could just get the code right.

My guess is that the problems here came about when the old more templated CPU code met with the legacy CUDA and the designs were not aligned.

**Comment by ye-luo** [comment]
Removed the preprocessor workaround
EinsplineSet.h (legacy spline SPO) should not be included at all when host side is built mixed precision (MIXED_PRECISION).
GNU and Intel seem to check the actual function pattern only when compiling the function definition.
Clang seems to check every function declaration.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@prckent good?

**Review by ye-luo — APPROVED** [review]
LGTM

**Review by prckent — APPROVED** [review]
LGTM

Reading through these updates I was reminded that EinsplineSet* is a very probable location for the breakage in the CUDA2HIP conversion for AMD, whether our bug or theirs.

**Pull request merged**
