### PR TITLE
Deterministic  DMC density/spin density tests

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Add deterministic DMC tests for the density and spin density.  Care has been taken with the walker count and timestep to ensure that at least a few branching operations occur. 

An adjustment to check_scalars.py has been made to not check per block sums in the equilibration period.  This is needed to construct a currently passing test given the persisting problem with the weight of the first block in DMC.

This PR depends on #2774. 

## What type(s) of changes does this code introduce?

- Other (please describe): Tests

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]
LGTM

Verified OK with Intel2019.1.3

```
$ ctest -R "det.*dmc.*dens"
Test project /home/pk7/projects/qmc/git_QMCPACK_prckent/build_intel
    Start 920: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1
1/8 Test #920: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1 .............   Passed    0.91 sec
    Start 921: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1-check
2/8 Test #921: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1-check .......   Passed    0.31 sec
    Start 922: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4
3/8 Test #922: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4 .............   Passed    9.24 sec
    Start 923: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4-check
4/8 Test #923: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4-check .......   Passed    0.30 sec
    Start 928: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1
5/8 Test #928: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1 .........   Passed    0.89 sec
    Start 929: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1-check
6/8 Test #929: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1-check ...   Passed    0.30 sec
    Start 930: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4
7/8 Test #930: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4 .........   Passed   10.65 sec
    Start 931: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4-check
8/8 Test #931: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4-check ...   Passed    0.31 sec

100% tests passed, 0 tests failed out of 8
```

**Comment by prckent** [comment]
OK to test

**Review by prckent — CHANGES_REQUESTED** [review]
Unfortunately these are reliably breaking with the complex build. Possibly the Monte Carlo takes a different path (fixed phase/fixed node) but we should check carefully.

**Comment by jtkrogel** [comment]
I will look into this.  If DMC complex diverges from real in the version used to generate the tests I will then opt to make a second reference specific to complex.

**Comment by jtkrogel** [comment]
I made the updates for complex.

Two observations:
(1) DMC complex appears to be non-deterministic with threading turned on.
(2) The 4 mpi 4 thread DMC tests are now taking ~11s vs. ~1s for serial.  When I first made these, I believe all the times were ~1s.

**Comment by prckent** [comment]
After our offline discussion just now, I'll note that we agreed a key step is to establish whether the non-determinism is coming from the underlying DMC (by checking the energy) or is coming from the observable implementation.

**Comment by ye-luo** [comment]
As long as the RNG seed is fixed, the code is expected to be deterministic. It is a must to figure out where the non-determinism is coming from.

**Comment by jtkrogel** [comment]
A more careful review showed the problem was not non-determinism, but a copy paste error in the run script (serially generated references were erroneously used with parallel tests).  All tests pass now.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Confirming that these are working now. However the timings are rather strange (as also noticed by @jtkrogel ): the 4-4 tests for both vmc and dmc take 7-9 seconds, while the 1-1 tests take under 1 second. Either the runs are accidentally very different of there is a problem in the code:

```
build_intel]$ grep density ctest.out 
        Start  530: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-1-1
 46/303 Test  #530: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-1-1 .........................   Passed    0.75 sec
        Start  531: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-1-1-check
 47/303 Test  #531: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-1-1-check ...................   Passed    0.33 sec
        Start  532: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-4-4
 48/303 Test  #532: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-4-4 .........................   Passed    6.92 sec
        Start  533: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-4-4-check
 49/303 Test  #533: deterministic-diamondC_1x1x1_pp-vmc-estimator-density-4-4-check ...................   Passed    0.32 sec
        Start  534: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1
 50/303 Test  #534: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1 .........................   Passed    0.89 sec
        Start  535: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1-check
 51/303 Test  #535: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-1-1-check ...................   Passed    0.32 sec
        Start  536: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4
 52/303 Test  #536: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4 .........................   Passed    9.48 sec
        Start  537: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4-check
 53/303 Test  #537: deterministic-diamondC_1x1x1_pp-dmc-estimator-density-4-4-check ...................   Passed    0.32 sec
        Start  538: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-1-1
 54/303 Test  #538: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-1-1 .....................   Passed    0.77 sec
        Start  539: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-1-1-check
 55/303 Test  #539: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-1-1-check ...............   Passed    0.32 sec
        Start  540: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4
 56/303 Test  #540: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4 .....................   Passed    7.16 sec
        Start  541: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check
 57/303 Test  #541: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check ...............   Passed    0.32 sec
        Start  542: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1
 58/303 Test  #542: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1 .....................   Passed    0.90 sec
        Start  543: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1-check
 59/303 Test  #543: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-1-1-check ...............   Passed    0.32 sec
        Start  544: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4
 60/303 Test  #544: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4 .....................   Passed    9.69 sec
        Start  545: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4-check
 61/303 Test  #545: deterministic-diamondC_1x1x1_pp-dmc-estimator-spindensity-4-4-check ...............   Passed    0.32 sec
```

**Comment by ye-luo** [comment]
Did you run with '-j'?

**Comment by prckent** [comment]
No. Running with -j 16 did the trick. The 4-4 runs are now appropriately faster than 1-1.

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
