### PR TITLE
Enable output of vp file override by default

### LINKED ISSUE #4188: vp.h5 line in opt.xml
**Describe the bug**
I ran multiple blocks of optimization
```
<loop max="3">
<loop max="3">
<loop max="2">
```
I got
```
grep vp *.opt.xml
NiO-fcc-S1-dmc.s004.opt.xml:<override_variational_parameters href="NiO-fcc-S1-dmc.s004.vp.h5"/></wavefunction>
NiO-fcc-S1-dmc.s006.opt.xml:<override_variational_parameters href="NiO-fcc-S1-dmc.s006.vp.h5"/></wavefunction>
NiO-fcc-S1-dmc.s007.opt.xml:<override_variational_parameters href="NiO-fcc-S1-dmc.s007.vp.h5"/></wavefunction>
```
I'm wondering why vp.h5 is not written in every opt.xml

PS: also missing a new line before `</wavefunction>`

### PR DESCRIPTION
**Pull request by markdewing**
Sets output_vp_override to on by default (part way to #3653)
Uses the boolean parameter handling to simplify the code.
Fixes the lack of default initialization that would lead to the tag being output intermittently (fixes #4188)

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
@markdewing could you add a manual entry for this option?

**Comment by markdewing** [comment]
Given the goal is to remove the option entirely in #3653 , does it need to be documented in the manual?

**Comment by ye-luo** [comment]
Either just remove this option completely. Or document it if you think this option is worth being kept.
Last time, I failed in finding any mention in the documentation and had to read the source code. That is counter-productive.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Pull request merged**
