### PR TITLE
Rename spline coefs and restart tests deterministic

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

As per title. Also rename coefs -> spline_coefs for clarity. Also make runs shorter. Should now run in CI and reported coverage should be greater.

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

gcc 12 mpi , sulfur nightly config.

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- NA. Code added or changed in the PR has been clang-formatted
- NA. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- NA. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
Happily our CI is working and this test finds a memory leak. Best look at other PRs until fixed.

```
==5330==ERROR: LeakSanitizer: detected memory leaks
Indirect leak of 600 byte(s) in 5 object(s) allocated from:
    #0 0x4c3dcd in malloc (/__w/qmcpack/qmcpack-build/bin/qmcpack+0x4c3dcd)
    #1 0x7f358a6d2e45  (/lib/x86_64-linux-gnu/libxml2.so.2+0x13ae45)
Indirect leak of 480 byte(s) in 5 object(s) allocated from:
    #0 0x4c3dcd in malloc (/__w/qmcpack/qmcpack-build/bin/qmcpack+0x4c3dcd)
    #1 0x7f358a5f7197 in xmlNewNsPropEatName (/lib/x86_64-linux-gnu/libxml2.so.2+0x5f197)
Indirect leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x4c3dcd in malloc (/__w/qmcpack/qmcpack-build/bin/qmcpack+0x4c3dcd)
    #1 0x7f358a5fb85e in xmlNewDocNodeEatName (/lib/x86_64-linux-gnu/libxml2.so.2+0x6385e)
Indirect leak of 15 byte(s) in 1 object(s) allocated from:
    #0 0x4c3dcd in malloc (/__w/qmcpack/qmcpack-build/bin/qmcpack+0x4c3dcd)
    #1 0x7f358a66a3d5 in xmlStrndup (/lib/x86_64-linux-gnu/libxml2.so.2+0xd23d5)
SUMMARY: AddressSanitizer: 1215 byte(s) leaked in 12 allocation(s).
```

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Comment by prckent** [comment]
Thanks Ye!

I am wondering if you guessed this or (ideally) it was obvious in a debug sanitizer build.

**Comment by ye-luo** [comment]
> Thanks Ye!
> 
> I am wondering if you guessed this or (ideally) it was obvious in a debug sanitizer build.

The existing sanitizer printout is not helpful because the xml library has no debug symbols. I tried building the code locally and linked with an libxml with debug turned on but still didn't get much clue about the indirect leak.

Then I realized that the failure only happens with the restart input file. So it must be related to `mcwalkerset` xml node and very quickly found the leak as I read through the code.

**Pull request merged**
