### PR TITLE
Fix all-particle move DMC driver

### PR DESCRIPTION
**Pull request by ye-luo**
See more details in #753 for the bug and use that issue to track progress.

This PR adds an integration test for VMC and DMC with all particle moves on diamondC 1x1x1.
Reference values of VMC and DMC are taken from pbyp moves.

This PR largely rewrite the DMC driver routine makes the DMC tests passing but VMC part remains failing. PR #423 also touched the VMC driver but I have no idea if the VMC was broken even before.

### CODE REVIEW

**Comment by Paul-St-Young** [comment]
@ye-luo I can confirm your updated DMC driver (dd3a976) outputs the correct values in both `scalar.dat` and `stat.h5`. Although I wonder if the amount of changes can be reduced. Please see the changes I applied to my branch [here](https://github.com/Paul-St-Young/qmcpack/commit/a2421400448738fa1145b3b04483fd555705b896). Basically, I separated calls to `auxH->evaluate` from calls to `auxH->setParticlePropertyList`. The `evaluate` routine accumulates `P.Collectables`, whereas `setParticlePropertyList` overwrites `P.PropertyList`. I believe the behavior difference, i.e. accumulate v.s. overwrite, is the main discrepancy between the `scalar.dat` and `stat.h5` collection paths.

**Comment by Paul-St-Young** [comment]
I also realized that this bug extends to the pbyp driver as well. Namely, the `stat.h5` numbers are wrong when the acceptance rate is low. Basically, every time a move is rejected, `P.Collectables` loses statistics. This bug does not show up normally because there are so many accepted moves (one for each particle*~99%).

One can produce the bug only under special circumstances. Examples I can think of:
1. low acceptance due to large time step or bad wave function.
2. very long run where statistical noise is smaller than the bias.

I have produced the bug using method 1 below

allp-pbyp1_sofk

**Comment by ye-luo** [comment]
@Paul-St-Young Thanks for checking. It is good that the driver is correct now. I largely rewrite the driver more for consistency. Your simple fix can make the S(k) correct but if a quantity depends on the WF, it is still wrong. For this reason, I prefer to have the whole WF recomputed if a move is rejected just like what we changed in the VMC driver. I really don't like `H.rejectedMove`. I get the point of your change of API in the H. However, at this point, I prefer not to add more APIs. I used to find so many useless APIs in TrialWavefunctions and the roles are not clear and logical. For the same reason, I prefer to clean up current APIs.

To be honest, I have several concerns in the implementation of data collection in both PropertyList and P.collectables. A lot of housekeeping work is needed.

**Comment by ye-luo** [comment]
@Paul-St-Young please make an issue describing the different collected data in stat.h5 and scalar.dat. I will keep an eye on it when I clean up the estimators.

**Comment by jtkrogel** [comment]
If I recall correctly, that statistical approach used to make stat.h5 matches scalar.dat for VMC, but for DMC it matches dmc.dat (which does not match scalar.dat!).  The difference in the weighting approaches should vanish with population size.  An observed loss of statistics is another matter, but this should also show up for scalar values in stat.h5 as well as energy normed quantities like the energy density.

**Comment by prckent** [comment]
Concurring with @ye-luo 's comments on the APIs: we need to reduce these and document what we have. They are one of the reasons for code inaccessibility.

**Comment by jtkrogel** [comment]
I strongly agree.

**Comment by Paul-St-Young** [comment]
@ye-luo Thanks for the explanation. I totally agree we should keep the API under control. My [commit](https://github.com/Paul-St-Young/qmcpack/commit/a2421400448738fa1145b3b04483fd555705b896) was more an explanation than a real fix.

**Comment by Paul-St-Young** [comment]
I will make a new PR with all I can find out about the `scalar.dat` v.s. `stat.h5` collection paths. I think the development/observables section would serve as a reasonable home for these explanations.

**Comment by ye-luo** [comment]
@prckent Shall we merge this PR? I think the problem inside this driver is fully resolved.

**Comment by ye-luo** [comment]
@Paul-St-Young Please add an issue for the test you have planned and assign it to yourself. Then make a new PR to close it.

**Comment by Paul-St-Young** [comment]
Got it

**Comment by prckent** [comment]
Approving. Important to complete #756 . For the time being, what advice should we give users regarding use of all particle moves?

**Pull request merged**
