### PR TITLE
Added compilation instructions for SummitDev

### PR DESCRIPTION
**Pull request by atillack**
This commit adds a short subsection containing the build instructions for SummitDev at ORNL.

### CODE REVIEW

**Comment by atillack** [comment]
@prckent Thank you. I added the optimization settings for Pascal and a warning that these instructions are preliminary.

**Comment by atillack** [comment]
@prckent and @jefflarkin I added build instructions for libxml2 as well. The whole procedure is now fully self-consistent for a new user and should work "out of the box".

**Comment by jefflarkin** [comment]
@atillack It may be worth noting that one can switch from XL to GCC by setting OMPI_CC=gcc  OMPI_CXX=g++.

**Comment by atillack** [comment]
@jefflarkin You are correct, but unfortunately on SummitDev it is a bit more involved as this changes the available modules and requires some hardcoded directories (for BLAS and LAPACK) - nothing I would recommend right now.

**Comment by jefflarkin** [comment]
@atillack Gotcha. I'm building on a different p8 machine where the change was necessary. Stick with what you've got, since it's specific to summitdev.

**Pull request merged**
