### PR TITLE
Rewrite override vp file XML node

### PR DESCRIPTION
**Pull request by markdewing**
Rewrite the `href` attribute to the `override_variational_parameters` element if it is already present in the file.
If the element is not present, create it.

Previously the code created multiple `override_variational_parameters` elements when starting from a wavefunction that already had it.

The change to the targetExcited line is a formatting change from running clang-format.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
laptop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes This PR is up to date with current the current state of 'develop'
- Yes Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
LGTM.
Hopefully we can get ride of all direct xml calls in QMCCostFunctionBase::updateXmlNodes

**Comment by markdewing** [comment]
There was a sanitizer failure, due to a leak of the xpath object.  I switched the code to use OhmmsXPathObject to automatically take care of it (prompted by Ye's comment about moving away from direct libxml calls)

**Comment by PDoakORNL** [comment]
Can't say its at all clear why codecov/patch is failing

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
new code, no unit test.

**Comment by ye-luo** [comment]
Since the dependency is only TWF, should be unit testable.

**Review by ye-luo — APPROVED** [review]
LGTM. Need non-ANL approval.

**Review by prckent — APPROVED** [review]

**Review by PDoakORNL — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
