### PR TITLE
Fix counting Jas test failure

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes

Fix https://cdash.qmcpack.org/CDash/testDetails.php?test=21311124&build=342868

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
I think this points to a weakness of the current class/function setup - we ought to force an optimizable object to implement this function.

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
> I think this points to a weakness of the current class/function setup - we ought to force an optimizable object to implement this function.

Actually extractOptimizableObjectRefs is required by WFC, OptimizableObject doesn't require this and probably should not. CountingJastrow inherit both classes and thus looks like it is being required by OptimizableObject. So far, my bug trap actually works as intended.

**Comment by prckent** [comment]
Compile time trap would be better though.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
