### PR TITLE
Cleaned Converter and remove unused and untested functions

### PR DESCRIPTION
**Pull request by anbenali**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Remove Gamess FMO as never tested and linked to a branch of Gamess not in main line. 
Remove QP text file  support. H5 support more reliable
Remove Gamess XML specification as no test available
Deprecate "gamessascii" tag
Cleanup tags.
In QMCGaussianParserBase, unify most functions to read from HDF5, to the exception of legacy Gamess.
 
## What type(s) of changes does this code introduce?
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
Laptop Benali

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by jtkrogel** [comment]
Why is the `gamessascii` tag deprecated?  This the only `gamess*` tag Nexus uses.

**Comment by anbenali** [comment]
@jtkrogel Because there is only gamessascii. We don't have any test for GamessXML or any other type of Gamess input. As far as I know, the only available Gamess is Gamess Ascii. So making it Gamess, make more sens?

**Comment by jtkrogel** [comment]
OK, I should change the Nexus usage to `-gamess` as it is functionally equivalent to `-gamessascii`.  Thanks.

**Comment by anbenali** [comment]
@jtkrogel : Thanks. this is just to make the converter less crowded with unused tags.

**Comment by ye-luo** [comment]
Okay to test

**Review by prckent — CHANGES_REQUESTED** [review]
Please update the docs and other files for the gamessascii change
```
grep -r -n -i gamessascii *
docs/lab_advanced_molecules.rst:120:  jobrun_vesta convert4qmc -gamessAscii h2o.hf.output -add3BodyJ
docs/lab_advanced_molecules.rst:756:          convert4qmc -gamessAscii single det.out
docs/lab_advanced_molecules.rst:768:      convert4qmc -gamessAscii orbitals multidet.out -ci cicoeff
docs/lab_advanced_molecules.rst:781:     convert4qmc -gamessAscii multi det.out -ci multi det.out
docs/lab_advanced_molecules.rst:789:-  **-gamessAscii file.out**: Standard output of GAMESS calculation.
labs/misc/jobrun_vesta:33:jobrun_vesta convert4qmc -gamessAscii H2O.CISD.orbs.output -ci H2O.CISD.orbs.output -threshold 0.01 -readInitialGuess 60  -add3BodyJ
labs/lab3_advanced_molecules/GAMESS/DFT/HF/submit_convert.csh:31:runjob --np ${nodes} -p ${tasks} --block $COBALT_PARTNAME --verbose=INFO --envs OMP_NUM_THREADS=$threads : $convert -gamessAscii ${output_orbitals} -add3BodyJ
labs/lab3_advanced_molecules/GAMESS/DFT/HF/submit_convert.csh:34:#runjob --np ${nodes} -p ${tasks} --block $COBALT_PARTNAME --verbose=INFO --envs OMP_NUM_THREADS=$threads : $convert -gamessAscii ${output_orbitals} -ci ${output_ci} -threshold ${thres} -readInitialGuess ${norb} -add3BodyJ
labs/lab3_advanced_molecules/QMCPACK/Generic_Files/submit_convert.csh:31:runjob --np ${nodes} -p ${tasks} --block $COBALT_PARTNAME --verbose=INFO --envs OMP_NUM_THREADS=$threads : $convert -gamessAscii ${output_orbitals} -add3BodyJ
labs/lab3_advanced_molecules/QMCPACK/Generic_Files/submit_convert.csh:34:#runjob --np ${nodes} -p ${tasks} --block $COBALT_PARTNAME --verbose=INFO --envs OMP_NUM_THREADS=$threads : $convert -gamessAscii ${output_orbitals} -ci ${output_ci} -threshold ${thres} -readInitialGuess ${norb} -add3BodyJ
grep: labs/lab3_advanced_molecules/exercises_ref/ex2_slater-jastrow-wf-options/jastrow/2j/h2o.ptcl.xml: No such file or directory
grep: labs/lab3_advanced_molecules/exercises_ref/ex2_slater-jastrow-wf-options/jastrow/12j/h2o.ptcl.xml: No such file or directory
grep: labs/lab3_advanced_molecules/exercises_ref/ex2_slater-jastrow-wf-options/jastrow/1j/h2o.ptcl.xml: No such file or directory
grep: labs/lab3_advanced_molecules/exercises_ref/ex3_multi-slater-jastrow/soci/thres0.01/h2o.soci.out: No such file or directory
grep: labs/lab3_advanced_molecules/exercises_ref/ex3_multi-slater-jastrow/soci/thres0.0075/h2o.soci.out: No such file or directory
grep: labs/lab3_advanced_molecules/exercises/ex3_multi-slater-jastrow/soci/thres0.01/h2o.soci.out: No such file or directory
grep: labs/lab3_advanced_molecules/exercises/ex3_multi-slater-jastrow/soci/thres0.0075/h2o.soci.out: No such file or directory
nexus/tests/unit/test_qmcpack_converter_simulations.py:330:    assert(sim.job.app_command=='convert4qmc -gamessAscii ../rhf/rhf.out')
nexus/tests/unit/test_qmcpack_converter_input.py:208:    assert(ci.write()=='convert4qmc -gamessAscii singledet.out')
nexus/tests/unit/test_qmcpack_converter_input.py:214:    assert(ci.write()=='convert4qmc -gamessAscii orbitals_multidet.out -ci cicoeff_multidet.out')
nexus/tests/unit/test_qmcpack_converter_input.py:221:    assert(ci.write()=='convert4qmc -gamessAscii multidet.out -ci multidet.out -readInitialGuess 42')
nexus/lib/qmcpack_converters.py:431:        gamess_ascii       = 'gamessAscii',
src/QMCTools/convert4qmc.cpp:104:    else if (a == "-gamessAscii" || a == "-gamess")
src/QMCTools/convert4qmc.cpp:106:      if (a == "-gamessAscii")
src/QMCTools/convert4qmc.cpp:107:        std::cout << "Option \"-gamessAscii\" is deprecated and will be removed in the next release. Please use "
tests/molecules/LiH_pp/gamess/c4q.in:1:convert4qmc -prefix c4q -gamessAscii gms.out
tests/converter/converter_test.py:48:    #convert4qmc -nojastrow -prefix gold -gamessAscii be.out
```

**Review by prckent — APPROVED** [review]

**Pull request merged**
