### PR TITLE
Fixes  #5069

### LINKED ISSUE #5069: A strange saveWalker call at MCpopulation
https://github.com/QMCPACK/qmcpack/pull/5063#discussion_r1655626388
Needs visiting. Right now `MCpopulation::saveWalkerConfigurations` seems showing two source of truth.
Walker configuration can be source from `walker_elec_particle_sets_` and `walkers_`.
Better clearly define the scope of both objects when data is up-to-date.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
MCpopulation::saveWalkerConfigurations should only save data from internal walker configurations not particlesets.
It affects DMC restart.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — APPROVED** [review]
Anything similar lurking in DMC?

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
It seems that I made a fix to VMC but there is actually no change to VMC. DMC is the one got affected. Due to branching, coordinates in ParticletSets may not be the same as Walkers. Using the former one is incorrect.

**Comment by prckent** [comment]
I was wondering about any similar Walker / ParticleSet manipulations that might be lurking in the DMC sources. There are reports of the batched code paths being noisier than legacy, so perhaps there is some similar confusion.

**Comment by ye-luo** [comment]
> I was wondering about any similar Walker / ParticleSet manipulations that might be lurking in the DMC sources. There are reports of the batched code paths being noisier than legacy, so perhaps there is some similar confusion.

Would like to know what the reports are especially those after Jan 2024.

**Pull request merged**
