### PR TITLE
Fix single det + WFOpt

### LINKED ISSUE #2496: Variance minimization failure between v3.6.0 and v3.7.0
I noticed that QMCPACK currently struggles badly to optimize a Jastrow by variance minimization for a simple oxygen atom with a fairly short ranged two-body Jastrow (J1 rcut=3.5, J2 rcut=6.0).  Even when handed a good Jastrow optimized via an older build, the optimizer still drifts away to extremely poor wavefunctions.

Below is a sequence of optimizations performed for QMCPACK versions spanning 3.5.0 to 3.9.2.  The behavior of the code is reproducible before and after the breakage, which was introduced somewhere between v3.6.0 and v3.7.0:

```
                          LocalEnergy              Variance                ratio 
v350_soa_real  series 0  -15.728765 +/- 0.009463   1.492333 +/- 0.028086   0.0949 
v350_soa_real  series 1  -15.867034 +/- 0.004702   0.401681 +/- 0.021359   0.0253 
v350_soa_real  series 2  -15.867630 +/- 0.005569   0.355559 +/- 0.007041   0.0224 
v350_soa_real  series 3  -15.870056 +/- 0.004769   0.403680 +/- 0.041663   0.0254 
v350_soa_real  series 4  -15.855346 +/- 0.004068   0.376875 +/- 0.015588   0.0238 
v350_soa_real  series 5  -15.872111 +/- 0.004198   0.383714 +/- 0.013272   0.0242 
v350_soa_real  series 6  -15.864396 +/- 0.003779   0.381579 +/- 0.013733   0.0241 
v350_soa_real  series 7  -15.862345 +/- 0.004467   0.365200 +/- 0.012512   0.0230 
 
v360_soa_real  series 0  -15.729211 +/- 0.008024   1.530882 +/- 0.023830   0.0973 
v360_soa_real  series 1  -15.868733 +/- 0.004633   0.392810 +/- 0.029925   0.0248 
v360_soa_real  series 2  -15.870868 +/- 0.004801   0.358298 +/- 0.009480   0.0226 
v360_soa_real  series 3  -15.867750 +/- 0.003984   0.343698 +/- 0.009605   0.0217 
v360_soa_real  series 4  -15.868260 +/- 0.004139   0.364282 +/- 0.012437   0.0230 
v360_soa_real  series 5  -15.871399 +/- 0.004174   0.385131 +/- 0.019431   0.0243 
v360_soa_real  series 6  -15.860257 +/- 0.004646   0.351132 +/- 0.011940   0.0221 
v360_soa_real  series 7  -15.847381 +/- 0.004128   0.401248 +/- 0.008341   0.0253 
 
v370_soa_real  series 0  -15.724448 +/- 0.007897   1.544877 +/- 0.023274   0.0982 
v370_soa_real  series 1  -15.749744 +/- 0.010039   1.989610 +/- 0.067119   0.1263 
v370_soa_real  series 2  -15.774872 +/- 0.015697   2.582455 +/- 0.177060   0.1637 
v370_soa_real  series 3  -15.737155 +/- 0.010289   2.424819 +/- 0.080883   0.1541 
v370_soa_real  series 4  -15.728370 +/- 0.011444   2.359724 +/- 0.049627   0.1500 
v370_soa_real  series 5  -15.705689 +/- 0.010365   2.383542 +/- 0.058148   0.1518 
v370_soa_real  series 6  -15.728391 +/- 0.013717   2.453381 +/- 0.070631   0.1560 
v370_soa_real  series 7  -15.713733 +/- 0.009296   2.441217 +/- 0.052501   0.1554 
 
v380_soa_real  series 0  -15.728750 +/- 0.007862   1.502734 +/- 0.021760   0.0955 
v380_soa_real  series 1  -15.777613 +/- 0.009606   1.884318 +/- 0.059431   0.1194 
v380_soa_real  series 2  -15.763667 +/- 0.009097   2.276413 +/- 0.070049   0.1444 
v380_soa_real  series 3  -15.746334 +/- 0.009049   2.081680 +/- 0.047240   0.1322 
v380_soa_real  series 4  -15.735534 +/- 0.011223   2.158009 +/- 0.063911   0.1371 
v380_soa_real  series 5  -15.732327 +/- 0.009506   2.243873 +/- 0.046932   0.1426 
v380_soa_real  series 6  -15.720645 +/- 0.012374   2.206366 +/- 0.070763   0.1403 
v380_soa_real  series 7  -15.728993 +/- 0.008947   2.112217 +/- 0.059391   0.1343 
 
v392_soa_real  series 0  -15.721737 +/- 0.011744   1.565547 +/- 0.033137   0.0996 
v392_soa_real  series 1  -15.725116 +/- 0.010556   2.609049 +/- 0.061071   0.1659 
v392_soa_real  series 2  -15.728824 +/- 0.011605   2.423152 +/- 0.049712   0.1541 
v392_soa_real  series 3  -15.738421 +/- 0.009981   2.125916 +/- 0.048893   0.1351 
v392_soa_real  series 4  -15.718103 +/- 0.011568   2.528542 +/- 0.081094   0.1609 
v392_soa_real  series 5  -15.724731 +/- 0.010427   2.767007 +/- 0.086160   0.1760 
v392_soa_real  series 6  -15.717093 +/- 0.010098   2.275466 +/- 0.060844   0.1448 
v392_soa_real  series 7  -15.713159 +/- 0.011786   2.196424 +/- 0.063463   0.1398 
```

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Fix #2496, both cases
The bug affected single det + WF optimization. When the optimizer reset WF, the single det was not reset clean.
A safeguard is introduced to check recomputed variance against the earlier VMC variance.

This PR can be reviewed independent of #2682 but be sure to merge after #2682

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by prckent** [comment]
Thanks Ye. Assuming this fixes all the issues, do you have any opinions as to how to avoid mistakes like this in future?

**Comment by ye-luo** [comment]
I tried to make a precise and trimmed reproducer but it was not successful. So I put this approximate safeguard which is more universally valid like our NaN checks. Apart from what developers adding more tests or checks, I'm wondering if we can build more diagnosis on the statistics in the code or workflow tools to help catching issues in the code.

**Comment by prckent** [comment]
Does the new check catch both reported errors?

We are clearly lacking in deterministic optimizer checks for different wavefunctions.

**Comment by ye-luo** [comment]
> Does the new check catch both reported errors?
> 
> We are clearly lacking in deterministic optimizer checks for different wavefunctions.

Yes. The added safeguard traps the reported bugs.

**Review by prckent — APPROVED** [review]
Adding internal checks is very worthwhile, particularly between the optimizer and the vmc driver where there is a big handoff.

**Pull request merged**
