### PR TITLE
Expand Werror CI with Mixed precision variants

### LINKED ISSUE #4178: Mixed precision in github action CI
**Is your feature request related to a problem? Please describe.**
There is no mixed precision variant and relies on self-hosted CI to run this case.
It is better to catch issues early as self-hosted CI are much slower to run.
Expand GCC11-NoMPI-Werror-Complex and complex mixed precision build will be sufficient.

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

PR add mixed precision variants to real and complex Werror CI on GitHub Actions runners
Fixes #4178 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must pass GitHub Actions CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — APPROVED** [review]
Thanks!

**Review by prckent — DISMISSED** [review]
We should keep an eye on the runtimes for the growing number of variants.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
> We should keep an eye on the runtimes for the growing number of variants.

Right now, the rocm (1.5h) is the bottleneck.

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
