### PR TITLE
Add math libraries as CMake targets

### PR DESCRIPTION
**Pull request by ye-luo**
~~Merge after #2289~~
## Proposed changes
Add Math::scalar_vector_function Math::BLAS_LAPACK Math::FFTW targets for external libraries.
The overall searching order is
1. Look for vendor optimized libraries.
2. If 1 found nothing, look for individual fallback

## What type(s) of changes does this code introduce?
_Put an `x` in the boxes that apply._

- [ ] Bugfix
- [ ] New feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

## What systems has this change been tested on?
ALCF Theta Intel
NERSC Cori Intel
OLCF Summit GNU, XL, CUDA
My workstation, GNU no MPI, GNU finds MPI not via compiler wrapper.

## Checklist

_Put an x in the boxes that apply. You can also fill these out after creating
the PR. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- [x] this PR is up to date with current the current state of 'develop'
- [ ] code added or changed in the PR has been clang-formatted
- [ ] this PR adds tests to cover any new code, or to catch a bug that is being fixed
- [ ] documentation has been added (if appropriate)

### CODE REVIEW

**Comment by markdewing** [comment]
I think it would be helpful to point out a couple CMake features that form a background for a full understanding of this PR.  The first is a move to using CMake interface libraries

https://cmake.org/cmake/help/latest/command/add_library.html?highlight=interface#interface-libraries

The line
```
add_library(mylib INTERFACE IMPORTED)
```
defines the library.   Various properties are set, such as
```
set_target_properties(mylib PROPERTIES INTERFACE_COMPILE_DEFINTIONS "USING_MYLIB")
```
In this case, INTERFACE_COMPILE_DEFINTIONS will add "-DUSING_MYLIB" to the compile line for any target that depends on "mylib".



The second feature is the use of double colons in the imported library name. 
See policy 0028 for some more details https://cmake.org/cmake/help/latest/policy/CMP0028.html

With the new policy, names with double colons are treated special by CMake, as a name for an imported library.  If the name is not found, an error message is issued at configuration time.

```
add_executable(hello hello.cpp)
target_link_libraries(hello Math::BLAS_LAPACK)
```
With the above in the cmake file, running cmake will give the error:
```
CMake Error at CMakeLists.txt:17 (add_executable):
  Target "hello" links to target "Math::BLAS_LAPACK" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```

With the old policy, the name is treated as a library name (i.e. a file name on disk somewhere), and no error is issued at configuration time.   The library is not reported as missing until compile time.
```
/usr/bin/ld: cannot find -lMath::BLAS_LAPACK
collect2: error: ld returned 1 exit status
CMakeFiles/hello.dir/build.make:84: recipe for target 'hello' failed
make[2]: *** [hello] Error 1
```

Note that one also gets the old policy behavior (regardless of policy setting) for library targets that do not have a double colon:
```
add_executable(hello hello.cpp)
target_link_libraries(hello mylib)
```
The above configuration will give the following error:
```
/usr/bin/ld: cannot find -lmylib
collect2: error: ld returned 1 exit status
CMakeFiles/hello.dir/build.make:84: recipe for target 'hello' failed
make[2]: *** [hello] Error 1
```

**Comment by prckent** [comment]
Working with MKL and random system blas library for at least a subset of our nightly build combinations.

**Comment by prckent** [comment]
Thanks @markdewing for the explainer above.

**Comment by ye-luo** [comment]
Thanks @mark for the introduction of background knowledge. I was not also aware of "double colons" special rule. Anyone puzzled by PRIVATE, INTERFACE, PUBLIC keywords may read https://cmake.org/pipermail/cmake/2016-May/063400.html.

**Pull request merged**
