### PR TITLE
Consolidate SPOSet input handling

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
1. Make all SPOSetBuilderFactory static functions and variables scoped.
2. #2070 input style 2 and 3 all prints `!!!!!!! Deprecated input style`
3. basisset handling is moved into LCAOrbitalSet constructor. basisset can be named now.
Another step to memory clean code.

## What type(s) of changes does this code introduce?
- New feature
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Ryzen-box

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — CHANGES_REQUESTED** [review]
We should give stronger warnings+solution. e.g.:

!!!!!!! Deprecated input style. Creating SPO set inside determinantset
=>
Deprecated input style: creating an SPO set inside a determinantset. Support for this usage will soon be removed. SPO sets should be built outside.

**Comment by ye-luo** [comment]
@prckent Warning messages are updated. My current plan is to delete the legacy way after the next release.

**Comment by prckent** [comment]
@ye-luo I agree with you. We will need at least one release with the warning in (v4.0.0).

**Comment by ye-luo** [comment]
@prckent OK to merge?

**Review by prckent — APPROVED** [review]
Editorial: The historic use of mystery integers to code radialOrbType is unfortunate.

**Pull request merged**
