### PR TITLE
Consolidate boolean handling in AttributeSet/ParameterSet

### LINKED ISSUE #2758: ParameterSet cannot handle boolean
**Describe the bug**
ParameterSet::add(bool) doesn't parse bool correctly.
The most funny logic is fliping value if the input entry is empty.
https://github.com/QMCPACK/qmcpack/blob/41b802bd38cb639ce040c555b4c20c4ecf490427/src/OhmmsData/OhmmsParameter.h#L171

**Expected behavior**
parse yes/no correctly

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Restrict input to "yes"/"no"/"true"/"false" values. block unknown or empty value.
Closes #2758

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
std::string yes should be renamed to input_string or somesuch. This avoids yes == "yes" etc.

Are the bool values converted to lower case anywhere? What about supporting "No" and "Yes"? A polite user friendly feature would be to support these variants, even if we don't advertise.

**Comment by ye-luo** [comment]
> std::string yes should be renamed to input_string or somesuch. This avoids yes == "yes" etc.
> 
> Are the bool values converted to lower case anywhere? What about supporting "No" and "Yes"? A polite user friendly feature would be to support these variants, even if we don't advertise.

Added upper case handling.

**Review by prckent — APPROVED** [review]
Thanks.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
