### PR TITLE
Switch MPI point2point manager to ucx on sulfur

### LINKED ISSUE #3658: sulfur CI MPI converter tests are broken
**Describe the bug**
converter tests are showing errors in stderr due to some MPI configuration issues with PSM3

```
Start   68: converter_test_HDF5_Be_ccd
 68/912 Test   #68: converter_test_HDF5_Be_ccd ........................................................................***Failed  Error regular expression found in output. Regex=[  FAIL]  0.71 sec
Stderr not empty
sulfur.ornl.gov:rank0: PSM3 can't open nic unit: 0 (err=23)
--------------------------------------------------------------------------
Open MPI failed an OFI Libfabric library call (fi_endpoint).  This is highly
unusual; your job may behave unpredictably (and/or abort) after this.

  Local host: sulfur
  Location: mtl_ofi_component.c:513
  Error: Invalid argument (22)
--------------------------------------------------------------------------
Rank =    0  Free Memory = 362979 MB
```
**To Reproduce**
1. `develop` branch 
2. cmake command:
    
 ```
    cmake -GNinja \
-DCMAKE_C_COMPILER=/usr/lib64/openmpi/bin/mpicc \
-DCMAKE_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx \
-DMPIEXEC_EXECUTABLE=/usr/lib64/openmpi/bin/mpirun \
-DBUILD_AFQMC=ON \
-DENABLE_CUDA=ON \
-DCMAKE_PREFIX_PATH=/opt/OpenBLAS/0.3.18 \
-DQMC_COMPLEX=0 \
-DQMC_MIXED_PRECISION=1 \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
..
```

3. ninja
4. `ctest -R converter`

**Expected behavior**
CI should pass on sulfur

**System:**
sulfur

**Additional context**
There was a recent update on CUDA version and sulfur restart (@prckent can provide more context)
Will try switching MPI management layer

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Switch point to point manager to ucx
Attempts to fix #3658 

## What type(s) of changes does this code introduce?

- Bugfix

### Does this introduce a breaking change?

- Yes

## What systems has this change been tested on?
sulfur, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]
@prckent seem we need to force a merge.

**Comment by williamfgc** [comment]
The solution is somehow flawed as it's not capturing the hostname, let me dig into this.

**Comment by williamfgc** [comment]
Start testing in-house

**Comment by williamfgc** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
