### PR TITLE
Respect QMC_GPU_ARCHS as the single source of truth

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Use CMAKE_CUDA/HIP_ARCHITECTURES as hints and get them overwritten once QMC_GPU_ARCHS is settled.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
JLSE

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Review by PDoakORNL — CHANGES_REQUESTED** [review]
In general I'm used to using `CMAKE_CUDA_ARCHITECTURES` `CMAKE_HIP_ARCHITECTURES` since the architecture tags aren't portable anyway.

Seems like that would stop working here.

**Comment by ye-luo** [comment]
> In general I'm used to using `CMAKE_CUDA_ARCHITECTURES` `CMAKE_HIP_ARCHITECTURES` since the architecture tags aren't portable anyway.
> 
> Seems like that would stop working here.

They still work as it was.

**Review by rcclay — APPROVED** [review]

**Comment by ye-luo** [comment]
ping @PDoakORNL

**Review by PDoakORNL — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
