### PR TITLE
Add deterministic test for 1x1 2D graphene 

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
Add deterministic test for 1X1 2D graphene to reproduce the issue claimed on #2105 . Two deterministic tests for graphene within 'p p n' boundary condition has added. 1. 10 A for z direction. 2. 20 A for z direction using 'vacuum' parameter.

Here are comments for this deterministic tests.

1.  References for ion-ion term are slightly difference between compiler used to build QMCPACK.
eg. intel18 ion-ion : 14.00302796   gcc 6.2 : 14.00303308

2. As reported on the issue, the current QMC ion-ion term shows much difference with the original DFT result. (10A vacuum graphene :  0.025 eV, 20A vacuum graphene : 0.889 eV ion-ion term difference) Therefore, the current references for the test may not right values, so they need to be changed when the issue has resolved.

3. I put references from QMCPACK 3.6, and DFT ion-ion term on CMakeList as the comment. They will be removed when the issue has resolved. Currently, tests for only full-precision non-cuda build have added. The test for the other build will be added also when the issue has resolved.

Hyeondeok Shin

### CODE REVIEW

**Comment by Hyeondeok-Shin** [comment]
@prckent I'll add ion-ion term for the other build, and change bconds and references for 'p p p' if values are changed. The reason why I put references as the bad ion-ion term is to make CI pass (alcf-gnu6-mkl18) to merge. I can change the test name to merge. It will break our rule to make a title for the test but temporary until the issue has resolved.

**Comment by prckent** [comment]
OK to test

**Comment by Hyeondeok-Shin** [comment]
@prckent Now, test is available with all builds.
 I changed ion-ion term references to Q.E. output and change test name to issue-deterministic-grapheneC_1x1_pp-vmc_sdj. This name is temporary, and not detected with ctest -L deterministic, so CI will be passed. On the other hand, it is detected with ctest -R deterministic, so test can be seen on cdash for certain build using ctest -R deterministic. (eg. cetus)
  Please let me know if you need additional commit on this.

**Comment by prckent** [comment]
This should end up under "nightly" on cdash, since this part of the dashboard catches tests that  don't match labels (EXCLUDE_LABEL "deterministic|performance|converter|unstable")

**Comment by Hyeondeok-Shin** [comment]
@prckent based on results from @jtkrogel, ion-ion energy difference between Q.E. and QMCPACK becomes significantly larger as increasing z cell size for graphene. Actually, current test shows ~ 0.025 eV difference with 10 A z cell, but 20 A z cell (ppn) shows large 0.88 eV difference. 
 So, if we want to see larger difference than current test, we should increase z cell size, but I don't recommend it with ppp because h5 size will extremely large.  
 Is it good to revive only ion-ion test for p p n with vacuum?  It will give large difference without adding large h5 file. I don't see any significant difference on energy between ppp and ppn for 10 A Z cell, so I think 20 A z cell is the same.

**Comment by prckent** [comment]
Lets focus on ppp since this is what QE calculates. 

We should have looked at the file sizes earlier. Please can you investigate the file sizes with (say) a 10Ry cutoff? The wavefunctions are irrelevant for these tests, so the full 120Ry is not needed. This should allow the current 10A and a new 20A one to have a sensible size. 

Regarding ppn, I would like the conversation around ppp and the 3D bug to proceed further before we decide what to do with mixed boundary conditions.

**Comment by prckent** [comment]
Another option would be to make this a test that actually runs QE, as we do for the qe-atomO test. The reference ion-ion energy could be grabbed from the QE output. An example like this would make it very convenient to add more tests without inflating the size of the repository.

**Comment by Hyeondeok-Shin** [comment]
@prckent I'll do with the smaller cut-off first and make an additional test for larger z size. It can be done quickly. We can talk about Q.E. test if we feel additional z sizes are needed after checking it.

**Comment by prckent** [comment]
Please remake the PR from a fresh branch so we don't have big file in the git history.

**Comment by Hyeondeok-Shin** [comment]
I'll close this PR and remake it when ready.

**Pull request closed without merging**
