### PR TITLE
Fix OpenBC PP with SoA.

### PR DESCRIPTION
**Pull request by ye-luo**
The PP local channel computation was not correct with SoA. Reported by H. Shin.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by prckent** [comment]
Why did not our tests catch this?

**Comment by ye-luo** [comment]
We only have one OpenBC test in the QE test atomO. In that case, the local channel contribution is small. This was caught on a H PP with only a local channel.

**Comment by prckent** [comment]
Suggestion: make some "edge case" tests, e.g. pseudopotential hydrogen atom, splines and gaussians. This will only have one occupied spin channel and might catch some edge cases that we don't normally test. It would also catch this case.

**Pull request merged**
