### PR TITLE
Resolve MSD table method numerical instability

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
In the MSD implementations
MSD(R) = \sum_i C_i * det^up_i(R) * det^dn_i(R)
This value grows as exp(Ne) as individual determinant grows the same way.
The old implementation uses MSD(R) in a few places and cased NaN due to over or underflow of float point numbers.
The new implementation fixes by using
MSD'(R)= C_ref + \sum_(i!=ref) C_i * det^up_i(R) * det^dn_i(R) / (det^up_ref(R) * det^dn_ref(R))
which is not vulnerable to over/underflow.

This should fixes https://groups.google.com/g/qmcpack/c/Yb3mVKBzH0Q 

## What type(s) of changes does this code introduce?
- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
I couldn't find sposet_collection in our docs. Please explain the what/where/why etc.

**Comment by ye-luo** [comment]
> I couldn't find sposet_collection in our docs. Please explain the what/where/why etc.

it is interchangeable with `sposet_builder` right now which can be used to build SPOs outside determinant tag. Calling `builder` is just to techinical. When using the following style
```
<sposet_collection ....>
  <sposet name="a" ....>
  <sposet name="b" ....>
</sposet_collection>
```
a set of sposets of the same type are built. Thus, I prefer calling it `sposet_collection`

**Comment by prckent** [comment]
Thanks for the explanation. We'll need to update the docs as `sposet_collection` is solidified.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
LGTM. Good improvement. I'll note we have a deterministic test on MSD wavefunctions run in the CI, so this code is tested. We should keep an eye on optimization tests in the nightlies.

**Comment by ye-luo** [comment]
I did all the development work based on unit tests and then everything works out-of-box. I enjoyed the dev experience this time. I did test optimization in `short`.

**Pull request merged**
