### PR TITLE
Nexus: tool to process ESHDF kinetic energy

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

This PR adds a new tool to process ESHDF files, with the first capability being the calculation of total or per-orbital kinetic energies.  The tool is self-documenting:

```
>eshdf

  User error:
    First argument must be operation to perform on ESHDF file.
    e.g. to examine kinetic energies, type "eshdf kinetic ..."
    Valid operations are: ['kinetic']
  exiting.
```

```
>eshdf kinetic

Usage: eshdf kinetic [options] [eshdf_file]

Options:
  --version     show program's version number and exit
  -h, --help    Print help information and exit (default=False).
  --Ef=E_FERMI  Fermi energy in eV (default=None).
  -o, --orb     Print per orbital kinetic energies (default=False).
```

Reported information when pointed at an ESHDF file:

```
>eshdf kinetic ./diamond_twist/pwscf.pwscf.h5 --Ef=13.2874

Number of spins              : 1
Number kpoints               : 32
Number of electrons per spin : [128]
Total kinetic energy         : 136.2794469773107 Ha
Kinetic energy per spin      : [136.27944698] Ha
```

Suggestions for future updates are welcomed, especially from those who have shown interest in the creation of the tool (e.g. @rcclay, @jptowns, and @mcbennet ).

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Desktop 

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Comment by lshulen** [comment]
It would be great to fold this into the converter tests for initial wavefunctions coming from plane wave codes.  Along those lines, it might be worth adding a quick check that the SPOs are consistently normalized.  Not so useful scientifically (I believe QMCPACK does this internally) but could be helpful for testing.

**Comment by jtkrogel** [comment]
Thanks Luke, those are good suggestions.  It would be easy to report the summed norms, which should match the electron count.

**Comment by jtkrogel** [comment]
@lshulen Norms added:

```
>eshdf kinetic ./diamond_twist/pwscf.pwscf.h5 --Ef=13.2874

Number of spins              : 1
Number kpoints               : 32
Number of electrons per spin : 128
Summed orbital norm per spin : 128.
Total kinetic energy         : 136.2794469773107 Ha
Kinetic energy per spin      : 136.27944698 Ha
```

**Comment by prckent** [comment]
Add a warning if the norms are not as expected?

**Comment by jtkrogel** [comment]
Warning added.

**Pull request merged**
