### PR TITLE
Add batch driver tests for He orbital rotation parameter gradient

### PR DESCRIPTION
**Pull request by markdewing**
Add batch driver versions of single thread and multi-thread tests for parameter gradient for He with orbital rotation.

Also update the test names with "short-" prefix.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- Yes This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — DISMISSED** [review]
LGTM

Note that these don't run in the CI so please eyeball the nightlies after merge.

**Comment by prckent** [comment]
Test this please

**Comment by markdewing** [comment]
Test this please

**Comment by markdewing** [comment]
Updated to exclude the tests from the complex build.  Addresses nightly test failures such as https://cdash.qmcpack.org/CDash/testDetails.php?test=20387688&build=329863

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
