### PR TITLE
Merge Rc 3130 to main for release

### PR DESCRIPTION
**Pull request by prckent**
## Proposed changes

Merge the release candidate to main following https://github.com/QMCPACK/qmcpack/wiki/Release-process

Assuming no issues aim to push release tomorrow morning (Wednesday).

## What type(s) of changes does this code introduce?

- Bugfix
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- Yes (some minor legacy code paths removed)

## What systems has this change been tested on?

Weekly tests were run ahead of branching the rc

## Checklist

- No. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
(Testing my understanding of how the actions setup is propagated. Not expecting the cloud tests to run)

**Comment by ye-luo** [comment]
Test this please

**Review by ye-luo — DISMISSED** [review]

**Review by ye-luo — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Per the official release process I am also running a build of this PR. Intel+random libraries from RHEL. This step is definitely less needed now than when we had fewer deterministic tests and CI.

I noticed one of the save coefs tests failed. Will wait for the full set to complete before merging.

**Comment by prckent** [comment]
Output of
```
export UCX_TLS=ud,sm,self
export I_MPI_FABRICS=shm
export OMP_NUM_THREADS=16
cmake -DCMAKE_C_COMPILER=mpiicc -DCMAKE_CXX_COMPILER=mpiicpc -DQMC_DATA=/scratch/pk7/QMC_DATA_FULL/ -DQMC_NIO_MAX_SIZE=32 ../qmcpack/
make -j 32
nohup nice ctest -j 48 --output-on-failure >& ctest.out &
```
No particular concerns:
```
Total Test time (real) = 9855.23 sec

The following tests FAILED:
        265 - short-li2_sto-sj_dmc-4-4-totenergy (Failed)
        286 - short-C2_pp_msdj-XML-vmc-1-16-totenergy (Failed)
        323 - short-C4_md-ae-ground-qp-vmc-1-16-variance (Failed)
        358 - short-LiH_ae_qp-vmc_hf_noj-1-16-kinetic (Failed)
        359 - short-LiH_ae_qp-vmc_hf_noj-1-16-totenergy (Failed)
        387 - short-LiH_pp-vmc_hf_sdj_xml-4-4-totenergy (Failed)
        448 - short-H2-orb-opt-spindepjas-16-1-totenergy (Failed)
        460 - short-H4-RHF-orb-opt-16-1-totenergy (Failed)
        464 - short-H4-orb-opt-1-16-totenergy (Failed)
        465 - short-H4-orb-opt-dmc-16-1 (Failed)
        466 - short-H4-orb-opt-dmc-16-1-totenergy (Failed)
        468 - short-H4-orb-opt-dmc-1-16-totenergy (Failed)
        492 - short-H4-msd-orb-opt-16-1-totenergy (Failed)
        740 - short-bccH_1x1x1_ae-vmc-all-nodrift_sdj-1-16-kinetic (Failed)
        744 - short-bccH_1x1x1_ae-vmc-all-nodrift_sdj-1-16-potential (Failed)
        758 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1 (Failed)
        759 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-totenergy_A (Failed)
        760 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-totenergy_B (Failed)
        761 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-dtotenergy_AB (Failed)
        762 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-ionion_A (Failed)
        763 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-ionion_B (Failed)
        764 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-dionion_AB (Failed)
        765 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-eeenergy_A (Failed)
        766 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-eeenergy_B (Failed)
        767 - short-bccH_1x1x1_ae-csvmc-pbyp-nodrift_sdj-16-1-deeenergy_AB (Failed)
        768 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1 (Failed)
        769 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-totenergy_A (Failed)
        770 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-totenergy_B (Failed)
        771 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-dtotenergy_AB (Failed)
        772 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-ionion_A (Failed)
        773 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-ionion_B (Failed)
        774 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-dionion_AB (Failed)
        775 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-eeenergy_A (Failed)
        776 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-eeenergy_B (Failed)
        777 - short-bccH_1x1x1_ae-csvmc-all-nodrift_sdj-16-1-deeenergy_AB (Failed)
        778 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1 (Failed)
        779 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-totenergy_A (Failed)
        780 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-totenergy_B (Failed)
        781 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-dtotenergy_AB (Failed)
        782 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-ionion_A (Failed)
        783 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-ionion_B (Failed)
        784 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-dionion_AB (Failed)
        785 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-eeenergy_A (Failed)
        786 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-eeenergy_B (Failed)
        787 - short-bccH_1x1x1_ae-csvmc-all_sdj-16-1-deeenergy_AB (Failed)
        1302 - long-diamondC_2x1x1_pp-vmc_sdj_excited-1-16 (SIGHUP)
        1304 - long-diamondC_2x1x1_pp-vmc_sdj_excited-1-16-samples (Failed)
        1804 - short-diamondC_2x1x1-Gaussian_pp_MSD-1-16-localecp (Failed)
        1929 - long-diamondC_2x1x1_pp-dmc_gaussian_sdj-1-16 (SIGHUP)
        1930 - long-diamondC_2x1x1_pp-dmc_gaussian_sdj-1-16-totenergy (Failed)
        1943 - long-hcpBe_1x1x1_pp-vmc_sdj-1-16 (SIGHUP)
        1945 - long-hcpBe_1x1x1_pp-vmc_sdj-1-16-samples (Failed)
Errors while running CTest
```

**Pull request merged**
