### PR TITLE
Explicitly set OpenMP runtime library rpath like other normal libraries

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
This should resolve OpenMP runtime library mismatch issue at runtime.

## What type(s) of changes does this code introduce?
- Bugfix
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — COMMENTED** [review]
Can you explain how this helps someone running build/bin/qmcpack ? It does look like it will help for ctest runs.

**Comment by ye-luo** [comment]
BUILD_RPATH embeds rpath/runpath when linking executables in the build directory. When we run ctest, this info will be used for look up libraries although the priority is lower than environment variable LD_LIBRARY_PATH.
INSTALL_RPATH makes sure rpath/runpath are kept after `make install`

**Comment by ye-luo** [comment]
Test this please

**Review by PDoakORNL — APPROVED** [review]
LGTM

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
