### PR TITLE
Update docs with recently added Complex CI runs

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Dummy PR with docs changes to trigger CI for newly added cases in #3962 
Some formatting

## What type(s) of changes does this code introduce?

- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
CI must pass

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by williamfgc** [comment]
Test this please

**Comment by williamfgc** [comment]
Something is still not right. I will try to find what's different from local runs. The unit wave function test passes, though.

**Comment by ye-luo** [comment]
MSD tests spit out bad numbers due to MultiSlaterDetTableMethod.cpp offload regions being recompiled. On my workstation (sm_80) and JLSE (sm_70), as long as using CUDA <= 11.2, tests pass.

**Comment by ye-luo** [comment]
In PR #3921 failure, https://github.com/QMCPACK/qmcpack/runs/6104394600?check_suite_focus=true
```
/scratch/ci/actions-runner-2/_work/qmcpack/qmcpack/src/QMCWaveFunctions/tests/test_multi_slater_determinant.cpp:274: FAILED:
  CHECK( grad_new.grads_positions[0][1] == ValueApprox(1.2425653495) )
with expansion:
  -nan == Approx( 1.2425653495 )
```
The second element of [3] array went wrong, just like the imaginary part of a complex type.

**Comment by ye-luo** [comment]
I think I know the problem.
run_step.sh script doesn't carry all the parameters set during "configure" to "build"

**Comment by williamfgc** [comment]
Test this please. Thanks @ye-luo let's try with the latest commit, tests pass locally.

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
It looks better than before on #3921
Before failing complex, complex-mixed, real.
https://github.com/QMCPACK/qmcpack/actions/runs/2199014055
With this PR only complex failed.
https://github.com/QMCPACK/qmcpack/actions/runs/2203064218
Still don't know why complex failed.

**Pull request merged**
