### PR TITLE
Add openmp offload build on GitHub Actions CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add build-only test for OpenMP offload x86-64 target using no-mpi clang-12 on Ubuntu 20.04
Add Dockerfile for Ubuntu 20.04 container image with clang-12 already available in [DockerHub](https://hub.docker.com/r/williamfgc/qmcpack-ci/tags?page=1&ordering=last_updated)
Add container to docs
Related to #3169 

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests): new CI job for openmp offload using clang-12
- Documentation changes: new Docker container

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 20.04, must pass GitHub Actions CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by prckent — CHANGES_REQUESTED** [review]
`wget -O - https://apt.llvm.org/llvm.sh`

ha ha! It is the codecov security hole all over again. Can you store a local copy, verify the hash, or find a better way?

Once the tests are working with  x86 offload, we'll want to change this to real and complex coverage build. Note that complex does not add much.

**Comment by prckent** [comment]
(Trying to compile this but running into rocm dependency issues and other newb problems.)

**Comment by williamfgc** [comment]
@prckent silly me, great catch. I modified the Dockerfile to add the gpg keys to the llvm repo if that's a better route. I'm updating the generated container as well. 

> Once the tests are working with x86 offload, we'll want to change this to real and complex coverage build. Note that complex does not add much.

Sounds good, right now this is just building. Thanks!

**Comment by ye-luo** [comment]
@williamfgc can we turn on "-L unit" tests?

**Review by ye-luo — APPROVED** [review]

**Review by prckent — COMMENTED** [review]
@williamfgc Your gpg fix helps but doesn't prevent the problem unless you store the key locally or (say) get the key from an independent site.

**Comment by williamfgc** [comment]
@prckent yes, this version requires the gpg key for downloading from a trusted site (apt.llvm.org). Since it's only a one way thing to create a docker container it should meet our needs. On a side note, `apt-key add` [is deprecated](http://manpages.ubuntu.com/manpages/groovy/man8/apt-key.8.html) starting on Ubuntu 20.10 so future contains will need a different authentication. Thanks!

**Comment by williamfgc** [comment]
@ye-luo I accidentaly closed this PR, please feel free to reactivated it as I don't

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
OK to test

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
