### PR TITLE
Deterministic spin density test with multiple walkers/mpi/threads

### PR DESCRIPTION
**Pull request by jtkrogel**
## Proposed changes

Add deterministic VMC test for spin density with multiple walkers, mpi ranks, and threads.

Note: removing MPC from these speeds up the deterministic test from 3s to 1.4s.  Probably worth doing on all deterministic tests that don't explicitly need to check MPC.

## What type(s) of changes does this code introduce?

- New test

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
@jtkrogel you can find the CI failure by clicking the details of alcf-gnu-mkl18

**Comment by prckent** [comment]
A naive build with Intel2020 is failing for me in deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check. The error looks to be plumbing related. I'll investigate further but the missing file error is likely general and should be reproducible (?).
```
> ctest -R deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4 -VV
...
896: Timer      Inclusive_time  Exclusive_time  Calls       Time_per_call
896: Total         6.1709     0.0755              1       6.170946836
896:   Startup     4.8664     4.8664              1       4.866437912
896:   VMC         1.2290     1.2290              1       1.229032993
1/2 Test #896: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4 .........   Passed    8.70 sec
test 897
    Start 897: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check

897: Test command: /home/pk7/projects/qmc/git_QMCPACK_prckent/qmcpack/tests/scripts/check_stats.py "-s" "0" "-q" "spindensity" "-e" "0" "-c" "8" "-p" "det_qmc_spindens_short" "-r" "qmc-ref/det_qmc_spindens_short_mw.s000.stat_ref_spindensity_4_4.dat"
897: Test timeout computed to be: 3600
897: stat.h5 file matching prefix det_qmc_spindens_short.s000 was not found
897: search path: ./
897: Test status: fail
2/2 Test #897: deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check ...***Failed    0.33 sec

The following tests passed:
	deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4

50% tests passed, 1 tests failed out of 2

Label Time Summary:
deterministic      = 139.53 sec*proc (2 tests)
quality_unknown    = 139.53 sec*proc (2 tests)

Total Test time (real) =   9.08 sec

The following tests FAILED:
	897 - deterministic-diamondC_1x1x1_pp-vmc-estimator-spindensity-4-4-check (Failed)
Errors while running CTest
```

**Comment by prckent** [comment]
Working with Intel2020 after simple plumbing fix - a _mw was missing from the check_stats.py invocation.

**Comment by prckent** [comment]
Confirming working with GCC10.2 and OpenBLAS using OpenMPI, both real and complex builds. The 4-4 test is correctly skipped when built without MPI.

**Comment by prckent** [comment]
LGTM but a non-ORNL person is needed to review+merge.

**Comment by prckent** [comment]
OK to test

**Review by markdewing — APPROVED** [review]

**Pull request merged**
