### PR TITLE
Fix CI offload build failure and add checks upon CMake return failure

### PR DESCRIPTION
**Pull request by ye-luo**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## Proposed changes

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Bugfix
- New feature
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no api changes)
- Build related changes
- Testing changes (e.g. new unit/integration/performance tests)
- Documentation changes
- Other (please describe):

### Does this introduce a breaking change?

- Yes
- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes/No. This PR is up to date with current the current state of 'develop'
- Yes/No. Code added or changed in the PR has been clang-formatted
- Yes/No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes/No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
AFQMC shows some issue as https://cdash.qmcpack.org/CDash/testDetails.php?test=28616963&build=447804 when using CUDA 12.1. Revert back to 11.2.

**Comment by prckent** [comment]
We should make some issues to track the problems found here. e.g. We could easily add a couple of different labeled CUDA versions in the nightlies, labeling the CI builds etc.

**Review by prckent — APPROVED** [review]
Thanks for spending all the time investigating this.

**Comment by correaa** [comment]
I am compiling with these flags and compilers, would it be meaningful test if I ran it:

```cpp
$ mpicc --version
gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0

correaa@cuk:~/qmcpack/build.cuda12.0$ mpicxx --version 
g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0

correaa@cuk:~/qmcpack/build.cuda12.0$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

$ cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DMPIEXEC_EXECUTABLE=mpirun -DBUILD_AFQMC=ON -DENABLE_CUDA=ON -DQMC_GPU_ARCHS=sm_75 -DENABLE_OFFLOAD=ON -DQMC_COMPLEX=0 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-fno-lto"
```

**Comment by ye-luo** [comment]
> I am compiling with these flags and compilers, would it be meaningful test if I ran it:
> 
> ```c++
> $ mpicc --version
> gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
> 
> correaa@cuk:~/qmcpack/build.cuda12.0$ mpicxx --version 
> g++ (Ubuntu 13.2.0-4ubuntu3) 13.2.0
> 
> correaa@cuk:~/qmcpack/build.cuda12.0$ nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Fri_Jan__6_16:45:21_PST_2023
> Cuda compilation tools, release 12.0, V12.0.140
> Build cuda_12.0.r12.0/compiler.32267302_0
> 
> $ cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DMPIEXEC_EXECUTABLE=mpirun -DBUILD_AFQMC=ON -DENABLE_CUDA=ON -DQMC_GPU_ARCHS=sm_75 -DENABLE_OFFLOAD=ON -DQMC_COMPLEX=0 -DQMC_MIXED_PRECISION=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-fno-lto" .. --fresh
> ```

Not understanding what your question is and why you are asking in this PR.

**Comment by correaa** [comment]
@prckent asked me to look into this PR. I interpret it is a regression.

**Comment by ye-luo** [comment]
> @prckent asked me to look into this PR. I interpret it is a regression. There was a missing question mark: "would it be meaningful test if I ran it?"

Still not understanding... What regression?

**Comment by ye-luo** [comment]
Do you intend to use GCC for offload?

**Comment by prckent** [comment]
The request is to investigate + make the afqmc tests work. https://cdash.qmcpack.org/CDash/testSummary.php?project=1&name=deterministic-unit_test_afqmc_numerics&date=2023-12-06 The afqmc numerics check appears to be broken in some circumstances. It should work with any recent compiler and CUDA, and at worst we should understand where problems in the toolchain are. Real space is now working with 12.3 due to bug fixes by NV.

**Comment by prckent** [comment]
This is not obvious, but for anything reporting to cdash, you can check under the "nightly" test category and selecting the build name or the configure and build entries in the same row, e.g. https://cdash.qmcpack.org/CDash/buildSummary.php?buildid=451448 . This gives access to the cmake output.

**Pull request merged**
