### PR TITLE
Nexus: Add function to slice scalar data in XSF from 3 input positions

### PR DESCRIPTION
**Pull request by mcbennet**
## Proposed changes

The function `coordinatesToSlice` will generate scalar data over a 2D slice defined by 3 input positions r1, r2, and r3.
This function returns the following:

- `slice_dens`: scalar data over the slice bounded by the input cell
- `mrpx,mrpy`: The corresponding meshgrids
- `rp1,rp2,rp3`: Input positions in a basis consistent with the meshgrids

## What type(s) of changes does this code introduce?

- New feature

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

Laptop

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by mcbennet** [comment]
@jtkrogel Those are reasonable requests. I have pushed a change for `interpolate_slice`

**Comment by mcbennet** [comment]
Tidying up a bit. My last push removes the redundant pass of a number of variables (grid,cell,corner) -- these variables are already accessible as class members.

**Comment by ye-luo** [comment]
@jtkrogel OK now?

**Comment by prckent** [comment]
OK to test

**Pull request merged**
