### PR TITLE
Add deterministic test for VMC & DMC runs with multiple walkers per threads

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
As @ye-luo requested on #1776 , deterministic test for VMC & DMC runs with 2 walkers per threads is added on diamondC_1x1x1 testset. 2 VMC cycles and 1 DMC cycle are included. 

 References are generated on QMCPACK 3.6.0 and references are fully tested including CUDA build with V100 (summit).

 Hyeondeok Shin

### CODE REVIEW

**Comment by grahamlopez** [comment]
okay to test

**Comment by Hyeondeok-Shin** [comment]
@ye-luo 2nd DMC cycle has added.
@prckent I checked with older version of QMCPACK, all deterministic test passed up to 3.5.0. (They failed on 3.4.0.) Please let me know if you need test results with a specific branch for older QMCPACK.

**Comment by ye-luo** [comment]
@Hyeondeok-Shin initialization changed between v3.4 and v3.5. The code behaviour change is expected.

**Comment by ye-luo** [comment]
Test this please

**Comment by grahamlopez** [comment]
test this please

**Pull request merged**
