### PR TITLE
Turn on NLPP energy derivatives by default.

### LINKED ISSUE #3968: Unusual behavior of "OneShiftOnly" and comparison of other optimizers
**Describe the bug**
An unusual behavior was observed for the Tb atom using `OneShiftOnly` optimizer. See the comparison of optimizers for energy and variance.

energy
variance
ratio

**To Reproduce**
1. Built from a recent commit 0ac62ea27694550d1698ae75dffacd67e42ba75b
2. Compile script is attached.

**System:**
 - system name: NERSC/Cori-KNL
 - modules loaded: See attached file

**Additional context**
All optimizers use the same parameters:
```
                linopt1 = linear(
                    energy               = 0.9,
                    unreweightedvariance = 0.0,
                    reweightedvariance   = 0.1,
                    samples              = int(1e6),
                    substeps             = 3,
                    warmupSteps          = 20,
                    blocks               = 50,
                    nonlocalpp           = True,
                    usedrift             = True,
                    minmethod            = optimizer,
                    minwalkers           = 0.1,
                    timestep             = 0.5,
                    )
```
Other parameters are default ones.

Using the same resources, the execution times are given below:
```
Optimizer	Execution Time (secs)
quartic		1641
apative		895.4
OneShiftOnly	359
descent		269.5
```
[optimizers_compare.zip](https://github.com/QMCPACK/qmcpack/files/8543611/optimizers_compare.zip)

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Requested by #3789
Fixes #3968

## What type(s) of changes does this code introduce?
- Documentation changes
- Other (please describe): Default changed.

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by lshulen** [comment]
In changing the default to include the nonlocal pp derivs, I was surprised to see that including the NLPP energy in the cost function is still turned off by default.  Should that also be changed?

**Comment by ye-luo** [comment]
> In changing the default to include the nonlocal pp derivs, I was surprised to see that including the NLPP energy in the cost function is still turned off by default. Should that also be changed?

I'm also surprised. Unfortunately, the code won't fix itself.

That is not on/off change and requires additional cleaning. nonlocalpp input actually allows the customized name of NLPP XML entry and there are look-up mechanism. I just mean need more code reading and at least a separate PR.

**Comment by lshulen** [comment]
Is a subsequent PR changing the NLPP energy on by default forthcoming, or should we make an issue to document the need?

**Comment by ye-luo** [comment]
There is an issue #3791

**Comment by prckent** [comment]
"I was surprised to see that including the NLPP energy in the cost function is still turned off by default". So not only do we ignore the gradient (pre this PR) but the value was not included! Crazy! Unfortunately the app won't fix itself. Hopefully we have enough eyes on the code that nothing like that would get in these days (@PDoakORNL , @ye-luo , @markdewing  etc.)

**Review by lshulen — CHANGES_REQUESTED** [review]
I'm happy with the direction.  I'd like to request a further change in the documentation and then I'll be happy to approve.  Could the description for the nonlocalpp variable to be changed to reflect current understanding of that feature?  Perhaps:
include non-local PP energy in the cost function --> Re-evaluate nonlocal pp energy in correlated sampling optimizations?

**Comment by ye-luo** [comment]
> I'm happy with the direction. I'd like to request a further change in the documentation and then I'll be happy to approve. Could the description for the nonlocalpp variable to be changed to reflect current understanding of that feature? Perhaps: include non-local PP energy in the cost function --> Re-evaluate nonlocal pp energy in correlated sampling optimizations?

@lshulen Indeed. I'm reading the code again and making a few test run to confirm my understanding. I will need to update the issue and also update documentation. It will take a bit time and for now I'd like to this PR merged to minimize PRs on my table.. Does it sound OK for you?

**Review by lshulen — APPROVED** [review]

**Pull request merged**
