### PR TITLE
Remove correlated sampling linear method

### PR DESCRIPTION
**Pull request by markdewing**
This driver ("cs_linear") appears to be unused.

The tests with cs_linear in the name call the "linear" method.

Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?
- Yes - cs_linear optimizer is no longer in code base

## What systems has this change been tested on?
desktop

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- N/A. Code added or changed in the PR has been clang-formatted
- N/A This PR adds tests to cover any new code, or to catch a bug that is being fixed
- N/A. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
@jtkrogel OK with the deletion of unmaintained classes and their tests?

**Comment by prckent** [comment]
Some people are on vacation. Lets label this [WIP] until they have had a chance to comment.

**Comment by ye-luo** [comment]
@jtkrogel any concern left?

**Review by jtkrogel — APPROVED** [review]
Please move forward.

**Comment by ye-luo** [comment]
Start testing in-house

**Pull request merged**
