### PR TITLE
Initial support for PGI compiler

### PR DESCRIPTION
**Pull request by markdewing**
As part of testing language standard and CMake support for various compilers, I added minimal support for the PGI compiler.

It compiles and passes unit tests on my laptop.

### CODE REVIEW

**Comment by prckent** [comment]
What did you use for the C++ 14 standard library?

**Comment by markdewing** [comment]
It came from gcc 7 on my laptop.   The C++ standard library headers used are set at install time.   I think there is a way to create a configuration file to point to a newer standard library, but I haven't gotten it to work yet.

**Comment by prckent** [comment]
I'll try 7.2.0 which is mentioned in the release notes. The standard library check fails with gcc 8.2.0 available to pgi.

**Comment by prckent** [comment]
Partial success. Two definite issues:

1. I needed to one-time configure PGI 18.7 (latest release) to see the spack installed gcc. The installer had grabbed the old gcc 4.8 despite the newer gcc being on the path during installation.
```
spack load gcc@7.2.0
GCC_DIR=`spack location --install-dir gcc@7.2.0`
PGI_DIR=$(dirname $(which makelocalrc))
makelocalrc -x $PGI_DIR -gcc $GCC_DIR/bin/gcc -gpp $GCC_DIR/bin/g++ -g77 $GCC_DIR/bin/gfortran
```
2. A newline is required after the end of try_cxx14_library.cpp Please can you modify the PR?
```
file(WRITE ${TEST_CXX14_SOURCE}
"// Test for C++14 standard library support
#include <tuple>

int main(int argc, char **argv)
{
    std::tuple<int,double> t(1, 3.5);
    // Accessing a tuple member by type is a C++14 feature
    int j = std::get<int>(t);
    return 0;
}
")

```

PGI puts out a delicious number of new warnings making this exercise already worthwhile.
My compilation currently aborts, as below. Running make -i suggests that this might be the only problem - just about everything else compiles.
```
[ 22%] Building CXX object src/QMCWaveFunctions/CMakeFiles/qmcwfs.dir/Jastrow/JastrowBuilder.cpp.o
cd /home/pk7/projects/qmc/git_QMCPACK_qmcpack/build_pgi/src/QMCWaveFunctions && /opt/pgi/linux86-64/2018/bin/pgc++  -DADD_ -DH5_USE_16_API -DHAVE_CONFIG_H -DHAVE_LMY_ENGINE -DINLINE_ALL=inline -DUSE_REAL_STRUCT_FACTOR -Drestrict=__restrict__ -I/usr/include/libxml2 -I/home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/src -I/home/pk7/projects/qmc/git_QMCPACK_qmcpack/build_pgi/src -I/home/pk7/projects/qmc/git_QMCPACK_qmcpack/build_pgi/include -I/home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/external_codes/catch  -mp=allcores -D__forceinline=inline -fast -O3 -DNDEBUG -fast   --c++14 -A -o CMakeFiles/qmcwfs.dir/Jastrow/JastrowBuilder.cpp.o -c /home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/src/QMCWaveFunctions/Jastrow/JastrowBuilder.cpp
"/home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/src/Particle/DistanceTableD
          ata.h", line 73: warning: storage class is not first
    CONSTEXPR static unsigned DIM=OHMMS_DIM;
              ^

"/home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/src/QMCWaveFunctions/Jastro
          w/kSpaceJastrow.h", line 201: error: virtual inline function
          "qmcplusplus::kSpaceJastrow::evaluateRatiosAlltoOne" was never
          defined
    inline void evaluateRatiosAlltoOne(ParticleSet& P, std::vector<ValueType>& ratios);
                ^

1 error detected in the compilation of "/home/pk7/projects/qmc/git_QMCPACK_qmcpack/qmcpack/src/QMCWaveFunctions/Jastrow/JastrowBuilder.cpp".
```

**Pull request merged**
