### PR TITLE
Add more AFQMC documentation

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Added documentation:

- Wavefunction format
- Include existing tutorials
- afqmctools
- current feature status on cpu / gpu table

@mmorale3 can you check the current feature status table in particular. I wasn't sure about the MSD status with different Hamiltonians.

## What type(s) of changes does this code introduce?

- Documentation content changes

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

macbook pro python3.7.7 sphinx3.0.5

## Checklist

- Ye. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- Yes. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
We should discuss how much theory to put in - I notice that the theory background is not longer coming soon.

**Comment by fdmalone** [comment]
Yeah, I was debating to put more theory but didn't know how useful it was. Is there detailed DMC/VMC theory in the docs?

**Comment by prckent** [comment]
Real space theory: there is some in the tutorials, but nothing organized in the front matter. There probably should be, hence the need for a discussion.

**Pull request merged**
