### PR TITLE
Reduce warmup step for diamondC_2x1x1-Gaussian_pp/det_qmc_short_vmcbatch_dmcbatch.in.xml

### LINKED ISSUE #4950: Too many warmup steps, diamondC_2x1x1-Gaussian_pp/det_qmc_short_vmcbatch_dmcbatch.in.xml
**Describe the bug**
https://github.com/QMCPACK/qmcpack/blob/03e821b46f933546108b94af564bd707a894138d/tests/solids/diamondC_2x1x1-Gaussian_pp/det_qmc_short_vmcbatch_dmcbatch.in.xml#L20
100 step warmup makes GPU runs taking 20sec. It is too long. Better to reduce it to 3 like all other deterministic tests.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

Close #4950. This PR is to reduce the warm up step and update references for diamondC_2x1x1-Gaussian_pp test.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Workstation

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
I noticed that we don’t have mixed precision + MPI on github action.

**Comment by ye-luo** [comment]
Test this please

**Review by prckent — APPROVED** [review]
Thank you Hyeondeok

**Pull request merged**
