### PR TITLE
Replace NR LU code in ppconvert

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

This PR replaces NR LU factorization by a hand written version

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Comment by correaa** [comment]
I removed  any code from NR or resembling NR. This finished the PR. 

I pending issue is that, although I cannot prove that the LU decomposition/solve is not executed in any path, I am pretty sure that this part of the code is not exercised by the current `ppconvert` test. 

The LU replacement is quite clean though.

**Comment by correaa** [comment]
not sure what causes the failure, I don't see compilation errors.  What I see is messages like this:

FATAL: Channel "hudson.remoting.Channel@5d8c6273:compute002.mcs.anl.gov": Remote call on compute002.mcs.anl.gov failed. The channel is closing down or has closed down
java.io.EOFException

**Comment by ye-luo** [comment]
glitches in the Jenkins

**Review by prckent — APPROVED** [review]
Thanks Alfredo. I would have preferred this to be separated from all the multi updates. Lets proceed though to save hassle.

The LU replacement looks sensible. Since so far no one has suggested how to reach this code, I think we can merge.

**Pull request merged**
