### PR TITLE
AFQMC MULTI Update

### PR DESCRIPTION
**Pull request by correaa**
## Proposed changes

Updates multi with modifications to make it work with AFQMC

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## Checklist

- Yes This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by ye-luo** [comment]
Okay to test

**Comment by ye-luo** [comment]
@correaa could you fix the gnu warning as the warning-as-error build reports?

**Comment by prckent** [comment]
@correaa We need the gnu warning-clean version to merge. Unless there is some deep reason it can't be avoided, we don't merge code that increases gnu errors. Over time the exception list is being decreased. Is it viable to get rid of the current gnu warnings?

**Comment by correaa** [comment]
> @correaa We need the gnu warning-clean version to merge. Unless there is some deep reason it can't be avoided, we don't merge code that increases gnu errors. Over time the exception list is being decreased. Is it viable to get rid of the current gnu warnings?

yes, the last commits are for that. The gnu warnings were reasonable and fixable.

I didn't know you were suppressing some warning-as-errors already.
If that is the case you can now get rid of the warning-error:

```
qmcpack/src/AFQMC/Wavefunctions/WavefunctionFactory.cpp:1236:1: error: control reaches end of non-void function [-Werror=return-type]
```
which was there before I started this PR.

> Edit: I assume that once this PR is ready we can merge and then update the ppconvert one which will then also pass.

yes, that is what I wanted to mean in my last post.

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
