### PR TITLE
Replace cuda/hip specific memory allocation and copying routines with arch versions.

### PR DESCRIPTION
**Pull request by fdmalone**
## Proposed changes

Uses arch::malloc/free/memcopy consistently throughout the code. Previously cuda/hipMalloc etc were called in many places without checking the error code, this PR replaces these calls with already existing arch::malloc which does the error checking internally.

## What type(s) of changes does this code introduce?

- Refactoring (no functional changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?

clang10+rocm3.6 and gcc/7.3.1+cuda9.2.88

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — COMMENTED** [review]
Could you use "const std::string& message"?
C++17 has std::string_view but we cannot use it right now.

**Comment by ye-luo** [comment]
Okay to test

**Review by ye-luo — APPROVED** [review]
LGTM

**Review by mmorale3 — APPROVED** [review]

**Comment by fdmalone** [comment]
Sorry I missed a const

**Review by ye-luo — APPROVED** [review]

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
