### PR TITLE
Check compilers before handling MPI in CMake

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Usually [findMPI failure](https://github.com/QMCPACK/qmcpack/actions/runs/6856906594/job/18647090392) is caused by compiler failure. Move the compilation ahead of findMPI.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
FYI, this machine currently has /usr/local/{cuda,cuda-12,cuda-12.1,cuda-12.2,cuda-12.3}

**Review by prckent — COMMENTED** [review]
I propose we update to 12.3 and force merge this, then use the improved diagnostics to help see what is happening with any ongoing breakage in the CI for the . There is no useful error log produced currently.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Comment by ye-luo** [comment]
> I propose we update to 12.3 and force merge this, then use the improved diagnostics to help see what is happening with any ongoing breakage in the CI for the . There is no useful error log produced currently.

I still prefer 12.1 instead of 12.3 for the following reason.
Users may use a wide range of CUDA releases and get affected by #3922.
Using 12.1 we can detect breakage if we re-trigger the bug during modification.
Using 12.3 won't expose such breakage in CI.

**Comment by prckent** [comment]
Valid point. Q. What is the smallest set of tests that catches the bugs in CUDA <12.3? We might consider adding another test config so that we are checking the latest CUDA release and also versions where we know there are issues in the wild.

**Comment by ye-luo** [comment]
> Valid point. Q. What is the smallest set of tests that catches the bugs in CUDA <12.3? We might consider adding another test config so that we are checking the latest CUDA release and also versions where we know there are issues in the wild.


Based on #4767 test_wavefunction_determinant can fail
Based on #3922 deterministic-diamondC_2x1x1-gaussian_pp_MSD-vmcbatch-dmcbatch-mwalkers_sdj-1-4 and 1-16 can fail

**Pull request merged**
