### PR TITLE
Update CMakeLists and all shebangs to require Python3

### PR DESCRIPTION
**Pull request by prckent**
Search and replace. Does not imply that I checked the scripts actually work with python 3. Notice lots of example scripts are touched.

### CODE REVIEW

**Comment by prckent** [comment]
check_stats.py is updated in #2198

**Comment by prckent** [comment]
ALCF python3 does not have numpy
```
185/236 Test #566: deterministic-diamondC_1x1x1_pp-vmc-dmc-trace_scalars-1-1-check ............***Failed    0.09 sec

Traceback (most recent call last):

  File "/sandbox/jenkins-ci/workspace/QMCPACK-CI-GNU6-MKL18/label/skylake-only/type/Complex/tests/scripts/check_traces.py", line 19, in <module>

    import numpy as np

ImportError: No module named 'numpy'



```

**Comment by ye-luo** [comment]
FindPython3 requires cmake 3.12 released on 2018-06-14 which is shorter than 2 years.
I personally prefer just bump up cmake version. I never difficulty to build cmake on any machine including old machines like BGQ in the past.

**Comment by jtkrogel** [comment]
Thumbs down on adding a requirement to build new CMake on systems older than 18 months.

Trying to run `python3` and `python` on a short Python 3 script should suffice.

**Comment by ye-luo** [comment]
Changed my mind. Add a cmake version check. If <3.12, run a simple python script.

**Comment by prckent** [comment]
Good catch with FindPython3. Since it is very easy to check with our own code, I am in favor of the new solution and maintaining the two year rule.

**Comment by ye-luo** [comment]
Test this please

**Comment by ye-luo** [comment]
The last failure seems related to the random unit test failure with the cuda build. Try CI again.

**Comment by ye-luo** [comment]
Test this please

**Comment by prckent** [comment]
We should keep an eye on cdash for flaky CUDA build results. e.g. https://cdash.qmcpack.org/CDash/testDetails.php?test=7129211&build=99071 has deterministic-unit_test_particle_base failing.

**Comment by prckent** [comment]
Second time lucky.

**Pull request merged**
