### PR TITLE
Remove legacy alternateXXX in TrialWaveFunction and WaveFunctionComponent.

### PR DESCRIPTION
**Pull request by ye-luo**
I didn't see any actual implementation in a derived WaveFunctionComponent.

### CODE REVIEW

**Comment by prckent** [comment]
More good cleanup. Will wait to hear from @rcclay in case there is some use known/planned.  Could you determine the context in which these functions were added?

**Comment by ye-luo** [comment]
We think they were added for the release node.

**Comment by prckent** [comment]
A shame release node was "lost". Fortunately we have other ways of checking convergence now.

**Comment by rcclay** [comment]
@prckent I can't remember these being used in recent memory, nor am I aware of plans to use them.

**Pull request merged**
