### PR TITLE
Ensure check_stats.py exits with error when h5py read fails.

### LINKED ISSUE #4997: deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4 hidden error
**Describe the bug**
Current develop.
```
ctest -R deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4 -VV
    Start 1148: deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4-check

1148: Test command: /usr/bin/python3.10 "/home/yeluo/opt/qmcpack/tests/scripts/check_stats.py" "-s" "1" "-q" "1rdm" "-e" "0" "-c" "8" "-p" "det_qmc_1rdm_short_vmc_dmc" "-r" "qmc-ref/det_qmc_1rdm_short_vmc_dmc.s001.stat_ref_1rdm_4_4_real.dat"
1148: Test timeout computed to be: 3600
1148: hdfreader error: encountered invalid type: <class 'h5py._debian_h5py_serial._hl.group.Group'>
2/2 Test #1148: deterministic-diamondC_1x1x1_pp-dmc-estimator-1rdm-4-4-check ...   Passed    0.11 sec
```
both tests show pass but the "hdfreader error" is concerning. 
Is check_stats.py not robust? Probably not checking file operation(open/read) status?

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Closes #4997
Before the fix, `sys.exit()` return 0 and gave false negative results.

## What type(s) of changes does this code introduce?
- Bugfix
- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
laptop ubuntu 22.04

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by ye-luo** [comment]
Test this please

**Review by jtkrogel — APPROVED** [review]
This looks fine as a fix.  Strange that debian changes the class details themselves.

**Comment by prckent** [comment]
Thanks Ye and Jaron. Would be interesting to know the backstory here if we can find it -- why is there this patched/forked h5py with different names? What can we learn to avoid similar issues in future?

**Comment by ye-luo** [comment]
I have almost no knowledge of h5py and just made an ad-hoc fix. Not sure if it is worth exploring the actual issue.

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
