### PR TITLE
Convert4QMC section + CIPSI description in manual 

### PR DESCRIPTION
**Pull request by anbenali**
CIPSI section is done
Convert4qmc should follow soon.

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by anbenali** [comment]
Ready to review!!

**Comment by markdewing** [comment]
I made a number of changes to the manual text - someone else should read it over and approve the review.

**Comment by jtkrogel** [comment]
Excellent.  Really glad to see all of this in the manual.

**Pull request merged**
