### PR TITLE
Check for dataset existence in hdf5 write wrapper

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Patch to overwrite dataset data properly checking for dataset existence.
Related to #3249 

## What type(s) of changes does this code introduce?

- Bugfix
- Refactoring (no functional changes, no api changes)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Ubuntu 20.04, must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- Yes. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by camelto2 — APPROVED** [review]
LGTM, I checked this change and there is no longer any error messages from the converter

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Test this please

**Comment by prckent** [comment]
start testing in-house

**Pull request merged**
