### PR TITLE
Add deterministic test for backflow optimization and VMC

### LINKED ISSUE #3103: Deterministic backflow test needed
Looking at the current CI coverage results, adding a deterministic backflow test based on the statistical one would catch a many files that are currently completely missed.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

 Close #3103 

 This PR is to add deterministic test for backflow optimization parameters and VMC runs.
 check_opt.py is updated to check backflow parameters in addition to Jastrows, and location is moved to /tests/scripts.

## What type(s) of changes does this code introduce?

- Other (please describe): Add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
 Intel Xeon, intel 19 compiler

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
OK to test

**Comment by Hyeondeok-Shin** [comment]
In failed CI, I noticed that optimization parameters are not deterministic now. I'll check it tomorrow.

**Comment by prckent** [comment]
Is the vmc backflow determinsitic (no optimization)? If the runs are not deterministic it might be indicating a bug. Could neighbor lists not be correctly handled in backflow?

**Comment by Hyeondeok-Shin** [comment]
Only VMC with backflow is fine. The issue is in only the optimization in Jastrow or backflow. Only Jastrow has the same issue but current deterministic test couldn't detect as it is using a single parameter. I'll make separated VMC test for the backflow only. I also talked with @ye-luo for this issue, and he will play with the optimization test with many number of parameters to see the problem when the test is merged with the small number of parameters. I will rework for them.

**Comment by Hyeondeok-Shin** [comment]
I added VMC deterministic test for backflow, and fixed optimization test. I expect they will pass CI but need to see.

@ye-luo In the input, it seems there are 3 triggers making optimization test non-deterministic.
1. Increase size of backflow parameters to 3.
2. optimize backflow and Jastrow at the same time.
3. optimized Jastrow only but increase size to 3.

**Review by prckent — APPROVED** [review]
LGTM

**Comment by prckent** [comment]
Notice that this increases our coverage by 1.16% :-)

**Pull request merged**
