### PR TITLE
Update to quantum espresso python drivers

### PR DESCRIPTION
**Pull request by mmorale3**
Please review the [developer documentation](https://github.com/QMCPACK/qmcpack/wiki/Development-workflow)
on the wiki of this project that contains help and requirements.

Describe what this PR changes and why.  If it closes an issue, link to it here
with [a supported keyword](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Updated qe driver routines. Added a new class for optimizable basis sets.
Added documentation for most of the qe driver routines.

## What type(s) of changes does this code introduce?

Update qe driver.
Documentation content changes

### Does this introduce a breaking change?

Yes (only on python routines)

## What systems has this change been tested on?

This PR is up to date with current the current state of 'develop'
Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by fdmalone** [comment]
What is the breaking change?

**Comment by mmorale3** [comment]
The signature of some of the python routines is different (expecting now an OptimizableBasisSet object).
Not that it matters, since I don't think anyone has used them yet.

**Comment by fdmalone** [comment]
You mean the QE converter has to be updated separately?

**Comment by mmorale3** [comment]
The signature of the routine gen_qe_gto has changed.
Other than this, it is not a breaking change.

**Comment by ye-luo** [comment]
Ping @prckent

**Pull request merged**
