### PR TITLE
Remove resetTargetParticleSet in BackflowTransformation.h

### PR DESCRIPTION
**Pull request by ye-luo**
resetTargetParticleSet is an unnecessary state machine. The cleaning work needs to be done from the leaves of the call tree.

### CODE REVIEW

**Comment by prckent** [comment]
A deterministic backflow test would give more confidence in these changes. Do you have one?

**Comment by ye-luo** [comment]
We don't have a determinstic. I ran the HEG sjb test 16-1, 4-4, 1-16 all pass.

**Comment by prckent** [comment]
There are lots of calls to resetTargetParticleSet in the code outside of backflow. I suspect many are there more out of a concern for safety and not understand/respecting the state machine(s). What is your plan for them?

**Comment by ye-luo** [comment]
All the resetTargetParticleSet should be removed. So far some pieces of code still need it, for example AoS LCAO. The cleaning work needs to be done via the dependence chain gradually SPO->WF->Ham.

**Comment by prckent** [comment]
Keep chopping.

**Pull request merged**
