### PR TITLE
Minor changes related to JeeI.

### PR DESCRIPTION
**Pull request by ye-luo**
1) add a unit test for OhmmsMatrix row/col swap.
2) allow eeI Jastrow defined only on partial atoms.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
@ye-luo Please state specifically what you mean by partial atoms and what is enabled by the JeeI patch, e.g. by giving an example here of an input configuration that would now work (for records purposes).

**Comment by ye-luo** [comment]
For example, you in a H2O molecule. You can only specify O-u-u and O-u-d correlation but don't add H-u-u and H-u-d correlation.
The AoS supports this but SoA was not because I was not protecting the nullptr case.

**Comment by prckent** [comment]
Matching capability of SoA code with AoS code. 
+1

**Pull request merged**
