### PR TITLE
GPU Device memory reporting and initial SPOSet resource handling

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Review after #2944
1. Introduce resource handling in SPOSet. Only APIs added, will continue after.
2. Print memory usage with device memory info.
```
###################################################################
### Memory usage report : DMCBatched after initialLogEvaluation ###
###################################################################
Available memory on node 0, free + buffers :    7472 MiB
Memory footprint by rank 0 on node 0       :   13313 MiB
Device memory allocated via CUDA allocator :     238 MiB
Free memory available on default device    :     704 MiB
Device memory allocated via OpenMP offload :    3981 MiB
###################################################################
```
It also tell me how much memory is held by driver, CUDA runtime, cublas, OpenMP runtime libraries.
My card has 8GB, only 3981 + 238 MiB are allocated by us explicitly. 704 MiB Free. 3269 MiB is taken by others.

## What type(s) of changes does this code introduce?
- New feature

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Simple updates to consider while #2944  is processing:

Use QMCPACK like sectioning ===s or ---s not ###s

Upgrade print_mem to be more C++ : strings, not char* and char[NN] .

**Comment by ye-luo** [comment]
updated style
```
===================================================================
--- Memory usage report : VMCBatched after initialLogEvaluation ---
===================================================================
Available memory on node 0, free + buffers : 18536   MiB
Memory footprint by rank 0 on node 0       : 2193    MiB
Device memory allocated via CUDA allocator : 2       MiB
Free memory available on default device    : 3972    MiB
Device memory allocated via OpenMP offload : 1232    MiB
===================================================================
```

**Review by prckent — APPROVED** [review]
LGTM

Currently generates ~1 memory report per QMC section

**Comment by ye-luo** [comment]
Currently 4 for default verbosity=high, 1 for verbosity=low, one per block for verbosity=debug

**Pull request merged**
