### PR TITLE
Update Frontier recipe to ROCm 6.0.0

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
Also stop Cray Compiler Wrapper forcing RPATH. Use RUNPATH instead.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Frontier

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by prckent** [comment]
Confirmed working and performant?

Was darshan misbehaving?

I have been using
module load cpe/23.12
module load amd-mixed/6.0.0
which seems to work and does not SEGV.

**Comment by ye-luo** [comment]
> Confirmed working and performant?

No surprise so far.

> Was darshan misbehaving?

darshan blocks use of `-add-runpath` which I need for switching debug version of libraries.

> I have been using module load cpe/23.12 module load amd-mixed/6.0.0 which seems to work and does not SEGV.

I still don't see why `amd-mixed` is used. What is your PrgEnv? I assume you use `PrgEnv-amd` which loads `amd` and then 'amd-mixed' cannot even been loaded.  `PrgEnv-amd` selects compiler wrapper and uses amdclang underneath.

**Comment by prckent** [comment]
Cray PrgEnv with amdclang and cray MPI wrappers. Just following OLCF suggestions, no preferences other than wanting an actually reliable toolchain :-)

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Test this please

**Pull request merged**
