### PR TITLE
Fix NLPP race in batched implementation.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
There is a data race in NLPP where the joblist is prepared. The race is caused by sharing the same RNG withing a crowd.
The issue was not exposed because this level of threading is only active when crowd level threading is turned off which is a scenario when I debug codes.

## What type(s) of changes does this code introduce?
- Bugfix

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
epyc-server, bora

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by markdewing** [comment]
Could you explain more about how this fixes the race.
Is the removal of the OpenMP parallel region?  (No data races if no parallel code??)
Is it moving/changing the computation of max_num_jobs?

**Comment by ye-luo** [comment]
In this case no "omp parallel" no race.

Actually both.
RNG is shared. Calling it under "omp parallel" creates a race.
max_num_jobs was also part of the race but I prefer to move it to a more local scope anyway.

**Comment by ye-luo** [comment]
Start testing in-house

**Review by PDoakORNL — APPROVED** [review]
LGTM
Better caught in debugging than production.
We need a better way to handle nested concurrency contexts,  even if in most production cases on HPC systems weak in  CPU and strong in GPU it is not used much.

**Review by prckent — APPROVED** [review]
LGTM

Do you have any suggestions for how we could have caught this?

**Comment by ye-luo** [comment]
Indeed, we don't have NLPP batched API unit tests #3454

**Pull request merged**
