### PR TITLE
Increase restart check tolerance

### PR DESCRIPTION
**Pull request by ye-luo**
Printout is more verbose.
Check up to 7th digit after the decimal.

Issue #258

Because I was not able to reproduce the failure on my platforms, I only simulated the case for checking the fix.

### CODE REVIEW

**Comment by markdewing** [comment]
okay to test

**Comment by prckent** [comment]
Should this print a FAIL if there is a difference?

**Comment by prckent** [comment]
I verified this new restart checker, including using a modified check.sh to ensure failures are caught.

**Comment by ye-luo** [comment]
@prckent This checker doesn't print Fail but returns a failure value which is picked up by ctest.

**Pull request merged**
