### PR TITLE
Remove CrayPE specialization for OpenMP offload.

### PR DESCRIPTION
**Pull request by ye-luo**
## Proposed changes
CrayPE has architecture modules. The GPU ones like craype-accel-nvidia80 introduces a lot of undesirable side effects. Since such modules are mostly useful for GPU aware MPI which we don't need, we can just avoid using them and rely on our usually ways of setting GPU flags.

## What type(s) of changes does this code introduce?
- Build related changes

### Does this introduce a breaking change?
- No

## What systems has this change been tested on?
Polaris. Tested with PrgEnv-gnu,  PrgEnv-nvhpc,  PrgEnv-cray. I also tested Cray compiler offload to AMD gpus, the compilation went as expected.

## Checklist
- Yes. This PR is up to date with current the current state of 'develop'

### CODE REVIEW

**Comment by PDoakORNL** [comment]
Does this require a manual update as well?

**Comment by ye-luo** [comment]
> Does this require a manual update as well?

Pushed an update

**Comment by prckent** [comment]
Please can you confirm that this is OK on spock.

**Review by PDoakORNL — APPROVED** [review]
I agree with @ye-luo with how to handle Cray

**Comment by prckent** [comment]
After discussing with Ye, I am also OK with this change.

**Review by prckent — APPROVED** [review]

**Comment by prckent** [comment]
Start testing in-house

**Comment by ye-luo** [comment]
I removed clang14dev as required. I think we should use stable clang13 instead for offload builds in CI.

**Comment by prckent** [comment]
@ye-luo Do you have evidence that clang13 is OK? Using a release version is an improvement, I admit.

@williamfgc  Please can you update the CI based on the eventual responses.

**Comment by williamfgc** [comment]
@ye-luo @prckent clang13 has that bug that increased memory allocation when offloading that @ye-luo reported and is fixed [in the development branch](https://reviews.llvm.org/rG01d59c0de822099c62f12f275c41338f6df9f5ac). I'll upgrade to clang14 when it comes out. Let me know how to proceed.

**Comment by prckent** [comment]
@ye-luo Newer clang dev OK?

**Comment by ye-luo** [comment]
Current clang dev main has regression since it moved to a new DeviceRTL. A few bugs still needs to be eliminated before being recommended for use. Now I remember that the clang14dev used in CI is likely a version I recommended. I think for the moment, we should stick to this version at least until I have clang 14 commit to recommend.

**Pull request merged**
