### PR TITLE
Add ctest -j parallel jobs option to all CI

### PR DESCRIPTION
**Pull request by williamfgc**
## Proposed changes

Add the -j option to ctest in CI for GitHub Actions (2 for Linux and 3 for macOS) and ornl-hosted (16) runners.
This option can be tested on this PR (no need to merge first).

## What type(s) of changes does this code introduce?
_Delete the items that do not apply_

- Testing changes (e.g. new unit/integration/performance tests)

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
Must pass CI

## Checklist

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- No. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Comment by prckent** [comment]
Test this please

**Review by prckent — APPROVED** [review]
LGTM

Lets see what happens in CI before merging.

**Comment by williamfgc** [comment]
Rebase develop and fix the script

**Comment by williamfgc** [comment]
Start testing in-house

**Review by ye-luo — APPROVED** [review]

**Pull request merged**
