### PR TITLE
Update C-molecule performance test walker counts.

### PR DESCRIPTION
**Pull request by Hyeondeok-Shin**
## Proposed changes

This PR is a part of #4081 .
Update C-molecule performance test walker counts to more detailed performance check for the real simulation.
C-graphite performance test update will be followed with expanding its system size for the test. (Current graphite performance test has only one system size to check.)

## What type(s) of changes does this code introduce?

- Other (please describe): add test

### Does this introduce a breaking change?

- No

## What systems has this change been tested on?
 Intel Xeon

## Checklist

_Update the following with a yes where the items apply. If you're unsure about any of them, don't hesitate to ask.  This is
simply a reminder of what we are going to look for before merging your code._

- Yes. This PR is up to date with current the current state of 'develop'
- No. Code added or changed in the PR has been clang-formatted
- Yes. This PR adds tests to cover any new code, or to catch a bug that is being fixed
- No. Documentation has been added (if appropriate)

### CODE REVIEW

**Review by ye-luo — COMMENTED** [review]
Thanks for adding batched_driver variants.

**Review by ye-luo — DISMISSED** [review]
Need non-ANL approval.

**Review by prckent — DISMISSED** [review]
Thank you. Looks reasonable, but have not made a test run. Check the nightlies after merge.

**Review by ye-luo — DISMISSED** [review]

**Review by ye-luo — APPROVED** [review]

**Comment by ye-luo** [comment]
Test this please

**Pull request merged**
