### PR TITLE
Add NiO performance tests

### PR DESCRIPTION
**Pull request by markdewing**
Externally set variables are:
QMC_DATA_NIO_H5 - directory containing all *.h5 files (assumes all these are in a single directory).  If this variable is not set, the tests are not configured.
QMC_NIO_MAX_SIZE - limit the size (measured in supercells) of tests configured.  Many machines will not be able to run all the sizes due to time or memory limits.  If this is not set, all sizes will be configured.

For this initial version, the number of threads is fixed at 1.  Eventually we will need to vary this.

The *.h5 files and the pseudopotential files are always symlinked, regardless of the QMC_SYMLINK_TEST_FILES setting.  Should this follow that setting or not?  Are there situations where we want a copy of the very large benchmark files?

### CODE REVIEW

**Comment by prckent** [comment]
- Suggest using QMC_DATA for the h5. We already have this defined. h5 data can be in a NiO subdirectory. 
- Suggest implementing the SYMLINK setting since we could be archiving the test files on a not widely visible filesystem.
- Check h5 files are present?
- Are the run settings consistent with the ECP benchmarks? @lshulen @ye-luo e.g. Reasonable walker counts for GPU?
- Fine timers are enabled as an option but code might not have been built with timers.
- ctest script will eventually need updating if we run automatically.

**Comment by ye-luo** [comment]
All the GPU runs are with 32 walkers. They are a bit small for S8 and S16 but right for S32 which is the largest runnable size on K20X. I suggest to set default max size to S32. 32 walker for S8 S16 are OK for monitoring performance.

**Comment by ye-luo** [comment]
As Paul suggested, better to use QMC_DATA folder and look for NiO folder and check if the h5 exists. I might download only some of them not all.

**Comment by ye-luo** [comment]
1. Current setup doesn't go through regular RUN_QMC_APP route and doesn't take mpirun.
2, For me 1 MPI + 16 threads can be a good case we run regularly no matter using GPU or not.
3. Fine timers can be added by checking build option ENABLE_TIMERS.
4, QMC_NIO_MAX_SIZE limits the number of jobs added during building. It is better to add all of them at the beginning but run optionally. I don't want redo cmake or rebuild to access larger tests.

@prckent These input files are my benchmark for ECP. They are not for real calculations but good enough to monitor performance. They run pretty fast.
I need to update them before the final merge.

**Comment by prckent** [comment]
@ye-luo "not for real calculations" - yes, noted. e.g. They use reconfiguration which is currently bugged #18 . Not a problem for performance though when the time step is small and the number of steps is modest.

**Comment by prckent** [comment]
A pointer to the h5 files is needed to test this. Please email or note here.

**Comment by prckent** [comment]
@markdewing Do the quotes fix the following:

 Git branch: develop
  Last git commit: #define GIT_COMMIT_LAST_CHANGED_RAW Mon Jan 30 14:52:02 2017 -0500
  Last commit date: GIT_COMMIT_LAST_CHANGED_RAW

( from http://cdash.qmcpack.org/CDash/testDetails.php?test=278642&build=5437 . This was a titan build. Other builds at around the same time appeared OK. )

**Comment by ye-luo** [comment]
@prckent Could you explain more about your last comment? I'm not able to understand...

**Comment by prckent** [comment]
Where to I get the h5 inputs to test this?

**Comment by prckent** [comment]
I noticed that "sometimes" instead of printing the Last git commit name we print "#define ..." indicating some kind of error. I don't know if this is a problem with certain commit messages, specific git versions, or titan/Cray weirdness (etc.)

**Comment by markdewing** [comment]
@prckent That looks like some glitch where git could not get some information.

From the config log:
<pre>
-- Ready to build qmcpack
fatal: unable to read tree a231a5f30d257af300870b85b814cff2b7c150f7
Git branch: develop
Git commit hash: 
</pre>.
The fix for the subject line won't mitigate the problems caused by this.

**Comment by markdewing** [comment]
@prckent I checked in a fix so those glitches with git output won't cascade to the rest of the include file

**Comment by ye-luo** [comment]
Can I change to 16 threads? I was running on BGQ but the benefit is the same for Xeon.
    Start 160: performance-NiO-cpu-S8-1-1
1/6 Test #160: performance-NiO-cpu-S8-1-1 .......   Passed  347.11 sec
    Start 161: performance-NiO-cpu-S16-1-1
2/6 Test #161: performance-NiO-cpu-S16-1-1 ......   Passed  581.68 sec
    Start 162: performance-NiO-cpu-S32-1-1
3/6 Test #162: performance-NiO-cpu-S32-1-1 ......   Passed  1070.71 sec
    Start 163: performance-NiO-cpu-S8-J3-1-1
Instead with 16 threads.
1/6 Test #160: performance-NiO-cpu-S8-1-16 .......   Passed   91.48 sec
    Start 161: performance-NiO-cpu-S16-1-16
2/6 Test #161: performance-NiO-cpu-S16-1-16 ......   Passed  170.99 sec
    Start 162: performance-NiO-cpu-S32-1-16
3/6 Test #162: performance-NiO-cpu-S32-1-16 ......   Passed  422.97 sec
    Start 163: performance-NiO-cpu-S8-J3-1-16

The initialization time is largely cut Coulomb break-up is threaded.
running S32 with 16 thread needs no more than 16GB memory with the current code.

**Comment by prckent** [comment]
@ye-luo Please add full comments to your run scripts. If we are to include run scripts here, include machine names & example usage in the discussion and the shell scripts. Should run_gpu.sh be run_gpu_cooley.sh ? The README should say that the ctest defaults to a certain number of threads etc. but explain that what is the performance metric (throughput, walker moves/sec) and that for best results the user is welcome to tune parameters, this is turn requires explaining which tweaks are valid.

I still need the location of the h5 files.

**Comment by ye-luo** [comment]
@prckent run_gpu.sh and run_cpu.sh are general but *.sub are machine specific. Is the README good enough now?

**Comment by prckent** [comment]
I am currently testing on oxygen, CPU version. So far behaviour as expected: tests are correctly not added and appropriate messages are printed if QMC_DATA is not set or NiO directory is missing.

**Comment by prckent** [comment]
@ye-luo Please check expanded README for any bugs introduced by me

**Comment by prckent** [comment]
Thanks for the patience and discussion. Merging.

**Pull request merged**
